import typing, clr
from System.Collections.ObjectModel import ReadOnlyCollection_1
from System import IDisposable, EventArgs, TimeSpan, Array_1, Exception, IAsyncResult, AsyncCallback, MulticastDelegate
from System.Collections.Generic import IList_1, IEnumerable_1, List_1
from Microsoft.Xna.Framework.GamerServices import SignedInGamer, LeaderboardWriter, Gamer, GamerCollection_1
from System.Net import IPAddress
from System.Collections import IDictionary
from System.Reflection import MethodBase, MethodInfo
from System.ComponentModel import INotifyPropertyChanged
from System.IO import BinaryReader, Stream, BinaryWriter
from Microsoft.Xna.Framework import Color, Matrix, Quaternion, Vector2, Vector3, Vector4

class AvailableNetworkSession:
    def __init__(self) -> None: ...
    @property
    def CurrentGamerCount(self) -> int: ...
    @CurrentGamerCount.setter
    def CurrentGamerCount(self, value: int) -> int: ...
    @property
    def HostGamertag(self) -> str: ...
    @HostGamertag.setter
    def HostGamertag(self, value: str) -> str: ...
    @property
    def OpenPrivateGamerSlots(self) -> int: ...
    @OpenPrivateGamerSlots.setter
    def OpenPrivateGamerSlots(self, value: int) -> int: ...
    @property
    def OpenPublicGamerSlots(self) -> int: ...
    @OpenPublicGamerSlots.setter
    def OpenPublicGamerSlots(self, value: int) -> int: ...
    @property
    def QualityOfService(self) -> QualityOfService: ...
    @QualityOfService.setter
    def QualityOfService(self, value: QualityOfService) -> QualityOfService: ...
    @property
    def SessionProperties(self) -> NetworkSessionProperties: ...
    @SessionProperties.setter
    def SessionProperties(self, value: NetworkSessionProperties) -> NetworkSessionProperties: ...


class AvailableNetworkSessionCollection(ReadOnlyCollection_1[AvailableNetworkSession], IDisposable):
    def __init__(self, list: IList_1[AvailableNetworkSession]) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> AvailableNetworkSession: ...
    def Dispose(self) -> None: ...


class CommandEventType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    GamerJoined : CommandEventType # 0
    GamerLeft : CommandEventType # 1
    SessionStateChange : CommandEventType # 2
    SendData : CommandEventType # 3
    ReceiveData : CommandEventType # 4
    GamerStateChange : CommandEventType # 5


class GameEndedEventArgs(EventArgs):
    def __init__(self) -> None: ...


class GamerJoinedEventArgs(EventArgs):
    def __init__(self, aGamer: NetworkGamer) -> None: ...
    @property
    def Gamer(self) -> NetworkGamer: ...


class GamerLeftEventArgs(EventArgs):
    def __init__(self, aGamer: NetworkGamer) -> None: ...
    @property
    def Gamer(self) -> NetworkGamer: ...


class GamerStates(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Local : GamerStates # 1
    Host : GamerStates # 16
    HasVoice : GamerStates # 256
    Guest : GamerStates # 4096
    MutedByLocalUser : GamerStates # 65536
    PrivateSlot : GamerStates # 1048576
    Ready : GamerStates # 16777216


class GameStartedEventArgs(EventArgs):
    def __init__(self) -> None: ...


class HostChangedEventArgs(EventArgs):
    def __init__(self, aNewHost: NetworkGamer, aOldHost: NetworkGamer) -> None: ...
    @property
    def NewHost(self) -> NetworkGamer: ...
    @property
    def OldHost(self) -> NetworkGamer: ...


class InviteAcceptedEventArgs(EventArgs):
    def __init__(self, aGamer: SignedInGamer) -> None: ...
    @property
    def Gamer(self) -> SignedInGamer: ...
    @property
    def IsCurrentSession(self) -> bool: ...


class LocalNetworkGamer(NetworkGamer):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, session: NetworkSession, id: int, state: GamerStates) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> str: ...
    @property
    def Gamertag(self) -> str: ...
    @Gamertag.setter
    def Gamertag(self, value: str) -> str: ...
    @property
    def HasLeftSession(self) -> bool: ...
    @property
    def HasVoice(self) -> bool: ...
    @property
    def Id(self) -> int: ...
    @property
    def IsDataAvailable(self) -> bool: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IsGuest(self) -> bool: ...
    @property
    def IsHost(self) -> bool: ...
    @property
    def IsLocal(self) -> bool: ...
    @property
    def IsMutedByLocalUser(self) -> bool: ...
    @property
    def IsPrivateSlot(self) -> bool: ...
    @property
    def IsReady(self) -> bool: ...
    @IsReady.setter
    def IsReady(self, value: bool) -> bool: ...
    @property
    def IsTalking(self) -> bool: ...
    @property
    def LeaderboardWriter(self) -> LeaderboardWriter: ...
    @LeaderboardWriter.setter
    def LeaderboardWriter(self, value: LeaderboardWriter) -> LeaderboardWriter: ...
    @property
    def Machine(self) -> NetworkMachine: ...
    @Machine.setter
    def Machine(self, value: NetworkMachine) -> NetworkMachine: ...
    @property
    def RoundtripTime(self) -> TimeSpan: ...
    @property
    def Session(self) -> NetworkSession: ...
    @property
    def SignedInGamer(self) -> SignedInGamer: ...
    @SignedInGamer.setter
    def SignedInGamer(self, value: SignedInGamer) -> SignedInGamer: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    # Skipped ReceiveData due to it being static, abstract and generic.

    ReceiveData : ReceiveData_MethodGroup
    class ReceiveData_MethodGroup:
        @typing.overload
        def __call__(self, data: Array_1[int], sender: clr.Reference[NetworkGamer]) -> int:...
        @typing.overload
        def __call__(self, data: PacketReader, sender: clr.Reference[NetworkGamer]) -> int:...
        @typing.overload
        def __call__(self, data: Array_1[int], offset: int, sender: clr.Reference[NetworkGamer]) -> int:...

    # Skipped SendData due to it being static, abstract and generic.

    SendData : SendData_MethodGroup
    class SendData_MethodGroup:
        @typing.overload
        def __call__(self, data: Array_1[int], options: SendDataOptions) -> None:...
        @typing.overload
        def __call__(self, data: PacketWriter, options: SendDataOptions) -> None:...
        @typing.overload
        def __call__(self, data: Array_1[int], options: SendDataOptions, recipient: NetworkGamer) -> None:...
        @typing.overload
        def __call__(self, data: PacketWriter, options: SendDataOptions, recipient: NetworkGamer) -> None:...
        @typing.overload
        def __call__(self, data: Array_1[int], offset: int, count: int, options: SendDataOptions) -> None:...
        @typing.overload
        def __call__(self, data: Array_1[int], offset: int, count: int, options: SendDataOptions, recipient: NetworkGamer) -> None:...



class MonoGameNetworkConfiguration:
    def __init__(self) -> None: ...
    Broadcast : IPAddress


class NetworkException(Exception):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str) -> None: ...
    @typing.overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @property
    def Data(self) -> IDictionary: ...
    @property
    def HelpLink(self) -> str: ...
    @HelpLink.setter
    def HelpLink(self, value: str) -> str: ...
    @property
    def HResult(self) -> int: ...
    @HResult.setter
    def HResult(self, value: int) -> int: ...
    @property
    def InnerException(self) -> Exception: ...
    @property
    def Message(self) -> str: ...
    @property
    def Source(self) -> str: ...
    @Source.setter
    def Source(self, value: str) -> str: ...
    @property
    def StackTrace(self) -> str: ...
    @property
    def TargetSite(self) -> MethodBase: ...


class NetworkGamer(Gamer, INotifyPropertyChanged):
    def __init__(self, session: NetworkSession, id: int, state: GamerStates) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> str: ...
    @property
    def Gamertag(self) -> str: ...
    @Gamertag.setter
    def Gamertag(self, value: str) -> str: ...
    @property
    def HasLeftSession(self) -> bool: ...
    @property
    def HasVoice(self) -> bool: ...
    @property
    def Id(self) -> int: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IsGuest(self) -> bool: ...
    @property
    def IsHost(self) -> bool: ...
    @property
    def IsLocal(self) -> bool: ...
    @property
    def IsMutedByLocalUser(self) -> bool: ...
    @property
    def IsPrivateSlot(self) -> bool: ...
    @property
    def IsReady(self) -> bool: ...
    @IsReady.setter
    def IsReady(self, value: bool) -> bool: ...
    @property
    def IsTalking(self) -> bool: ...
    @property
    def LeaderboardWriter(self) -> LeaderboardWriter: ...
    @LeaderboardWriter.setter
    def LeaderboardWriter(self, value: LeaderboardWriter) -> LeaderboardWriter: ...
    @property
    def Machine(self) -> NetworkMachine: ...
    @Machine.setter
    def Machine(self, value: NetworkMachine) -> NetworkMachine: ...
    @property
    def RoundtripTime(self) -> TimeSpan: ...
    @property
    def Session(self) -> NetworkSession: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...


class NetworkMachine:
    def __init__(self) -> None: ...
    @property
    def Gamers(self) -> GamerCollection_1[NetworkGamer]: ...


class NetworkNotAvailableException(NetworkException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str) -> None: ...
    @typing.overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @property
    def Data(self) -> IDictionary: ...
    @property
    def HelpLink(self) -> str: ...
    @HelpLink.setter
    def HelpLink(self, value: str) -> str: ...
    @property
    def HResult(self) -> int: ...
    @HResult.setter
    def HResult(self, value: int) -> int: ...
    @property
    def InnerException(self) -> Exception: ...
    @property
    def Message(self) -> str: ...
    @property
    def Source(self) -> str: ...
    @Source.setter
    def Source(self, value: str) -> str: ...
    @property
    def StackTrace(self) -> str: ...
    @property
    def TargetSite(self) -> MethodBase: ...


class NetworkSession(IDisposable):
    @property
    def AllGamers(self) -> GamerCollection_1[NetworkGamer]: ...
    @property
    def AllowHostMigration(self) -> bool: ...
    @AllowHostMigration.setter
    def AllowHostMigration(self, value: bool) -> bool: ...
    @property
    def AllowJoinInProgress(self) -> bool: ...
    @AllowJoinInProgress.setter
    def AllowJoinInProgress(self, value: bool) -> bool: ...
    @property
    def Host(self) -> NetworkGamer: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IsEveryoneReady(self) -> bool: ...
    @property
    def IsHost(self) -> bool: ...
    @property
    def LocalGamers(self) -> GamerCollection_1[LocalNetworkGamer]: ...
    @property
    def MaxGamers(self) -> int: ...
    @MaxGamers.setter
    def MaxGamers(self, value: int) -> int: ...
    @property
    def PreviousGamers(self) -> GamerCollection_1[NetworkGamer]: ...
    @property
    def PrivateGamerSlots(self) -> int: ...
    @PrivateGamerSlots.setter
    def PrivateGamerSlots(self, value: int) -> int: ...
    @property
    def RemoteGamers(self) -> GamerCollection_1[NetworkGamer]: ...
    @property
    def SessionProperties(self) -> NetworkSessionProperties: ...
    @property
    def SessionState(self) -> NetworkSessionState: ...
    @property
    def SessionType(self) -> NetworkSessionType: ...
    @property
    def SimulatedLatency(self) -> TimeSpan: ...
    @SimulatedLatency.setter
    def SimulatedLatency(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def SimulatedPacketLoss(self) -> float: ...
    @SimulatedPacketLoss.setter
    def SimulatedPacketLoss(self, value: float) -> float: ...
    def AddLocalGamer(self, gamer: SignedInGamer) -> None: ...
    @staticmethod
    def BeginJoin(availableSession: AvailableNetworkSession, callback: AsyncCallback, asyncState: typing.Any) -> IAsyncResult: ...
    @staticmethod
    def EndCreate(result: IAsyncResult) -> NetworkSession: ...
    @staticmethod
    def EndFind(result: IAsyncResult) -> AvailableNetworkSessionCollection: ...
    def EndGame(self) -> None: ...
    @staticmethod
    def EndJoin(result: IAsyncResult) -> NetworkSession: ...
    def FindGamerById(self, gamerId: int) -> NetworkGamer: ...
    @staticmethod
    def Join(availableSession: AvailableNetworkSession) -> NetworkSession: ...
    def ResetReady(self) -> None: ...
    def StartGame(self) -> None: ...
    def Update(self) -> None: ...
    # Skipped BeginCreate due to it being static, abstract and generic.

    BeginCreate : BeginCreate_MethodGroup
    class BeginCreate_MethodGroup:
        @typing.overload
        def __call__(self, sessionType: NetworkSessionType, maxLocalGamers: int, maxGamers: int, callback: AsyncCallback, asyncState: typing.Any) -> IAsyncResult:...
        @typing.overload
        def __call__(self, sessionType: NetworkSessionType, maxLocalGamers: int, maxGamers: int, privateGamerSlots: int, sessionProperties: NetworkSessionProperties, callback: AsyncCallback, asyncState: typing.Any) -> IAsyncResult:...
        @typing.overload
        def __call__(self, sessionType: NetworkSessionType, localGamers: IEnumerable_1[SignedInGamer], maxGamers: int, privateGamerSlots: int, sessionProperties: NetworkSessionProperties, callback: AsyncCallback, asyncState: typing.Any) -> IAsyncResult:...

    # Skipped BeginFind due to it being static, abstract and generic.

    BeginFind : BeginFind_MethodGroup
    class BeginFind_MethodGroup:
        @typing.overload
        def __call__(self, sessionType: NetworkSessionType, maxLocalGamers: int, searchProperties: NetworkSessionProperties, callback: AsyncCallback, asyncState: typing.Any) -> IAsyncResult:...
        @typing.overload
        def __call__(self, sessionType: NetworkSessionType, localGamers: IEnumerable_1[SignedInGamer], searchProperties: NetworkSessionProperties, callback: AsyncCallback, asyncState: typing.Any) -> IAsyncResult:...

    # Skipped Create due to it being static, abstract and generic.

    Create : Create_MethodGroup
    class Create_MethodGroup:
        @typing.overload
        def __call__(self, sessionType: NetworkSessionType, maxLocalGamers: int, maxGamers: int) -> NetworkSession:...
        @typing.overload
        def __call__(self, sessionType: NetworkSessionType, maxLocalGamers: int, maxGamers: int, privateGamerSlots: int, sessionProperties: NetworkSessionProperties) -> NetworkSession:...
        @typing.overload
        def __call__(self, sessionType: NetworkSessionType, localGamers: IEnumerable_1[SignedInGamer], maxGamers: int, privateGamerSlots: int, sessionProperties: NetworkSessionProperties) -> NetworkSession:...

    # Skipped Dispose due to it being static, abstract and generic.

    Dispose : Dispose_MethodGroup
    class Dispose_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, disposing: bool) -> None:...

    # Skipped Find due to it being static, abstract and generic.

    Find : Find_MethodGroup
    class Find_MethodGroup:
        @typing.overload
        def __call__(self, sessionType: NetworkSessionType, maxLocalGamers: int, searchProperties: NetworkSessionProperties) -> AvailableNetworkSessionCollection:...
        @typing.overload
        def __call__(self, sessionType: NetworkSessionType, localGamers: IEnumerable_1[SignedInGamer], searchProperties: NetworkSessionProperties) -> AvailableNetworkSessionCollection:...



class NetworkSessionAsynchronousCreate(MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, sessionType: NetworkSessionType, maxLocalGamers: int, maxGamers: int, privateGamerSlots: int, sessionProperties: NetworkSessionProperties, hostGamer: int, isHost: bool, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> NetworkSession: ...
    def Invoke(self, sessionType: NetworkSessionType, maxLocalGamers: int, maxGamers: int, privateGamerSlots: int, sessionProperties: NetworkSessionProperties, hostGamer: int, isHost: bool) -> NetworkSession: ...


class NetworkSessionAsynchronousFind(MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, sessionType: NetworkSessionType, hostGamer: int, maxLocalGamers: int, searchProperties: NetworkSessionProperties, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> AvailableNetworkSessionCollection: ...
    def Invoke(self, sessionType: NetworkSessionType, hostGamer: int, maxLocalGamers: int, searchProperties: NetworkSessionProperties) -> AvailableNetworkSessionCollection: ...


class NetworkSessionAsynchronousJoin(MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, availableSession: AvailableNetworkSession, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> NetworkSession: ...
    def Invoke(self, availableSession: AvailableNetworkSession) -> NetworkSession: ...


class NetworkSessionAsynchronousJoinInvited(MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, maxLocalGamers: int, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> NetworkSession: ...
    def Invoke(self, maxLocalGamers: int) -> NetworkSession: ...


class NetworkSessionEndedEventArgs(EventArgs):
    def __init__(self, aEndReason: NetworkSessionEndReason) -> None: ...
    @property
    def EndReason(self) -> NetworkSessionEndReason: ...


class NetworkSessionEndReason(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    ClientSignedOut : NetworkSessionEndReason # 0
    HostEndedSession : NetworkSessionEndReason # 1
    RemovedByHost : NetworkSessionEndReason # 2
    Disconnected : NetworkSessionEndReason # 3


class NetworkSessionJoinError(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    SessionNotFound : NetworkSessionJoinError # 0
    SessionNotJoinable : NetworkSessionJoinError # 1
    SessionFull : NetworkSessionJoinError # 2


class NetworkSessionJoinException(NetworkException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str) -> None: ...
    @typing.overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @typing.overload
    def __init__(self, message: str, joinError: NetworkSessionJoinError) -> None: ...
    @property
    def Data(self) -> IDictionary: ...
    @property
    def HelpLink(self) -> str: ...
    @HelpLink.setter
    def HelpLink(self, value: str) -> str: ...
    @property
    def HResult(self) -> int: ...
    @HResult.setter
    def HResult(self, value: int) -> int: ...
    @property
    def InnerException(self) -> Exception: ...
    @property
    def JoinError(self) -> NetworkSessionJoinError: ...
    @JoinError.setter
    def JoinError(self, value: NetworkSessionJoinError) -> NetworkSessionJoinError: ...
    @property
    def Message(self) -> str: ...
    @property
    def Source(self) -> str: ...
    @Source.setter
    def Source(self, value: str) -> str: ...
    @property
    def StackTrace(self) -> str: ...
    @property
    def TargetSite(self) -> MethodBase: ...


class NetworkSessionProperties(List_1[typing.Optional[int]]):
    def __init__(self) -> None: ...
    @property
    def Capacity(self) -> int: ...
    @Capacity.setter
    def Capacity(self, value: int) -> int: ...
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> typing.Optional[int]: ...
    @Item.setter
    def Item(self, value: typing.Optional[int]) -> typing.Optional[int]: ...
    @staticmethod
    def ReadProperties(properties: NetworkSessionProperties, propertyData: Array_1[int]) -> None: ...
    @staticmethod
    def WriteProperties(properties: NetworkSessionProperties, propertyData: Array_1[int]) -> None: ...


class NetworkSessionState(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Lobby : NetworkSessionState # 0
    Playing : NetworkSessionState # 1
    Ended : NetworkSessionState # 2


class NetworkSessionType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Local : NetworkSessionType # 0
    SystemLink : NetworkSessionType # 1
    PlayerMatch : NetworkSessionType # 2
    Ranked : NetworkSessionType # 3


class PacketReader(BinaryReader):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, capacity: int) -> None: ...
    @property
    def BaseStream(self) -> Stream: ...
    @property
    def Length(self) -> int: ...
    @property
    def Position(self) -> int: ...
    @Position.setter
    def Position(self, value: int) -> int: ...
    def ReadColor(self) -> Color: ...
    def ReadDouble(self) -> float: ...
    def ReadMatrix(self) -> Matrix: ...
    def ReadQuaternion(self) -> Quaternion: ...
    def ReadVector2(self) -> Vector2: ...
    def ReadVector3(self) -> Vector3: ...
    def ReadVector4(self) -> Vector4: ...


class PacketWriter(BinaryWriter):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, capacity: int) -> None: ...
    @property
    def BaseStream(self) -> Stream: ...
    @property
    def Length(self) -> int: ...
    @property
    def Position(self) -> int: ...
    @Position.setter
    def Position(self, value: int) -> int: ...
    # Skipped Write due to it being static, abstract and generic.

    Write : Write_MethodGroup
    class Write_MethodGroup:
        @typing.overload
        def __call__(self, Value: float) -> None:...
        # Method Write(Value : Single) was skipped since it collides with above method
        @typing.overload
        def __call__(self, Value: Color) -> None:...
        @typing.overload
        def __call__(self, Value: Matrix) -> None:...
        @typing.overload
        def __call__(self, Value: Quaternion) -> None:...
        @typing.overload
        def __call__(self, Value: Vector2) -> None:...
        @typing.overload
        def __call__(self, Value: Vector3) -> None:...
        @typing.overload
        def __call__(self, Value: Vector4) -> None:...



class QualityOfService:
    def __init__(self) -> None: ...
    @property
    def AverageRoundtripTime(self) -> TimeSpan: ...
    @property
    def BytesPerSecondDownstream(self) -> int: ...
    @property
    def BytesPerSecondUpstream(self) -> int: ...
    @property
    def IsAvailable(self) -> bool: ...
    @property
    def MinimumRoundtripTime(self) -> TimeSpan: ...


class SendDataOptions(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : SendDataOptions # 0
    Reliable : SendDataOptions # 1
    InOrder : SendDataOptions # 2
    ReliableInOrder : SendDataOptions # 3
    Chat : SendDataOptions # 4

