import typing
from Microsoft.Xna.Framework import Vector3
from System import IDisposable, Array_1

class AudioEmitter:
    def __init__(self) -> None: ...
    @property
    def DopplerScale(self) -> float: ...
    @DopplerScale.setter
    def DopplerScale(self, value: float) -> float: ...
    @property
    def Forward(self) -> Vector3: ...
    @Forward.setter
    def Forward(self, value: Vector3) -> Vector3: ...
    @property
    def Position(self) -> Vector3: ...
    @Position.setter
    def Position(self, value: Vector3) -> Vector3: ...
    @property
    def Up(self) -> Vector3: ...
    @Up.setter
    def Up(self, value: Vector3) -> Vector3: ...
    @property
    def Velocity(self) -> Vector3: ...
    @Velocity.setter
    def Velocity(self, value: Vector3) -> Vector3: ...


class AudioListener:
    def __init__(self) -> None: ...
    @property
    def Forward(self) -> Vector3: ...
    @Forward.setter
    def Forward(self, value: Vector3) -> Vector3: ...
    @property
    def Position(self) -> Vector3: ...
    @Position.setter
    def Position(self, value: Vector3) -> Vector3: ...
    @property
    def Up(self) -> Vector3: ...
    @Up.setter
    def Up(self, value: Vector3) -> Vector3: ...
    @property
    def Velocity(self) -> Vector3: ...
    @Velocity.setter
    def Velocity(self, value: Vector3) -> Vector3: ...


class SoundEffectInstance(IDisposable):
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IsLooped(self) -> bool: ...
    @IsLooped.setter
    def IsLooped(self, value: bool) -> bool: ...
    @property
    def Pan(self) -> float: ...
    @Pan.setter
    def Pan(self, value: float) -> float: ...
    @property
    def Pitch(self) -> float: ...
    @Pitch.setter
    def Pitch(self, value: float) -> float: ...
    @property
    def State(self) -> SoundState: ...
    @property
    def Volume(self) -> float: ...
    @Volume.setter
    def Volume(self, value: float) -> float: ...
    def Dispose(self) -> None: ...
    def Pause(self) -> None: ...
    def Play(self) -> None: ...
    def Resume(self) -> None: ...
    # Skipped Apply3D due to it being static, abstract and generic.

    Apply3D : Apply3D_MethodGroup
    class Apply3D_MethodGroup:
        @typing.overload
        def __call__(self, listeners: Array_1[AudioListener], emitter: AudioEmitter) -> None:...
        @typing.overload
        def __call__(self, listener: AudioListener, emitter: AudioEmitter) -> None:...

    # Skipped Stop due to it being static, abstract and generic.

    Stop : Stop_MethodGroup
    class Stop_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, immediate: bool) -> None:...



class SoundState(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Playing : SoundState # 0
    Paused : SoundState # 1
    Stopped : SoundState # 2

