import typing
from System.Dynamic import IDynamicMetaObjectProvider, DynamicMetaObject
from IronPython.Runtime import ICodeFormattable, CodeContext, SiteLocalStorage_1, PythonTuple, IPythonMembersList, IWeakReferenceableByProxy, IWeakReferenceable, PythonDictionary, PythonList
from System.Collections.Generic import IList_1, IDictionary_2
from System.Reflection import MethodBase
from System.Runtime.CompilerServices import CallSite_1, CallSite
from System import Func_6, Array_1
from System.Linq.Expressions import Expression

class BuiltinFunction(PythonTypeSlot, IDynamicMetaObjectProvider, ICodeFormattable):
    @property
    def __doc__(self) -> str: ...
    @property
    def __name__(self) -> str: ...
    @property
    def __self__(self) -> typing.Any: ...
    @property
    def DeclaringType(self) -> typing.Type[typing.Any]: ...
    @property
    def Overloads(self) -> BuiltinFunctionOverloadMapper: ...
    @property
    def Targets(self) -> IList_1[MethodBase]: ...
    def __call__(self, context: CodeContext, storage: SiteLocalStorage_1[CallSite_1[Func_6[CallSite, CodeContext, typing.Any, Array_1[typing.Any], IDictionary_2[typing.Any, typing.Any], typing.Any]]], dictArgs: IDictionary_2[typing.Any, typing.Any], args: Array_1[typing.Any]) -> typing.Any: ...
    def __eq__(self, other: BuiltinFunction) -> bool: ...
    def __ge__(self, context: CodeContext, other: typing.Any) -> NotImplementedType: ...
    def __gt__(self, context: CodeContext, other: typing.Any) -> NotImplementedType: ...
    def __hash__(self, context: CodeContext) -> int: ...
    def __le__(self, context: CodeContext, other: typing.Any) -> NotImplementedType: ...
    def __lt__(self, context: CodeContext, other: typing.Any) -> NotImplementedType: ...
    def __ne__(self, other: BuiltinFunction) -> bool: ...
    def __reduce__(self) -> str: ...
    def __repr__(self, context: CodeContext) -> str: ...
    def Get__module__(self, context: CodeContext) -> str: ...
    def Set__module__(self, value: str) -> None: ...


class BuiltinFunctionOverloadMapper(ICodeFormattable):
    def __init__(self, builtinFunction: BuiltinFunction, instance: typing.Any) -> None: ...
    @property
    def Function(self) -> BuiltinFunction: ...
    @property
    def Functions(self) -> PythonTuple: ...
    @property
    def Item(self) -> typing.Any: ...
    @property
    def Targets(self) -> IList_1[MethodBase]: ...
    def __repr__(self, context: CodeContext) -> str: ...
    def ThrowOverloadException(self, sig: Array_1[typing.Type[typing.Any]], targets: IList_1[MethodBase]) -> None: ...


class BuiltinMethodDescriptor(PythonTypeSlot, ICodeFormattable, IDynamicMetaObjectProvider):
    @property
    def __doc__(self) -> str: ...
    @property
    def __name__(self) -> str: ...
    @property
    def __objclass__(self) -> PythonType: ...
    @property
    def DeclaringType(self) -> typing.Type[typing.Any]: ...
    def __call__(self, context: CodeContext, storage: SiteLocalStorage_1[CallSite_1[Func_6[CallSite, CodeContext, typing.Any, Array_1[typing.Any], IDictionary_2[typing.Any, typing.Any], typing.Any]]], dictArgs: IDictionary_2[typing.Any, typing.Any], args: Array_1[typing.Any]) -> typing.Any: ...
    def __repr__(self, context: CodeContext) -> str: ...


class NotImplementedType(ICodeFormattable):
    def __hash__(self) -> int: ...
    @staticmethod
    def __new__(context: CodeContext, cls: PythonType) -> NotImplementedType: ...
    def __repr__(self, context: CodeContext) -> str: ...


class PythonType(IPythonMembersList, ICodeFormattable, IWeakReferenceableByProxy, IWeakReferenceable, IDynamicMetaObjectProvider):
    def __init__(self, context: CodeContext, name: str, bases: PythonTuple, dict: PythonDictionary) -> None: ...
    __dict__ : PythonTypeSlot
    @property
    def Item(self) -> PythonType: ...
    @property
    def Item(self) -> typing.Any: ...
    def __clrtype__(self) -> typing.Type[typing.Any]: ...
    def __delattr__(self, context: CodeContext, name: str) -> None: ...
    def __getattribute__(self, context: CodeContext, name: str) -> typing.Any: ...
    def __instancecheck__(self, instance: typing.Any) -> bool: ...
    @staticmethod
    def __prepare__(kwargs: IDictionary_2[typing.Any, typing.Any], args: Array_1[typing.Any]) -> PythonDictionary: ...
    def __repr__(self, context: CodeContext) -> str: ...
    def __setattr__(self, context: CodeContext, name: str, value: typing.Any) -> None: ...
    def __subclasscheck__(self, sub: PythonType) -> bool: ...
    def __subclasses__(self, context: CodeContext) -> PythonList: ...
    @staticmethod
    def Delete__module__(context: CodeContext, self: PythonType) -> None: ...
    @staticmethod
    def Get__base__(context: CodeContext, type: PythonType) -> PythonType: ...
    @staticmethod
    def Get__bases__(context: CodeContext, type: PythonType) -> PythonTuple: ...
    @staticmethod
    def Get__clr_assembly__(self: PythonType) -> str: ...
    @staticmethod
    def Get__doc__(context: CodeContext, self: PythonType) -> typing.Any: ...
    @staticmethod
    def Get__flags__(context: CodeContext, type: PythonType) -> int: ...
    @staticmethod
    def Get__module__(context: CodeContext, self: PythonType) -> typing.Any: ...
    @staticmethod
    def Get__mro__(type: PythonType) -> PythonTuple: ...
    @staticmethod
    def Get__name__(type: PythonType) -> str: ...
    @staticmethod
    def Get__qualname__(type: PythonType) -> str: ...
    def GetMetaObject(self, parameter: Expression) -> DynamicMetaObject: ...
    def mro(self) -> PythonList: ...
    # Operator not supported op_Implicit(self: PythonType)
    # Operator not supported op_Implicit(self: PythonType)
    @staticmethod
    def Set__bases__(context: CodeContext, type: PythonType, value: typing.Any) -> None: ...
    @staticmethod
    def Set__module__(context: CodeContext, self: PythonType, value: typing.Any) -> None: ...
    @staticmethod
    def Set__name__(type: PythonType, name: str) -> None: ...
    @staticmethod
    def Set__qualname__(type: PythonType, name: str) -> None: ...
    # Skipped __call__ due to it being static, abstract and generic.

    __call__ : __call___MethodGroup
    class __call___MethodGroup:
        @typing.overload
        def __call__(self, context: CodeContext, args: Array_1[typing.Any]) -> typing.Any:...
        @typing.overload
        def __call__(self, context: CodeContext, kwArgs: IDictionary_2[str, typing.Any], args: Array_1[typing.Any]) -> typing.Any:...

    # Skipped __init__ due to it being static, abstract and generic.

    __init__ : __init___MethodGroup
    class __init___MethodGroup:
        @typing.overload
        def __call__(self, o: typing.Any) -> None:...
        @typing.overload
        def __call__(self, name: str, bases: PythonTuple, dict: PythonDictionary, kwargs: IDictionary_2[typing.Any, typing.Any]) -> None:...

    # Skipped __new__ due to it being static, abstract and generic.

    __new__ : __new___MethodGroup
    class __new___MethodGroup:
        @typing.overload
        def __call__(self, context: CodeContext, cls: typing.Any, o: typing.Any) -> typing.Any:...
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, name: str, bases: PythonTuple, dict: PythonDictionary) -> typing.Any:...



class PythonTypeSlot:
    def __init__(self) -> None: ...
    def __get__(self, context: CodeContext, instance: typing.Any, typeContext: typing.Any = ...) -> typing.Any: ...

