import typing, clr, abc
from System import Array_1, MulticastDelegate, IAsyncResult, AsyncCallback, Predicate_1, Action_1, Converter_2, Comparison_1
from System.Reflection import MethodInfo
from System.Collections.Generic import IEqualityComparer_1, IEnumerable_1, List_1, IEnumerator_1, IComparer_1, ICollection_1
from System.IO import TextReader
from Microsoft.Xna.Framework.Graphics import GraphicsDevice, Texture2D, Effect, IVertexType, VertexDeclaration
from Microsoft.Xna.Framework import Color, Vector3, Vector2

class Animation:
    def __init__(self, name: str, timelines: ExposedList_1[Timeline], duration: float) -> None: ...
    @property
    def Duration(self) -> float: ...
    @Duration.setter
    def Duration(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def Timelines(self) -> ExposedList_1[Timeline]: ...
    @Timelines.setter
    def Timelines(self, value: ExposedList_1[Timeline]) -> ExposedList_1[Timeline]: ...
    def Apply(self, skeleton: Skeleton, lastTime: float, time: float, loop: bool, events: ExposedList_1[Event], alpha: float, blend: MixBlend, direction: MixDirection) -> None: ...
    def HasTimeline(self, propertyIds: Array_1[str]) -> bool: ...
    def SetTimelines(self, timelines: ExposedList_1[Timeline]) -> None: ...
    def ToString(self) -> str: ...


class AnimationState:
    def __init__(self, data: AnimationStateData) -> None: ...
    @property
    def Data(self) -> AnimationStateData: ...
    @Data.setter
    def Data(self, value: AnimationStateData) -> AnimationStateData: ...
    @property
    def TimeScale(self) -> float: ...
    @TimeScale.setter
    def TimeScale(self, value: float) -> float: ...
    @property
    def Tracks(self) -> ExposedList_1[TrackEntry]: ...
    def AddEmptyAnimation(self, trackIndex: int, mixDuration: float, delay: float) -> TrackEntry: ...
    def AddEventSubscribersFrom(self, src: AnimationState) -> None: ...
    def Apply(self, skeleton: Skeleton) -> bool: ...
    def ApplyEventTimelinesOnly(self, skeleton: Skeleton, issueEvents: bool = ...) -> bool: ...
    def AssignEventSubscribersFrom(self, src: AnimationState) -> None: ...
    def ClearListenerNotifications(self) -> None: ...
    def ClearNext(self, entry: TrackEntry) -> None: ...
    def ClearTrack(self, trackIndex: int) -> None: ...
    def ClearTracks(self) -> None: ...
    def GetCurrent(self, trackIndex: int) -> TrackEntry: ...
    def SetEmptyAnimation(self, trackIndex: int, mixDuration: float) -> TrackEntry: ...
    def SetEmptyAnimations(self, mixDuration: float) -> None: ...
    def ToString(self) -> str: ...
    def Update(self, delta: float) -> None: ...
    # Skipped AddAnimation due to it being static, abstract and generic.

    AddAnimation : AddAnimation_MethodGroup
    class AddAnimation_MethodGroup:
        @typing.overload
        def __call__(self, trackIndex: int, animationName: str, loop: bool, delay: float) -> TrackEntry:...
        @typing.overload
        def __call__(self, trackIndex: int, animation: Animation, loop: bool, delay: float) -> TrackEntry:...

    # Skipped SetAnimation due to it being static, abstract and generic.

    SetAnimation : SetAnimation_MethodGroup
    class SetAnimation_MethodGroup:
        @typing.overload
        def __call__(self, trackIndex: int, animationName: str, loop: bool) -> TrackEntry:...
        @typing.overload
        def __call__(self, trackIndex: int, animation: Animation, loop: bool) -> TrackEntry:...


    class TrackEntryDelegate(MulticastDelegate):
        def __init__(self, object: typing.Any, method: int) -> None: ...
        @property
        def Method(self) -> MethodInfo: ...
        @property
        def Target(self) -> typing.Any: ...
        def BeginInvoke(self, trackEntry: TrackEntry, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
        def EndInvoke(self, result: IAsyncResult) -> None: ...
        def Invoke(self, trackEntry: TrackEntry) -> None: ...


    class TrackEntryEventDelegate(MulticastDelegate):
        def __init__(self, object: typing.Any, method: int) -> None: ...
        @property
        def Method(self) -> MethodInfo: ...
        @property
        def Target(self) -> typing.Any: ...
        def BeginInvoke(self, trackEntry: TrackEntry, e: Event, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
        def EndInvoke(self, result: IAsyncResult) -> None: ...
        def Invoke(self, trackEntry: TrackEntry, e: Event) -> None: ...



class AnimationStateData:
    def __init__(self, skeletonData: SkeletonData) -> None: ...
    @property
    def DefaultMix(self) -> float: ...
    @DefaultMix.setter
    def DefaultMix(self, value: float) -> float: ...
    @property
    def SkeletonData(self) -> SkeletonData: ...
    def GetMix(self, from_: Animation, to: Animation) -> float: ...
    # Skipped SetMix due to it being static, abstract and generic.

    SetMix : SetMix_MethodGroup
    class SetMix_MethodGroup:
        @typing.overload
        def __call__(self, fromName: str, toName: str, duration: float) -> None:...
        @typing.overload
        def __call__(self, from_: Animation, to: Animation, duration: float) -> None:...


    class AnimationPair:
        def __init__(self, a1: Animation, a2: Animation) -> None: ...
        a1 : Animation
        a2 : Animation
        def ToString(self) -> str: ...


    class AnimationPairComparer(IEqualityComparer_1[AnimationStateData.AnimationPair]):
        def __init__(self) -> None: ...
        Instance : AnimationStateData.AnimationPairComparer



class Atlas(IEnumerable_1[AtlasRegion]):
    @typing.overload
    def __init__(self, pages: List_1[AtlasPage], regions: List_1[AtlasRegion]) -> None: ...
    @typing.overload
    def __init__(self, path: str, textureLoader: TextureLoader) -> None: ...
    @typing.overload
    def __init__(self, reader: TextReader, imagesDir: str, textureLoader: TextureLoader) -> None: ...
    @property
    def Pages(self) -> List_1[AtlasPage]: ...
    @property
    def Regions(self) -> List_1[AtlasRegion]: ...
    def Dispose(self) -> None: ...
    def FindRegion(self, name: str) -> AtlasRegion: ...
    def FlipV(self) -> None: ...
    def GetEnumerator(self) -> IEnumerator_1[AtlasRegion]: ...


class AtlasPage:
    def __init__(self) -> None: ...
    format : Format
    height : int
    magFilter : TextureFilter
    minFilter : TextureFilter
    name : str
    pma : bool
    rendererObject : typing.Any
    uWrap : TextureWrap
    vWrap : TextureWrap
    width : int
    def Clone(self) -> AtlasPage: ...


class AtlasRegion(TextureRegion):
    def __init__(self) -> None: ...
    degrees : int
    height : int
    index : int
    name : str
    names : Array_1[str]
    offsetX : float
    offsetY : float
    originalHeight : int
    originalWidth : int
    page : AtlasPage
    rotate : bool
    u : float
    u2 : float
    v : float
    v2 : float
    values : Array_1[Array_1[int]]
    width : int
    x : int
    y : int
    @property
    def OriginalHeight(self) -> int: ...
    @property
    def OriginalWidth(self) -> int: ...
    @property
    def packedHeight(self) -> int: ...
    @packedHeight.setter
    def packedHeight(self, value: int) -> int: ...
    @property
    def packedWidth(self) -> int: ...
    @packedWidth.setter
    def packedWidth(self, value: int) -> int: ...
    def Clone(self) -> AtlasRegion: ...


class Attachment(abc.ABC):
    @property
    def Name(self) -> str: ...
    @abc.abstractmethod
    def Copy(self) -> Attachment: ...
    def ToString(self) -> str: ...


class BlendMode(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Normal : BlendMode # 0
    Additive : BlendMode # 1
    Multiply : BlendMode # 2
    Screen : BlendMode # 3


class Bone(IUpdatable):
    @typing.overload
    def __init__(self, bone: Bone, skeleton: Skeleton, parent: Bone) -> None: ...
    @typing.overload
    def __init__(self, data: BoneData, skeleton: Skeleton, parent: Bone) -> None: ...
    yDown : bool
    @property
    def A(self) -> float: ...
    @A.setter
    def A(self, value: float) -> float: ...
    @property
    def Active(self) -> bool: ...
    @property
    def AppliedRotation(self) -> float: ...
    @AppliedRotation.setter
    def AppliedRotation(self, value: float) -> float: ...
    @property
    def AScaleX(self) -> float: ...
    @AScaleX.setter
    def AScaleX(self, value: float) -> float: ...
    @property
    def AScaleY(self) -> float: ...
    @AScaleY.setter
    def AScaleY(self, value: float) -> float: ...
    @property
    def AShearX(self) -> float: ...
    @AShearX.setter
    def AShearX(self, value: float) -> float: ...
    @property
    def AShearY(self) -> float: ...
    @AShearY.setter
    def AShearY(self, value: float) -> float: ...
    @property
    def AX(self) -> float: ...
    @AX.setter
    def AX(self, value: float) -> float: ...
    @property
    def AY(self) -> float: ...
    @AY.setter
    def AY(self, value: float) -> float: ...
    @property
    def B(self) -> float: ...
    @B.setter
    def B(self, value: float) -> float: ...
    @property
    def C(self) -> float: ...
    @C.setter
    def C(self, value: float) -> float: ...
    @property
    def Children(self) -> ExposedList_1[Bone]: ...
    @property
    def D(self) -> float: ...
    @D.setter
    def D(self, value: float) -> float: ...
    @property
    def Data(self) -> BoneData: ...
    @property
    def Inherit(self) -> Inherit: ...
    @Inherit.setter
    def Inherit(self, value: Inherit) -> Inherit: ...
    @property
    def Parent(self) -> Bone: ...
    @property
    def Rotation(self) -> float: ...
    @Rotation.setter
    def Rotation(self, value: float) -> float: ...
    @property
    def ScaleX(self) -> float: ...
    @ScaleX.setter
    def ScaleX(self, value: float) -> float: ...
    @property
    def ScaleY(self) -> float: ...
    @ScaleY.setter
    def ScaleY(self, value: float) -> float: ...
    @property
    def ShearX(self) -> float: ...
    @ShearX.setter
    def ShearX(self, value: float) -> float: ...
    @property
    def ShearY(self) -> float: ...
    @ShearY.setter
    def ShearY(self, value: float) -> float: ...
    @property
    def Skeleton(self) -> Skeleton: ...
    @property
    def WorldRotationX(self) -> float: ...
    @property
    def WorldRotationY(self) -> float: ...
    @property
    def WorldScaleX(self) -> float: ...
    @property
    def WorldScaleY(self) -> float: ...
    @property
    def WorldX(self) -> float: ...
    @WorldX.setter
    def WorldX(self, value: float) -> float: ...
    @property
    def WorldY(self) -> float: ...
    @WorldY.setter
    def WorldY(self, value: float) -> float: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> float: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> float: ...
    def LocalToWorld(self, localX: float, localY: float, worldX: clr.Reference[float], worldY: clr.Reference[float]) -> None: ...
    def LocalToWorldRotation(self, localRotation: float) -> float: ...
    def ParentToWorld(self, parentX: float, parentY: float, worldX: clr.Reference[float], worldY: clr.Reference[float]) -> None: ...
    def RotateWorld(self, degrees: float) -> None: ...
    def SetToSetupPose(self) -> None: ...
    def ToString(self) -> str: ...
    def Update(self, physics: Skeleton.Physics) -> None: ...
    def UpdateAppliedTransform(self) -> None: ...
    def WorldToLocal(self, worldX: float, worldY: float, localX: clr.Reference[float], localY: clr.Reference[float]) -> None: ...
    def WorldToLocalRotation(self, worldRotation: float) -> float: ...
    def WorldToParent(self, worldX: float, worldY: float, parentX: clr.Reference[float], parentY: clr.Reference[float]) -> None: ...
    # Skipped UpdateWorldTransform due to it being static, abstract and generic.

    UpdateWorldTransform : UpdateWorldTransform_MethodGroup
    class UpdateWorldTransform_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, x: float, y: float, rotation: float, scaleX: float, scaleY: float, shearX: float, shearY: float) -> None:...



class BoneData:
    def __init__(self, index: int, name: str, parent: BoneData) -> None: ...
    @property
    def Index(self) -> int: ...
    @property
    def Inherit(self) -> Inherit: ...
    @Inherit.setter
    def Inherit(self, value: Inherit) -> Inherit: ...
    @property
    def Length(self) -> float: ...
    @Length.setter
    def Length(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def Parent(self) -> BoneData: ...
    @property
    def Rotation(self) -> float: ...
    @Rotation.setter
    def Rotation(self, value: float) -> float: ...
    @property
    def ScaleX(self) -> float: ...
    @ScaleX.setter
    def ScaleX(self, value: float) -> float: ...
    @property
    def ScaleY(self) -> float: ...
    @ScaleY.setter
    def ScaleY(self, value: float) -> float: ...
    @property
    def ShearX(self) -> float: ...
    @ShearX.setter
    def ShearX(self, value: float) -> float: ...
    @property
    def ShearY(self) -> float: ...
    @ShearY.setter
    def ShearY(self, value: float) -> float: ...
    @property
    def SkinRequired(self) -> bool: ...
    @SkinRequired.setter
    def SkinRequired(self, value: bool) -> bool: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> float: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> float: ...
    def ToString(self) -> str: ...


class ClippingAttachment(VertexAttachment):
    def __init__(self, name: str) -> None: ...
    @property
    def Bones(self) -> Array_1[int]: ...
    @Bones.setter
    def Bones(self, value: Array_1[int]) -> Array_1[int]: ...
    @property
    def EndSlot(self) -> SlotData: ...
    @EndSlot.setter
    def EndSlot(self, value: SlotData) -> SlotData: ...
    @property
    def Id(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def TimelineAttachment(self) -> VertexAttachment: ...
    @TimelineAttachment.setter
    def TimelineAttachment(self, value: VertexAttachment) -> VertexAttachment: ...
    @property
    def Vertices(self) -> Array_1[float]: ...
    @Vertices.setter
    def Vertices(self, value: Array_1[float]) -> Array_1[float]: ...
    @property
    def WorldVerticesLength(self) -> int: ...
    @WorldVerticesLength.setter
    def WorldVerticesLength(self, value: int) -> int: ...
    def Copy(self) -> Attachment: ...


class ConstraintData(abc.ABC):
    def __init__(self, name: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @property
    def Order(self) -> int: ...
    @Order.setter
    def Order(self, value: int) -> int: ...
    @property
    def SkinRequired(self) -> bool: ...
    @SkinRequired.setter
    def SkinRequired(self, value: bool) -> bool: ...
    def ToString(self) -> str: ...


class Event:
    def __init__(self, time: float, data: EventData) -> None: ...
    @property
    def Balance(self) -> float: ...
    @Balance.setter
    def Balance(self, value: float) -> float: ...
    @property
    def Data(self) -> EventData: ...
    @property
    def Float(self) -> float: ...
    @Float.setter
    def Float(self, value: float) -> float: ...
    @property
    def Int(self) -> int: ...
    @Int.setter
    def Int(self, value: int) -> int: ...
    @property
    def String(self) -> str: ...
    @String.setter
    def String(self, value: str) -> str: ...
    @property
    def Time(self) -> float: ...
    @property
    def Volume(self) -> float: ...
    @Volume.setter
    def Volume(self, value: float) -> float: ...
    def ToString(self) -> str: ...


class EventData:
    def __init__(self, name: str) -> None: ...
    @property
    def AudioPath(self) -> str: ...
    @AudioPath.setter
    def AudioPath(self, value: str) -> str: ...
    @property
    def Balance(self) -> float: ...
    @Balance.setter
    def Balance(self, value: float) -> float: ...
    @property
    def Float(self) -> float: ...
    @Float.setter
    def Float(self, value: float) -> float: ...
    @property
    def Int(self) -> int: ...
    @Int.setter
    def Int(self, value: int) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def String(self) -> str: ...
    @String.setter
    def String(self, value: str) -> str: ...
    @property
    def Volume(self) -> float: ...
    @Volume.setter
    def Volume(self, value: float) -> float: ...
    def ToString(self) -> str: ...


class ExposedList_GenericClasses(abc.ABCMeta):
    Generic_ExposedList_GenericClasses_ExposedList_1_T = typing.TypeVar('Generic_ExposedList_GenericClasses_ExposedList_1_T')
    def __getitem__(self, types : typing.Type[Generic_ExposedList_GenericClasses_ExposedList_1_T]) -> typing.Type[ExposedList_1[Generic_ExposedList_GenericClasses_ExposedList_1_T]]: ...

ExposedList : ExposedList_GenericClasses

ExposedList_1_T = typing.TypeVar('ExposedList_1_T')
class ExposedList_1(typing.Generic[ExposedList_1_T], IEnumerable_1[ExposedList_1_T]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, capacity: int) -> None: ...
    @typing.overload
    def __init__(self, collection: IEnumerable_1[ExposedList_1_T]) -> None: ...
    Count : int
    Items : Array_1[ExposedList_1_T]
    @property
    def Capacity(self) -> int: ...
    @Capacity.setter
    def Capacity(self, value: int) -> int: ...
    def Add(self, item: ExposedList_1_T) -> None: ...
    def Clear(self, clearArray: bool = ...) -> None: ...
    def Contains(self, item: ExposedList_1_T) -> bool: ...
    def EnsureCapacity(self, min: int) -> None: ...
    def Exists(self, match: Predicate_1[ExposedList_1_T]) -> bool: ...
    def Find(self, match: Predicate_1[ExposedList_1_T]) -> ExposedList_1_T: ...
    def FindAll(self, match: Predicate_1[ExposedList_1_T]) -> ExposedList_1[ExposedList_1_T]: ...
    def FindLast(self, match: Predicate_1[ExposedList_1_T]) -> ExposedList_1_T: ...
    def ForEach(self, action: Action_1[ExposedList_1_T]) -> None: ...
    def GetEnumerator(self) -> ExposedList_1.Enumerator_1[ExposedList_1_T]: ...
    def GetRange(self, index: int, count: int) -> ExposedList_1[ExposedList_1_T]: ...
    def GrowIfNeeded(self, addedCount: int) -> None: ...
    def Insert(self, index: int, item: ExposedList_1_T) -> None: ...
    def InsertRange(self, index: int, collection: IEnumerable_1[ExposedList_1_T]) -> None: ...
    def Pop(self) -> ExposedList_1_T: ...
    def Remove(self, item: ExposedList_1_T) -> bool: ...
    def RemoveAll(self, match: Predicate_1[ExposedList_1_T]) -> int: ...
    def RemoveAt(self, index: int) -> None: ...
    def RemoveRange(self, index: int, count: int) -> None: ...
    def Resize(self, newSize: int) -> ExposedList_1[ExposedList_1_T]: ...
    def ToArray(self) -> Array_1[ExposedList_1_T]: ...
    def TrimExcess(self) -> None: ...
    def TrueForAll(self, match: Predicate_1[ExposedList_1_T]) -> bool: ...
    # Skipped AddRange due to it being static, abstract and generic.

    AddRange : AddRange_MethodGroup[ExposedList_1_T]
    AddRange_MethodGroup_ExposedList_1_T = typing.TypeVar('AddRange_MethodGroup_ExposedList_1_T')
    class AddRange_MethodGroup(typing.Generic[AddRange_MethodGroup_ExposedList_1_T]):
        AddRange_MethodGroup_ExposedList_1_T = ExposedList_1.AddRange_MethodGroup_ExposedList_1_T
        @typing.overload
        def __call__(self, list: ExposedList_1[AddRange_MethodGroup_ExposedList_1_T]) -> None:...
        @typing.overload
        def __call__(self, collection: IEnumerable_1[AddRange_MethodGroup_ExposedList_1_T]) -> None:...

    # Skipped BinarySearch due to it being static, abstract and generic.

    BinarySearch : BinarySearch_MethodGroup[ExposedList_1_T]
    BinarySearch_MethodGroup_ExposedList_1_T = typing.TypeVar('BinarySearch_MethodGroup_ExposedList_1_T')
    class BinarySearch_MethodGroup(typing.Generic[BinarySearch_MethodGroup_ExposedList_1_T]):
        BinarySearch_MethodGroup_ExposedList_1_T = ExposedList_1.BinarySearch_MethodGroup_ExposedList_1_T
        @typing.overload
        def __call__(self, item: BinarySearch_MethodGroup_ExposedList_1_T) -> int:...
        @typing.overload
        def __call__(self, item: BinarySearch_MethodGroup_ExposedList_1_T, comparer: IComparer_1[BinarySearch_MethodGroup_ExposedList_1_T]) -> int:...
        @typing.overload
        def __call__(self, index: int, count: int, item: BinarySearch_MethodGroup_ExposedList_1_T, comparer: IComparer_1[BinarySearch_MethodGroup_ExposedList_1_T]) -> int:...

    # Skipped ConvertAll due to it being static, abstract and generic.

    ConvertAll : ConvertAll_MethodGroup[ExposedList_1_T]
    ConvertAll_MethodGroup_ExposedList_1_T = typing.TypeVar('ConvertAll_MethodGroup_ExposedList_1_T')
    class ConvertAll_MethodGroup(typing.Generic[ConvertAll_MethodGroup_ExposedList_1_T]):
        ConvertAll_MethodGroup_ExposedList_1_T = ExposedList_1.ConvertAll_MethodGroup_ExposedList_1_T
        def __getitem__(self, t:typing.Type[ConvertAll_1_T1]) -> ConvertAll_1[ConvertAll_MethodGroup_ExposedList_1_T, ConvertAll_1_T1]: ...

        ConvertAll_1_ExposedList_1_T = typing.TypeVar('ConvertAll_1_ExposedList_1_T')
        ConvertAll_1_T1 = typing.TypeVar('ConvertAll_1_T1')
        class ConvertAll_1(typing.Generic[ConvertAll_1_ExposedList_1_T, ConvertAll_1_T1]):
            ConvertAll_1_ExposedList_1_T = ExposedList_1.ConvertAll_MethodGroup.ConvertAll_1_ExposedList_1_T
            ConvertAll_1_TOutput = ExposedList_1.ConvertAll_MethodGroup.ConvertAll_1_T1
            def __call__(self, converter: Converter_2[ConvertAll_1_ExposedList_1_T, ConvertAll_1_TOutput]) -> ExposedList_1[ConvertAll_1_TOutput]:...


    # Skipped CopyTo due to it being static, abstract and generic.

    CopyTo : CopyTo_MethodGroup[ExposedList_1_T]
    CopyTo_MethodGroup_ExposedList_1_T = typing.TypeVar('CopyTo_MethodGroup_ExposedList_1_T')
    class CopyTo_MethodGroup(typing.Generic[CopyTo_MethodGroup_ExposedList_1_T]):
        CopyTo_MethodGroup_ExposedList_1_T = ExposedList_1.CopyTo_MethodGroup_ExposedList_1_T
        @typing.overload
        def __call__(self, array: Array_1[CopyTo_MethodGroup_ExposedList_1_T]) -> None:...
        @typing.overload
        def __call__(self, array: Array_1[CopyTo_MethodGroup_ExposedList_1_T], arrayIndex: int) -> None:...
        @typing.overload
        def __call__(self, index: int, array: Array_1[CopyTo_MethodGroup_ExposedList_1_T], arrayIndex: int, count: int) -> None:...

    # Skipped FindIndex due to it being static, abstract and generic.

    FindIndex : FindIndex_MethodGroup[ExposedList_1_T]
    FindIndex_MethodGroup_ExposedList_1_T = typing.TypeVar('FindIndex_MethodGroup_ExposedList_1_T')
    class FindIndex_MethodGroup(typing.Generic[FindIndex_MethodGroup_ExposedList_1_T]):
        FindIndex_MethodGroup_ExposedList_1_T = ExposedList_1.FindIndex_MethodGroup_ExposedList_1_T
        @typing.overload
        def __call__(self, match: Predicate_1[FindIndex_MethodGroup_ExposedList_1_T]) -> int:...
        @typing.overload
        def __call__(self, startIndex: int, match: Predicate_1[FindIndex_MethodGroup_ExposedList_1_T]) -> int:...
        @typing.overload
        def __call__(self, startIndex: int, count: int, match: Predicate_1[FindIndex_MethodGroup_ExposedList_1_T]) -> int:...

    # Skipped FindLastIndex due to it being static, abstract and generic.

    FindLastIndex : FindLastIndex_MethodGroup[ExposedList_1_T]
    FindLastIndex_MethodGroup_ExposedList_1_T = typing.TypeVar('FindLastIndex_MethodGroup_ExposedList_1_T')
    class FindLastIndex_MethodGroup(typing.Generic[FindLastIndex_MethodGroup_ExposedList_1_T]):
        FindLastIndex_MethodGroup_ExposedList_1_T = ExposedList_1.FindLastIndex_MethodGroup_ExposedList_1_T
        @typing.overload
        def __call__(self, match: Predicate_1[FindLastIndex_MethodGroup_ExposedList_1_T]) -> int:...
        @typing.overload
        def __call__(self, startIndex: int, match: Predicate_1[FindLastIndex_MethodGroup_ExposedList_1_T]) -> int:...
        @typing.overload
        def __call__(self, startIndex: int, count: int, match: Predicate_1[FindLastIndex_MethodGroup_ExposedList_1_T]) -> int:...

    # Skipped IndexOf due to it being static, abstract and generic.

    IndexOf : IndexOf_MethodGroup[ExposedList_1_T]
    IndexOf_MethodGroup_ExposedList_1_T = typing.TypeVar('IndexOf_MethodGroup_ExposedList_1_T')
    class IndexOf_MethodGroup(typing.Generic[IndexOf_MethodGroup_ExposedList_1_T]):
        IndexOf_MethodGroup_ExposedList_1_T = ExposedList_1.IndexOf_MethodGroup_ExposedList_1_T
        @typing.overload
        def __call__(self, item: IndexOf_MethodGroup_ExposedList_1_T) -> int:...
        @typing.overload
        def __call__(self, item: IndexOf_MethodGroup_ExposedList_1_T, index: int) -> int:...
        @typing.overload
        def __call__(self, item: IndexOf_MethodGroup_ExposedList_1_T, index: int, count: int) -> int:...

    # Skipped LastIndexOf due to it being static, abstract and generic.

    LastIndexOf : LastIndexOf_MethodGroup[ExposedList_1_T]
    LastIndexOf_MethodGroup_ExposedList_1_T = typing.TypeVar('LastIndexOf_MethodGroup_ExposedList_1_T')
    class LastIndexOf_MethodGroup(typing.Generic[LastIndexOf_MethodGroup_ExposedList_1_T]):
        LastIndexOf_MethodGroup_ExposedList_1_T = ExposedList_1.LastIndexOf_MethodGroup_ExposedList_1_T
        @typing.overload
        def __call__(self, item: LastIndexOf_MethodGroup_ExposedList_1_T) -> int:...
        @typing.overload
        def __call__(self, item: LastIndexOf_MethodGroup_ExposedList_1_T, index: int) -> int:...
        @typing.overload
        def __call__(self, item: LastIndexOf_MethodGroup_ExposedList_1_T, index: int, count: int) -> int:...

    # Skipped Reverse due to it being static, abstract and generic.

    Reverse : Reverse_MethodGroup[ExposedList_1_T]
    Reverse_MethodGroup_ExposedList_1_T = typing.TypeVar('Reverse_MethodGroup_ExposedList_1_T')
    class Reverse_MethodGroup(typing.Generic[Reverse_MethodGroup_ExposedList_1_T]):
        Reverse_MethodGroup_ExposedList_1_T = ExposedList_1.Reverse_MethodGroup_ExposedList_1_T
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, index: int, count: int) -> None:...

    # Skipped Sort due to it being static, abstract and generic.

    Sort : Sort_MethodGroup[ExposedList_1_T]
    Sort_MethodGroup_ExposedList_1_T = typing.TypeVar('Sort_MethodGroup_ExposedList_1_T')
    class Sort_MethodGroup(typing.Generic[Sort_MethodGroup_ExposedList_1_T]):
        Sort_MethodGroup_ExposedList_1_T = ExposedList_1.Sort_MethodGroup_ExposedList_1_T
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, comparison: Comparison_1[Sort_MethodGroup_ExposedList_1_T]) -> None:...
        @typing.overload
        def __call__(self, comparer: IComparer_1[Sort_MethodGroup_ExposedList_1_T]) -> None:...
        @typing.overload
        def __call__(self, index: int, count: int, comparer: IComparer_1[Sort_MethodGroup_ExposedList_1_T]) -> None:...


    Enumerator_GenericClasses_ExposedList_1_T = typing.TypeVar('Enumerator_GenericClasses_ExposedList_1_T')
    class Enumerator_GenericClasses(typing.Generic[Enumerator_GenericClasses_ExposedList_1_T], abc.ABCMeta):
        Enumerator_GenericClasses_ExposedList_1_T = ExposedList_1.Enumerator_GenericClasses_ExposedList_1_T
        def __call__(self) -> ExposedList_1.Enumerator_1[Enumerator_GenericClasses_ExposedList_1_T]: ...

    Enumerator : Enumerator_GenericClasses[ExposedList_1_T]

    Enumerator_1_T = typing.TypeVar('Enumerator_1_T')
    class Enumerator_1(typing.Generic[Enumerator_1_T], IEnumerator_1[Enumerator_1_T]):
        Enumerator_1_T = ExposedList_1.Enumerator_1_T
        @property
        def Current(self) -> Enumerator_1_T: ...
        def Dispose(self) -> None: ...
        def MoveNext(self) -> bool: ...



class Format(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Alpha : Format # 0
    Intensity : Format # 1
    LuminanceAlpha : Format # 2
    RGB565 : Format # 3
    RGBA4444 : Format # 4
    RGB888 : Format # 5
    RGBA8888 : Format # 6


class IkConstraint(IUpdatable):
    @typing.overload
    def __init__(self, constraint: IkConstraint, skeleton: Skeleton) -> None: ...
    @typing.overload
    def __init__(self, data: IkConstraintData, skeleton: Skeleton) -> None: ...
    @property
    def Active(self) -> bool: ...
    @property
    def BendDirection(self) -> int: ...
    @BendDirection.setter
    def BendDirection(self, value: int) -> int: ...
    @property
    def Bones(self) -> ExposedList_1[Bone]: ...
    @property
    def Compress(self) -> bool: ...
    @Compress.setter
    def Compress(self, value: bool) -> bool: ...
    @property
    def Data(self) -> IkConstraintData: ...
    @property
    def Mix(self) -> float: ...
    @Mix.setter
    def Mix(self, value: float) -> float: ...
    @property
    def Softness(self) -> float: ...
    @Softness.setter
    def Softness(self, value: float) -> float: ...
    @property
    def Stretch(self) -> bool: ...
    @Stretch.setter
    def Stretch(self, value: bool) -> bool: ...
    @property
    def Target(self) -> Bone: ...
    @Target.setter
    def Target(self, value: Bone) -> Bone: ...
    def SetToSetupPose(self) -> None: ...
    def ToString(self) -> str: ...
    def Update(self, physics: Skeleton.Physics) -> None: ...
    # Skipped Apply due to it being static, abstract and generic.

    Apply : Apply_MethodGroup
    class Apply_MethodGroup:
        @typing.overload
        def __call__(self, bone: Bone, targetX: float, targetY: float, compress: bool, stretch: bool, uniform: bool, alpha: float) -> None:...
        @typing.overload
        def __call__(self, parent: Bone, child: Bone, targetX: float, targetY: float, bendDir: int, stretch: bool, uniform: bool, softness: float, alpha: float) -> None:...



class IkConstraintData(ConstraintData):
    def __init__(self, name: str) -> None: ...
    @property
    def BendDirection(self) -> int: ...
    @BendDirection.setter
    def BendDirection(self, value: int) -> int: ...
    @property
    def Bones(self) -> ExposedList_1[BoneData]: ...
    @property
    def Compress(self) -> bool: ...
    @Compress.setter
    def Compress(self, value: bool) -> bool: ...
    @property
    def Mix(self) -> float: ...
    @Mix.setter
    def Mix(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def Order(self) -> int: ...
    @Order.setter
    def Order(self, value: int) -> int: ...
    @property
    def SkinRequired(self) -> bool: ...
    @SkinRequired.setter
    def SkinRequired(self, value: bool) -> bool: ...
    @property
    def Softness(self) -> float: ...
    @Softness.setter
    def Softness(self, value: float) -> float: ...
    @property
    def Stretch(self) -> bool: ...
    @Stretch.setter
    def Stretch(self, value: bool) -> bool: ...
    @property
    def Target(self) -> BoneData: ...
    @Target.setter
    def Target(self, value: BoneData) -> BoneData: ...
    @property
    def Uniform(self) -> bool: ...
    @Uniform.setter
    def Uniform(self, value: bool) -> bool: ...


class Inherit(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Normal : Inherit # 0
    OnlyTranslation : Inherit # 1
    NoRotationOrReflection : Inherit # 2
    NoScale : Inherit # 3
    NoScaleOrReflection : Inherit # 4


class IUpdatable(typing.Protocol):
    @property
    def Active(self) -> bool: ...
    @abc.abstractmethod
    def Update(self, physics: Skeleton.Physics) -> None: ...


class IVertexEffect(typing.Protocol):
    @abc.abstractmethod
    def Begin(self, skeleton: Skeleton) -> None: ...
    @abc.abstractmethod
    def End(self) -> None: ...
    @abc.abstractmethod
    def Transform(self, vertex: clr.Reference[VertexPositionColorTextureColor]) -> None: ...


class MeshBatcher:
    def __init__(self) -> None: ...
    def AfterLastDrawPass(self) -> None: ...
    def Draw(self, device: GraphicsDevice) -> None: ...
    def NextItem(self, vertexCount: int, triangleCount: int) -> MeshItem: ...


class MeshItem:
    def __init__(self) -> None: ...
    texture : Texture2D
    textureLayers : Array_1[Texture2D]
    triangleCount : int
    triangles : Array_1[int]
    vertexCount : int
    vertices : Array_1[VertexPositionColorTextureColor]


class MixBlend(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Setup : MixBlend # 0
    First : MixBlend # 1
    Replace : MixBlend # 2
    Add : MixBlend # 3


class MixDirection(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    In : MixDirection # 0
    Out : MixDirection # 1


class PathConstraint(IUpdatable):
    @typing.overload
    def __init__(self, constraint: PathConstraint, skeleton: Skeleton) -> None: ...
    @typing.overload
    def __init__(self, data: PathConstraintData, skeleton: Skeleton) -> None: ...
    @property
    def Active(self) -> bool: ...
    @property
    def Bones(self) -> ExposedList_1[Bone]: ...
    @property
    def Data(self) -> PathConstraintData: ...
    @property
    def MixRotate(self) -> float: ...
    @MixRotate.setter
    def MixRotate(self, value: float) -> float: ...
    @property
    def MixX(self) -> float: ...
    @MixX.setter
    def MixX(self, value: float) -> float: ...
    @property
    def MixY(self) -> float: ...
    @MixY.setter
    def MixY(self, value: float) -> float: ...
    @property
    def Position(self) -> float: ...
    @Position.setter
    def Position(self, value: float) -> float: ...
    @property
    def Spacing(self) -> float: ...
    @Spacing.setter
    def Spacing(self, value: float) -> float: ...
    @property
    def Target(self) -> Slot: ...
    @Target.setter
    def Target(self, value: Slot) -> Slot: ...
    @staticmethod
    def ArraysFill(a: Array_1[float], fromIndex: int, toIndex: int, val: float) -> None: ...
    def SetToSetupPose(self) -> None: ...
    def ToString(self) -> str: ...
    def Update(self, physics: Skeleton.Physics) -> None: ...


class PathConstraintData(ConstraintData):
    def __init__(self, name: str) -> None: ...
    @property
    def Bones(self) -> ExposedList_1[BoneData]: ...
    @property
    def MixX(self) -> float: ...
    @MixX.setter
    def MixX(self, value: float) -> float: ...
    @property
    def MixY(self) -> float: ...
    @MixY.setter
    def MixY(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def OffsetRotation(self) -> float: ...
    @OffsetRotation.setter
    def OffsetRotation(self, value: float) -> float: ...
    @property
    def Order(self) -> int: ...
    @Order.setter
    def Order(self, value: int) -> int: ...
    @property
    def Position(self) -> float: ...
    @Position.setter
    def Position(self, value: float) -> float: ...
    @property
    def PositionMode(self) -> PositionMode: ...
    @PositionMode.setter
    def PositionMode(self, value: PositionMode) -> PositionMode: ...
    @property
    def RotateMix(self) -> float: ...
    @RotateMix.setter
    def RotateMix(self, value: float) -> float: ...
    @property
    def RotateMode(self) -> RotateMode: ...
    @RotateMode.setter
    def RotateMode(self, value: RotateMode) -> RotateMode: ...
    @property
    def SkinRequired(self) -> bool: ...
    @SkinRequired.setter
    def SkinRequired(self, value: bool) -> bool: ...
    @property
    def Spacing(self) -> float: ...
    @Spacing.setter
    def Spacing(self, value: float) -> float: ...
    @property
    def SpacingMode(self) -> SpacingMode: ...
    @SpacingMode.setter
    def SpacingMode(self, value: SpacingMode) -> SpacingMode: ...
    @property
    def Target(self) -> SlotData: ...
    @Target.setter
    def Target(self, value: SlotData) -> SlotData: ...


class PhysicsConstraint(IUpdatable):
    @typing.overload
    def __init__(self, constraint: PhysicsConstraint, skeleton: Skeleton) -> None: ...
    @typing.overload
    def __init__(self, data: PhysicsConstraintData, skeleton: Skeleton) -> None: ...
    bone : Bone
    @property
    def Active(self) -> bool: ...
    @property
    def Bone(self) -> Bone: ...
    @Bone.setter
    def Bone(self, value: Bone) -> Bone: ...
    @property
    def Damping(self) -> float: ...
    @Damping.setter
    def Damping(self, value: float) -> float: ...
    @property
    def Data(self) -> PhysicsConstraintData: ...
    @property
    def Gravity(self) -> float: ...
    @Gravity.setter
    def Gravity(self, value: float) -> float: ...
    @property
    def Inertia(self) -> float: ...
    @Inertia.setter
    def Inertia(self, value: float) -> float: ...
    @property
    def MassInverse(self) -> float: ...
    @MassInverse.setter
    def MassInverse(self, value: float) -> float: ...
    @property
    def Mix(self) -> float: ...
    @Mix.setter
    def Mix(self, value: float) -> float: ...
    @property
    def Strength(self) -> float: ...
    @Strength.setter
    def Strength(self, value: float) -> float: ...
    @property
    def Wind(self) -> float: ...
    @Wind.setter
    def Wind(self, value: float) -> float: ...
    def getData(self) -> PhysicsConstraintData: ...
    def Reset(self) -> None: ...
    def Rotate(self, x: float, y: float, degrees: float) -> None: ...
    def SetToSetupPose(self) -> None: ...
    def ToString(self) -> str: ...
    def Translate(self, x: float, y: float) -> None: ...
    def Update(self, physics: Skeleton.Physics) -> None: ...


class PhysicsConstraintData(ConstraintData):
    def __init__(self, name: str) -> None: ...
    @property
    def Bone(self) -> BoneData: ...
    @property
    def Damping(self) -> float: ...
    @Damping.setter
    def Damping(self, value: float) -> float: ...
    @property
    def DampingGlobal(self) -> bool: ...
    @DampingGlobal.setter
    def DampingGlobal(self, value: bool) -> bool: ...
    @property
    def Gravity(self) -> float: ...
    @Gravity.setter
    def Gravity(self, value: float) -> float: ...
    @property
    def GravityGlobal(self) -> bool: ...
    @GravityGlobal.setter
    def GravityGlobal(self, value: bool) -> bool: ...
    @property
    def Inertia(self) -> float: ...
    @Inertia.setter
    def Inertia(self, value: float) -> float: ...
    @property
    def InertiaGlobal(self) -> bool: ...
    @InertiaGlobal.setter
    def InertiaGlobal(self, value: bool) -> bool: ...
    @property
    def Limit(self) -> float: ...
    @Limit.setter
    def Limit(self, value: float) -> float: ...
    @property
    def MassGlobal(self) -> bool: ...
    @MassGlobal.setter
    def MassGlobal(self, value: bool) -> bool: ...
    @property
    def MassInverse(self) -> float: ...
    @MassInverse.setter
    def MassInverse(self, value: float) -> float: ...
    @property
    def Mix(self) -> float: ...
    @Mix.setter
    def Mix(self, value: float) -> float: ...
    @property
    def MixGlobal(self) -> bool: ...
    @MixGlobal.setter
    def MixGlobal(self, value: bool) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Order(self) -> int: ...
    @Order.setter
    def Order(self, value: int) -> int: ...
    @property
    def Rotate(self) -> float: ...
    @Rotate.setter
    def Rotate(self, value: float) -> float: ...
    @property
    def ScaleX(self) -> float: ...
    @ScaleX.setter
    def ScaleX(self, value: float) -> float: ...
    @property
    def ShearX(self) -> float: ...
    @ShearX.setter
    def ShearX(self, value: float) -> float: ...
    @property
    def SkinRequired(self) -> bool: ...
    @SkinRequired.setter
    def SkinRequired(self, value: bool) -> bool: ...
    @property
    def Step(self) -> float: ...
    @Step.setter
    def Step(self, value: float) -> float: ...
    @property
    def Strength(self) -> float: ...
    @Strength.setter
    def Strength(self, value: float) -> float: ...
    @property
    def StrengthGlobal(self) -> bool: ...
    @StrengthGlobal.setter
    def StrengthGlobal(self, value: bool) -> bool: ...
    @property
    def Wind(self) -> float: ...
    @Wind.setter
    def Wind(self, value: float) -> float: ...
    @property
    def WindGlobal(self) -> bool: ...
    @WindGlobal.setter
    def WindGlobal(self, value: bool) -> bool: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> float: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> float: ...


class PositionMode(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Fixed : PositionMode # 0
    Percent : PositionMode # 1


class RotateMode(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Tangent : RotateMode # 0
    Chain : RotateMode # 1
    ChainScale : RotateMode # 2


class Skeleton:
    @typing.overload
    def __init__(self, data: SkeletonData) -> None: ...
    @typing.overload
    def __init__(self, skeleton: Skeleton) -> None: ...
    @property
    def A(self) -> float: ...
    @A.setter
    def A(self, value: float) -> float: ...
    @property
    def B(self) -> float: ...
    @B.setter
    def B(self, value: float) -> float: ...
    @property
    def Bones(self) -> ExposedList_1[Bone]: ...
    @property
    def Data(self) -> SkeletonData: ...
    @property
    def DrawOrder(self) -> ExposedList_1[Slot]: ...
    @property
    def FlipX(self) -> bool: ...
    @FlipX.setter
    def FlipX(self, value: bool) -> bool: ...
    @property
    def FlipY(self) -> bool: ...
    @FlipY.setter
    def FlipY(self, value: bool) -> bool: ...
    @property
    def G(self) -> float: ...
    @G.setter
    def G(self, value: float) -> float: ...
    @property
    def IkConstraints(self) -> ExposedList_1[IkConstraint]: ...
    @property
    def PathConstraints(self) -> ExposedList_1[PathConstraint]: ...
    @property
    def PhysicsConstraints(self) -> ExposedList_1[PhysicsConstraint]: ...
    @property
    def R(self) -> float: ...
    @R.setter
    def R(self, value: float) -> float: ...
    @property
    def RootBone(self) -> Bone: ...
    @property
    def ScaleX(self) -> float: ...
    @ScaleX.setter
    def ScaleX(self, value: float) -> float: ...
    @property
    def ScaleY(self) -> float: ...
    @ScaleY.setter
    def ScaleY(self, value: float) -> float: ...
    @property
    def Skin(self) -> Skin: ...
    @Skin.setter
    def Skin(self, value: Skin) -> Skin: ...
    @property
    def Slots(self) -> ExposedList_1[Slot]: ...
    @property
    def Time(self) -> float: ...
    @Time.setter
    def Time(self, value: float) -> float: ...
    @property
    def TransformConstraints(self) -> ExposedList_1[TransformConstraint]: ...
    @property
    def UpdateCacheList(self) -> ExposedList_1[IUpdatable]: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> float: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> float: ...
    def FindBone(self, boneName: str) -> Bone: ...
    def FindIkConstraint(self, constraintName: str) -> IkConstraint: ...
    def FindPathConstraint(self, constraintName: str) -> PathConstraint: ...
    def FindPhysicsConstraint(self, constraintName: str) -> PhysicsConstraint: ...
    def FindSlot(self, slotName: str) -> Slot: ...
    def FindTransformConstraint(self, constraintName: str) -> TransformConstraint: ...
    def GetBounds(self, x: clr.Reference[float], y: clr.Reference[float], width: clr.Reference[float], height: clr.Reference[float], vertexBuffer: clr.Reference[Array_1[float]], clipper: SkeletonClipping = ...) -> None: ...
    def PhysicsRotate(self, x: float, y: float, degrees: float) -> None: ...
    def PhysicsTranslate(self, x: float, y: float) -> None: ...
    def SetAttachment(self, slotName: str, attachmentName: str) -> None: ...
    def SetBonesToSetupPose(self) -> None: ...
    def SetSlotsToSetupPose(self) -> None: ...
    def SetToSetupPose(self) -> None: ...
    def ToString(self) -> str: ...
    def Update(self, delta: float) -> None: ...
    def UpdateCache(self) -> None: ...
    # Skipped GetAttachment due to it being static, abstract and generic.

    GetAttachment : GetAttachment_MethodGroup
    class GetAttachment_MethodGroup:
        @typing.overload
        def __call__(self, slotIndex: int, attachmentName: str) -> Attachment:...
        @typing.overload
        def __call__(self, slotName: str, attachmentName: str) -> Attachment:...

    # Skipped SetSkin due to it being static, abstract and generic.

    SetSkin : SetSkin_MethodGroup
    class SetSkin_MethodGroup:
        @typing.overload
        def __call__(self, skinName: str) -> None:...
        @typing.overload
        def __call__(self, newSkin: Skin) -> None:...

    # Skipped UpdateWorldTransform due to it being static, abstract and generic.

    UpdateWorldTransform : UpdateWorldTransform_MethodGroup
    class UpdateWorldTransform_MethodGroup:
        @typing.overload
        def __call__(self, physics: Skeleton.Physics) -> None:...
        @typing.overload
        def __call__(self, physics: Skeleton.Physics, parent: Bone) -> None:...


    class Physics(typing.SupportsInt):
        @typing.overload
        def __init__(self, value : int) -> None: ...
        @typing.overload
        def __init__(self, value : int, force_if_true: bool) -> None: ...
        def __int__(self) -> int: ...
        
        # Values:
        None_ : Skeleton.Physics # 0
        Reset : Skeleton.Physics # 1
        Update : Skeleton.Physics # 2
        Pose : Skeleton.Physics # 3



class SkeletonClipping:
    def __init__(self) -> None: ...
    @property
    def ClippedTriangles(self) -> ExposedList_1[int]: ...
    @property
    def ClippedUVs(self) -> ExposedList_1[float]: ...
    @property
    def ClippedVertices(self) -> ExposedList_1[float]: ...
    @property
    def IsClipping(self) -> bool: ...
    def ClipStart(self, slot: Slot, clip: ClippingAttachment) -> int: ...
    @staticmethod
    def MakeClockwise(polygon: ExposedList_1[float]) -> None: ...
    # Skipped ClipEnd due to it being static, abstract and generic.

    ClipEnd : ClipEnd_MethodGroup
    class ClipEnd_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, slot: Slot) -> None:...

    # Skipped ClipTriangles due to it being static, abstract and generic.

    ClipTriangles : ClipTriangles_MethodGroup
    class ClipTriangles_MethodGroup:
        @typing.overload
        def __call__(self, vertices: Array_1[float], triangles: Array_1[int], trianglesLength: int) -> None:...
        @typing.overload
        def __call__(self, vertices: Array_1[float], triangles: Array_1[int], trianglesLength: int, uvs: Array_1[float]) -> None:...



class SkeletonData:
    def __init__(self) -> None: ...
    @property
    def Animations(self) -> ExposedList_1[Animation]: ...
    @Animations.setter
    def Animations(self, value: ExposedList_1[Animation]) -> ExposedList_1[Animation]: ...
    @property
    def AudioPath(self) -> str: ...
    @AudioPath.setter
    def AudioPath(self, value: str) -> str: ...
    @property
    def Bones(self) -> ExposedList_1[BoneData]: ...
    @property
    def DefaultSkin(self) -> Skin: ...
    @DefaultSkin.setter
    def DefaultSkin(self, value: Skin) -> Skin: ...
    @property
    def Events(self) -> ExposedList_1[EventData]: ...
    @Events.setter
    def Events(self, value: ExposedList_1[EventData]) -> ExposedList_1[EventData]: ...
    @property
    def Fps(self) -> float: ...
    @Fps.setter
    def Fps(self, value: float) -> float: ...
    @property
    def Hash(self) -> str: ...
    @Hash.setter
    def Hash(self, value: str) -> str: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def IkConstraints(self) -> ExposedList_1[IkConstraintData]: ...
    @IkConstraints.setter
    def IkConstraints(self, value: ExposedList_1[IkConstraintData]) -> ExposedList_1[IkConstraintData]: ...
    @property
    def ImagesPath(self) -> str: ...
    @ImagesPath.setter
    def ImagesPath(self, value: str) -> str: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def PathConstraints(self) -> ExposedList_1[PathConstraintData]: ...
    @PathConstraints.setter
    def PathConstraints(self, value: ExposedList_1[PathConstraintData]) -> ExposedList_1[PathConstraintData]: ...
    @property
    def PhysicsConstraints(self) -> ExposedList_1[PhysicsConstraintData]: ...
    @PhysicsConstraints.setter
    def PhysicsConstraints(self, value: ExposedList_1[PhysicsConstraintData]) -> ExposedList_1[PhysicsConstraintData]: ...
    @property
    def ReferenceScale(self) -> float: ...
    @ReferenceScale.setter
    def ReferenceScale(self, value: float) -> float: ...
    @property
    def Skins(self) -> ExposedList_1[Skin]: ...
    @Skins.setter
    def Skins(self, value: ExposedList_1[Skin]) -> ExposedList_1[Skin]: ...
    @property
    def Slots(self) -> ExposedList_1[SlotData]: ...
    @property
    def TransformConstraints(self) -> ExposedList_1[TransformConstraintData]: ...
    @TransformConstraints.setter
    def TransformConstraints(self, value: ExposedList_1[TransformConstraintData]) -> ExposedList_1[TransformConstraintData]: ...
    @property
    def Version(self) -> str: ...
    @Version.setter
    def Version(self, value: str) -> str: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> float: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> float: ...
    def FindAnimation(self, animationName: str) -> Animation: ...
    def FindBone(self, boneName: str) -> BoneData: ...
    def FindEvent(self, eventDataName: str) -> EventData: ...
    def FindIkConstraint(self, constraintName: str) -> IkConstraintData: ...
    def FindPathConstraint(self, constraintName: str) -> PathConstraintData: ...
    def FindPhysicsConstraint(self, constraintName: str) -> PhysicsConstraintData: ...
    def FindSkin(self, skinName: str) -> Skin: ...
    def FindSlot(self, slotName: str) -> SlotData: ...
    def FindTransformConstraint(self, constraintName: str) -> TransformConstraintData: ...
    def ToString(self) -> str: ...


class SkeletonRenderer:
    def __init__(self, device: GraphicsDevice, scissorTest: bool = ...) -> None: ...
    @property
    def Batcher(self) -> MeshBatcher: ...
    @property
    def Effect(self) -> Effect: ...
    @Effect.setter
    def Effect(self, value: Effect) -> Effect: ...
    @property
    def PremultipliedAlpha(self) -> bool: ...
    @PremultipliedAlpha.setter
    def PremultipliedAlpha(self, value: bool) -> bool: ...
    @property
    def SkeletonClipping(self) -> SkeletonClipping: ...
    @property
    def VertexEffect(self) -> IVertexEffect: ...
    @VertexEffect.setter
    def VertexEffect(self, value: IVertexEffect) -> IVertexEffect: ...
    @property
    def Z(self) -> float: ...
    @Z.setter
    def Z(self, value: float) -> float: ...
    @property
    def ZSpacing(self) -> float: ...
    @ZSpacing.setter
    def ZSpacing(self, value: float) -> float: ...
    def Begin(self) -> None: ...
    def Draw(self, skeleton: Skeleton) -> None: ...
    def End(self) -> None: ...


class Skin:
    def __init__(self, name: str) -> None: ...
    @property
    def Attachments(self) -> ICollection_1[Skin.SkinEntry]: ...
    @property
    def Bones(self) -> ExposedList_1[BoneData]: ...
    @property
    def Constraints(self) -> ExposedList_1[ConstraintData]: ...
    @property
    def Name(self) -> str: ...
    def AddSkin(self, skin: Skin) -> None: ...
    def Clear(self) -> None: ...
    def CopySkin(self, skin: Skin) -> None: ...
    def GetAttachment(self, slotIndex: int, name: str) -> Attachment: ...
    def GetAttachments(self, slotIndex: int, attachments: List_1[Skin.SkinEntry]) -> None: ...
    def RemoveAttachment(self, slotIndex: int, name: str) -> None: ...
    def SetAttachment(self, slotIndex: int, name: str, attachment: Attachment) -> None: ...
    def ToString(self) -> str: ...

    class SkinEntry:
        def __init__(self, slotIndex: int, name: str, attachment: Attachment) -> None: ...
        @property
        def Attachment(self) -> Attachment: ...
        @property
        def Name(self) -> str: ...
        @property
        def SlotIndex(self) -> int: ...



class Slot:
    @typing.overload
    def __init__(self, data: SlotData, bone: Bone) -> None: ...
    @typing.overload
    def __init__(self, slot: Slot, bone: Bone) -> None: ...
    @property
    def A(self) -> float: ...
    @A.setter
    def A(self, value: float) -> float: ...
    @property
    def Attachment(self) -> Attachment: ...
    @Attachment.setter
    def Attachment(self, value: Attachment) -> Attachment: ...
    @property
    def B(self) -> float: ...
    @B.setter
    def B(self, value: float) -> float: ...
    @property
    def B2(self) -> float: ...
    @B2.setter
    def B2(self, value: float) -> float: ...
    @property
    def Bone(self) -> Bone: ...
    @property
    def Data(self) -> SlotData: ...
    @property
    def Deform(self) -> ExposedList_1[float]: ...
    @Deform.setter
    def Deform(self, value: ExposedList_1[float]) -> ExposedList_1[float]: ...
    @property
    def G(self) -> float: ...
    @G.setter
    def G(self, value: float) -> float: ...
    @property
    def G2(self) -> float: ...
    @G2.setter
    def G2(self, value: float) -> float: ...
    @property
    def HasSecondColor(self) -> bool: ...
    @HasSecondColor.setter
    def HasSecondColor(self, value: bool) -> bool: ...
    @property
    def R(self) -> float: ...
    @R.setter
    def R(self, value: float) -> float: ...
    @property
    def R2(self) -> float: ...
    @R2.setter
    def R2(self, value: float) -> float: ...
    @property
    def SequenceIndex(self) -> int: ...
    @SequenceIndex.setter
    def SequenceIndex(self, value: int) -> int: ...
    @property
    def Skeleton(self) -> Skeleton: ...
    def ClampColor(self) -> None: ...
    def ClampSecondColor(self) -> None: ...
    def SetToSetupPose(self) -> None: ...
    def ToString(self) -> str: ...


class SlotData:
    def __init__(self, index: int, name: str, boneData: BoneData) -> None: ...
    @property
    def A(self) -> float: ...
    @A.setter
    def A(self, value: float) -> float: ...
    @property
    def AttachmentName(self) -> str: ...
    @AttachmentName.setter
    def AttachmentName(self, value: str) -> str: ...
    @property
    def B(self) -> float: ...
    @B.setter
    def B(self, value: float) -> float: ...
    @property
    def B2(self) -> float: ...
    @B2.setter
    def B2(self, value: float) -> float: ...
    @property
    def BlendMode(self) -> BlendMode: ...
    @BlendMode.setter
    def BlendMode(self, value: BlendMode) -> BlendMode: ...
    @property
    def BoneData(self) -> BoneData: ...
    @property
    def G(self) -> float: ...
    @G.setter
    def G(self, value: float) -> float: ...
    @property
    def G2(self) -> float: ...
    @G2.setter
    def G2(self, value: float) -> float: ...
    @property
    def HasSecondColor(self) -> bool: ...
    @HasSecondColor.setter
    def HasSecondColor(self, value: bool) -> bool: ...
    @property
    def Index(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def R(self) -> float: ...
    @R.setter
    def R(self, value: float) -> float: ...
    @property
    def R2(self) -> float: ...
    @R2.setter
    def R2(self, value: float) -> float: ...
    def ToString(self) -> str: ...


class SpacingMode(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Length : SpacingMode # 0
    Fixed : SpacingMode # 1
    Percent : SpacingMode # 2
    Proportional : SpacingMode # 3


class TextureFilter(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Nearest : TextureFilter # 0
    Linear : TextureFilter # 1
    MipMap : TextureFilter # 2
    MipMapNearestNearest : TextureFilter # 3
    MipMapLinearNearest : TextureFilter # 4
    MipMapNearestLinear : TextureFilter # 5
    MipMapLinearLinear : TextureFilter # 6


class TextureLoader(typing.Protocol):
    @abc.abstractmethod
    def Load(self, page: AtlasPage, path: str) -> None: ...
    @abc.abstractmethod
    def Unload(self, texture: typing.Any) -> None: ...


class TextureRegion:
    def __init__(self) -> None: ...
    height : int
    u : float
    u2 : float
    v : float
    v2 : float
    width : int
    @property
    def OriginalHeight(self) -> int: ...
    @property
    def OriginalWidth(self) -> int: ...


class TextureWrap(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    MirroredRepeat : TextureWrap # 0
    ClampToEdge : TextureWrap # 1
    Repeat : TextureWrap # 2


class Timeline(abc.ABC):
    def __init__(self, frameCount: int, propertyIds: Array_1[str]) -> None: ...
    @property
    def Duration(self) -> float: ...
    @property
    def FrameCount(self) -> int: ...
    @property
    def FrameEntries(self) -> int: ...
    @property
    def Frames(self) -> Array_1[float]: ...
    @property
    def PropertyIds(self) -> Array_1[str]: ...
    @abc.abstractmethod
    def Apply(self, skeleton: Skeleton, lastTime: float, time: float, events: ExposedList_1[Event], alpha: float, blend: MixBlend, direction: MixDirection) -> None: ...


class TrackEntry:
    def __init__(self) -> None: ...
    @property
    def Alpha(self) -> float: ...
    @Alpha.setter
    def Alpha(self, value: float) -> float: ...
    @property
    def AlphaAttachmentThreshold(self) -> float: ...
    @AlphaAttachmentThreshold.setter
    def AlphaAttachmentThreshold(self, value: float) -> float: ...
    @property
    def Animation(self) -> Animation: ...
    @property
    def AnimationEnd(self) -> float: ...
    @AnimationEnd.setter
    def AnimationEnd(self, value: float) -> float: ...
    @property
    def AnimationLast(self) -> float: ...
    @AnimationLast.setter
    def AnimationLast(self, value: float) -> float: ...
    @property
    def AnimationStart(self) -> float: ...
    @AnimationStart.setter
    def AnimationStart(self, value: float) -> float: ...
    @property
    def AnimationTime(self) -> float: ...
    @property
    def Delay(self) -> float: ...
    @Delay.setter
    def Delay(self, value: float) -> float: ...
    @property
    def EventThreshold(self) -> float: ...
    @EventThreshold.setter
    def EventThreshold(self, value: float) -> float: ...
    @property
    def HoldPrevious(self) -> bool: ...
    @HoldPrevious.setter
    def HoldPrevious(self, value: bool) -> bool: ...
    @property
    def InterruptAlpha(self) -> float: ...
    @property
    def IsComplete(self) -> bool: ...
    @property
    def IsEmptyAnimation(self) -> bool: ...
    @property
    def IsNextReady(self) -> bool: ...
    @property
    def Loop(self) -> bool: ...
    @Loop.setter
    def Loop(self, value: bool) -> bool: ...
    @property
    def MixAttachmentThreshold(self) -> float: ...
    @MixAttachmentThreshold.setter
    def MixAttachmentThreshold(self, value: float) -> float: ...
    @property
    def MixBlend(self) -> MixBlend: ...
    @MixBlend.setter
    def MixBlend(self, value: MixBlend) -> MixBlend: ...
    @property
    def MixDrawOrderThreshold(self) -> float: ...
    @MixDrawOrderThreshold.setter
    def MixDrawOrderThreshold(self, value: float) -> float: ...
    @property
    def MixDuration(self) -> float: ...
    @MixDuration.setter
    def MixDuration(self, value: float) -> float: ...
    @property
    def MixingFrom(self) -> TrackEntry: ...
    @property
    def MixingTo(self) -> TrackEntry: ...
    @property
    def MixTime(self) -> float: ...
    @MixTime.setter
    def MixTime(self, value: float) -> float: ...
    @property
    def Next(self) -> TrackEntry: ...
    @property
    def Previous(self) -> TrackEntry: ...
    @property
    def Reverse(self) -> bool: ...
    @Reverse.setter
    def Reverse(self, value: bool) -> bool: ...
    @property
    def ShortestRotation(self) -> bool: ...
    @ShortestRotation.setter
    def ShortestRotation(self, value: bool) -> bool: ...
    @property
    def TimeScale(self) -> float: ...
    @TimeScale.setter
    def TimeScale(self, value: float) -> float: ...
    @property
    def TrackComplete(self) -> float: ...
    @property
    def TrackEnd(self) -> float: ...
    @TrackEnd.setter
    def TrackEnd(self, value: float) -> float: ...
    @property
    def TrackIndex(self) -> int: ...
    @property
    def TrackTime(self) -> float: ...
    @TrackTime.setter
    def TrackTime(self, value: float) -> float: ...
    @property
    def WasApplied(self) -> bool: ...
    def AllowImmediateQueue(self) -> None: ...
    def Reset(self) -> None: ...
    def ResetRotationDirections(self) -> None: ...
    def SetMixDuration(self, mixDuration: float, delay: float) -> None: ...
    def ToString(self) -> str: ...


class TransformConstraint(IUpdatable):
    @typing.overload
    def __init__(self, constraint: TransformConstraint, skeleton: Skeleton) -> None: ...
    @typing.overload
    def __init__(self, data: TransformConstraintData, skeleton: Skeleton) -> None: ...
    @property
    def Active(self) -> bool: ...
    @property
    def Bones(self) -> ExposedList_1[Bone]: ...
    @property
    def Data(self) -> TransformConstraintData: ...
    @property
    def MixRotate(self) -> float: ...
    @MixRotate.setter
    def MixRotate(self, value: float) -> float: ...
    @property
    def MixScaleX(self) -> float: ...
    @MixScaleX.setter
    def MixScaleX(self, value: float) -> float: ...
    @property
    def MixScaleY(self) -> float: ...
    @MixScaleY.setter
    def MixScaleY(self, value: float) -> float: ...
    @property
    def MixShearY(self) -> float: ...
    @MixShearY.setter
    def MixShearY(self, value: float) -> float: ...
    @property
    def MixX(self) -> float: ...
    @MixX.setter
    def MixX(self, value: float) -> float: ...
    @property
    def MixY(self) -> float: ...
    @MixY.setter
    def MixY(self, value: float) -> float: ...
    @property
    def Target(self) -> Bone: ...
    @Target.setter
    def Target(self, value: Bone) -> Bone: ...
    def SetToSetupPose(self) -> None: ...
    def ToString(self) -> str: ...
    def Update(self, physics: Skeleton.Physics) -> None: ...


class TransformConstraintData(ConstraintData):
    def __init__(self, name: str) -> None: ...
    @property
    def Bones(self) -> ExposedList_1[BoneData]: ...
    @property
    def Local(self) -> bool: ...
    @Local.setter
    def Local(self, value: bool) -> bool: ...
    @property
    def MixRotate(self) -> float: ...
    @MixRotate.setter
    def MixRotate(self, value: float) -> float: ...
    @property
    def MixScaleX(self) -> float: ...
    @MixScaleX.setter
    def MixScaleX(self, value: float) -> float: ...
    @property
    def MixScaleY(self) -> float: ...
    @MixScaleY.setter
    def MixScaleY(self, value: float) -> float: ...
    @property
    def MixShearY(self) -> float: ...
    @MixShearY.setter
    def MixShearY(self, value: float) -> float: ...
    @property
    def MixX(self) -> float: ...
    @MixX.setter
    def MixX(self, value: float) -> float: ...
    @property
    def MixY(self) -> float: ...
    @MixY.setter
    def MixY(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def OffsetRotation(self) -> float: ...
    @OffsetRotation.setter
    def OffsetRotation(self, value: float) -> float: ...
    @property
    def OffsetScaleX(self) -> float: ...
    @OffsetScaleX.setter
    def OffsetScaleX(self, value: float) -> float: ...
    @property
    def OffsetScaleY(self) -> float: ...
    @OffsetScaleY.setter
    def OffsetScaleY(self, value: float) -> float: ...
    @property
    def OffsetShearY(self) -> float: ...
    @OffsetShearY.setter
    def OffsetShearY(self, value: float) -> float: ...
    @property
    def OffsetX(self) -> float: ...
    @OffsetX.setter
    def OffsetX(self, value: float) -> float: ...
    @property
    def OffsetY(self) -> float: ...
    @OffsetY.setter
    def OffsetY(self, value: float) -> float: ...
    @property
    def Order(self) -> int: ...
    @Order.setter
    def Order(self, value: int) -> int: ...
    @property
    def Relative(self) -> bool: ...
    @Relative.setter
    def Relative(self, value: bool) -> bool: ...
    @property
    def SkinRequired(self) -> bool: ...
    @SkinRequired.setter
    def SkinRequired(self, value: bool) -> bool: ...
    @property
    def Target(self) -> BoneData: ...
    @Target.setter
    def Target(self, value: BoneData) -> BoneData: ...


class VertexAttachment(Attachment):
    @typing.overload
    def __init__(self, name: str) -> None: ...
    @typing.overload
    def __init__(self, other: VertexAttachment) -> None: ...
    @property
    def Bones(self) -> Array_1[int]: ...
    @Bones.setter
    def Bones(self, value: Array_1[int]) -> Array_1[int]: ...
    @property
    def Id(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def TimelineAttachment(self) -> VertexAttachment: ...
    @TimelineAttachment.setter
    def TimelineAttachment(self, value: VertexAttachment) -> VertexAttachment: ...
    @property
    def Vertices(self) -> Array_1[float]: ...
    @Vertices.setter
    def Vertices(self, value: Array_1[float]) -> Array_1[float]: ...
    @property
    def WorldVerticesLength(self) -> int: ...
    @WorldVerticesLength.setter
    def WorldVerticesLength(self, value: int) -> int: ...
    # Skipped ComputeWorldVertices due to it being static, abstract and generic.

    ComputeWorldVertices : ComputeWorldVertices_MethodGroup
    class ComputeWorldVertices_MethodGroup:
        @typing.overload
        def __call__(self, slot: Slot, worldVertices: Array_1[float]) -> None:...
        @typing.overload
        def __call__(self, slot: Slot, start: int, count: int, worldVertices: Array_1[float], offset: int, stride: int = ...) -> None:...



class VertexPositionColorTextureColor(IVertexType):
    Color : Color
    Color2 : Color
    Position : Vector3
    TextureCoordinate : Vector2
    VertexDeclaration : VertexDeclaration

