window.PGvZData = (() => {
    const seedTypes = [
        { label: '豌豆射手', value: 'Peashooter', en: 'Peashooter' },
        { label: '向日葵', value: 'Sunflower', en: 'Sunflower' },
        { label: '樱桃炸弹', value: 'Cherrybomb', en: 'Cherrybomb' },
        { label: '坚果墙', value: 'Wallnut', en: 'Wallnut' },
        { label: '土豆雷', value: 'Potatomine', en: 'Potatomine' },
        { label: '雪花豌豆', value: 'Snowpea', en: 'Snowpea' },
        { label: '大嘴花', value: 'Chomper', en: 'Chomper' },
        { label: '双发射手', value: 'Repeater', en: 'Repeater' },
        { label: '小喷菇', value: 'Puffshroom', en: 'Puffshroom' },
        { label: '阳光菇', value: 'Sunshroom', en: 'Sunshroom' },
        { label: '大喷菇', value: 'Fumeshroom', en: 'Fumeshroom' },
        { label: '墓碑吞噬者', value: 'Gravebuster', en: 'Gravebuster' },
        { label: '魅惑菇', value: 'Hypnoshroom', en: 'Hypnoshroom' },
        { label: '胆小菇', value: 'Scaredyshroom', en: 'Scaredyshroom' },
        { label: '寒冰菇', value: 'Iceshroom', en: 'Iceshroom' },
        { label: '毁灭菇', value: 'Doomshroom', en: 'Doomshroom' },
        { label: '睡莲', value: 'Lilypad', en: 'Lilypad' },
        { label: '窝瓜', value: 'Squash', en: 'Squash' },
        { label: '三线射手', value: 'Threepeater', en: 'Threepeater' },
        { label: '缠绕水草', value: 'Tanglekelp', en: 'Tanglekelp' },
        { label: '火爆辣椒', value: 'Jalapeno', en: 'Jalapeno' },
        { label: '地刺', value: 'Spikeweed', en: 'Spikeweed' },
        { label: '火炬树桩', value: 'Torchwood', en: 'Torchwood' },
        { label: '高坚果', value: 'Tallnut', en: 'Tallnut' },
        { label: '海蘑菇', value: 'Seashroom', en: 'Seashroom' },
        { label: '路灯花', value: 'Plantern', en: 'Plantern' },
        { label: '仙人掌', value: 'Cactus', en: 'Cactus' },
        { label: '三叶草', value: 'Blover', en: 'Blover' },
        { label: '裂荚射手', value: 'Splitpea', en: 'Splitpea' },
        { label: '杨桃', value: 'Starfruit', en: 'Starfruit' },
        { label: '南瓜头', value: 'Pumpkinshell', en: 'Pumpkinshell' },
        { label: '磁力菇', value: 'Magnetshroom', en: 'Magnetshroom' },
        { label: '卷心菜投手', value: 'Cabbagepult', en: 'Cabbagepult' },
        { label: '花盆', value: 'Flowerpot', en: 'Flowerpot' },
        { label: '玉米投手', value: 'Kernelpult', en: 'Kernelpult' },
        { label: '咖啡豆', value: 'InstantCoffee', en: 'Instant Coffee' },
        { label: '大蒜', value: 'Garlic', en: 'Garlic' },
        { label: '莴苣', value: 'Umbrella', en: 'Umbrella' },
        { label: '金盏花', value: 'Marigold', en: 'Marigold' },
        { label: '西瓜投手', value: 'Melonpult', en: 'Melonpult' },
        { label: '机枪射手', value: 'Gatlingpea', en: 'Gatlingpea' },
        { label: '双子向日葵', value: 'Twinsunflower', en: 'Twinsunflower' },
        { label: '忧郁蘑菇', value: 'Gloomshroom', en: 'Gloomshroom' },
        { label: '猫尾草', value: 'Cattail', en: 'Cattail' },
        { label: '冰瓜', value: 'Wintermelon', en: 'Wintermelon' },
        { label: '吸金磁', value: 'GoldMagnet', en: 'Gold Magnet' },
        { label: '钢地刺', value: 'Spikerock', en: 'Spikerock' },
        { label: '玉米加农炮', value: 'Cobcannon', en: 'Cobcannon' },
        { label: '超级大嘴花', value: 'SuperChomper', en: 'Super Chomper' },
        { label: '泡椒', value: 'PickledPepper', en: 'Pickled Pepper' },
        { label: '火蘑菇', value: 'FireShroom', en: 'Fire Shroom' },
        { label: '龙舌兰', value: 'Agave', en: 'Agave' },
        { label: '火红莲', value: 'Endoflame', en: 'Endoflame' },
        { label: '模仿者', value: 'Imitater', en: 'Imitater' },
        { label: '爆炸坚果', value: 'ExplodeONut', en: 'Explode ONut' },
        { label: '巨型坚果', value: 'GiantWallnut', en: 'Giant Wallnut' },
        { label: '反向双发射手', value: 'Leftpeater', en: 'Leftpeater' },
        { label: '随机植物', value: 'ImitaterRandomPlant', en: 'Imitater Random Plant' },
        { label: '随机僵尸', value: 'ImitaterRandomZombie', en: 'Imitater Random Zombie' },
        { label: '魅惑香蒲', value: 'HypnoCattail', en: 'Hypno Cattail' },
        { label: '向日葵豌豆', value: 'SunflowerPea', en: 'Sunflower Pea' },
        { label: '豌豆坚果', value: 'PeaWallnut', en: 'Pea Wallnut' },
        { label: '向日葵坚果', value: 'SunflowerWallnut', en: 'Sunflower Wallnut' },
        { label: '冰坚果', value: 'IceWallnut', en: 'Ice Wallnut' },
        { label: '普通僵尸', value: 'ZombieNormal', en: 'Zombie Normal' },
        { label: '路障僵尸', value: 'ZombieTrafficCone', en: 'Zombie Traffic Cone' },
        { label: '撑杆僵尸', value: 'ZombiePolevaulter', en: 'Zombie Polevaulter' },
        { label: '铁桶僵尸', value: 'ZombiePail', en: 'Zombie Pail' },
        { label: '扶梯僵尸', value: 'ZombieLadder', en: 'Zombie Ladder' },
        { label: '矿工僵尸', value: 'ZombieDigger', en: 'Zombie Digger' },
        { label: '蹦极僵尸', value: 'ZombieBungee', en: 'Zombie Bungee' },
        { label: '橄榄球僵尸', value: 'ZombieFootball', en: 'Zombie Football' },
        { label: '气球僵尸', value: 'ZombieBalloon', en: 'Zombie Balloon' },
        { label: '铁栅门僵尸', value: 'ZombieScreenDoor', en: 'Zombie Screen Door' },
        { label: '冰车僵尸', value: 'Zomboni', en: 'Zomboni' },
        { label: '跳跳僵尸', value: 'ZombiePogo', en: 'Zombie Pogo' },
        { label: '舞王僵尸', value: 'ZombieDancer', en: 'Zombie Dancer' },
        { label: '巨人僵尸', value: 'ZombieGargantuar', en: 'Zombie Gargantuar' },
        { label: '小鬼僵尸', value: 'ZombieImp', en: 'Zombie Imp' },
    ];

    const zombieTypes = [
        { label: '普通僵尸', value: 'Normal', en: 'Normal' },
        { label: '旗帜僵尸', value: 'Flag', en: 'Flag' },
        { label: '路障僵尸', value: 'TrafficCone', en: 'Traffic Cone' },
        { label: '撑杆僵尸', value: 'Polevaulter', en: 'Polevaulter' },
        { label: '铁桶僵尸', value: 'Pail', en: 'Pail' },
        { label: '读报僵尸', value: 'Newspaper', en: 'Newspaper' },
        { label: '铁栅门僵尸', value: 'Door', en: 'Door' },
        { label: '橄榄球僵尸', value: 'Football', en: 'Football' },
        { label: '舞王僵尸', value: 'Dancer', en: 'Dancer' },
        { label: '伴舞僵尸', value: 'BackupDancer', en: 'Backup Dancer' },
        { label: '救生圈僵尸', value: 'DuckyTube', en: 'Ducky Tube' },
        { label: '潜水僵尸', value: 'Snorkel', en: 'Snorkel' },
        { label: '冰车僵尸', value: 'Zamboni', en: 'Zamboni' },
        { label: '雪橇小队', value: 'Bobsled', en: 'Bobsled' },
        { label: '海豚僵尸', value: 'DolphinRider', en: 'Dolphin Rider' },
        { label: '玩偶匣僵尸', value: 'JackInTheBox', en: 'Jack In The Box' },
        { label: '气球僵尸', value: 'Balloon', en: 'Balloon' },
        { label: '矿工僵尸', value: 'Digger', en: 'Digger' },
        { label: '跳跳僵尸', value: 'Pogo', en: 'Pogo' },
        { label: '雪人僵尸', value: 'Yeti', en: 'Yeti' },
        { label: '蹦极僵尸', value: 'Bungee', en: 'Bungee' },
        { label: '扶梯僵尸', value: 'Ladder', en: 'Ladder' },
        { label: '投石车僵尸', value: 'Catapult', en: 'Catapult' },
        { label: '巨人僵尸', value: 'Gargantuar', en: 'Gargantuar' },
        { label: '小鬼僵尸', value: 'Imp', en: 'Imp' },
        { label: '僵王博士', value: 'Boss', en: 'Boss' },
        { label: '豌豆僵尸', value: 'PeaHead', en: 'Pea Head' },
        { label: '坚果僵尸', value: 'WallnutHead', en: 'Wallnut Head' },
        { label: '辣椒僵尸', value: 'JalapenoHead', en: 'Jalapeno Head' },
        { label: '机枪豌豆僵尸', value: 'GatlingHead', en: 'Gatling Head' },
        { label: '窝瓜僵尸', value: 'SquashHead', en: 'Squash Head' },
        { label: '高坚果僵尸', value: 'TallnutHead', en: 'Tallnut Head' },
        { label: '红眼巨人僵尸', value: 'RedeyeGargantuar', en: 'Redeye Gargantuar' },
        { label: '机械巨人僵尸', value: 'RobotTitan', en: 'Robot Titan' },
        { label: '红眼机械巨人僵尸', value: 'RedeyeRobotTitan', en: 'Redeye Robot Titan' },
        { label: '武僧僵尸', value: 'Monk', en: 'Monk' },
        { label: '黑橄榄僵尸', value: 'FootballPremium', en: 'Football Premium' },
        { label: '女忍者僵尸', value: 'Ninja', en: 'Ninja' },
        { label: '天尸', value: 'Talisman', en: 'Talisman' },
        { label: '螺旋桨僵尸', value: 'Propeller', en: 'Propeller' },
    ];

    const setZombieTypes = [
        { label: '路障僵尸', value: 'TrafficCone', en: 'Traffic Cone' },
        { label: '撑杆僵尸', value: 'Polevaulter', en: 'Polevaulter' },
        { label: '铁桶僵尸', value: 'Pail', en: 'Pail' },
        { label: '读报僵尸', value: 'Newspaper', en: 'Newspaper' },
        { label: '铁栅门僵尸', value: 'Door', en: 'Door' },
        { label: '橄榄球僵尸', value: 'Football', en: 'Football' },
        { label: '舞王僵尸', value: 'Dancer', en: 'Dancer' },
        { label: '潜水僵尸', value: 'Snorkel', en: 'Snorkel' },
        { label: '冰车僵尸', value: 'Zamboni', en: 'Zamboni' },
        { label: '海豚僵尸', value: 'DolphinRider', en: 'Dolphin Rider' },
        { label: '玩偶匣僵尸', value: 'JackInTheBox', en: 'Jack In The Box' },
        { label: '气球僵尸', value: 'Balloon', en: 'Balloon' },
        { label: '矿工僵尸', value: 'Digger', en: 'Digger' },
        { label: '跳跳僵尸', value: 'Pogo', en: 'Pogo' },
        { label: '蹦极僵尸', value: 'Bungee', en: 'Bungee' },
        { label: '扶梯僵尸', value: 'Ladder', en: 'Ladder' },
        { label: '投石车僵尸', value: 'Catapult', en: 'Catapult' },
        { label: '巨人僵尸', value: 'Gargantuar', en: 'Gargantuar' },
        { label: '红眼巨人僵尸', value: 'RedeyeGargantuar', en: 'Redeye Gargantuar' },
        { label: '机械巨人僵尸', value: 'RobotTitan', en: 'Robot Titan' },
        { label: '红眼机械巨人僵尸', value: 'RedeyeRobotTitan', en: 'Redeye Robot Titan' },
        { label: '武僧僵尸', value: 'Monk', en: 'Monk' },
        { label: '黑橄榄僵尸', value: 'FootballPremium', en: 'Football Premium' },
        { label: '女忍者僵尸', value: 'Ninja', en: 'Ninja' },
        { label: '天尸', value: 'Talisman', en: 'Talisman' },
        { label: '螺旋桨僵尸', value: 'Propeller', en: 'Propeller' },
    ];

    const selectRows = [
        { label: '全部', value: -1, en: 'All' },
        { label: '1', value: 0, en: '1' },
        { label: '2', value: 1, en: '2' },
        { label: '3', value: 2, en: '3' },
        { label: '4', value: 3, en: '4' },
        { label: '5', value: 4, en: '5' },
        { label: '6', value: 5, en: '6' },
    ];

    const selectCols = [
        { label: '全部', value: -1, en: 'All' },
        { label: '1', value: 0, en: '1' },
        { label: '2', value: 1, en: '2' },
        { label: '3', value: 2, en: '3' },
        { label: '4', value: 3, en: '4' },
        { label: '5', value: 4, en: '5' },
        { label: '6', value: 5, en: '6' },
        { label: '7', value: 6, en: '7' },
        { label: '8', value: 7, en: '8' },
        { label: '9', value: 8, en: '9' },
    ];

    const packetIdx = [
        { label: '1', value: 0, en: '1' },
        { label: '2', value: 1, en: '2' },
        { label: '3', value: 2, en: '3' },
        { label: '4', value: 3, en: '4' },
        { label: '5', value: 4, en: '5' },
        { label: '6', value: 5, en: '6' },
        { label: '7', value: 6, en: '7' },
        { label: '8', value: 7, en: '8' },
        { label: '9', value: 8, en: '9' },
        { label: '10', value: 9, en: '10' },
    ];

    // 会出问题，或者没什么意义的暂时不给相关功能
    const gridItemTypes = [
        { label: '墓碑', value: 'Gravestone', en: 'Gravestone' },
        { label: '弹坑', value: 'Crater', en: 'Crater' },
        { label: '梯子', value: 'Ladder', en: 'Ladder' },
        { label: '罐子', value: 'ScaryPot', en: 'Vase' },
        { label: '钉耙', value: 'Rake', en: 'Rake' },
        { label: '封印符咒', value: 'Talisman', en: 'Talisman' },
        { label: '移动符咒', value: 'TalismanMove', en: 'Moving Talisman' },
    ];

    const easyPlaceModeList = [
        { label: '植物', value: 'plant', en: 'Plant' },
        { label: '僵尸', value: 'zombie', en: 'Zombie' },
        { label: '场地物品', value: 'griditem', en: 'Grid Item' },
        { label: '掉落物', value: 'coin', en: 'Drop' },
        { label: '割草机', value: 'mower', en: 'Mower' },
        { label: '传送门', value: 'portal', en: 'Portal' },
    ];

    const scaryPotType = [
        { label: '空', value: 'None', en: 'Empty' },
        { label: '植物', value: 'Seed', en: 'Seed' },
        { label: '僵尸', value: 'Zombie', en: 'Zombie' },
        { label: '1阳光', value: 'Sun1', en: '1 Sun' },
        { label: '2阳光', value: 'Sun2', en: '2 Sun' },
        { label: '3阳光', value: 'Sun3', en: '3 Sun' },
    ];

    const scaryPotAppearance = [
        { label: '未知', value: 'ScaryPotQuestion', en: 'Question Vase' },
        { label: '植物', value: 'ScaryPotLeaf', en: 'Plant Vase' },
        { label: '僵尸', value: 'ScaryPotZombie', en: 'Zombie Vase' },
    ];

    const coinTypes = [
        { label: '银币', value: 'Silver', en: 'Silver Coin' },
        { label: '金币', value: 'Gold', en: 'Gold Coin' },
        { label: '钻石', value: 'Diamond', en: 'Diamond' },
        { label: '阳光', value: 'Sun', en: 'Sun' },
        { label: '小阳光', value: 'Smallsun', en: 'Small Sun' },
        { label: '大阳光', value: 'Largesun', en: 'Large Sun' },
        { label: '种子包', value: 'FinalSeedPacket', en: 'Seed Packet' },
        { label: '奖杯', value: 'Trophy', en: 'Trophy' },
        { label: '铲子', value: 'Shovel', en: 'Shovel' },
        { label: '图鉴', value: 'Almanac', en: 'Almanac' },
        { label: '车钥匙', value: 'Carkeys', en: 'Car Keys' },
        { label: '水壶', value: 'WateringCan', en: 'Watering Can' },
        { label: '玉米卷', value: 'Taco', en: 'Taco' },
        { label: '纸条', value: 'Note', en: 'Note' },
        { label: '卡片', value: 'UsableSeedPacket', en: 'Seed Card' },
        { label: '盆栽', value: 'PresentPlant', en: 'Potted Plant' },
        { label: '钱袋', value: 'AwardMoneyBag', en: 'Money Bag' },
        { label: '礼物', value: 'AwardPresent', en: 'Present' },
        { label: '钻石袋', value: 'AwardBagDiamond', en: 'Diamond Bag' },
        { label: '巧克力', value: 'Chocolate', en: 'Chocolate' },
        { label: '奖励巧克力', value: 'AwardChocolate', en: 'Bonus Chocolate' },
        { label: '小游戏模式礼物', value: 'PresentMinigames', en: 'Minigames Gift' },
        { label: '解密模式礼物', value: 'PresentPuzzleMode', en: 'Puzzle Mode Gift' },
        { label: '培根', value: 'Bacon', en: 'Bacon' },
        { label: '银向日葵奖杯', value: 'AwardSliverSunflower', en: 'Silver Sunflower Trophy' },
        { label: '金向日葵奖杯', value: 'AwardGoldSunflower', en: 'Gold Sunflower Trophy' },
        { label: '微型阳光', value: 'Tinysun', en: 'Tiny Sun' },
        { label: '十个盆栽礼物', value: 'Award10PottedPlants', en: '10 Potted Plants Gift' },
    ];

    const gameModes = [
        { label: '冒险模式', value: 'Adventure', en: 'Adventure' },
        { label: '生存白天', value: 'SurvivalNormalStage1', en: 'Survival Day' },
        { label: '生存黑夜', value: 'SurvivalNormalStage2', en: 'Survival Night' },
        { label: '生存泳池', value: 'SurvivalNormalStage3', en: 'Survival Pool' },
        { label: '生存雾夜', value: 'SurvivalNormalStage4', en: 'Survival Fog' },
        { label: '生存屋顶', value: 'SurvivalNormalStage5', en: 'Survival Roof' },
        { label: '生存白天（困难）', value: 'SurvivalHardStage1', en: 'Survival Day (Hard)' },
        { label: '生存黑夜（困难）', value: 'SurvivalHardStage2', en: 'Survival Night (Hard)' },
        { label: '生存泳池（困难）', value: 'SurvivalHardStage3', en: 'Survival Pool (Hard)' },
        { label: '生存雾夜（困难）', value: 'SurvivalHardStage4', en: 'Survival Fog (Hard)' },
        { label: '生存屋顶（困难）', value: 'SurvivalHardStage5', en: 'Survival Roof (Hard)' },
        { label: '生存白天（无尽）', value: 'SurvivalEndlessStage1', en: 'Survival Day (Endless)' },
        { label: '生存黑夜（无尽）', value: 'SurvivalEndlessStage2', en: 'Survival Night (Endless)' },
        { label: '生存泳池（无尽）', value: 'SurvivalEndlessStage3', en: 'Survival Pool (Endless)' },
        { label: '生存雾夜（无尽）', value: 'SurvivalEndlessStage4', en: 'Survival Fog (Endless)' },
        { label: '生存屋顶（无尽）', value: 'SurvivalEndlessStage5', en: 'Survival Roof (Endless)' },
        { label: '植物僵尸', value: 'ChallengeWarAndPeas', en: 'War And Peas' },
        { label: '坚果保龄球', value: 'ChallengeWallnutBowling', en: 'Wallnut Bowling' },
        { label: '老虎机', value: 'ChallengeSlotMachine', en: 'Slot Machine' },
        { label: '种子雨', value: 'ChallengeRainingSeeds', en: 'Raining Seeds' },
        { label: '宝石迷阵', value: 'ChallengeBeghouled', en: 'Beghouled' },
        { label: '隐形战争', value: 'ChallengeInvisighoul', en: 'Invisighoul' },
        { label: '看星星', value: 'ChallengeSeeingStars', en: 'Seeing Stars' },
        { label: '宝石迷阵旋风', value: 'ChallengeBeghouledTwist', en: 'Beghouled Twist' },
        { label: '小僵尸大麻烦', value: 'ChallengeLittleTrouble', en: 'Little Trouble' },
        { label: '传送门', value: 'ChallengePortalCombat', en: 'Portal Combat' },
        { label: '排山倒海', value: 'ChallengeColumn', en: 'Column' },
        { label: '雪橇区', value: 'ChallengeBobsledBonanza', en: 'Bobsled Bonanza' },
        { label: '僵尸快跑', value: 'ChallengeSpeed', en: 'Speed' },
        { label: '锤僵尸', value: 'ChallengeWhackAZombie', en: 'Whack AZombie' },
        { label: '坚不可摧', value: 'ChallengeLastStand', en: 'Last Stand' },
        { label: '植物僵尸2', value: 'ChallengeWarAndPeas2', en: 'War And Peas2' },
        { label: '坚果保龄球2', value: 'ChallengeWallnutBowling2', en: 'Wallnut Bowling2' },
        { label: '跳跳舞会', value: 'ChallengePogoParty', en: 'Pogo Party' },
        { label: '僵王博士的复仇', value: 'ChallengeFinalBoss', en: 'Final Boss' },
        { label: '艺术锦标赛', value: 'ChallengeArtChallenge1', en: 'Art Challenge1' },
        { label: '晴天', value: 'ChallengeSunnyDay', en: 'Sunny Day' },
        { label: '无草皮之地', value: 'ChallengeResodded', en: 'Resodded' },
        { label: '重要时间', value: 'ChallengeBigTime', en: 'Big Time' },
        { label: '艺术锦标赛2', value: 'ChallengeArtChallenge2', en: 'Art Challenge2' },
        { label: '空袭', value: 'ChallengeAirRaid', en: 'Air Raid' },
        { label: '冰冻关卡', value: 'ChallengeIce', en: 'Ice' },
        { label: '禅境花园', value: 'ChallengeZenGarden', en: 'Zen Garden' },
        { label: '牛顿的力量', value: 'ChallengeHighGravity', en: 'High Gravity' },
        { label: '坟墓危险', value: 'ChallengeGraveDanger', en: 'Grave Danger' },
        { label: '地道战', value: 'ChallengeShovel', en: 'Shovel' },
        { label: '暴风雨夜', value: 'ChallengeStormyNight', en: 'Stormy Night' },
        { label: '蹦极闪电战', value: 'ChallengeBungeeBlitz', en: 'Bungee Blitz' },
        { label: '松鼠', value: 'ChallengeSquirrel', en: 'Squirrel' },
        { label: '智慧树', value: 'TreeOfWisdom', en: 'Tree Of Wisdom' },
        { label: '砸罐子1', value: 'ScaryPotter1', en: 'Vasebreaker 1' },
        { label: '砸罐子2', value: 'ScaryPotter2', en: 'Vasebreaker 2' },
        { label: '砸罐子3', value: 'ScaryPotter3', en: 'Vasebreaker 3' },
        { label: '砸罐子4', value: 'ScaryPotter4', en: 'Vasebreaker 4' },
        { label: '砸罐子5', value: 'ScaryPotter5', en: 'Vasebreaker 5' },
        { label: '砸罐子6', value: 'ScaryPotter6', en: 'Vasebreaker 6' },
        { label: '砸罐子7', value: 'ScaryPotter7', en: 'Vasebreaker 7' },
        { label: '砸罐子8', value: 'ScaryPotter8', en: 'Vasebreaker 8' },
        { label: '砸罐子9', value: 'ScaryPotter9', en: 'Vasebreaker 9' },
        { label: '砸罐子（无尽）', value: 'ScaryPotterEndless', en: 'Vasebreaker (Endless)' },
        { label: '我是僵尸1', value: 'PuzzleIZombie1', en: 'I, Zombie 1' },
        { label: '我是僵尸2', value: 'PuzzleIZombie2', en: 'I, Zombie 2' },
        { label: '我是僵尸3', value: 'PuzzleIZombie3', en: 'I, Zombie 3' },
        { label: '我是僵尸4', value: 'PuzzleIZombie4', en: 'I, Zombie 4' },
        { label: '我是僵尸5', value: 'PuzzleIZombie5', en: 'I, Zombie 5' },
        { label: '我是僵尸6', value: 'PuzzleIZombie6', en: 'I, Zombie 6' },
        { label: '我是僵尸7', value: 'PuzzleIZombie7', en: 'I, Zombie 7' },
        { label: '我是僵尸8', value: 'PuzzleIZombie8', en: 'I, Zombie 8' },
        { label: '我是僵尸9', value: 'PuzzleIZombie9', en: 'I, Zombie 9' },
        { label: '我是僵尸（无尽）', value: 'PuzzleIZombieEndless', en: 'I, Zombie (Endless)' },
        { label: '购买完整版', value: 'Upsell', en: 'Upsell' },
        { label: '介绍', value: 'Intro', en: 'Intro' },
        { label: '快速游戏1', value: 'Quickplay1', en: 'Quickplay 1' },
        { label: '快速游戏2', value: 'Quickplay2', en: 'Quickplay 2' },
        { label: '快速游戏3', value: 'Quickplay3', en: 'Quickplay 3' },
        { label: '快速游戏4', value: 'Quickplay4', en: 'Quickplay 4' },
        { label: '快速游戏5', value: 'Quickplay5', en: 'Quickplay 5' },
        { label: '快速游戏6', value: 'Quickplay6', en: 'Quickplay 6' },
        { label: '快速游戏7', value: 'Quickplay7', en: 'Quickplay 7' },
        { label: '快速游戏8', value: 'Quickplay8', en: 'Quickplay 8' },
        { label: '快速游戏9', value: 'Quickplay9', en: 'Quickplay 9' },
        { label: '快速游戏10', value: 'Quickplay10', en: 'Quickplay 10' },
        { label: '快速游戏11', value: 'Quickplay11', en: 'Quickplay 11' },
        { label: '快速游戏12', value: 'Quickplay12', en: 'Quickplay 12' },
        { label: '快速游戏13', value: 'Quickplay13', en: 'Quickplay 13' },
        { label: '快速游戏14', value: 'Quickplay14', en: 'Quickplay 14' },
        { label: '快速游戏15', value: 'Quickplay15', en: 'Quickplay 15' },
        { label: '快速游戏16', value: 'Quickplay16', en: 'Quickplay 16' },
        { label: '快速游戏17', value: 'Quickplay17', en: 'Quickplay 17' },
        { label: '快速游戏18', value: 'Quickplay18', en: 'Quickplay 18' },
        { label: '快速游戏19', value: 'Quickplay19', en: 'Quickplay 19' },
        { label: '快速游戏20', value: 'Quickplay20', en: 'Quickplay 20' },
        { label: '快速游戏21', value: 'Quickplay21', en: 'Quickplay 21' },
        { label: '快速游戏22', value: 'Quickplay22', en: 'Quickplay 22' },
        { label: '快速游戏23', value: 'Quickplay23', en: 'Quickplay 23' },
        { label: '快速游戏24', value: 'Quickplay24', en: 'Quickplay 24' },
        { label: '快速游戏25', value: 'Quickplay25', en: 'Quickplay 25' },
        { label: '快速游戏26', value: 'Quickplay26', en: 'Quickplay 26' },
        { label: '快速游戏27', value: 'Quickplay27', en: 'Quickplay 27' },
        { label: '快速游戏28', value: 'Quickplay28', en: 'Quickplay 28' },
        { label: '快速游戏29', value: 'Quickplay29', en: 'Quickplay 29' },
        { label: '快速游戏30', value: 'Quickplay30', en: 'Quickplay 30' },
        { label: '快速游戏31', value: 'Quickplay31', en: 'Quickplay 31' },
        { label: '快速游戏32', value: 'Quickplay32', en: 'Quickplay 32' },
        { label: '快速游戏33', value: 'Quickplay33', en: 'Quickplay 33' },
        { label: '快速游戏34', value: 'Quickplay34', en: 'Quickplay 34' },
        { label: '快速游戏35', value: 'Quickplay35', en: 'Quickplay 35' },
        { label: '快速游戏36', value: 'Quickplay36', en: 'Quickplay 36' },
        { label: '快速游戏37', value: 'Quickplay37', en: 'Quickplay 37' },
        { label: '快速游戏38', value: 'Quickplay38', en: 'Quickplay 38' },
        { label: '快速游戏39', value: 'Quickplay39', en: 'Quickplay 39' },
        { label: '快速游戏40', value: 'Quickplay40', en: 'Quickplay 40' },
        { label: '快速游戏41', value: 'Quickplay41', en: 'Quickplay 41' },
        { label: '快速游戏42', value: 'Quickplay42', en: 'Quickplay 42' },
        { label: '快速游戏43', value: 'Quickplay43', en: 'Quickplay 43' },
        { label: '快速游戏44', value: 'Quickplay44', en: 'Quickplay 44' },
        { label: '快速游戏45', value: 'Quickplay45', en: 'Quickplay 45' },
        { label: '快速游戏46', value: 'Quickplay46', en: 'Quickplay 46' },
        { label: '快速游戏47', value: 'Quickplay47', en: 'Quickplay 47' },
        { label: '快速游戏48', value: 'Quickplay48', en: 'Quickplay 48' },
        { label: '快速游戏49', value: 'Quickplay49', en: 'Quickplay 49' },
        { label: '快速游戏50', value: 'Quickplay50', en: 'Quickplay 50' },
        { label: '僵尸水族馆', value: 'ChallengeZombiquarium', en: 'Zombiquarium' },
        { label: '巨人之怒1', value: 'ChallengeAttackOnTitans', en: 'Attack On Titans' },
        { label: '巨人之怒2', value: 'ChallengeAttackOnTitans2', en: 'Attack On Titans2' },
        { label: '巨人之怒3', value: 'ChallengeAttackOnTitans3', en: 'Attack On Titans3' },
        { label: '奇人异尸1', value: 'MarvelousPeople', en: 'Marvelous People' },
        { label: '奇人异尸2', value: 'MarvelousPeople2', en: 'Marvelous People2' },
        { label: '奇人异尸3', value: 'MarvelousPeople3', en: 'Marvelous People3' },
        { label: '随机传送带（无尽）', value: 'RogueConveyorbelt', en: 'Rogue Conveyorbelt' },
        { label: '随机传送带', value: 'RogueConveyorbeltHard', en: 'Rogue Conveyorbelt Hard' },
        { label: '僵王博士的复仇2', value: 'ChallengeFinalBoss2', en: 'Final Boss2' },
        { label: '随机模仿者', value: 'ImitaterRandom', en: 'Imitater Random' },
        { label: '排山倒海2', value: 'ChallengeColumn2', en: 'Column2' },
        { label: '排山倒海3', value: 'ChallengeColumn3', en: 'Column3' },
        { label: '排山倒海4', value: 'ChallengeColumn4', en: 'Column4' },
        { label: '生存白天（地狱）', value: 'SurvivalHellStage1', en: 'Survival Day (Hell)' },
        { label: '生存黑夜（地狱）', value: 'SurvivalHellStage2', en: 'Survival Night (Hell)' },
        { label: '生存泳池（地狱）', value: 'SurvivalHellStage3', en: 'Survival Pool (Hell)' },
        { label: '生存雾夜（地狱）', value: 'SurvivalHellStage4', en: 'Survival Fog (Hell)' },
        { label: '生存屋顶（地狱）', value: 'SurvivalHellStage5', en: 'Survival Roof (Hell)' },
        { label: '奇人异尸4', value: 'MarvelousPeople4', en: 'Marvelous People4' },
        { label: '泳池派对', value: 'PoolParty', en: 'Pool Party' },
        { label: '雪橇区2', value: 'ChallengeBobsledBonanza2', en: 'Bobsled Bonanza2' },
        { label: '空袭2', value: 'ChallengeMoreAirRaid', en: 'More Air Raid' },
        { label: '大泳池', value: 'BigPoolSurvivalNormalStage', en: 'Big Pool Survival' },
        { label: '大泳池（困难）', value: 'BigPoolSurvivalHardStage', en: 'Big Pool Survival (Hard)' },
        { label: '大泳池（地狱）', value: 'BigPoolSurvivalHellStage', en: 'Big Pool Survival (Hell)' },
        { label: '融合', value: 'ChallengeFusion', en: 'Fusion' },
        { label: '随机挑战', value: 'ChallengeStageRandom', en: 'Stage Random' },
        { label: '占领高地', value: 'OccupyHighGround', en: 'Occupy High Ground' },
    ];

    const lineupCodeMap = {
        day: [
            { label: '[DE] 双核无炮', value: 'LI5HDH3kARQDFMNVWlAyXvhBVN360d/4UBcwRTg+hJhVVLXDWrRU' },
            { label: '[DE] 神之无炮', value: 'LI43NBRTVn9Rgl44QQzfdmZH3ONm+BEF50ZwUvCDZjRRVFowX/lU' },
            { label: '[DE] 长矛无炮', value: 'LI5HDH3kARQDFMNVWlAyXvhR3vlBDF9DDV3RJAX4PoSYVVR08kQKVA==' },
            { label: '[DE] 群曾无炮', value: 'LI5HDH3tBib/1HpXSFyYwAhfQI1+5MI1eQAwcUSOXNSRUIK2Btc6WlTc/0bzVA==' },
            { label: '[DE] 后置三炮', value: 'LI5HjH7tAiZ/lxVSbEQMfW0HJnGXAtLhJEVPdoA0zFdUQ0pboFQ=' },
            { label: '[DE] 镂空四炮', value: 'LI43jH/tASbxsALS11hk5MPVVZwzFELV/uVVFhY+tHZUWD1bsFQ=' },
            { label: '[DE] 屑四炮', value: 'LI5HjH7tASbx1HrXeldAXJjACF9AjX7kQlCVdmIU7EbQTQIWgfgxbFzwWmaUVQRaGVBUYCxbMlQ=' },
            { label: '[DE] 后置四炮', value: 'LI5H5MUIf+3BtXRXSFyYUN74MIye5EJ6UMDBeBEF50IJ2dTZsBgAJ1SYb1otVA==' },
            { label: '[DE] 奥赛罗五炮', value: 'LI435DU0xAiflJQkxFVSFPjpVn/VsB78XAQKJnFVYSK8slRUfQ9fLVQ=' },
            { label: '[DE] 柱子五炮', value: 'LI5HzH3tAibxsALS11gEdBRxRVTCikaVVA==' },
            { label: '[DE] 双核底线五炮', value: 'LI43bJyUdOQCNHGXHlJMVN4c+kEMn+RBnCJUFtycHuTOwQyAlBEEmVVUq+dblVQ=' },
            { label: '[DE] 底线五炮', value: 'LI43bJyUdOQGNHFXV9dZlwJSRFTd+FHeVWWXDuwcd0yOdN34UaZ1aDBhDzVWVGL6RDRU' },
            { label: '[DE] 无保护六炮', value: 'LI43bJyUlORD3BVgUIxk+FHf+FAWXGzcErcG1zZaVBScX6VU' },
            { label: '[DE] 雪花六炮', value: 'LI43NDQ0xAh97cG1dFdIHPrByH3txlV1MnftQFw3lajXbIA0zFdUtwtb51Q=' },
            { label: '[DE] 后置六炮', value: 'LI5H5MUIf+3BtXRXSFz4wcjdflY2H8L2/RWD4UYJQ1TLmlnoVA==' },
            { label: '[DE] 冰矿工六炮', value: 'LI43NMQIf+0GJnGXAtLXWERU8HEzHjox5NXf1ID4Ud9ktAHXNlpUQapEx1Q=' },
            { label: '[DE] 双冰六炮', value: 'LI5H5MfIfe0GJn+XFVJ8RAx/7UJ80nBWNh2SHsJ2/c1dANf+n1IJQ1R5i0T7VA==' },
            { label: '[DE] 花园六炮', value: 'LI5H5MUIf+1GXINejGTU1ZQO0tcUvnTMUUUNXUMN3QdZ0m1UReFEaVQ=' },
            { label: '[DE] 云中仙七炮', value: 'LI43NDTkxQh/7cKV0lVSAmZIUMZTlXhcbNzQJf1VVuRtJFRUakdfKFQ=' },
            { label: '[DE] 樱桃七炮', value: 'LI5HDH/tAib/sALS11hkVDDVkER2VnRhf3ED1hBQgrYF1zZaVNQRRiZU' },
            { label: '[DE] C2f八炮', value: 'LI5H5DVsnJRUkgR0NJfkQpgLXUMNHdBOWCdUWbFeylQ=' },
            { label: '[DE] 神之八炮', value: 'LI43NJRUU01McIMe+lCFNFhFzV1B5Tfklf5SV1RUXARfU1Q=' },
            { label: '[DE] 超前置八炮', value: 'LI43bJyUdO0CJn9XxFI3ZF1Azd1y5kb+Ul4UfnDjXvgwzF1DDV0GdzSXNFe1V1QHeUVDVA==' },
            { label: '[DE] 简化八炮', value: 'LI43bJyUdO0CJnFXxNJWT53hNE51JkTZkvVSgUhUSQZfSVQ=' },
            { label: '[DE] 瞬杀八炮', value: 'LI43bJyUdO0CJnGXGFJPUlzU3Ugw1FVPdGhcxZX9UpdIVOB6Wh9U' },
            { label: '[DE] 前置八炮', value: 'LI43bJyUdO0CJn9XxNJWT3Qrct5cHJkencFQgfTMV1SujFvtVA==' },
            { label: '[DE] 雪花十炮', value: 'LI43NDQMnyTE1VXYdZRSkMIIn+RGelL2A1b1WQhYB1nSbVT/Z1omVA==' },
            { label: '[DE] 全场超前置十炮', value: 'LI43NMQIfe3C1dW1dEBX1bAOnc38dlZ/UThc/RVjU1TxQVrEVA==' },
            { label: '[DE] 沙漏十一炮', value: 'LI43bJyUlFSXRDRXs/vQ34wUrX8l/pVkU1RuvV+0VA==' },
            { label: '[DE] 神之十一炮', value: 'LI43NNRWT0zXtXRX17AOncF0TthNtHgodkyyVFSlLF4YVA==' },
            { label: '[DE] 守钉耙十一炮', value: 'LI5H5DXMneRDXONmSDBUV9Xhxj9x4x6aMOTV3dQ8ncHGf5Wo1yTF4RRhvHYcPlTFqEd3BA==' },
            { label: '[DE] 守城十二炮', value: 'LI43bJyUlFSX3VhYHGjQ3FlM+lAXCD5kEFTSOFn1VA==' },
            { label: '[DE] 撞南墙十二炮', value: 'LI43bJyUdO0GJnFXxFI3ZH3tAiZ5xtxZ19nweFBmcrYE1zVaVE2WRItU' },
            { label: '[DE] 挂机十二炮', value: 'LI43bJyUdO0CJn9XxFI3ZF1HxQh/5EJ+5gYmcQCQUvNOQCdUmXBArVQ=' },
            { label: '[DE] 中开十四炮', value: 'LI43DJ3kxrV0V1dIZ2Q03oxUdX5s3NLl3FRU85BZ/1Q=' },
            { label: '[DE] 雪花十四炮', value: 'LI43DJ3kxrV0V1dMF1TWW0dv3NJNTDhkgIx03dVVVPcZWWpU' },
            { label: '[DE] 守全场十四炮', value: 'LI43bJyUlNTYdbAefBBCNVTHXEVPUm9kEtz0zFdUpKZbLVQ=' },
            { label: '[DE] 连拦十四炮', value: 'LI43bJyUdO0CJnlXxFI3ZN1+duRGVsUQOLQ43Ep4dlQkBUV3VA==' },
            { label: '[DE] 十四炮', value: 'LI43bJyUdO0CJn9XxFI3ZN0RMPGwHlJPfEvDTkBFVDttRstU' },
            { label: '[DE] 十五炮', value: 'LI43bJyUdO0CJn9XxFI3ZN0RMHFFPgQQVNMYR2RU' },
            { label: '[DE] 空炸十六炮', value: 'LI43bJyUlNTYBS1ERVJST9XBRJw01xdZ0lxUhmRbOVQ=' },
            { label: '[DE] 十六炮', value: 'LI43bJyUdO0CJnFXxFI3ZH3tApRSAVBRtwTXPlpUeLVFEVQ=' },
            { label: '[DE] 十七炮', value: 'LI43bJyUdO0GJnFXxFI3ZH3tAiZ5/tzU2dRZ/lxeknZWVGRCRC5U' },
            { label: '[DE] 十八炮', value: 'LI43bJyUlFSXf004xCyMERTMfEVUgwBbCVQ=' },
            { label: '[DE] 十九炮', value: 'LI43bJyUlNTYBS3Mdn9NONTEXAlUh0hbIVQ=' },
        ],
        night: [
            { label: '[NE] 无神无炮', value: 'LI5H/MDIfe0GNP+UAlIJUmRE/FAWYEWdHiBhzO5wA/beVFQkQ0YXVQ==' },
            { label: '[NE] 十一格无炮', value: 'LI43NBRTVn9Rgl74MAzfdmZHfNYDWXJUVN7OU4BV' },
            { label: '[NE] 超后退无炮', value: 'LI5HDH3tBib/1HpXSFyYQAx/5AE0ecZcEJkeMGHGP3Hl/RVmU1TvjFmlVQ==' },
            { label: '[NE] 小无炮', value: 'LI5HDH3kAjTxlALV4VgEVLCZULbBfHY/xQFEU1TqSF5vVQ==' },
            { label: '[NE] 小楼梯无炮', value: 'LI4ZnuVZVGRcVxUSJL91TMxFfAgu68QcxaymoDxc2kGYNnbDYM8y0sI8kITjxe5DkqS4VPklRWVV' },
            { label: '[NE] 双七列曾神之无炮', value: 'LI43NBRTVj9xgx76wIie5AE0+ZQO5Jwenc0UxcFYD00CtgbXXVTrbFqGVQ==' },
            { label: '[NE] 群曾无炮', value: 'LI5HDH3tBib/8HrXeldAXJjACF9AjX7kwjV5ADBxBFD8HlR8cuRC805gJ1TueEflVQ==' },
            { label: '[NE] 减速无炮', value: 'LI5HDH3tAib/8HrXeldAXJhQ3zhBDH/kQn7mBkZYUeKWEeT9FWdTVMu7R1hV' },
            { label: '[NE] 冰雨无炮', value: 'LI5HDH3tAibxsAJEQAyfVFBWZ9V2DwUQFKbQgfTNV1SsS09dVQ==' },
            { label: '[NE] 压制无炮', value: 'LI5HDH3tAib/8HrXeldAXJjQ3Fz4MQxfQQ19XdJWD1GCXviR/VKZSFTSgEbNVQ==' },
            { label: '[NE] 双六列曾神之无炮', value: 'LI43NBRTVj9xgx76QAx/5MI1eQAw8bAY9Jwe1fk0Bfg+ZFVUyMtZqlU=' },
            { label: '[NE] 双七列曾神之一炮', value: 'LI43NBRTVj9xgx76wIh+5AE0+ZQO5Jwenc0UxcFYUyX/lVBU/uVaAVU=' },
            { label: '[NE] 变奏一炮', value: 'LI5HDH3tAgYDFMMVw1VeUDJWEQJe+EAMn+RCfiBEfA5eQDVEDH9UQkcM3/oSNPGwGAAnVHByRMRV' },
            { label: '[NE] 小二炮', value: 'LI5HDH3tAiZ/lxVSbEQMfW1HFzD5sB7VwVY/TRxUVNxjXZRV' },
            { label: '[NE] 双七列曾神之二炮', value: 'LI43NBRTVj9xgx76wIh+5AE0+ZQO5IQVUlL0nB5E2QdZUlRU3O5Z/1U=' },
            { label: '[NE] 点赞三炮', value: 'LI43NJRQxj8FrVZ/cTMe+jBs3HbmAiZ/zpwYAEVUAEZd6VU=' },
            { label: '[NE] 瞬杀三炮', value: 'LI5HDH3tAib/1HrXeldAXJhADH/kQVyDXvjR3vgwjJ4kRBx3/TUMX0INX0OVBFdUUHRamlU=' },
            { label: '[NE] 土豆四炮', value: 'LI43NJRQxj9xAx76MGxcQ1TlEHHj1r3hbIA0VFTgkF19VQ==' },
            { label: '[NE] 前置四炮', value: 'LI43NMSIXtZYU020FCb5sBhgxcF0nGTHNXlKYTyyVFSoaVulVQ==' },
            { label: '[NE] 小梦四炮', value: 'LI43NDQ0xAh97ca1dFdGxAh/bcc1cZcOcPXXBNgTWf5tVHR8X/1V' },
            { label: '[NE] 后置四炮', value: 'LI5HDH/tASZ/lxVSbETMfe1CGTDxcEReODEM3xNZ0m1UQ2ZbtFU=' },
            { label: '[NE] 神之四炮', value: 'LI43NJRUU01McIMe+lCFVj+VdmcVKJ3NWH9N4hYRZIE0VFQfqVgpVQ==' },
            { label: '[NE] 倾斜四炮', value: 'LI4RnGVFVGRYFgVw5HZ21n/1VzdQgA3HWr1L7C+E5gbPMrb0/4GCY7zikqFof7wtQseVlCBVoZlGZlU=' },
            { label: '[NE] 智商五炮', value: 'LI43NFRVncFYU00EVLF2VAjJU8RV' },
            { label: '[NE] 压碑五炮', value: 'LI43NMQIfe0BJr/W11NMWmQU1LAOnc08dn8V/lz+FWVTVOJUTlRV' },
            { label: '[NE] 神之五炮', value: 'LI43NJRUU01MUIJe+FGFXEWdwcYPlWZ/FVZWf3GDVrUecGFMVFS7Y17EVQ==' },
            { label: '[NE] 鬼位五炮', value: 'LI5HDH3kxrV0V0ZEzH3tQnB25EJ6lnRdAndkR9vOwcY8slRUO6dY0lU=' },
            { label: '[NE] 底线五炮', value: 'LI43bJyUdORGWONmFFQcMHlE+kAM33CGXNK8Pk4l/1VUGTBFClU=' },
            { label: '[NE] 神之六炮', value: 'LI43NJRUU01McIMe+jEMXTaVEQIe+jCM3nbW/lJXVFRG/V9+VQ==' },
            { label: '[NE] 镂空六炮', value: 'LI43bJyUdO3C1RU2f1fEUVV06rAe5ExQSNCmA0YE1zZaVMT+WY5V' },
            { label: '[NE] 快六炮', value: 'LI5HDH/tAibysALS11gEdGRHfOZGDVCQxtjBeBEGF9B6VAgLRdtV' },
            { label: '[NE] 全梯六炮', value: 'LI7HCH/tAib/sALS11gEdN11VjYd+sAI3RtZ8lxUxwtG/1U=' },
            { label: '[NE] 雪花七炮', value: 'LI43NDQ0xAh97cG1dFdIHPrByN12IkR2UrJLkPVSl0hUuilbpFU=' },
            { label: '[NE] 瞬杀七炮', value: 'LI5HDH1tBybxsALS11gEdOQCJnkEWHh25EJ4IETV1XZn5f1FlGRTVJVwQEBV' },
            { label: '[NE] 美学八炮', value: 'LI43bJyUdO3CVU2UEALWDBDflFQIUFRgiF+RVQ==' },
            { label: '[NE] 简化八炮', value: 'LI43bJyUdO0CJnFXxNLWzcY/lWAWsHRO2RdZ/m1UF4Bfg1U=' },
            { label: '[NE] 生死劫', value: 'LI43NMQIf+0GJn+XFVJMVOaEkJR2WN1TTAQRBKH1p1Vtb0UcVQ==' },
            { label: '[NE] 前置八炮', value: 'LI43bJyUdO0CJn9XxNLWwRRq/lwcmR52gPTcVFRlsUSTVQ==' },
            { label: '[NE] 放羊九炮', value: 'LI43NBRTVj9FRH4gxNUVJvGwAkRZkkTF4cZ/ZRDEgFRUJY1bsFU=' },
            { label: '[NE] 请君入瓮', value: 'LI43bJyUdO0CJnmXAlJ0X1h0dn+VKOTMlB7VwVhcxNwZWVfSbVRwikSkVQ==' },
            { label: '[NE] 核代十炮', value: 'LI43bJyUdO0CJnlXxNJWuHZ/cQNGANd2VlSwyFtrVQ==' },
            { label: '[NE] 九龙阁十一炮', value: 'LI43bJyUdO0CJnlXxNJWGMXBNKIVZF/6UtpNhJD0VFTlWVjiVQ==' },
            { label: '[NE] 十二炮', value: 'LI43NDRsnNSURNR9lpTkRl4l/xVHVVR3cF/lVQ==' },
            { label: '[NE] 舞夜惊魂', value: 'LI43bJyUdO3CNXtXl9bXU0wUxFV4dm0HJn/enAKd+XROdlIBV0M11L8WzFdUHBZJylU=' },
            { label: '[NE] 守钉耙十三炮', value: 'LI43bJyUdO0CJvKwAlJ0X1h0dj9xA/bc+NCmW3b9zd115kJ1VlQqXka+ZQ==' },
            { label: '[NE] 丑十四炮', value: 'LI43NDRsnNSUWFMUkB5kL3kQUFgEgNQBFID40N9IEANRVPTtWvRV' },
            { label: '[NE] 十五炮', value: 'LI43bJyUdO0CJnFXxFI3ZF1ADd9y5sZcYXyyVFQplEaoVQ==' },
            { label: '[NE] 十八炮', value: 'LI43bJyUlFSWf5VwV8DTCVDS3UZVVO78WrFV' },
            { label: '[NE] 十九炮', value: 'LI43bJyUlNTYBS0kRdXBVn9d/RVBVVSx51uSVQ==' },
        ],
        pool: [
            { label: '[PE] 最简无炮', value: 'LI43NBRTVn9RgvbebPggzL3kRpBeDN925kV11v1fR1RUKNleulY=' },
            { label: '[PE] 伪无伤无炮', value: 'LI43jH/9X9ZYXOQDJvKwAvScDszUlx7TwVhPSThI4laNPzV2FOxBkNfcNL42lGRNVC9jR75W' },
            { label: '[PE] 自然控丑无炮', value: 'LI5HDH5d0FYfTTZN9BQ0+bAYnflW7ljuZEXTwXSc5GU0OZQOMEVTT9DclB4gCVYPcYP23lRUQEBBvFY=' },
            { label: '[PE] 火焰无炮', value: 'LI5HDH5U0ljlWAR0ZAcm+bAGHXBF08FEnORlNDmUDnBFT9Bc8npVWMdV80pNcFY=' },
            { label: '[PE] 后退无炮', value: 'LI5HjH7kAhQDFMNVWlAyHvrBiH79n+RCcrbkRlBNYm44WQxP5EJ1tjS3NFdHlYBx1DVmVFohQjVW' },
            { label: '[PE] 超前置无炮', value: 'LI5p2JVZlGRcV2nW61iVUgWRXPjDRa6kx6lOxAaLn3ONwJ2e3lqT0DEvGHdc3OOd3walSAL4+DrnjkCvEZSpbZK9rKdVi4tIelY=' },
            { label: '[PE] 王子无炮', value: 'LI5HDH5U1eVYL9VEXFAyXvhB5EWMXpBiWGJ0RdPBWj9JAmY4WIxONEfkQlDVdn+Vdn/VRHhWg+EBNHlXTNQMFPifVNY0VFRWb0t/Vg==' },
            { label: '[PE] 机械钟无炮', value: 'LI4Z2GVFVHRYV391f3YklNTQjhcW01hYoRNfSBMqnltbe3jafgG6ZBRgbHxo8g873U7yZl1HGvIO5Fnsbw22v5Cvn19OY0/kVg==' },
            { label: '[PE] 神之无炮', value: 'LI43NBRTVj/VJH9M+jEMX0YlDF3SD1c41CR5XDbeNL6WUFTFW02xVg==' },
            { label: '[PE] 石英钟无炮', value: 'LI5HDH/kARTDVVD1FDTyVBw4eQQgeRCQNXFcZjhY5FWW4XRcRSVUplFiFhBkIV00zFhUj59OmVY=' },
            { label: '[PE] 靠天无炮', value: 'LI5HzH3tAib/sAJSCVJ8RIxeRUWEQQyf5EJwtgS9NLfkgTV/lxLV2VU/FUR8ZkcBUAfDVNKdVIfdSy5W' },
            { label: '[PE] 压制一炮', value: 'LI5HzH3tAQYDFMNVWlCCHvpR3WX40d1s+FCW11pYVX9XglL40d+MZDhYjF5HlYBx1DVmVFo/QtVW' },
            { label: '[PE] 小二炮', value: 'LI5HDH3tAiZ/lxVSbEQMfW1HAZA1cVxeOFgM30RdDN+0RV9Uq2VZMVY=' },
            { label: '[PE] 火焰二炮', value: 'LI5HDH7tAib9lAbSDFJ8RMzderbkhrX0VxeUnlTP1OE8dn81dszuUGQYUlR9gEKOVg==' },
            { label: '[PE] 核武二炮', value: 'LI5HDH3kAjTxlAJSCVJ8RMxdQA1fQA1fRyVsvJS05GE0MdRZxLmwtFRFNYxcQFX+JSQkJJbyH1SXMFR6mENAVg==' },
            { label: '[PE] 分裂二炮', value: 'LI5HzH3tASZ/lxVSbEQMf+1CAZA18Zce1dl0ApQO0NzX2dfZlJLU+VU/FQRUUONevF68ZhSBXNQYgsGAMYTRzVdUX+NCklY=' },
            { label: '[PE] 方正二炮', value: 'LI43bJyUdOQCNPGUAlJPUlxU3hz6wVDd+NFcbJggDL/kZjQ/lJ5U/FyXEiBF1c10acYPUSA17lDCHtY0eARQPmZU9XNNfVY=' },
            { label: '[PE] 经典二炮', value: 'LI5HDH/tAQYDFMNVWlAyHtaRTIKWEEgCZjggbLyURDRH5GI0eRBQXBV2DzV2zO5QZBhSVL1zQaRW' },
            { label: '[PE] 冲关三炮', value: 'LI5HDH5U1uVY8VgEdGQHNPnU2ZQCdO1CdrbkhjX5lxVTUtXZVX9XgtZ03NN+1v1fmIJBhDGMX2dNVBODSMxW' },
            { label: '[PE] 太极四炮', value: 'LI43NFRVncFYU03E1LAOUk9SQGXT11pYWn9NVleC9t5R+DB0TlRUyu9d9lY=' },
            { label: '[PE] 全金属四炮', value: 'LI43NMSIfu3B1dW1dFdIHPrBCN9+lvRZ0FhYzhTcB1AHQ+6dVDZmXvFW' },
            { label: '[PE] 方块四炮', value: 'LI43NJRScIMe+jBs3Hi2JITVdZRyNHlqRRgJ/FRUYSpec1Y=' },
            { label: '[PE] 青四炮', value: 'LI43NDQ0xMh9ZMdVXRz6wQh95AY0edi75EZcOUg4VgJS+NDe+FHeSCA0VN6UAWVI0DYw1JZTVLkbRDJW' },
            { label: '[PE] 水路无植物四炮', value: 'LI5H5MXIfe3GtXRXSFz4wQh/7UEN0EzU/R80ce6dVMPfX8BW' },
            { label: '[PE] 方四炮', value: 'LI43NDQ0xAh97cZVXRz6wchd0D81KNPXWlhaYhRc8CXdNL42lGRNVNuRW4lW' },
            { label: '[PE] 葬花吟', value: 'LI43NDQ0xAidlHRUkGR07cLVFSRiBDh50Etlh7X0VxfUSczI2UTd5BXcFCAdmhC8NpRkTVSYK0VtVg==' },
            { label: '[PE] 神之四炮', value: 'LI43NJRQxj9xMx46MQxft29IIFS31MEU7ELvXPJ6GFRU5c9EnVY=' },
            { label: '[PE] 双核底线四炮', value: 'LI43bJyUdOQCNHmXAlJSUlNSRFTeHPpBzF1GRSRU3W2YIAy95GZUXBWGWnRFTzBFIAlcReydNFRUUexBjFY=' },
            { label: '[PE] 经典四炮', value: 'LI43NMQIfe3BldJVXRz6wchdQA9ft29IIFS3VM/U4Tx2f1eCtoaR1DVmVFO7RlZW' },
            { label: '[PE] 心四炮', value: 'LI4B3+VFVGRcVk2VwgkG7HrRMVKcMsXnnLFfLe1XXAVUQSkZAEBjkTknx3PF/yeN0r2KO7wJtdcuKlXzIUWJVg==' },
            { label: '[PE] 火焰四炮', value: 'LI5HDH7tAib9sAbSDFJ8RMzderYkhFXYVwJSjFD4EUcNXUWVgHHUNWZUGEZD+lY=' },
            { label: '[PE] 底线四炮', value: 'LI43bJyUdO0CJvGUAlIJUlyURCUMvWSHNTHU2ZSS1MFVP8URVuJS+NHc1CBd+EGMfvTfOFr+XFQj00OhVg==' },
            { label: '[PE] 传统四炮', value: 'LI5HjH7kAjT/1HrXeldAXJhQ3vhBDH3kwTV5EJC19FdMU/hY5F0MX9Ycdg91dszuUGQYUlR6YUggVg==' },
            { label: '[PE] 半场无植物五炮', value: 'LI5H5MUIf+0GJn+XFVJ8RNTc+BDcbEgg1LfU4XScFEJUVEgKWSFW' },
            { label: '[PE] 散炸五炮', value: 'LI43NMQIXtZY5VgkdOQCNPKUAtLhZOqXFVNkWoxO5GI0eebclJLUzVViRAHGP3EzHjoxDN2Ec+1GXONmSNClVZiCQgxW' },
            { label: '[PE] 心五炮', value: 'LI43NMQIf23H1RU08ZQeUlxsnFRGj172UYLWUEg4SFpuZNQklJ7U4UQRWj8VKNXZZGpcHJrAiH7UtLtRFlIdCdBoVO/lR89W' },
            { label: '[PE] 陆路无植物六炮', value: 'LI43NHRYSFpulCWUHnQI330W0GVYVIQCWTFW' },
            { label: '[PE] 水路无植物六炮', value: 'LI43bJyUdO0CJnFXxNJWGEV21NRZ7kr0nBid+Zx2VPkWX2NW' },
            { label: '[PE] 禅房花木深', value: 'LI43NDRsnFSVXGQHJvmwDtLNZPqXFVNS08EUXPD1dn9JOJT2Ylp/Jb1W1sE0J7V+VIfTRSVW' },
            { label: '[PE] 青苔六炮', value: 'LI43NDRsnFSVXOQGJvmwDtLBZPqXHlNP09daWBQmcXpFGAlYTHJXVJx9RINW' },
            { label: '[PE] 神之六炮', value: 'LI43NJRQxj9xMx46MWxct29IIFS31MFVYlU/5d80vpZQVNmXRENW' },
            { label: '[PE] 玉米六炮', value: 'LI43NMS4URVSRNBWneHGZ3HjZkjQpUlabtQllB50CN8JUAdDV9KdVEV/Q11W' },
            { label: '[PE] 空炸六炮', value: 'LI43NMQIXdAPTcTUsA6dzRTF4WTqlxVTXApN5GI0ed7cGVREFsFJ0DZQDJ9kx5VSlVFUGfBFkVY=' },
            { label: '[PE] 超后置六炮', value: 'LI5HDH/twbV0V0ZEzH3tQgGQNXFESiA0XORdDN8fUAfDVNKdVHrIRmVW' },
            { label: '[PE] 方六炮', value: 'LI43NDQ0xIieJMRVXRz6wchdQIcxDF+1b0ggVLfU+VVnV4I2Q5WAkdQ1ZlQmKEBtVg==' },
            { label: '[PE] 蝶语', value: 'LI5HDH/txlVYcAJe+FGFVj9xM9aQcAIemNDcbEggNNwMTTRH5UaQ1t1Q+NjkXdTfVJUV9MrNdEZVcIIWZFBUVH3cQWdW' },
            { label: '[PE] 一勺汤圆', value: 'LI43NDRsnJSU5MZVVXSo11xV09daWFp/FXBcULzWkUSo4XQGNHnX2bACnflYYlY/Na5QghZ02FtUJ+NFc1Y=' },
            { label: '[PE] 间隔无植物七炮', value: 'LI43NJRUU01McIMe+lGFNNhRbEggNCQMXXLVTFPkVc7mBiZxjFhPxFRUE0Vfq1Y=' },
            { label: '[PE] 玉兔茕茕', value: 'LI43NFRVnfnGD00E1LAencFWPzVo09daNNiWC11FJeRVX0lQtsE0xtWVUv64dEZdUFRPflpkVg==' },
            { label: '[PE] 无保护八炮', value: 'LI43jJ/kw9XVNX+XFVJM1N2YMAxfRSRsvFST7BBkIWU0zFhUx7hABVY=' },
            { label: '[PE] 树八炮', value: 'LI43NFTV0h5SQITk4jUylw5Qi7X0V9eXHkTdlgvdeJIkRPw7ctwQto/UdBhYVIKyRzJW' },
            { label: '[PE] 全对称树八炮', value: 'LI43NNTU0h5SQITk4jUylw5Qi7X0V9eXHkTdlgvdeJIkRPw7ctwQto/UdBBYVORIRzJW' },
            { label: '[PE] 矩形八炮', value: 'LI5H5MUIf+0GJnGXFVJ8RJREJWy8VJPsENxVVHJSWmFW' },
            { label: '[PE] 无套神之八炮', value: 'LI43NJRWgma4UYdTdQjTwVo/SVpuZJTlWfJc8noYVFTOUUTVVg==' },
            { label: '[PE] 灯台八炮', value: 'LI435DUMncRd0H9NOEx0tHRX17AOneF0TlZIAm6MbEggNFTGf7U2dGpEd1Xc2uEcdlP1TF5UvN9bgVY=' },
            { label: '[PE] 神之八炮', value: 'LI43NJRQxj/VJH+XFUyLtfRX15cYZF2QjBFkITVWVCQ/WztW' },
            { label: '[PE] 阴阳八炮', value: 'LI43NMSIfu0GJnnXWVdAXDjBCH9tByZxBDB5EJA18ZcYdOIlbLxUAbfkQpxTpkR2WFPFZO5MQFRU/iFHVFY=' },
            { label: '[PE] 浮萍八炮', value: 'LI43bJyUdO0GJnFXxFI3ZH3tAiZ5xlwFVPiTUg3TsAL07Rx2VHKpWPlW' },
            { label: '[PE] 后置八炮', value: 'LI43NMQIf+3BtXRXRsTI3X62JIRV2FcyUvgRR41eR5WAkdQ1ZlRFJEZNVg==' },
            { label: '[PE] 饲养海豚', value: 'LI43NMQIf+0GJn+XFVJsVKYzdt9QmCBsvJRUllVnV4LWELSo+RSN4QQJZwUZNVTN2HZWVIR3QNJW' },
            { label: '[PE] 玉米八炮', value: 'LI5HvMEIf41/jZ+EnyTEVVhQZBBIWm4UpB5TT9PBjBFQ3GRTVPknTcFW' },
            { label: '[PE] 经典八炮', value: 'LI43NMSIXtZYU020FCb5sBgwRdPXWjRI5GE0MpQOYMXBREUYCVhMcldUcSdDG1Y=' },
            { label: '[PE] 花海八炮', value: 'LI5HDH1d0lhTTUxMAlZl15QeneEU3HC25EZeW25k1CTUWfJc8npVWMdVgpZLTVY=' },
            { label: '[PE] C2八炮', value: 'LI5HDJ8kxNVV2PUUNHmXGGQreRiQlZo18ZcVU9LUwVUEZVNPIEUYCVZMcldUCDpHFVY=' },
            { label: '[PE] 冰心灯八炮', value: 'LI43bJyUdO0CJnlXxNJVdCtxRPrRpUlabmRsjFR1xJJx1v3fVZcwVATYR2VW' },
            { label: '[PE] 分离八炮', value: 'LI5HzH3tAiZ/lxVSUFTmlTbuFFxSWlNJTEiC1pzU+VU/5d80vkaUZE1UrtxCaVY=' },
            { label: '[PE] 全对称八炮', value: 'LI43NDQ0RAx/5MY1/5Qe1eFYBNR+tiSEVdbjlg1MdlgQzFdU9XdOI1Y=' },
            { label: '[PE] 3C八炮', value: 'LI5HjH7kAjT/lALS11hYWC/VzBU0cgwwchaQtfRXTFP4UJbhdNx91v0fVJcwVFwNdNtW' },
            { label: '[PE] ⑨炮', value: 'LI43NFTW1wRYV1MFPdPBFCyE1VXQRXY0TnqWNFfQ/PJk9KdVVHJYMlY=' },
            { label: '[PE] 方块九炮', value: 'LI43bJyUlFSXRNR1tiSEVdr1dn/VhFJc1WBXhVRU0MJYslY=' },
            { label: '[PE] C6i九炮', value: 'LI43NJRQxj9xAx76MMydNFe1b/ggzF2QU0lMFEx4NlfSHHYEJETeBS0ERVQO2URcVg==' },
            { label: '[PE] 心九炮', value: 'LI43NDQ0xAh97UEcSTDUVp3hxmdxA9atBGXTwVpTSUw0TAlYVXAzdhjVV09MV1RGLVuAVg==' },
            { label: '[PE] 轮炸九炮', value: 'LI43NMQIf+3BtXRXRsTI3X625IG19FdXXFP4IcxdQtWmdTZVP5Xugva/xwhe0OVcRVTbgkEPVg==' },
            { label: '[PE] ②炮', value: 'LI43NDRsnFSVZCRE2TIkDF1yW25kbIx0EBQoUuxclx7sLk9wqXwyV1T2O1huVg==' },
            { label: '[PE] 六芒星十炮', value: 'LI43NFTW11ictHRG0lbT11o02JoTQjcMXYI1l9R45kac099UVO0lWO5W' },
            { label: '[PE] 方块十炮', value: 'LI43NHRYSFpuFKQeU08IdlhTxWRaRVRy/lgBVg==' },
            { label: '[PE] 六边形十炮', value: 'LI43NJReWhZlQGxIIDQkDL00V/ZFKGRfelIC68aVUg1L/m1U3CdZblY=' },
            { label: '[PE] 斜方十炮', value: 'LI43NFTX11j8tHT+zJcVU1JTT3RQhoysjKA0zl9U2ZBfL1Y=' },
            { label: '[PE] 简化十炮', value: 'LI43NNTW11i8VHq2JIRV1QNujDRHNXSWSFS2FlkBVg==' },
            { label: '[PE] 后置十炮', value: 'LI43NMQIf+3BtXRXRsTI3X62JIRV2iXdNL42lGRNVJ3ZROdW' },
            { label: '[PE] 经典十炮', value: 'LI43NMQIf+0BJn+XFVJsVKYzdt9sSCAUtBC4dszuTGQYUlTsWEF5Vg==' },
            { label: '[PE] 六线囚尸', value: 'LI43HDCMf+0CJnFXV5cVUmREHMLIXUAPfe1BcrbEvCSE1VXSV9Q+V8aFEUxGhSFdcPfPWFTh+05VVg==' },
            { label: '[PE] 斜十炮', value: 'LI43bJyUlNTYBS0/FVZaU0l0jNLVdZRSejZX1hRF5E5SUp3hxmdxA2YULTTFwXTctFdUY/lGClY=' },
            { label: '[PE] 魔方十炮', value: 'LI43bJyUdO0CJnlXxNJWWMXUwVV/SVpu1D0IdlgQzFdUWy9C11Y=' },
            { label: '[PE] 戴夫的小汉堡', value: 'LI43NDRsnFSVZCTEVReYNXFQlq1TSbRMWjj0RPNtVGscWjRW' },
            { label: '[PE] 鸡尾酒', value: 'LI43bJyUlORGXBVgUNQMYhRcQyVsvJS05EZc1WDeTEZL+kfJ23BSVMT2WbxW' },
            { label: '[PE] 一勺汤圆十二炮', value: 'LI43NDRsnJSU5MZVVXSo11xV09daWFp/FXDQWUIXt9eBj1S1FWDHxKxUJDFbfVY=' },
            { label: '[PE] 玉壶春十二炮', value: 'LI43NFTW1wTYVDx2WlNJTEgCVnXEEraPVHUIWPgqcURKkDFaVNIpRK9W' },
            { label: '[PE] 半场十二炮', value: 'LI43bJyUlNTYBS00RdPXWnxMfOZGVlc4dMTVfFRU0eBEtVY=' },
            { label: '[PE] 简化十二炮', value: 'LI43NFRVncFYU9WAFVJsFEIlbLzU1lc4ZBFM3FRUrh9b/VY=' },
            { label: '[PE] 经典十二炮', value: 'LI43NMQIf+0BJn+XFVJsVKYzdt9sSCAUlYwQZCFlNMxYVKJYQjlW' },
            { label: '[PE] 火焰十二炮', value: 'LI5HDH7tAib9MHiXFVJ8RAx+bUcBkLX0V16Sctb9H1SXMFQdl0P1Vg==' },
            { label: '[PE] 冰雨十二炮·改', value: 'LI5HjH5tByb/cMwwbJxUUFYPcYPWEeKWEEhabvS01MHMdszuUGQYUlQZQXX/Vg==' },
            { label: '[PE] 神柱十二炮', value: 'LI43NJRUU01McIMeOlGFNJi0JITVlTX5lwJkWZCMEGQhNVZUc0RGrVY=' },
            { label: '[PE] 神之十二炮', value: 'LI43NJRUYsY/1SRxlxV0T9BNSFpu9DQ4dszuZFVUrGNGdVY=' },
            { label: '[PE] 水路无植物十二炮', value: 'LI43bJyUdO0GlNJVHNdlzMAIf+1CHdBM1P1flzBUSzNaFVY=' },
            { label: '[PE] 纯白悬空十二炮', value: 'LI43NIztIrOeyQ9DSDDUV/ScODDF0Nf8TM9c8npSWMdVqLZLHVY=' },
            { label: '[PE] 后花园十二炮', value: 'LI5HDH1d0lhTTUyUzBU08bAOdBBGJQxd0VNJTBRslFIHUAfDVNKdVL3WSy1W' },
            { label: '[PE] 玉米十二炮', value: 'LI435MW4wQhfkOlY6VhTTRQ0ce7clxVTQEjkRgdQB0NX0p1UJoJJiVY=' },
            { label: '[PE] 两路暴狂', value: 'LI5HDH7kAEZcUZTEdcLV1bV0V9ewDp3hdE7YTUhabmRs+CDkVYcUSNQRUAfDVNKdVDTSSQdW' },
            { label: '[PE] 九列十二炮', value: 'LI43NJRScIMe+hGkSFpudORZ0pwYRJ0kRP5fHGeM1B0wRWRUVBSURpZW' },
            { label: '[PE] 梯曾十二炮', value: 'LI43NMQIf+0BJn+XFVJ031VY1KjNnHZaU0kEZGJFGAlYTHJXVMV7TdFW' },
            { label: '[PE] 君海十二炮', value: 'LI43bJyUdO0CJnlXxFI3ZN1+tjST9J30WZdaZ9V2Z0UoUhn0aEIJzHZUAzZHt1Y=' },
            { label: '[PE] 箜篌引', value: 'LI43NDRsnFSVXFS2jXTfb0ggNCTkJQxd0BRC3lzA2/ZfDVDdW1TDNVutVg==' },
            { label: '[PE] 梅花十三', value: 'LI43NFTX11j8tHTmzJcVU0DYGVD+KnFEds8xV0Ll1SRUCm5EvlY=' },
            { label: '[PE] 最后之作', value: 'LI43bJyUlFSWYjTGVZ5Xtc0kRWQkDF3QU0kk3TS+lmRNVPidRIlW' },
            { label: '[PE] 冰心灯', value: 'LI43bJyUlFSXZNSSI2y8lLQ0V9AUTsNcSge0NlQcYVorVg==' },
            { label: '[PE] 太极十四炮', value: 'LI43NFTW1wRYV3SiHlJPzMyXFVNSU09k7UYQFhECdpC17jjUroQZ1qdVoCFGd1Y=' },
            { label: '[PE] 真·四炮', value: 'LI43NFTW1wRYV3TiWRaQtfRXfuKVQNX8wAjdNlrOXFSXIUUTVg==' },
            { label: '[PE] 神棍十四炮', value: 'LI5HDJ0kxNVV2PUUNHkIkFp2tiSEVdol3XS95tXeNMxYVLV/RKFW' },
            { label: '[PE] 神之十四炮', value: 'LI43NNRWT0zXtXRX17AOneF0TthNSFpu9LTUwcx2zO5MZBhSVASIQEVW' },
            { label: '[PE] 穿越十四炮', value: 'LI43bJyUdOQCNH9XzDJUVVhF09daJEjkRlxHZRFM3GRTVKtHT4VW' },
            { label: '[PE] 钻石十五炮', value: 'LI43NFTX11j8tHT+zJcVU2wSsxeRApahlKCNdN3VVVR1GkQKVg==' },
            { label: '[PE] 神之十五炮', value: 'LI43NDTkNVRVXF1WU01McIMe+lGFNJi0JIRVUVP4kEDV/9K/llBUBHVHElY=' },
            { label: '[PE] 真·二炮', value: 'LI43NDRsnNSUWDxgzLnkRlhbbmTUZAyQkjVyZktcOASYFIJbQ1NUWYJGCVY=' },
            { label: '[PE] 炮环十二花', value: 'LI43bJyUlNTYdbAefFDfbEggNCQMvTRX0H8VODh2zO5MZBhSVD8vTLlW' },
            { label: '[PE] 冰箱灯', value: 'LI43bJyUlNTYTUwC1j1PdGhcsmVsSCA0JOTVFnRPz1zyelJYx1XkQEHRVg==' },
            { label: '[PE] 对称十六炮', value: 'LI43NFTW1xToRhiWVN7clxVTXOLV52QQTNxkU1Rj1Ef5Vg==' },
            { label: '[PE] 神之十六炮', value: 'LI43NJRUU4Vk15cVUwA4133W/V9HVFTlfUVdVg==' },
            { label: '[PE] 裸奔十六炮', value: 'LI43NHRYSFpu9LRUTxhF0tcU0ZzMVQdQVImORX1W' },
            { label: '[PE] 双冰十六炮', value: 'LI43NNTW1wSYlDRz7QIm8rAe0NyXFVNA2BnQlVIJQ1fSnVTY7ECrVg==' },
            { label: '[PE] 超前置十六炮', value: 'LI43NDSMX9JTTUyUTFxwgx6awAjdRCVsvNTW5d1kjFUh+dC+1Mw3V2JRHVBUC6dDrFY=' },
            { label: '[PE] 火焰十六炮', value: 'LI5HDH7tAib9MHiXFVJSZDJElEQlbLzU1lcCNtyMXEQ1WlRgAUgGVg==' },
            { label: '[PE] 经典十六炮', value: 'LI43bJyUdO0CJnlXxNJWWEXT11p8TM9cV0WyVFSl5EIVVg==' },
            { label: '[PE] 冰魄十八炮', value: 'LI43bJyUlNTYBS00RdPXWnxMeOKGlVLSTUxkoDVBVVTbaUeWVg==' },
            { label: '[PE] 真·十八炮', value: 'LI43bJxUVlP1TM05V9A0ZdPXWgRGlhbkSQJWdRBY8j9xRHaYEGVNVBBEQHtW' },
            { label: '[PE] 纯十八炮', value: 'LI43bJyUlFSXRNR1tiSEVdUDNkM1dJZIVEkURjFW' },
            { label: '[PE] 尾炸十八炮', value: 'LI43bJyUlFSXRNR1tiSEVVE3R1X9wgh/7UL4P3lXFjByDDB/HFRUJdxBrVY=' },
            { label: '[PE] 经典十八炮', value: 'LI43NMQIX9APTVpmZNRlzBBBJWy81Nbl3TS+NpRkTVTbWU07Vg==' },
            { label: '[PE] 日花二十炮', value: 'LI43bJyUlNTYdfBZQNYRSFpu9DQ4djTBf/VENVrenVSXjEL9Vg==' },
            { label: '[PE] 纯二十炮', value: 'LI43bJyUlFSXRNR1tiSEVVFT+JBANXSWSFTNaEFTVg==' },
            { label: '[PE] 空炸二十炮', value: 'LI435MUIf+3G1dW1dEBnZIwcmhBBJWy81Nbl3ZQBd5iVRFVUqrxC3VY=' },
            { label: '[PE] 钉耙二十炮', value: 'LI43bJyUdO0CJnFXxFI3ZF1ADd9EJWy81NZXOGQRZCFlNMxYVO3jTgF2' },
            { label: '[PE] 新二十炮', value: 'LI43bJyUdO0CJn9XxFI3ZF1ADd9EJWy81NZXAjbcjDS+NpRkTVSCNk6OVg==' },
            { label: '[PE] 无冰瓜二十炮', value: 'LI43bJyUdO0CJnlXxFI3ZF1Azd1EJWy81NZXAjbcjDS+NpRkTVSedk72Vg==' },
            { label: '[PE] 绝望之路', value: 'LI43bJyUlNTYBS00RdPXWnxMfuaGNXkMgtLVdTRxV0WyVFTp8kH1Vg==' },
            { label: '[PE] 二十一炮', value: 'LI435DUMf+0CJnGXFVJSZFLH/HZaU0kEJNRZ8lwIYd5t/HZU85FMs1Y=' },
            { label: '[PE] 新二十二炮', value: 'LI43bJyUlNTYBS00RdPXWlzohjUx1FnyXFdFslRUarNMB1Y=' },
            { label: '[PE] 二十二炮', value: 'LI43bJyUdO0CJn9XxFI3ZN1+tiSEVVFT+JBE5dX/EmVTAVBU7CZNEFY=' },
            { label: '[PE] 无冰瓜二十二炮', value: 'LI43bJyUdO0CJnFXxFI3ZN1+tiSEVVFTjDTelAH3zNd+VlTMM0zrVg==' },
            { label: '[PE] 九列二十二炮', value: 'LI43bJyUdO0CJnFXxFI3ZN1+tiSEVVFTjDTelAHXZH5bOlpUyB1Mr1Y=' },
            { label: '[PE] 二十四炮', value: 'LI43bJyUlNTYBS00RdPXWnxsNHHS3FlXRbJUVHQGQ8pW' },
            { label: '[PE] 垫材二十四炮', value: 'LI43bJyUlNTYBS00RdPXWnxsNHHyXFdFslRUZEdMX1Y=' },
        ],
        fog: [
            { label: '[FE] 无神无炮', value: 'LI5H/ECMfgR99J/0n1RRVsHGZ3Hjdt9sAG74IAxN5GH0ZjRxADBx7lzyelVYx1XCuEBpVw==' },
            { label: '[FE] 两仪无炮', value: 'LI43NBRTVn9RgvbebPggzL3kRpBeDN8fUAdDclRUCFpeaVc=' },
            { label: '[FE] 十二格无炮', value: 'LI43NBRTVn9Rgl74EUIlDE1kZzRxKkUYCcxUVA0+XalX' },
            { label: '[FE] 太极无炮', value: 'LI43NJRQxj9xg3andwISmFgMTeRGETAxlDgwRVJS1eFWP02kVlTXKl6FVw==' },
            { label: '[FE] 水路无植物无炮', value: 'LI5HDH1tByb/1PrUeldAXPhADF+QD1GCZsRUUAIe+sEQhXFUYU31UlS4m1jKVw==' },
            { label: '[FE] 十二格玩具', value: 'LI43NHRYSAJu+FG2wVhYVT+1dmcFEVCCXvhxMFpUE5Ze5Vc=' },
            { label: '[FE] 间隔无炮', value: 'LI5HzH3kAjTxlA5SaJQ1cVBS+FgMT9QX8VScSOjyZGRUVEm/X8NX' },
            { label: '[FE] 方块无炮', value: 'LI43NBRTVn9Rgl44QQzfRCUMvWRnNDFUCkUYCcxUVEPNWTVX' },
            { label: '[FE] 热核无炮', value: 'LI5HjH7tAjT/lAJSbEQMf21HAZA1cVxS+FgM33LmQXV2ZEeXyPlWPHZUuyhB1lc=' },
            { label: '[FE] 半边无炮', value: 'LI5HDH3tAQbDFcNVWlAyXvhBjH7kwlVQlZQ1cVhS+FgMX9ZYMFVUGjla7lc=' },
            { label: '[FE] 茶壶无炮', value: 'LI43NJRQVj9RgnanSQJumFC2wXx2dKoS05jU4VU04VZncYMeOkGEMdS/QIxeQIVR3pRVVEAdRAdX' },
            { label: '[FE] 神之无炮', value: 'LI43NJRQVj9RgnanSQJumCAMneSFdWc0OZQO0FxclhBkITVWVDLJWz9X' },
            { label: '[FE] 心无炮', value: 'LI4R329FlGRYF1GV/xXQ13XMEnVR1lJZSWjCD8myLoXPoFcIClQSp528h5+fPGb5cOwdssGO/wREI76jH6lObKo9NKege2neQbVX' },
            { label: '[FE] 火焰无炮', value: 'LI5HDH/tQFBNNk30FDTylAZEUN740dxs+CAMX5AUbjQ5lA5wxcFcRRgJVkxyV1Sk9E7uVw==' },
            { label: '[FE] 智能无炮', value: 'LI5HDH/tAib/1HrXeldAXPjAyN1+tuRGUFeC1nR6RdXhvO5Q4l74QRRFVVRc5UJPVw==' },
            { label: '[FE] 后退无炮', value: 'LI5HjH7tAgYDFMNVWlAyXvhBjF5ADV9HJQxd1VXNVT9XgnYQTGJSONHdNL5GlGRNVH+DQ11X' },
            { label: '[FE] 塔曾无炮', value: 'LI43NBRTVn9RghZ0GJA18ZcYdApN5GI0eXpFGAnMVFRyPEYjVw==' },
            { label: '[FE] 顶满七列曾无炮', value: 'LI5HDH/tAib/8HpXXNbVlALVzRToQZwLX9AUtORGWE1I4lIwUvhRFfycHvScDlxAjH5tRzxaxnpVWMdV6HdLfVc=' },
            { label: '[FE] 无冰瓜一炮', value: 'LI5HzH3kAjT91HrXeldAVC10RXSd5EJ2tiSE1ZU18Zee1MFVFMXU4VU/FWj8XFcQEFQwmh500L/WztcwZlRfNk/dVw==' },
            { label: '[FE] 火焰二炮', value: 'LI5HDH7tAib9lAbSDFJ8RMzderbkhrX0V8RYDE3kQsNc8npVWMdVadNDc1c=' },
            { label: '[FE] 大雾二炮', value: 'LI5HDH/kQVwhTSBN9BQ08rAOHUBF08FaU0lMVgJS+FkM33525EVyduQGJnL+etXhvLJUVOOKQOFX' },
            { label: '[FE] 压制二炮', value: 'LI5HDH/tAQYDFMNVWlAyHtaRTIKWEEgCVrUVU1LV2VU/V4J231AwlhBkIV00zFhUo7pCRVc=' },
            { label: '[FE] 最简四炮', value: 'LI43NJRQxj9xA3anSVpu1GVXF5QOCHbM7mRVVB2qXltX' },
            { label: '[FE] 鬼位四炮', value: 'LI5HDH/twbV0V0ZEzH3UcrbkhjUxlJ7U4awQZCFdNMxYVI5vRNNX' },
            { label: '[FE] 落月四炮', value: 'LI43NDRsnNRdZJBIWm50pwLWrFp/VwJS+FGlV4JemMAIf+0BNHGXDsxOVXQLBgMUQ/VfVN9qWi9X' },
            { label: '[FE] 帆船四炮', value: 'LI43jJ8kxFVBuDHM3X6y5EZcW25kUABSMJYR1CjTwVhPV4JS+FHdXJhADH/kARTDNXkYQ8TjAhRDfFZTVEeTRq5X' },
            { label: '[FE] 神之四炮', value: 'LI43NJRQxj9xMx46MQxft29IIFS31MFVPyXdNL6WUFQbk1qDVw==' },
            { label: '[FE] 磁铁四炮', value: 'LI43bJyUdOQC9AU0cVdYlBCCXjjRXGxgFrUe1dlVPwURVgIWEGQhZTTMWFQMm0wVVw==' },
            { label: '[FE] 雾四炮', value: 'LI5HDH9tByb/1HrXeldAXPjACN9+tiSEVdhXglL4kXHW/R9UlzBUKUBH4Vc=' },
            { label: '[FE] 三角板六炮', value: 'LI43bJzUUlAyZvTdUfgwNCRsvNRwRuVGEHbfHZjQZrQuUQIe+sGIfmQHNHEYWFRts1jeVw==' },
            { label: '[FE] 玲珑六炮', value: 'LI43NFRVnc1WZ03E1LAOncFWf1GClqxaU0m0TMNc8nogx1XRI0RtVw==' },
            { label: '[FE] 烈焰八炮', value: 'LI5HDH7tACb5sAZVZDDcMTREVN34EEIlbLzU1uXdNL5GlGRNVLiuS5lX' },
            { label: '[FE] 无保护八炮', value: 'LI43NNTW11hc5EIBkDVxRPohbLyUVJaMEWQhZTTMWFQaDVq1Vw==' },
            { label: '[FE] 神之八炮', value: 'LI43NJRQxj/VJH+XFUyLtfRX15cYZF2QjBFkITVWVCQ/WztX' },
            { label: '[FE] 经典八炮', value: 'LI43NMQIfe0BJn+XFVJsxAh/bUcNkLX0V0xTOFnMTeRCGXBHdtb931WXMFRBR0KjVw==' },
            { label: '[FE] 七夕灯', value: 'LI43NDRsnFSVnFSQC920bkggNCQMXXblp5U0cQIHxJBUiQZY+1c=' },
            { label: '[FE] 斜方十炮', value: 'LI43NFTX11j8tHT+zJcVU1LTwRRc8OWl5b2VYENUuXBZe1c=' },
            { label: '[FE] 河洛十炮', value: 'LI43NHRSbEgg1DdwxcEUXEM1bFyQf9WkdFfmXFhXVVR87ll7Vw==' },
            { label: '[FE] 纯十二炮', value: 'LI43NFRVncFYU00EVObclxVTQNgZ0NVcJ1QrAURBVw==' },
            { label: '[FE] 水路无植物十二炮', value: 'LI43bJyUdO0CJnFXxFI3ZN1yFlh0lkhUB31beVc=' },
            { label: '[FE] 神之十二炮', value: 'LI43NBRTVn9xg1a1HtLXFFpcZ2xIIBSVjBBkITVWVGCmR09X' },
            { label: '[FE] 曲径通幽处', value: 'LI43bJyUlNTYBS00RdPXWlhaB9WgAERdQg29ZMfVVZbX3lYBHvpRlsEEBzR2f0V2VNLPQfJX' },
            { label: '[FE] 某十四炮', value: 'LI43NDRsnNSUZNSSIwy9JITVVdgDtkaVN14AWFTcsURnVw==' },
            { label: '[FE] 礼物盒十四炮', value: 'LI43bJxUVWROkhK2b0gg1DdwxcEUXENV/wtd0FNlGNXfVFQKyURnVw==' },
            { label: '[FE] 弦十四炮', value: 'LI43jJ8kxNVV2DU0e5cYAGXTwVpTSUw0TO9c8npSWMdVObhH01c=' },
            { label: '[FE] 奇门九劫', value: 'LI43NFTW1wRYV3SiHnTQ3m1IIDQkDN105d00vjaUZE1UBmRHg1c=' },
            { label: '[FE] 半场十四炮', value: 'LI43NHRYSFpudKQe08GMEExa9jV4dlS0vkVnVw==' },
            { label: '[FE] 灯笼十六炮', value: 'LI43bJyUlFSXRORGmpvQXGxIINQ3CHbM7kxkGFJUsulFYVc=' },
            { label: '[FE] 花环十六炮', value: 'LI43NDRsnNSURFQ2+VAW/NyXFVNS08FcRs9c8npSWMdV8vRBDVc=' },
            { label: '[FE] 中压制十八炮', value: 'LI43bJyUlFSXRNR1tiSEVdUDNkM1dJZIVEkURjFX' },
            { label: '[FE] 无冰瓜十八炮', value: 'LI43bJyUdO0CJnlXxFI3ZF1Azd1EJWy8lLTkhlUWV2UIMHEWUAdDV9KdVMe6TcJX' },
            { label: '[FE] 十九炮', value: 'LI43bJyUdO0CJnFXxNJW3JwO0NyXFVNS08E0Rty1dhxsdEf4Tk1nNN5UVLoFQt5X' },
            { label: '[FE] 二十二炮', value: 'LI43bJyUlNTYBS00RdPXWlzohjVxYkVSdphVVF+jQ29X' },
            { label: '[FE] 二十四炮', value: 'LI43bJyUlNTYBS00RdPXWnxsNHHyXFdFslRUZEdMX1c=' },
        ],
        roof: [
            { label: '[RE] 无神无炮', value: 'LI7P5CGWnl0UmFRTFIoYdIredhbSTlS8OkyxUA==' },
            { label: '[RE] 群曾无炮', value: 'LI7P5CaWgl1/c7xmlFXEa0fcgxoMj+RCfuYm1plQxO75ZGX4PoSYVVRFskubUA==' },
            { label: '[RE] 水晶杯四炮', value: 'LI4/DI00l9RWTgJimDg0zO3itTRXFlCcUrfhLID0zVdUT0JBYVA=' },
            { label: '[RE] #四炮', value: 'LI7P5Caygs0/M74ahDHU1tLNWVNPTNQ2D3P4OQxfQuVV3/jIXcI9zN0ZmVBYJ1Q3/XZIUA==' },
            { label: '[RE] 波纹五炮', value: 'LI4/bIyUZCe5mMFZYlgEhOTmVX5SQ81dR5f3UpdIVEc7TmxQ' },
            { label: '[RE] 小六炮', value: 'LI43NBRTWWJZP4UQWmJkYPhQ3lc9QEVSWEVwYVQgoEW3UA==' },
            { label: '[RE] 分隔六炮', value: 'LI4/bIyUZCe5mMFn42JUDYwVVw0+VE+RQl1Q' },
            { label: '[RE] 方三角六炮', value: 'LI4/bIyUZCe5mPlnA2YUFZeYUuSMUE/sXMRbRZf7UoFIVKnRTZtQ' },
            { label: '[RE] *道六炮', value: 'LI4/bIyUZCexmM1HAhqMjuTCVVxOOE4UNj9z+FGFjFXyzlJYJ1Q91UkXUA==' },
            { label: '[RE] 神之七炮', value: 'LI43NBRTWVNPTE44MvrJ7UaQ1t9UpZjhfHZ8PmRVVOmXQEJQ' },
            { label: '[RE] 方块八炮', value: 'LI4/bIyUhDSHVHA19DUxlxh0EkJ1H1lU1OJDR1A=' },
            { label: '[RE] 斜方八炮', value: 'LI43NDQ0PGyMlNRYFKjSwVwFfCtyFviVUhfZWUx2zVBUuq5C4lA=' },
            { label: '[RE] 理发八炮', value: 'LI4/bIyUZCW9kIzd8VkUQlxgNN6MYPg4zG6F9TV+xOKV9VIXUFRrQHUiUA==' },
            { label: '[RE] 沙漏八炮', value: 'LI4/bIyUhDSXVFBZFELM4j3MbSd5V5eYwSRFdGknsZjNHHYMgfTOV1Rtrk+lUA==' },
            { label: '[RE] #八炮', value: 'LI4/bIyUZCe5mMFn42JUDXSEZEeQzm0nsoJdZ0+C1hE4TnT+pP2VZFNUjBJwt1A=' },
            { label: '[RE] 螺旋十炮', value: 'LI43NDxsjFSSZFSy+zjkFdzVEThOMlYRBZEEAGX0zVBU2PpMB1A=' },
            { label: '[RE] 镂铭灯', value: 'LI43NDxsjJSUVHFN9PjSwVliFNh+wh0MWeZtVMO1TMRQ' },
            { label: '[RE] 天台十炮', value: 'LI4/bIyUZCe5mPln42JUDXRU9tWozTx2cP9VVIgtcJlQ' },
            { label: '[RE] 十一炮', value: 'LI4/jI4k5NU1so7NDzPWDVhYWWf1dme1dhRGeNIbWdJtVPcYfYBQ' },
            { label: '[RE] 花灯十二炮', value: 'LI4/bIyUhFSRRIQ0U7djjBURFLjBFBwcWd5tVFyFTgNQ' },
            { label: '[RE] 椭盘十二炮', value: 'LI43NDxsjFSVIlg0VLOPYIxhjPTcFGUMOHFMdt3UkcSsVEoHSPFQ' },
            { label: '[RE] 螺旋十二炮', value: 'LI4/DI00hyTk1VXQdfQ1cthbRz8UBocU0E5cVFTAUkk6UA==' },
            { label: '[RE] 鸟居十二炮', value: 'LI4/bIyUhNTQTQQsREVSGVI5QFgBYSe5mOEEQQTFXWJHODR2VGV7TtVQ' },
            { label: '[RE] 天台十二炮', value: 'LI4/bIyUZDW/mOFn45qIjlQwZ2TUHERS3TXc+Mg0h+RCw04AJ1QijH1QUA==' },
            { label: '[RE] 椭盘十四炮', value: 'LI4/5D1sjJRUklhEVDKXEbV2HEx85kaa49XfmBDc1lRU21dLg1A=' },
            { label: '[RE] 十六炮', value: 'LI4/bIyUhNTQTQQsLBE4MvrJ7UKW09/4yO1GclZUJBR2zVA=' },
            { label: '[RE] 十七炮', value: 'LI4/bIyUhFSXf084TERoNhHUTM9cVNyId9VQ' },
            { label: '[RE] 十八炮', value: 'LI4/bIyUhNTQTQQsEN34OOSVclZUIDR3CVA=' },
        ],
        moon: [
            { label: '[ME] 无神无炮', value: 'LI7P5CGWnl0UmFRTFIoYdIredhbSTlS8OkyxUQ==' },
            { label: '[ME] 核聚变无炮', value: 'LI7P5CGWHnSAMdTXXQ9zmFC24UeClhEC1rUCcEUYYUyyVFQN4E8kUQ==' },
            { label: '[ME] 群曾无炮', value: 'LI7P5CaWAnSAOYQx1NZdf3OYUN/5OQxfQw1t1VUNWP9OYCdUE/J0qVE=' },
            { label: '[ME] 长矛无炮', value: 'LI7P5CGWnl3uRyBNtFScy201v9DhR4J23dS0gl1YZAV4PmSYVVQ7q0h5UQ==' },
            { label: '[ME] 双核一炮', value: 'LI7P5CGWnl3uRyBNtFScy201v9DhR4J2EE5aYmRUkQK2Bdc1WlRWy03/UQ==' },
            { label: '[ME] 神之五炮', value: 'LI43NBRTWVNPTDL6ye0ilgJEX3jm5jWymMFnMxoMXUOVBNddVHhCQgNR' },
            { label: '[ME] 神之六炮', value: 'LI43NBRTWVNPTDL6ye0msgJEX3rmJrKYzX8FEASANFZUQaFBvVE=' },
            { label: '[ME] 底置六炮', value: 'LI4/bIyUZCe5mM1n42YUFZeYUsSMns0PT4IWEQJiFAFhSJD9UpdIVImASrRR' },
            { label: '[ME] 无蘑菇七炮', value: 'LI4/bIyUZDW/GHQ4VOYUVJzPXbabyN1w5kZYpfw9lGRTVB5BcrlR' },
            { label: '[ME] 对称八炮', value: 'LI4/bIyUlJRkJ3FXSGAUEIKWDCTFwUx2HD50VA1ZVJpGQA9R' },
            { label: '[ME] 奇怪的八炮', value: 'LI4/bIyUZCe5mPln42JUDXRU9jP6yG1HdWYVI9Z4V16UAIfUNVpUlaVK71E=' },
            { label: '[ME] 田八炮', value: 'LI4/bIyUZCd5V5eY+VkUQlxgNNwUlJjBXCJXRe5Uk1FNz1E=' },
            { label: '[ME] 轮回之瞳', value: 'LI43NDxsjFSSXITk5jUiF3IWWPJWGXDvNTKXHnAJPLJUVG2nQnBR' },
            { label: '[ME] 分隔九炮', value: 'LI4/bIyUhFSRRITk5jVyRNec4QRF5oBUVMniSSpR' },
            { label: '[ME] 无保护十炮', value: 'LI4/bIyUhOTGVVxO1HhMieRCF9AwYVQ+70M0UQ==' },
            { label: '[ME] 月夜十炮', value: 'LI4/bIyUZCe/mM1n42JUDXRU9jP6Ud713viQRHX0X1SOGXCdUQ==' },
            { label: '[ME] 瓮中捉鳖', value: 'LI43NDxsjFSSZFS3d5CU6ME03H7SF3NQVFTDv0zcUQ==' },
            { label: '[ME] 十三炮', value: 'LI4/bIyUhFSRRIQU8JyY4WczmghfR1ff+FCW+WRFVBvKSgpR' },
            { label: '[ME] 十八炮', value: 'LI4/bIyUhFSWfxVwXGC0QtU2thBUd7B1sVE=' },
            { label: '[ME] 十九炮', value: 'LI4/bIyUhFSXf09MTERofHIDUFQ+fHapUQ==' },
        ],
    };


    return {
        seedTypes,
        zombieTypes,
        setZombieTypes,
        selectRows,
        selectCols,
        packetIdx,
        gridItemTypes,
        easyPlaceModeList,
        scaryPotType,
        scaryPotAppearance,
        coinTypes,
        gameModes,
        lineupCodeMap,
    };
})();
