import typing, abc
from System.Collections.Generic import IDictionary_2, Dictionary_2, KeyValuePair_2
from System.Collections.ObjectModel import ReadOnlyCollection_1
from System import Array_1, StringComparer, IEquatable_1
from System.Reflection import Assembly
from System.IO import Stream, FileMode, FileAccess, FileShare, TextReader
from Microsoft.Scripting.Runtime import LanguageContext, Scope
from System.Text import Encoding
from System.Linq.Expressions import SymbolDocumentInfo

class CompilerOptions:
    def __init__(self) -> None: ...


class ErrorSink:
    Default : ErrorSink
    Null : ErrorSink
    # Skipped Add due to it being static, abstract and generic.

    Add : Add_MethodGroup
    class Add_MethodGroup:
        @typing.overload
        def __call__(self, source: SourceUnit, message: str, span: SourceSpan, errorCode: int, severity: Severity) -> None:...
        @typing.overload
        def __call__(self, message: str, path: str, code: str, line: str, span: SourceSpan, errorCode: int, severity: Severity) -> None:...



class LanguageOptions:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, options: IDictionary_2[str, typing.Any]) -> None: ...
    @property
    def CompilationThreshold(self) -> int: ...
    @property
    def ExceptionDetail(self) -> bool: ...
    @ExceptionDetail.setter
    def ExceptionDetail(self, value: bool) -> bool: ...
    @property
    def InterpretedMode(self) -> bool: ...
    @InterpretedMode.setter
    def InterpretedMode(self, value: bool) -> bool: ...
    @property
    def NoAdaptiveCompilation(self) -> bool: ...
    @property
    def PerfStats(self) -> bool: ...
    @property
    def SearchPaths(self) -> ReadOnlyCollection_1[str]: ...
    @property
    def ShowClrExceptions(self) -> bool: ...
    @ShowClrExceptions.setter
    def ShowClrExceptions(self, value: bool) -> bool: ...
    @staticmethod
    def GetSearchPathsOption(options: IDictionary_2[str, typing.Any]) -> ReadOnlyCollection_1[str]: ...
    @staticmethod
    def GetStringCollectionOption(options: IDictionary_2[str, typing.Any], name: str, separators: Array_1[str]) -> ReadOnlyCollection_1[str]: ...
    # Skipped GetOption due to it being static, abstract and generic.

    GetOption : GetOption_MethodGroup
    class GetOption_MethodGroup:
        def __getitem__(self, t:typing.Type[GetOption_1_T1]) -> GetOption_1[GetOption_1_T1]: ...

        GetOption_1_T1 = typing.TypeVar('GetOption_1_T1')
        class GetOption_1(typing.Generic[GetOption_1_T1]):
            GetOption_1_T = LanguageOptions.GetOption_MethodGroup.GetOption_1_T1
            def __call__(self, options: IDictionary_2[str, typing.Any], name: str, defaultValue: GetOption_1_T) -> GetOption_1_T:...




class PlatformAdaptationLayer:
    def __init__(self) -> None: ...
    Default : PlatformAdaptationLayer
    IsCompactFramework : bool
    @property
    def CurrentDirectory(self) -> str: ...
    @CurrentDirectory.setter
    def CurrentDirectory(self, value: str) -> str: ...
    @classmethod
    @property
    def IsNativeModule(cls) -> bool: ...
    @property
    def IsSingleRootFileSystem(self) -> bool: ...
    @property
    def PathComparer(self) -> StringComparer: ...
    def CombinePaths(self, path1: str, path2: str) -> str: ...
    def CreateDirectory(self, path: str) -> None: ...
    def DeleteDirectory(self, path: str, recursive: bool) -> None: ...
    def DeleteFile(self, path: str, deleteReadOnly: bool) -> None: ...
    def DirectoryExists(self, path: str) -> bool: ...
    def FileExists(self, path: str) -> bool: ...
    def GetDirectories(self, path: str, searchPattern: str) -> Array_1[str]: ...
    def GetDirectoryName(self, path: str) -> str: ...
    def GetEnvironmentVariable(self, key: str) -> str: ...
    def GetEnvironmentVariables(self) -> Dictionary_2[str, str]: ...
    def GetExtension(self, path: str) -> str: ...
    def GetFileName(self, path: str) -> str: ...
    def GetFileNameWithoutExtension(self, path: str) -> str: ...
    def GetFiles(self, path: str, searchPattern: str) -> Array_1[str]: ...
    def GetFullPath(self, path: str) -> str: ...
    def IsAbsolutePath(self, path: str) -> bool: ...
    def LoadAssembly(self, name: str) -> Assembly: ...
    def LoadAssemblyFromPath(self, path: str) -> Assembly: ...
    def MoveFileSystemEntry(self, sourcePath: str, destinationPath: str) -> None: ...
    def OpenFileStream(self, path: str, mode: FileMode = ..., access: FileAccess = ..., share: FileShare = ..., bufferSize: int = ...) -> Stream: ...
    def OpenInputFileStream(self, path: str, mode: FileMode = ..., access: FileAccess = ..., share: FileShare = ..., bufferSize: int = ...) -> Stream: ...
    def OpenOutputFileStream(self, path: str) -> Stream: ...
    def SetEnvironmentVariable(self, key: str, value: str) -> None: ...
    def TerminateScriptExecution(self, exitCode: int) -> None: ...
    # Skipped GetFileSystemEntries due to it being static, abstract and generic.

    GetFileSystemEntries : GetFileSystemEntries_MethodGroup
    class GetFileSystemEntries_MethodGroup:
        @typing.overload
        def __call__(self, path: str, searchPattern: str) -> Array_1[str]:...
        @typing.overload
        def __call__(self, path: str, searchPattern: str, includeFiles: bool, includeDirectories: bool) -> Array_1[str]:...



class ScriptCode(abc.ABC):
    @property
    def LanguageContext(self) -> LanguageContext: ...
    @property
    def SourceUnit(self) -> SourceUnit: ...
    def CreateScope(self) -> Scope: ...
    def ToString(self) -> str: ...
    # Skipped Run due to it being static, abstract and generic.

    Run : Run_MethodGroup
    class Run_MethodGroup:
        @typing.overload
        def __call__(self) -> typing.Any:...
        @typing.overload
        def __call__(self, scope: Scope) -> typing.Any:...



class ScriptCodeParseResult(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Complete : ScriptCodeParseResult # 0
    Empty : ScriptCodeParseResult # 1
    Invalid : ScriptCodeParseResult # 2
    IncompleteToken : ScriptCodeParseResult # 3
    IncompleteStatement : ScriptCodeParseResult # 4


class Severity(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Ignore : Severity # 0
    Warning : Severity # 1
    Error : Severity # 2
    FatalError : Severity # 3


class SourceCodeKind(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Unspecified : SourceCodeKind # 0
    Expression : SourceCodeKind # 1
    Statements : SourceCodeKind # 2
    SingleStatement : SourceCodeKind # 3
    File : SourceCodeKind # 4
    InteractiveCode : SourceCodeKind # 5
    AutoDetect : SourceCodeKind # 6


class SourceCodeReader(TextReader):
    def __init__(self, textReader: TextReader, encoding: Encoding) -> None: ...
    Null : SourceCodeReader
    @property
    def BaseReader(self) -> TextReader: ...
    @property
    def Encoding(self) -> Encoding: ...
    def Peek(self) -> int: ...
    def ReadLine(self) -> str: ...
    def ReadToEnd(self) -> str: ...
    def SeekLine(self, line: int) -> bool: ...
    # Skipped Read due to it being static, abstract and generic.

    Read : Read_MethodGroup
    class Read_MethodGroup:
        @typing.overload
        def __call__(self) -> int:...
        @typing.overload
        def __call__(self, buffer: Array_1[str], index: int, count: int) -> int:...



class SourceLocation(IEquatable_1[SourceLocation]):
    def __init__(self, index: int, line: int, column: int) -> None: ...
    Invalid : SourceLocation
    MinValue : SourceLocation
    None_ : SourceLocation
    @property
    def Column(self) -> int: ...
    @property
    def Index(self) -> int: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def Line(self) -> int: ...
    @staticmethod
    def Compare(left: SourceLocation, right: SourceLocation) -> int: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: SourceLocation, right: SourceLocation) -> bool: ...
    def __gt__(self, left: SourceLocation, right: SourceLocation) -> bool: ...
    def __ge__(self, left: SourceLocation, right: SourceLocation) -> bool: ...
    def __ne__(self, left: SourceLocation, right: SourceLocation) -> bool: ...
    def __lt__(self, left: SourceLocation, right: SourceLocation) -> bool: ...
    def __le__(self, left: SourceLocation, right: SourceLocation) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: SourceLocation) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class SourceSpan(IEquatable_1[SourceSpan]):
    def __init__(self, start: SourceLocation, end: SourceLocation) -> None: ...
    Invalid : SourceSpan
    None_ : SourceSpan
    @property
    def End(self) -> SourceLocation: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def Length(self) -> int: ...
    @property
    def Start(self) -> SourceLocation: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: SourceSpan, right: SourceSpan) -> bool: ...
    def __ne__(self, left: SourceSpan, right: SourceSpan) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: SourceSpan) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class SourceUnit:
    def __init__(self, context: LanguageContext, contentProvider: TextContentProvider, path: str, kind: SourceCodeKind) -> None: ...
    @property
    def CodeProperties(self) -> typing.Optional[ScriptCodeParseResult]: ...
    @CodeProperties.setter
    def CodeProperties(self, value: typing.Optional[ScriptCodeParseResult]) -> typing.Optional[ScriptCodeParseResult]: ...
    @property
    def Document(self) -> SymbolDocumentInfo: ...
    @property
    def EmitDebugSymbols(self) -> bool: ...
    @property
    def HasLineMapping(self) -> bool: ...
    @property
    def HasPath(self) -> bool: ...
    @property
    def Kind(self) -> SourceCodeKind: ...
    @property
    def LanguageContext(self) -> LanguageContext: ...
    @property
    def Path(self) -> str: ...
    def ExecuteProgram(self) -> int: ...
    def GetCode(self) -> str: ...
    def GetCodeLine(self, line: int) -> str: ...
    def GetCodeLines(self, start: int, count: int) -> Array_1[str]: ...
    def GetReader(self) -> SourceCodeReader: ...
    def MapLine(self, line: int) -> int: ...
    def SetLineMapping(self, lineMap: Array_1[KeyValuePair_2[int, int]]) -> None: ...
    # Skipped Compile due to it being static, abstract and generic.

    Compile : Compile_MethodGroup
    class Compile_MethodGroup:
        @typing.overload
        def __call__(self) -> ScriptCode:...
        @typing.overload
        def __call__(self, errorSink: ErrorSink) -> ScriptCode:...
        @typing.overload
        def __call__(self, options: CompilerOptions, errorSink: ErrorSink) -> ScriptCode:...

    # Skipped Execute due to it being static, abstract and generic.

    Execute : Execute_MethodGroup
    class Execute_MethodGroup:
        @typing.overload
        def __call__(self) -> typing.Any:...
        @typing.overload
        def __call__(self, errorSink: ErrorSink) -> typing.Any:...
        @typing.overload
        def __call__(self, scope: Scope) -> typing.Any:...
        @typing.overload
        def __call__(self, options: CompilerOptions, errorSink: ErrorSink) -> typing.Any:...
        @typing.overload
        def __call__(self, scope: Scope, errorSink: ErrorSink) -> typing.Any:...

    # Skipped GetCodeProperties due to it being static, abstract and generic.

    GetCodeProperties : GetCodeProperties_MethodGroup
    class GetCodeProperties_MethodGroup:
        @typing.overload
        def __call__(self) -> ScriptCodeParseResult:...
        @typing.overload
        def __call__(self, options: CompilerOptions) -> ScriptCodeParseResult:...

    # Skipped MakeLocation due to it being static, abstract and generic.

    MakeLocation : MakeLocation_MethodGroup
    class MakeLocation_MethodGroup:
        @typing.overload
        def __call__(self, loc: SourceLocation) -> SourceLocation:...
        @typing.overload
        def __call__(self, index: int, line: int, column: int) -> SourceLocation:...



class StreamContentProvider(abc.ABC):
    @abc.abstractmethod
    def GetStream(self) -> Stream: ...


class TextContentProvider(abc.ABC):
    @abc.abstractmethod
    def GetReader(self) -> SourceCodeReader: ...

