import typing, clr, abc
from System.Collections.Generic import IReadOnlyDictionary_2, IDictionary_2, IEnumerable_1, KeyValuePair_2, IEqualityComparer_1, ICollection_1, IEnumerator_1, IReadOnlyCollection_1
from System.Collections import IDictionary, ICollection
from System import Array_1, Func_3, Func_4, Func_2

class ConcurrentDictionary_GenericClasses(abc.ABCMeta):
    Generic_ConcurrentDictionary_GenericClasses_ConcurrentDictionary_2_TKey = typing.TypeVar('Generic_ConcurrentDictionary_GenericClasses_ConcurrentDictionary_2_TKey')
    Generic_ConcurrentDictionary_GenericClasses_ConcurrentDictionary_2_TValue = typing.TypeVar('Generic_ConcurrentDictionary_GenericClasses_ConcurrentDictionary_2_TValue')
    def __getitem__(self, types : typing.Tuple[typing.Type[Generic_ConcurrentDictionary_GenericClasses_ConcurrentDictionary_2_TKey], typing.Type[Generic_ConcurrentDictionary_GenericClasses_ConcurrentDictionary_2_TValue]]) -> typing.Type[ConcurrentDictionary_2[Generic_ConcurrentDictionary_GenericClasses_ConcurrentDictionary_2_TKey, Generic_ConcurrentDictionary_GenericClasses_ConcurrentDictionary_2_TValue]]: ...

ConcurrentDictionary : ConcurrentDictionary_GenericClasses

ConcurrentDictionary_2_TKey = typing.TypeVar('ConcurrentDictionary_2_TKey')
ConcurrentDictionary_2_TValue = typing.TypeVar('ConcurrentDictionary_2_TValue')
class ConcurrentDictionary_2(typing.Generic[ConcurrentDictionary_2_TKey, ConcurrentDictionary_2_TValue], IReadOnlyDictionary_2[ConcurrentDictionary_2_TKey, ConcurrentDictionary_2_TValue], IDictionary_2[ConcurrentDictionary_2_TKey, ConcurrentDictionary_2_TValue], IDictionary):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, collection: IEnumerable_1[KeyValuePair_2[ConcurrentDictionary_2_TKey, ConcurrentDictionary_2_TValue]]) -> None: ...
    @typing.overload
    def __init__(self, collection: IEnumerable_1[KeyValuePair_2[ConcurrentDictionary_2_TKey, ConcurrentDictionary_2_TValue]], comparer: IEqualityComparer_1[ConcurrentDictionary_2_TKey]) -> None: ...
    @typing.overload
    def __init__(self, comparer: IEqualityComparer_1[ConcurrentDictionary_2_TKey]) -> None: ...
    @typing.overload
    def __init__(self, concurrencyLevel: int, capacity: int) -> None: ...
    @typing.overload
    def __init__(self, concurrencyLevel: int, capacity: int, comparer: IEqualityComparer_1[ConcurrentDictionary_2_TKey]) -> None: ...
    @typing.overload
    def __init__(self, concurrencyLevel: int, collection: IEnumerable_1[KeyValuePair_2[ConcurrentDictionary_2_TKey, ConcurrentDictionary_2_TValue]], comparer: IEqualityComparer_1[ConcurrentDictionary_2_TKey]) -> None: ...
    @property
    def Comparer(self) -> IEqualityComparer_1[ConcurrentDictionary_2_TKey]: ...
    @property
    def Count(self) -> int: ...
    @property
    def IsEmpty(self) -> bool: ...
    @property
    def Item(self) -> ConcurrentDictionary_2_TValue: ...
    @Item.setter
    def Item(self, value: ConcurrentDictionary_2_TValue) -> ConcurrentDictionary_2_TValue: ...
    @property
    def Keys(self) -> ICollection_1[ConcurrentDictionary_2_TKey]: ...
    @property
    def Values(self) -> ICollection_1[ConcurrentDictionary_2_TValue]: ...
    def Clear(self) -> None: ...
    def ContainsKey(self, key: ConcurrentDictionary_2_TKey) -> bool: ...
    def GetEnumerator(self) -> IEnumerator_1[KeyValuePair_2[ConcurrentDictionary_2_TKey, ConcurrentDictionary_2_TValue]]: ...
    def ToArray(self) -> Array_1[KeyValuePair_2[ConcurrentDictionary_2_TKey, ConcurrentDictionary_2_TValue]]: ...
    def TryAdd(self, key: ConcurrentDictionary_2_TKey, value: ConcurrentDictionary_2_TValue) -> bool: ...
    def TryGetValue(self, key: ConcurrentDictionary_2_TKey, value: clr.Reference[ConcurrentDictionary_2_TValue]) -> bool: ...
    def TryUpdate(self, key: ConcurrentDictionary_2_TKey, newValue: ConcurrentDictionary_2_TValue, comparisonValue: ConcurrentDictionary_2_TValue) -> bool: ...
    # Skipped AddOrUpdate due to it being static, abstract and generic.

    AddOrUpdate : AddOrUpdate_MethodGroup[ConcurrentDictionary_2_TKey, ConcurrentDictionary_2_TValue]
    AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TKey = typing.TypeVar('AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TKey')
    AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue = typing.TypeVar('AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue')
    class AddOrUpdate_MethodGroup(typing.Generic[AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TKey, AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue]):
        AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TKey = ConcurrentDictionary_2.AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TKey
        AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue = ConcurrentDictionary_2.AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue
        def __getitem__(self, t:typing.Type[AddOrUpdate_1_T1]) -> AddOrUpdate_1[AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TKey, AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue, AddOrUpdate_1_T1]: ...

        AddOrUpdate_1_ConcurrentDictionary_2_TKey = typing.TypeVar('AddOrUpdate_1_ConcurrentDictionary_2_TKey')
        AddOrUpdate_1_ConcurrentDictionary_2_TValue = typing.TypeVar('AddOrUpdate_1_ConcurrentDictionary_2_TValue')
        AddOrUpdate_1_T1 = typing.TypeVar('AddOrUpdate_1_T1')
        class AddOrUpdate_1(typing.Generic[AddOrUpdate_1_ConcurrentDictionary_2_TKey, AddOrUpdate_1_ConcurrentDictionary_2_TValue, AddOrUpdate_1_T1]):
            AddOrUpdate_1_ConcurrentDictionary_2_TKey = ConcurrentDictionary_2.AddOrUpdate_MethodGroup.AddOrUpdate_1_ConcurrentDictionary_2_TKey
            AddOrUpdate_1_ConcurrentDictionary_2_TValue = ConcurrentDictionary_2.AddOrUpdate_MethodGroup.AddOrUpdate_1_ConcurrentDictionary_2_TValue
            AddOrUpdate_1_TArg = ConcurrentDictionary_2.AddOrUpdate_MethodGroup.AddOrUpdate_1_T1
            def __call__(self, key: AddOrUpdate_1_ConcurrentDictionary_2_TKey, addValueFactory: Func_3[AddOrUpdate_1_ConcurrentDictionary_2_TKey, AddOrUpdate_1_TArg, AddOrUpdate_1_ConcurrentDictionary_2_TValue], updateValueFactory: Func_4[AddOrUpdate_1_ConcurrentDictionary_2_TKey, AddOrUpdate_1_ConcurrentDictionary_2_TValue, AddOrUpdate_1_TArg, AddOrUpdate_1_ConcurrentDictionary_2_TValue], factoryArgument: AddOrUpdate_1_TArg) -> AddOrUpdate_1_ConcurrentDictionary_2_TValue:...

        @typing.overload
        def __call__(self, key: AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TKey, addValueFactory: Func_2[AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TKey, AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue], updateValueFactory: Func_3[AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TKey, AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue, AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue]) -> AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue:...
        @typing.overload
        def __call__(self, key: AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TKey, addValue: AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue, updateValueFactory: Func_3[AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TKey, AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue, AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue]) -> AddOrUpdate_MethodGroup_ConcurrentDictionary_2_TValue:...

    # Skipped GetOrAdd due to it being static, abstract and generic.

    GetOrAdd : GetOrAdd_MethodGroup[ConcurrentDictionary_2_TKey, ConcurrentDictionary_2_TValue]
    GetOrAdd_MethodGroup_ConcurrentDictionary_2_TKey = typing.TypeVar('GetOrAdd_MethodGroup_ConcurrentDictionary_2_TKey')
    GetOrAdd_MethodGroup_ConcurrentDictionary_2_TValue = typing.TypeVar('GetOrAdd_MethodGroup_ConcurrentDictionary_2_TValue')
    class GetOrAdd_MethodGroup(typing.Generic[GetOrAdd_MethodGroup_ConcurrentDictionary_2_TKey, GetOrAdd_MethodGroup_ConcurrentDictionary_2_TValue]):
        GetOrAdd_MethodGroup_ConcurrentDictionary_2_TKey = ConcurrentDictionary_2.GetOrAdd_MethodGroup_ConcurrentDictionary_2_TKey
        GetOrAdd_MethodGroup_ConcurrentDictionary_2_TValue = ConcurrentDictionary_2.GetOrAdd_MethodGroup_ConcurrentDictionary_2_TValue
        def __getitem__(self, t:typing.Type[GetOrAdd_1_T1]) -> GetOrAdd_1[GetOrAdd_MethodGroup_ConcurrentDictionary_2_TKey, GetOrAdd_MethodGroup_ConcurrentDictionary_2_TValue, GetOrAdd_1_T1]: ...

        GetOrAdd_1_ConcurrentDictionary_2_TKey = typing.TypeVar('GetOrAdd_1_ConcurrentDictionary_2_TKey')
        GetOrAdd_1_ConcurrentDictionary_2_TValue = typing.TypeVar('GetOrAdd_1_ConcurrentDictionary_2_TValue')
        GetOrAdd_1_T1 = typing.TypeVar('GetOrAdd_1_T1')
        class GetOrAdd_1(typing.Generic[GetOrAdd_1_ConcurrentDictionary_2_TKey, GetOrAdd_1_ConcurrentDictionary_2_TValue, GetOrAdd_1_T1]):
            GetOrAdd_1_ConcurrentDictionary_2_TKey = ConcurrentDictionary_2.GetOrAdd_MethodGroup.GetOrAdd_1_ConcurrentDictionary_2_TKey
            GetOrAdd_1_ConcurrentDictionary_2_TValue = ConcurrentDictionary_2.GetOrAdd_MethodGroup.GetOrAdd_1_ConcurrentDictionary_2_TValue
            GetOrAdd_1_TArg = ConcurrentDictionary_2.GetOrAdd_MethodGroup.GetOrAdd_1_T1
            def __call__(self, key: GetOrAdd_1_ConcurrentDictionary_2_TKey, valueFactory: Func_3[GetOrAdd_1_ConcurrentDictionary_2_TKey, GetOrAdd_1_TArg, GetOrAdd_1_ConcurrentDictionary_2_TValue], factoryArgument: GetOrAdd_1_TArg) -> GetOrAdd_1_ConcurrentDictionary_2_TValue:...

        @typing.overload
        def __call__(self, key: GetOrAdd_MethodGroup_ConcurrentDictionary_2_TKey, valueFactory: Func_2[GetOrAdd_MethodGroup_ConcurrentDictionary_2_TKey, GetOrAdd_MethodGroup_ConcurrentDictionary_2_TValue]) -> GetOrAdd_MethodGroup_ConcurrentDictionary_2_TValue:...
        @typing.overload
        def __call__(self, key: GetOrAdd_MethodGroup_ConcurrentDictionary_2_TKey, value: GetOrAdd_MethodGroup_ConcurrentDictionary_2_TValue) -> GetOrAdd_MethodGroup_ConcurrentDictionary_2_TValue:...

    # Skipped TryRemove due to it being static, abstract and generic.

    TryRemove : TryRemove_MethodGroup[ConcurrentDictionary_2_TKey, ConcurrentDictionary_2_TValue]
    TryRemove_MethodGroup_ConcurrentDictionary_2_TKey = typing.TypeVar('TryRemove_MethodGroup_ConcurrentDictionary_2_TKey')
    TryRemove_MethodGroup_ConcurrentDictionary_2_TValue = typing.TypeVar('TryRemove_MethodGroup_ConcurrentDictionary_2_TValue')
    class TryRemove_MethodGroup(typing.Generic[TryRemove_MethodGroup_ConcurrentDictionary_2_TKey, TryRemove_MethodGroup_ConcurrentDictionary_2_TValue]):
        TryRemove_MethodGroup_ConcurrentDictionary_2_TKey = ConcurrentDictionary_2.TryRemove_MethodGroup_ConcurrentDictionary_2_TKey
        TryRemove_MethodGroup_ConcurrentDictionary_2_TValue = ConcurrentDictionary_2.TryRemove_MethodGroup_ConcurrentDictionary_2_TValue
        @typing.overload
        def __call__(self, item: KeyValuePair_2[TryRemove_MethodGroup_ConcurrentDictionary_2_TKey, TryRemove_MethodGroup_ConcurrentDictionary_2_TValue]) -> bool:...
        @typing.overload
        def __call__(self, key: TryRemove_MethodGroup_ConcurrentDictionary_2_TKey, value: clr.Reference[TryRemove_MethodGroup_ConcurrentDictionary_2_TValue]) -> bool:...



class ConcurrentQueue_GenericClasses(abc.ABCMeta):
    Generic_ConcurrentQueue_GenericClasses_ConcurrentQueue_1_T = typing.TypeVar('Generic_ConcurrentQueue_GenericClasses_ConcurrentQueue_1_T')
    def __getitem__(self, types : typing.Type[Generic_ConcurrentQueue_GenericClasses_ConcurrentQueue_1_T]) -> typing.Type[ConcurrentQueue_1[Generic_ConcurrentQueue_GenericClasses_ConcurrentQueue_1_T]]: ...

ConcurrentQueue : ConcurrentQueue_GenericClasses

ConcurrentQueue_1_T = typing.TypeVar('ConcurrentQueue_1_T')
class ConcurrentQueue_1(typing.Generic[ConcurrentQueue_1_T], IReadOnlyCollection_1[ConcurrentQueue_1_T], IProducerConsumerCollection_1[ConcurrentQueue_1_T]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, collection: IEnumerable_1[ConcurrentQueue_1_T]) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def IsEmpty(self) -> bool: ...
    def Clear(self) -> None: ...
    def CopyTo(self, array: Array_1[ConcurrentQueue_1_T], index: int) -> None: ...
    def Enqueue(self, item: ConcurrentQueue_1_T) -> None: ...
    def GetEnumerator(self) -> IEnumerator_1[ConcurrentQueue_1_T]: ...
    def ToArray(self) -> Array_1[ConcurrentQueue_1_T]: ...
    def TryDequeue(self, result: clr.Reference[ConcurrentQueue_1_T]) -> bool: ...
    def TryPeek(self, result: clr.Reference[ConcurrentQueue_1_T]) -> bool: ...


class IProducerConsumerCollection_GenericClasses(abc.ABCMeta):
    Generic_IProducerConsumerCollection_GenericClasses_IProducerConsumerCollection_1_T = typing.TypeVar('Generic_IProducerConsumerCollection_GenericClasses_IProducerConsumerCollection_1_T')
    def __getitem__(self, types : typing.Type[Generic_IProducerConsumerCollection_GenericClasses_IProducerConsumerCollection_1_T]) -> typing.Type[IProducerConsumerCollection_1[Generic_IProducerConsumerCollection_GenericClasses_IProducerConsumerCollection_1_T]]: ...

IProducerConsumerCollection : IProducerConsumerCollection_GenericClasses

IProducerConsumerCollection_1_T = typing.TypeVar('IProducerConsumerCollection_1_T')
class IProducerConsumerCollection_1(typing.Generic[IProducerConsumerCollection_1_T], ICollection, IEnumerable_1[IProducerConsumerCollection_1_T], typing.Protocol):
    @abc.abstractmethod
    def CopyTo(self, array: Array_1[IProducerConsumerCollection_1_T], index: int) -> None: ...
    @abc.abstractmethod
    def ToArray(self) -> Array_1[IProducerConsumerCollection_1_T]: ...
    @abc.abstractmethod
    def TryAdd(self, item: IProducerConsumerCollection_1_T) -> bool: ...
    @abc.abstractmethod
    def TryTake(self, item: clr.Reference[IProducerConsumerCollection_1_T]) -> bool: ...

