import typing, clr, abc
from System import Array_1, ReadOnlySpan_1, Span_1
from System.Text.Unicode import UnicodeRange
from System.Buffers import OperationStatus
from System.IO import TextWriter
from System.Collections.Generic import IEnumerable_1

class JavaScriptEncoder(TextEncoder):
    @classmethod
    @property
    def Default(cls) -> JavaScriptEncoder: ...
    @property
    def MaxOutputCharactersPerInputCharacter(self) -> int: ...
    @classmethod
    @property
    def UnsafeRelaxedJsonEscaping(cls) -> JavaScriptEncoder: ...
    # Skipped Create due to it being static, abstract and generic.

    Create : Create_MethodGroup
    class Create_MethodGroup:
        @typing.overload
        def __call__(self, allowedRanges: Array_1[UnicodeRange]) -> JavaScriptEncoder:...
        @typing.overload
        def __call__(self, settings: TextEncoderSettings) -> JavaScriptEncoder:...



class TextEncoder(abc.ABC):
    @property
    def MaxOutputCharactersPerInputCharacter(self) -> int: ...
    def EncodeUtf8(self, utf8Source: ReadOnlySpan_1[int], utf8Destination: Span_1[int], bytesConsumed: clr.Reference[int], bytesWritten: clr.Reference[int], isFinalBlock: bool = ...) -> OperationStatus: ...
    @abc.abstractmethod
    def FindFirstCharacterToEncode(self, text: clr.Reference[str], textLength: int) -> int: ...
    def FindFirstCharacterToEncodeUtf8(self, utf8Text: ReadOnlySpan_1[int]) -> int: ...
    @abc.abstractmethod
    def TryEncodeUnicodeScalar(self, unicodeScalar: int, buffer: clr.Reference[str], bufferLength: int, numberOfCharactersWritten: clr.Reference[int]) -> bool: ...
    @abc.abstractmethod
    def WillEncode(self, unicodeScalar: int) -> bool: ...
    # Skipped Encode due to it being static, abstract and generic.

    Encode : Encode_MethodGroup
    class Encode_MethodGroup:
        @typing.overload
        def __call__(self, value: str) -> str:...
        @typing.overload
        def __call__(self, output: TextWriter, value: str) -> None:...
        @typing.overload
        def __call__(self, output: TextWriter, value: Array_1[str], startIndex: int, characterCount: int) -> None:...
        @typing.overload
        def __call__(self, output: TextWriter, value: str, startIndex: int, characterCount: int) -> None:...
        @typing.overload
        def __call__(self, source: ReadOnlySpan_1[str], destination: Span_1[str], charsConsumed: clr.Reference[int], charsWritten: clr.Reference[int], isFinalBlock: bool = ...) -> OperationStatus:...



class TextEncoderSettings:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, allowedRanges: Array_1[UnicodeRange]) -> None: ...
    @typing.overload
    def __init__(self, other: TextEncoderSettings) -> None: ...
    def AllowCharacter(self, character: str) -> None: ...
    def AllowCharacters(self, characters: Array_1[str]) -> None: ...
    def AllowCodePoints(self, codePoints: IEnumerable_1[int]) -> None: ...
    def AllowRange(self, range: UnicodeRange) -> None: ...
    def AllowRanges(self, ranges: Array_1[UnicodeRange]) -> None: ...
    def Clear(self) -> None: ...
    def ForbidCharacter(self, character: str) -> None: ...
    def ForbidCharacters(self, characters: Array_1[str]) -> None: ...
    def ForbidRange(self, range: UnicodeRange) -> None: ...
    def ForbidRanges(self, ranges: Array_1[UnicodeRange]) -> None: ...
    def GetAllowedCodePoints(self) -> IEnumerable_1[int]: ...

