import typing, clr, abc
from System import Array_1, Memory_1, Span_1, IDisposable, ReadOnlyMemory_1, SequencePosition, ReadOnlySpan_1, MulticastDelegate, IAsyncResult, AsyncCallback, IEquatable_1
from System.Runtime.InteropServices import GCHandle
from System.Reflection import MethodInfo

class ArrayPool_GenericClasses(abc.ABCMeta):
    Generic_ArrayPool_GenericClasses_ArrayPool_1_T = typing.TypeVar('Generic_ArrayPool_GenericClasses_ArrayPool_1_T')
    def __getitem__(self, types : typing.Type[Generic_ArrayPool_GenericClasses_ArrayPool_1_T]) -> typing.Type[ArrayPool_1[Generic_ArrayPool_GenericClasses_ArrayPool_1_T]]: ...

ArrayPool : ArrayPool_GenericClasses

ArrayPool_1_T = typing.TypeVar('ArrayPool_1_T')
class ArrayPool_1(typing.Generic[ArrayPool_1_T], abc.ABC):
    @classmethod
    @property
    def Shared(cls) -> ArrayPool_1[ArrayPool_1_T]: ...
    @abc.abstractmethod
    def Rent(self, minimumLength: int) -> Array_1[ArrayPool_1_T]: ...
    @abc.abstractmethod
    def Return(self, array: Array_1[ArrayPool_1_T], clearArray: bool = ...) -> None: ...
    # Skipped Create due to it being static, abstract and generic.

    Create : Create_MethodGroup[ArrayPool_1_T]
    Create_MethodGroup_ArrayPool_1_T = typing.TypeVar('Create_MethodGroup_ArrayPool_1_T')
    class Create_MethodGroup(typing.Generic[Create_MethodGroup_ArrayPool_1_T]):
        Create_MethodGroup_ArrayPool_1_T = ArrayPool_1.Create_MethodGroup_ArrayPool_1_T
        @typing.overload
        def __call__(self) -> ArrayPool_1[Create_MethodGroup_ArrayPool_1_T]:...
        @typing.overload
        def __call__(self, maxArrayLength: int, maxArraysPerBucket: int) -> ArrayPool_1[Create_MethodGroup_ArrayPool_1_T]:...



class IBufferWriter_GenericClasses(abc.ABCMeta):
    Generic_IBufferWriter_GenericClasses_IBufferWriter_1_T = typing.TypeVar('Generic_IBufferWriter_GenericClasses_IBufferWriter_1_T')
    def __getitem__(self, types : typing.Type[Generic_IBufferWriter_GenericClasses_IBufferWriter_1_T]) -> typing.Type[IBufferWriter_1[Generic_IBufferWriter_GenericClasses_IBufferWriter_1_T]]: ...

IBufferWriter : IBufferWriter_GenericClasses

IBufferWriter_1_T = typing.TypeVar('IBufferWriter_1_T')
class IBufferWriter_1(typing.Generic[IBufferWriter_1_T], typing.Protocol):
    @abc.abstractmethod
    def Advance(self, count: int) -> None: ...
    @abc.abstractmethod
    def GetMemory(self, sizeHint: int = ...) -> Memory_1[IBufferWriter_1_T]: ...
    @abc.abstractmethod
    def GetSpan(self, sizeHint: int = ...) -> Span_1[IBufferWriter_1_T]: ...


class IMemoryOwner_GenericClasses(abc.ABCMeta):
    Generic_IMemoryOwner_GenericClasses_IMemoryOwner_1_T = typing.TypeVar('Generic_IMemoryOwner_GenericClasses_IMemoryOwner_1_T')
    def __getitem__(self, types : typing.Type[Generic_IMemoryOwner_GenericClasses_IMemoryOwner_1_T]) -> typing.Type[IMemoryOwner_1[Generic_IMemoryOwner_GenericClasses_IMemoryOwner_1_T]]: ...

IMemoryOwner : IMemoryOwner_GenericClasses

IMemoryOwner_1_T = typing.TypeVar('IMemoryOwner_1_T')
class IMemoryOwner_1(typing.Generic[IMemoryOwner_1_T], IDisposable, typing.Protocol):
    @property
    def Memory(self) -> Memory_1[IMemoryOwner_1_T]: ...


class IPinnable(typing.Protocol):
    @abc.abstractmethod
    def Pin(self, elementIndex: int) -> MemoryHandle: ...
    @abc.abstractmethod
    def Unpin(self) -> None: ...


class MemoryHandle(IDisposable):
    def __init__(self, pointer: clr.Reference[None], handle: GCHandle = ..., pinnable: IPinnable = ...) -> None: ...
    @property
    def Pointer(self) -> clr.Reference[None]: ...
    def Dispose(self) -> None: ...


class MemoryManager_GenericClasses(abc.ABCMeta):
    Generic_MemoryManager_GenericClasses_MemoryManager_1_T = typing.TypeVar('Generic_MemoryManager_GenericClasses_MemoryManager_1_T')
    def __getitem__(self, types : typing.Type[Generic_MemoryManager_GenericClasses_MemoryManager_1_T]) -> typing.Type[MemoryManager_1[Generic_MemoryManager_GenericClasses_MemoryManager_1_T]]: ...

MemoryManager : MemoryManager_GenericClasses

MemoryManager_1_T = typing.TypeVar('MemoryManager_1_T')
class MemoryManager_1(typing.Generic[MemoryManager_1_T], IMemoryOwner_1[MemoryManager_1_T], IPinnable, abc.ABC):
    @property
    def Memory(self) -> Memory_1[MemoryManager_1_T]: ...
    @abc.abstractmethod
    def GetSpan(self) -> Span_1[MemoryManager_1_T]: ...
    @abc.abstractmethod
    def Pin(self, elementIndex: int = ...) -> MemoryHandle: ...
    @abc.abstractmethod
    def Unpin(self) -> None: ...


class OperationStatus(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Done : OperationStatus # 0
    DestinationTooSmall : OperationStatus # 1
    NeedMoreData : OperationStatus # 2
    InvalidData : OperationStatus # 3


class ReadOnlySequence_GenericClasses(abc.ABCMeta):
    Generic_ReadOnlySequence_GenericClasses_ReadOnlySequence_1_T = typing.TypeVar('Generic_ReadOnlySequence_GenericClasses_ReadOnlySequence_1_T')
    def __getitem__(self, types : typing.Type[Generic_ReadOnlySequence_GenericClasses_ReadOnlySequence_1_T]) -> typing.Type[ReadOnlySequence_1[Generic_ReadOnlySequence_GenericClasses_ReadOnlySequence_1_T]]: ...

ReadOnlySequence : ReadOnlySequence_GenericClasses

ReadOnlySequence_1_T = typing.TypeVar('ReadOnlySequence_1_T')
class ReadOnlySequence_1(typing.Generic[ReadOnlySequence_1_T]):
    @typing.overload
    def __init__(self, array: Array_1[ReadOnlySequence_1_T]) -> None: ...
    @typing.overload
    def __init__(self, array: Array_1[ReadOnlySequence_1_T], start: int, length: int) -> None: ...
    @typing.overload
    def __init__(self, memory: ReadOnlyMemory_1[ReadOnlySequence_1_T]) -> None: ...
    @typing.overload
    def __init__(self, startSegment: ReadOnlySequenceSegment_1[ReadOnlySequence_1_T], startIndex: int, endSegment: ReadOnlySequenceSegment_1[ReadOnlySequence_1_T], endIndex: int) -> None: ...
    Empty : ReadOnlySequence_1[ReadOnlySequence_1_T]
    @property
    def End(self) -> SequencePosition: ...
    @property
    def First(self) -> ReadOnlyMemory_1[ReadOnlySequence_1_T]: ...
    @property
    def FirstSpan(self) -> ReadOnlySpan_1[ReadOnlySequence_1_T]: ...
    @property
    def IsEmpty(self) -> bool: ...
    @property
    def IsSingleSegment(self) -> bool: ...
    @property
    def Length(self) -> int: ...
    @property
    def Start(self) -> SequencePosition: ...
    def GetEnumerator(self) -> ReadOnlySequence_1.Enumerator_1[ReadOnlySequence_1_T]: ...
    def GetOffset(self, position: SequencePosition) -> int: ...
    def ToString(self) -> str: ...
    def TryGet(self, position: clr.Reference[SequencePosition], memory: clr.Reference[ReadOnlyMemory_1[ReadOnlySequence_1_T]], advance: bool = ...) -> bool: ...
    # Skipped GetPosition due to it being static, abstract and generic.

    GetPosition : GetPosition_MethodGroup[ReadOnlySequence_1_T]
    GetPosition_MethodGroup_ReadOnlySequence_1_T = typing.TypeVar('GetPosition_MethodGroup_ReadOnlySequence_1_T')
    class GetPosition_MethodGroup(typing.Generic[GetPosition_MethodGroup_ReadOnlySequence_1_T]):
        GetPosition_MethodGroup_ReadOnlySequence_1_T = ReadOnlySequence_1.GetPosition_MethodGroup_ReadOnlySequence_1_T
        @typing.overload
        def __call__(self, offset: int) -> SequencePosition:...
        @typing.overload
        def __call__(self, offset: int, origin: SequencePosition) -> SequencePosition:...

    # Skipped Slice due to it being static, abstract and generic.

    Slice : Slice_MethodGroup[ReadOnlySequence_1_T]
    Slice_MethodGroup_ReadOnlySequence_1_T = typing.TypeVar('Slice_MethodGroup_ReadOnlySequence_1_T')
    class Slice_MethodGroup(typing.Generic[Slice_MethodGroup_ReadOnlySequence_1_T]):
        Slice_MethodGroup_ReadOnlySequence_1_T = ReadOnlySequence_1.Slice_MethodGroup_ReadOnlySequence_1_T
        @typing.overload
        def __call__(self, start: int) -> ReadOnlySequence_1[Slice_MethodGroup_ReadOnlySequence_1_T]:...
        @typing.overload
        def __call__(self, start: SequencePosition) -> ReadOnlySequence_1[Slice_MethodGroup_ReadOnlySequence_1_T]:...
        @typing.overload
        def __call__(self, start: int, length: int) -> ReadOnlySequence_1[Slice_MethodGroup_ReadOnlySequence_1_T]:...
        # Method Slice(start : Int32, length : Int32) was skipped since it collides with above method
        @typing.overload
        def __call__(self, start: int, end: SequencePosition) -> ReadOnlySequence_1[Slice_MethodGroup_ReadOnlySequence_1_T]:...
        # Method Slice(start : Int32, end : SequencePosition) was skipped since it collides with above method
        @typing.overload
        def __call__(self, start: SequencePosition, length: int) -> ReadOnlySequence_1[Slice_MethodGroup_ReadOnlySequence_1_T]:...
        # Method Slice(start : SequencePosition, length : Int32) was skipped since it collides with above method
        @typing.overload
        def __call__(self, start: SequencePosition, end: SequencePosition) -> ReadOnlySequence_1[Slice_MethodGroup_ReadOnlySequence_1_T]:...


    Enumerator_GenericClasses_ReadOnlySequence_1_T = typing.TypeVar('Enumerator_GenericClasses_ReadOnlySequence_1_T')
    class Enumerator_GenericClasses(typing.Generic[Enumerator_GenericClasses_ReadOnlySequence_1_T], abc.ABCMeta):
        Enumerator_GenericClasses_ReadOnlySequence_1_T = ReadOnlySequence_1.Enumerator_GenericClasses_ReadOnlySequence_1_T
        def __call__(self) -> ReadOnlySequence_1.Enumerator_1[Enumerator_GenericClasses_ReadOnlySequence_1_T]: ...

    Enumerator : Enumerator_GenericClasses[ReadOnlySequence_1_T]

    Enumerator_1_T = typing.TypeVar('Enumerator_1_T')
    class Enumerator_1(typing.Generic[Enumerator_1_T]):
        Enumerator_1_T = ReadOnlySequence_1.Enumerator_1_T
        def __init__(self, sequence: clr.Reference[ReadOnlySequence_1[Enumerator_1_T]]) -> None: ...
        @property
        def Current(self) -> ReadOnlyMemory_1[Enumerator_1_T]: ...
        def MoveNext(self) -> bool: ...



class ReadOnlySequenceSegment_GenericClasses(abc.ABCMeta):
    Generic_ReadOnlySequenceSegment_GenericClasses_ReadOnlySequenceSegment_1_T = typing.TypeVar('Generic_ReadOnlySequenceSegment_GenericClasses_ReadOnlySequenceSegment_1_T')
    def __getitem__(self, types : typing.Type[Generic_ReadOnlySequenceSegment_GenericClasses_ReadOnlySequenceSegment_1_T]) -> typing.Type[ReadOnlySequenceSegment_1[Generic_ReadOnlySequenceSegment_GenericClasses_ReadOnlySequenceSegment_1_T]]: ...

ReadOnlySequenceSegment : ReadOnlySequenceSegment_GenericClasses

ReadOnlySequenceSegment_1_T = typing.TypeVar('ReadOnlySequenceSegment_1_T')
class ReadOnlySequenceSegment_1(typing.Generic[ReadOnlySequenceSegment_1_T], abc.ABC):
    @property
    def Memory(self) -> ReadOnlyMemory_1[ReadOnlySequenceSegment_1_T]: ...
    @Memory.setter
    def Memory(self, value: ReadOnlyMemory_1[ReadOnlySequenceSegment_1_T]) -> ReadOnlyMemory_1[ReadOnlySequenceSegment_1_T]: ...
    @property
    def Next(self) -> ReadOnlySequenceSegment_1[ReadOnlySequenceSegment_1_T]: ...
    @Next.setter
    def Next(self, value: ReadOnlySequenceSegment_1[ReadOnlySequenceSegment_1_T]) -> ReadOnlySequenceSegment_1[ReadOnlySequenceSegment_1_T]: ...
    @property
    def RunningIndex(self) -> int: ...
    @RunningIndex.setter
    def RunningIndex(self, value: int) -> int: ...


class ReadOnlySpanAction_GenericClasses(abc.ABCMeta):
    Generic_ReadOnlySpanAction_GenericClasses_ReadOnlySpanAction_2_T = typing.TypeVar('Generic_ReadOnlySpanAction_GenericClasses_ReadOnlySpanAction_2_T')
    Generic_ReadOnlySpanAction_GenericClasses_ReadOnlySpanAction_2_TArg = typing.TypeVar('Generic_ReadOnlySpanAction_GenericClasses_ReadOnlySpanAction_2_TArg')
    def __getitem__(self, types : typing.Tuple[typing.Type[Generic_ReadOnlySpanAction_GenericClasses_ReadOnlySpanAction_2_T], typing.Type[Generic_ReadOnlySpanAction_GenericClasses_ReadOnlySpanAction_2_TArg]]) -> typing.Type[ReadOnlySpanAction_2[Generic_ReadOnlySpanAction_GenericClasses_ReadOnlySpanAction_2_T, Generic_ReadOnlySpanAction_GenericClasses_ReadOnlySpanAction_2_TArg]]: ...

ReadOnlySpanAction : ReadOnlySpanAction_GenericClasses

ReadOnlySpanAction_2_T = typing.TypeVar('ReadOnlySpanAction_2_T')
ReadOnlySpanAction_2_TArg = typing.TypeVar('ReadOnlySpanAction_2_TArg', contravariant=True)
class ReadOnlySpanAction_2(typing.Generic[ReadOnlySpanAction_2_T, ReadOnlySpanAction_2_TArg], MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, span: ReadOnlySpan_1[ReadOnlySpanAction_2_T], arg: ReadOnlySpanAction_2_TArg, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, span: ReadOnlySpan_1[ReadOnlySpanAction_2_T], arg: ReadOnlySpanAction_2_TArg) -> None: ...


class SpanAction_GenericClasses(abc.ABCMeta):
    Generic_SpanAction_GenericClasses_SpanAction_2_T = typing.TypeVar('Generic_SpanAction_GenericClasses_SpanAction_2_T')
    Generic_SpanAction_GenericClasses_SpanAction_2_TArg = typing.TypeVar('Generic_SpanAction_GenericClasses_SpanAction_2_TArg')
    def __getitem__(self, types : typing.Tuple[typing.Type[Generic_SpanAction_GenericClasses_SpanAction_2_T], typing.Type[Generic_SpanAction_GenericClasses_SpanAction_2_TArg]]) -> typing.Type[SpanAction_2[Generic_SpanAction_GenericClasses_SpanAction_2_T, Generic_SpanAction_GenericClasses_SpanAction_2_TArg]]: ...

SpanAction : SpanAction_GenericClasses

SpanAction_2_T = typing.TypeVar('SpanAction_2_T')
SpanAction_2_TArg = typing.TypeVar('SpanAction_2_TArg', contravariant=True)
class SpanAction_2(typing.Generic[SpanAction_2_T, SpanAction_2_TArg], MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, span: Span_1[SpanAction_2_T], arg: SpanAction_2_TArg, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, span: Span_1[SpanAction_2_T], arg: SpanAction_2_TArg) -> None: ...


class StandardFormat(IEquatable_1[StandardFormat]):
    def __init__(self, symbol: str, precision: int = ...) -> None: ...
    MaxPrecision : int
    NoPrecision : int
    @property
    def HasPrecision(self) -> bool: ...
    @property
    def IsDefault(self) -> bool: ...
    @property
    def Precision(self) -> int: ...
    @property
    def Symbol(self) -> str: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: StandardFormat, right: StandardFormat) -> bool: ...
    # Operator not supported op_Implicit(symbol: Char)
    def __ne__(self, left: StandardFormat, right: StandardFormat) -> bool: ...
    def ToString(self) -> str: ...
    @staticmethod
    def TryParse(format: ReadOnlySpan_1[str], result: clr.Reference[StandardFormat]) -> bool: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: StandardFormat) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...

    # Skipped Parse due to it being static, abstract and generic.

    Parse : Parse_MethodGroup
    class Parse_MethodGroup:
        @typing.overload
        def __call__(self, format: ReadOnlySpan_1[str]) -> StandardFormat:...
        @typing.overload
        def __call__(self, format: str) -> StandardFormat:...


