import typing, clr, abc
from System import IEquatable_1, StringComparer, Array_1, Delegate, Action_2, Func_3, Func_4, Func_5, Guid, Version, Exception
from System.Collections.Generic import IDictionary_2, IList_1, ICollection_1
from System.Reflection import MethodInfo, MethodBase, Assembly
from System.Linq.Expressions import ExpressionType, Expression
from System.Runtime.CompilerServices import CallSite_1, CallSite, CallSiteBinder
from Microsoft.Scripting import PlatformAdaptationLayer, LanguageOptions, ScriptCode, SourceUnit, CompilerOptions, ErrorSink, SourceCodeKind, SourceCodeReader, TextContentProvider, StreamContentProvider
from System.Text import Encoding
from System.Dynamic import BinaryOperationBinder, InvokeMemberBinder, CallInfo, ConvertBinder, CreateInstanceBinder, DeleteMemberBinder, GetMemberBinder, InvokeBinder, SetMemberBinder, UnaryOperationBinder, IDynamicMetaObjectProvider
from System.CodeDom import CodeObject
from System.IO import Stream, TextWriter, TextReader
from Microsoft.Scripting.Utils import ConsoleStreamType

class ContextId(IEquatable_1[ContextId]):
    Empty : ContextId
    @property
    def Id(self) -> int: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def LookupContext(identifier: typing.Any) -> ContextId: ...
    def __eq__(self, self: ContextId, other: ContextId) -> bool: ...
    def __ne__(self, self: ContextId, other: ContextId) -> bool: ...
    @staticmethod
    def RegisterContext(identifier: typing.Any) -> ContextId: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: ContextId) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class DlrConfiguration:
    def __init__(self, debugMode: bool, privateBinding: bool, options: IDictionary_2[str, typing.Any]) -> None: ...
    FileExtensionComparer : StringComparer
    LanguageNameComparer : StringComparer
    OptionNameComparer : StringComparer
    @property
    def DebugMode(self) -> bool: ...
    @property
    def PrivateBinding(self) -> bool: ...
    def AddLanguage(self, languageTypeName: str, displayName: str, names: IList_1[str], fileExtensions: IList_1[str], options: IDictionary_2[str, typing.Any]) -> None: ...
    # Skipped GetFileExtensions due to it being static, abstract and generic.

    GetFileExtensions : GetFileExtensions_MethodGroup
    class GetFileExtensions_MethodGroup:
        @typing.overload
        def __call__(self) -> Array_1[str]:...
        @typing.overload
        def __call__(self, context: LanguageContext) -> Array_1[str]:...

    # Skipped GetLanguageNames due to it being static, abstract and generic.

    GetLanguageNames : GetLanguageNames_MethodGroup
    class GetLanguageNames_MethodGroup:
        @typing.overload
        def __call__(self) -> Array_1[str]:...
        @typing.overload
        def __call__(self, context: LanguageContext) -> Array_1[str]:...



class DynamicDelegateCreator:
    def __init__(self, languageContext: LanguageContext) -> None: ...
    def GetDelegate(self, callableObject: typing.Any, delegateType: typing.Type[typing.Any]) -> Delegate: ...
    def GetOrCreateDelegateForDynamicObject(self, dynamicObject: typing.Any, delegateType: typing.Type[typing.Any], invoke: MethodInfo) -> Delegate: ...


class DynamicOperations:
    def __init__(self, lc: LanguageContext) -> None: ...
    def CreateInstance(self, obj: typing.Any, parameters: Array_1[typing.Any]) -> typing.Any: ...
    def Format(self, obj: typing.Any) -> str: ...
    def GetCallSignatures(self, o: typing.Any) -> IList_1[str]: ...
    def GetDocumentation(self, o: typing.Any) -> str: ...
    def GetMemberNames(self, obj: typing.Any) -> IList_1[str]: ...
    def Invoke(self, obj: typing.Any, parameters: Array_1[typing.Any]) -> typing.Any: ...
    def IsCallable(self, o: typing.Any) -> bool: ...
    # Skipped ContainsMember due to it being static, abstract and generic.

    ContainsMember : ContainsMember_MethodGroup
    class ContainsMember_MethodGroup:
        @typing.overload
        def __call__(self, obj: typing.Any, name: str) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any, name: str, ignoreCase: bool) -> bool:...

    # Skipped ConvertTo due to it being static, abstract and generic.

    ConvertTo : ConvertTo_MethodGroup
    class ConvertTo_MethodGroup:
        def __getitem__(self, t:typing.Type[ConvertTo_1_T1]) -> ConvertTo_1[ConvertTo_1_T1]: ...

        ConvertTo_1_T1 = typing.TypeVar('ConvertTo_1_T1')
        class ConvertTo_1(typing.Generic[ConvertTo_1_T1]):
            ConvertTo_1_T = DynamicOperations.ConvertTo_MethodGroup.ConvertTo_1_T1
            def __call__(self, obj: typing.Any) -> ConvertTo_1_T:...

        def __call__(self, obj: typing.Any, type: typing.Type[typing.Any]) -> typing.Any:...

    # Skipped DoOperation due to it being static, abstract and generic.

    DoOperation : DoOperation_MethodGroup
    class DoOperation_MethodGroup:
        @typing.overload
        def __getitem__(self, t:typing.Tuple[typing.Type[DoOperation_2_T1], typing.Type[DoOperation_2_T2]]) -> DoOperation_2[DoOperation_2_T1, DoOperation_2_T2]: ...

        DoOperation_2_T1 = typing.TypeVar('DoOperation_2_T1')
        DoOperation_2_T2 = typing.TypeVar('DoOperation_2_T2')
        class DoOperation_2(typing.Generic[DoOperation_2_T1, DoOperation_2_T2]):
            DoOperation_2_TTarget = DynamicOperations.DoOperation_MethodGroup.DoOperation_2_T1
            DoOperation_2_TResult = DynamicOperations.DoOperation_MethodGroup.DoOperation_2_T2
            def __call__(self, operation: ExpressionType, target: DoOperation_2_TTarget) -> DoOperation_2_TResult:...

        @typing.overload
        def __getitem__(self, t:typing.Tuple[typing.Type[DoOperation_3_T1], typing.Type[DoOperation_3_T2], typing.Type[DoOperation_3_T3]]) -> DoOperation_3[DoOperation_3_T1, DoOperation_3_T2, DoOperation_3_T3]: ...

        DoOperation_3_T1 = typing.TypeVar('DoOperation_3_T1')
        DoOperation_3_T2 = typing.TypeVar('DoOperation_3_T2')
        DoOperation_3_T3 = typing.TypeVar('DoOperation_3_T3')
        class DoOperation_3(typing.Generic[DoOperation_3_T1, DoOperation_3_T2, DoOperation_3_T3]):
            DoOperation_3_TTarget = DynamicOperations.DoOperation_MethodGroup.DoOperation_3_T1
            DoOperation_3_TOther = DynamicOperations.DoOperation_MethodGroup.DoOperation_3_T2
            DoOperation_3_TResult = DynamicOperations.DoOperation_MethodGroup.DoOperation_3_T3
            def __call__(self, operation: ExpressionType, target: DoOperation_3_TTarget, other: DoOperation_3_TOther) -> DoOperation_3_TResult:...


    # Skipped ExplicitConvertTo due to it being static, abstract and generic.

    ExplicitConvertTo : ExplicitConvertTo_MethodGroup
    class ExplicitConvertTo_MethodGroup:
        def __getitem__(self, t:typing.Type[ExplicitConvertTo_1_T1]) -> ExplicitConvertTo_1[ExplicitConvertTo_1_T1]: ...

        ExplicitConvertTo_1_T1 = typing.TypeVar('ExplicitConvertTo_1_T1')
        class ExplicitConvertTo_1(typing.Generic[ExplicitConvertTo_1_T1]):
            ExplicitConvertTo_1_T = DynamicOperations.ExplicitConvertTo_MethodGroup.ExplicitConvertTo_1_T1
            def __call__(self, obj: typing.Any) -> ExplicitConvertTo_1_T:...

        def __call__(self, obj: typing.Any, type: typing.Type[typing.Any]) -> typing.Any:...

    # Skipped GetMember due to it being static, abstract and generic.

    GetMember : GetMember_MethodGroup
    class GetMember_MethodGroup:
        def __getitem__(self, t:typing.Type[GetMember_1_T1]) -> GetMember_1[GetMember_1_T1]: ...

        GetMember_1_T1 = typing.TypeVar('GetMember_1_T1')
        class GetMember_1(typing.Generic[GetMember_1_T1]):
            GetMember_1_T = DynamicOperations.GetMember_MethodGroup.GetMember_1_T1
            @typing.overload
            def __call__(self, obj: typing.Any, name: str) -> GetMember_1_T:...
            @typing.overload
            def __call__(self, obj: typing.Any, name: str, ignoreCase: bool) -> GetMember_1_T:...

        @typing.overload
        def __call__(self, obj: typing.Any, name: str) -> typing.Any:...
        @typing.overload
        def __call__(self, obj: typing.Any, name: str, ignoreCase: bool) -> typing.Any:...

    # Skipped GetOrCreateActionSite due to it being static, abstract and generic.

    GetOrCreateActionSite : GetOrCreateActionSite_MethodGroup
    class GetOrCreateActionSite_MethodGroup:
        def __getitem__(self, t:typing.Type[GetOrCreateActionSite_1_T1]) -> GetOrCreateActionSite_1[GetOrCreateActionSite_1_T1]: ...

        GetOrCreateActionSite_1_T1 = typing.TypeVar('GetOrCreateActionSite_1_T1')
        class GetOrCreateActionSite_1(typing.Generic[GetOrCreateActionSite_1_T1]):
            GetOrCreateActionSite_1_T1 = DynamicOperations.GetOrCreateActionSite_MethodGroup.GetOrCreateActionSite_1_T1
            def __call__(self, siteBinder: CallSiteBinder) -> CallSite_1[Action_2[CallSite, GetOrCreateActionSite_1_T1]]:...


    # Skipped GetOrCreateSite due to it being static, abstract and generic.

    GetOrCreateSite : GetOrCreateSite_MethodGroup
    class GetOrCreateSite_MethodGroup:
        @typing.overload
        def __getitem__(self, t:typing.Tuple[typing.Type[GetOrCreateSite_2_T1], typing.Type[GetOrCreateSite_2_T2]]) -> GetOrCreateSite_2[GetOrCreateSite_2_T1, GetOrCreateSite_2_T2]: ...

        GetOrCreateSite_2_T1 = typing.TypeVar('GetOrCreateSite_2_T1')
        GetOrCreateSite_2_T2 = typing.TypeVar('GetOrCreateSite_2_T2')
        class GetOrCreateSite_2(typing.Generic[GetOrCreateSite_2_T1, GetOrCreateSite_2_T2]):
            GetOrCreateSite_2_T1 = DynamicOperations.GetOrCreateSite_MethodGroup.GetOrCreateSite_2_T1
            GetOrCreateSite_2_TResult = DynamicOperations.GetOrCreateSite_MethodGroup.GetOrCreateSite_2_T2
            def __call__(self, siteBinder: CallSiteBinder) -> CallSite_1[Func_3[CallSite, GetOrCreateSite_2_T1, GetOrCreateSite_2_TResult]]:...

        @typing.overload
        def __getitem__(self, t:typing.Tuple[typing.Type[GetOrCreateSite_3_T1], typing.Type[GetOrCreateSite_3_T2], typing.Type[GetOrCreateSite_3_T3]]) -> GetOrCreateSite_3[GetOrCreateSite_3_T1, GetOrCreateSite_3_T2, GetOrCreateSite_3_T3]: ...

        GetOrCreateSite_3_T1 = typing.TypeVar('GetOrCreateSite_3_T1')
        GetOrCreateSite_3_T2 = typing.TypeVar('GetOrCreateSite_3_T2')
        GetOrCreateSite_3_T3 = typing.TypeVar('GetOrCreateSite_3_T3')
        class GetOrCreateSite_3(typing.Generic[GetOrCreateSite_3_T1, GetOrCreateSite_3_T2, GetOrCreateSite_3_T3]):
            GetOrCreateSite_3_T1 = DynamicOperations.GetOrCreateSite_MethodGroup.GetOrCreateSite_3_T1
            GetOrCreateSite_3_T2 = DynamicOperations.GetOrCreateSite_MethodGroup.GetOrCreateSite_3_T2
            GetOrCreateSite_3_TResult = DynamicOperations.GetOrCreateSite_MethodGroup.GetOrCreateSite_3_T3
            def __call__(self, siteBinder: CallSiteBinder) -> CallSite_1[Func_4[CallSite, GetOrCreateSite_3_T1, GetOrCreateSite_3_T2, GetOrCreateSite_3_TResult]]:...

        @typing.overload
        def __getitem__(self, t:typing.Tuple[typing.Type[GetOrCreateSite_4_T1], typing.Type[GetOrCreateSite_4_T2], typing.Type[GetOrCreateSite_4_T3], typing.Type[GetOrCreateSite_4_T4]]) -> GetOrCreateSite_4[GetOrCreateSite_4_T1, GetOrCreateSite_4_T2, GetOrCreateSite_4_T3, GetOrCreateSite_4_T4]: ...

        GetOrCreateSite_4_T1 = typing.TypeVar('GetOrCreateSite_4_T1')
        GetOrCreateSite_4_T2 = typing.TypeVar('GetOrCreateSite_4_T2')
        GetOrCreateSite_4_T3 = typing.TypeVar('GetOrCreateSite_4_T3')
        GetOrCreateSite_4_T4 = typing.TypeVar('GetOrCreateSite_4_T4')
        class GetOrCreateSite_4(typing.Generic[GetOrCreateSite_4_T1, GetOrCreateSite_4_T2, GetOrCreateSite_4_T3, GetOrCreateSite_4_T4]):
            GetOrCreateSite_4_T1 = DynamicOperations.GetOrCreateSite_MethodGroup.GetOrCreateSite_4_T1
            GetOrCreateSite_4_T2 = DynamicOperations.GetOrCreateSite_MethodGroup.GetOrCreateSite_4_T2
            GetOrCreateSite_4_T3 = DynamicOperations.GetOrCreateSite_MethodGroup.GetOrCreateSite_4_T3
            GetOrCreateSite_4_TResult = DynamicOperations.GetOrCreateSite_MethodGroup.GetOrCreateSite_4_T4
            def __call__(self, siteBinder: CallSiteBinder) -> CallSite_1[Func_5[CallSite, GetOrCreateSite_4_T1, GetOrCreateSite_4_T2, GetOrCreateSite_4_T3, GetOrCreateSite_4_TResult]]:...

        @typing.overload
        def __getitem__(self, t:typing.Type[GetOrCreateSite_1_T1]) -> GetOrCreateSite_1[GetOrCreateSite_1_T1]: ...

        GetOrCreateSite_1_T1 = typing.TypeVar('GetOrCreateSite_1_T1')
        class GetOrCreateSite_1(typing.Generic[GetOrCreateSite_1_T1]):
            GetOrCreateSite_1_TSiteFunc = DynamicOperations.GetOrCreateSite_MethodGroup.GetOrCreateSite_1_T1
            def __call__(self, siteBinder: CallSiteBinder) -> CallSite_1[GetOrCreateSite_1_TSiteFunc]:...


    # Skipped ImplicitConvertTo due to it being static, abstract and generic.

    ImplicitConvertTo : ImplicitConvertTo_MethodGroup
    class ImplicitConvertTo_MethodGroup:
        def __getitem__(self, t:typing.Type[ImplicitConvertTo_1_T1]) -> ImplicitConvertTo_1[ImplicitConvertTo_1_T1]: ...

        ImplicitConvertTo_1_T1 = typing.TypeVar('ImplicitConvertTo_1_T1')
        class ImplicitConvertTo_1(typing.Generic[ImplicitConvertTo_1_T1]):
            ImplicitConvertTo_1_T = DynamicOperations.ImplicitConvertTo_MethodGroup.ImplicitConvertTo_1_T1
            def __call__(self, obj: typing.Any) -> ImplicitConvertTo_1_T:...

        def __call__(self, obj: typing.Any, type: typing.Type[typing.Any]) -> typing.Any:...

    # Skipped InvokeMember due to it being static, abstract and generic.

    InvokeMember : InvokeMember_MethodGroup
    class InvokeMember_MethodGroup:
        @typing.overload
        def __call__(self, obj: typing.Any, memberName: str, parameters: Array_1[typing.Any]) -> typing.Any:...
        @typing.overload
        def __call__(self, obj: typing.Any, memberName: str, ignoreCase: bool, parameters: Array_1[typing.Any]) -> typing.Any:...

    # Skipped RemoveMember due to it being static, abstract and generic.

    RemoveMember : RemoveMember_MethodGroup
    class RemoveMember_MethodGroup:
        @typing.overload
        def __call__(self, obj: typing.Any, name: str) -> None:...
        @typing.overload
        def __call__(self, obj: typing.Any, name: str, ignoreCase: bool) -> None:...

    # Skipped SetMember due to it being static, abstract and generic.

    SetMember : SetMember_MethodGroup
    class SetMember_MethodGroup:
        def __getitem__(self, t:typing.Type[SetMember_1_T1]) -> SetMember_1[SetMember_1_T1]: ...

        SetMember_1_T1 = typing.TypeVar('SetMember_1_T1')
        class SetMember_1(typing.Generic[SetMember_1_T1]):
            SetMember_1_T = DynamicOperations.SetMember_MethodGroup.SetMember_1_T1
            @typing.overload
            def __call__(self, obj: typing.Any, name: str, value: SetMember_1_T) -> None:...
            @typing.overload
            def __call__(self, obj: typing.Any, name: str, value: SetMember_1_T, ignoreCase: bool) -> None:...

        @typing.overload
        def __call__(self, obj: typing.Any, name: str, value: typing.Any) -> None:...
        @typing.overload
        def __call__(self, obj: typing.Any, name: str, value: typing.Any, ignoreCase: bool) -> None:...

    # Skipped TryConvertTo due to it being static, abstract and generic.

    TryConvertTo : TryConvertTo_MethodGroup
    class TryConvertTo_MethodGroup:
        def __getitem__(self, t:typing.Type[TryConvertTo_1_T1]) -> TryConvertTo_1[TryConvertTo_1_T1]: ...

        TryConvertTo_1_T1 = typing.TypeVar('TryConvertTo_1_T1')
        class TryConvertTo_1(typing.Generic[TryConvertTo_1_T1]):
            TryConvertTo_1_T = DynamicOperations.TryConvertTo_MethodGroup.TryConvertTo_1_T1
            def __call__(self, obj: typing.Any, result: clr.Reference[TryConvertTo_1_T]) -> bool:...

        def __call__(self, obj: typing.Any, type: typing.Type[typing.Any], result: clr.Reference[typing.Any]) -> bool:...

    # Skipped TryExplicitConvertTo due to it being static, abstract and generic.

    TryExplicitConvertTo : TryExplicitConvertTo_MethodGroup
    class TryExplicitConvertTo_MethodGroup:
        def __getitem__(self, t:typing.Type[TryExplicitConvertTo_1_T1]) -> TryExplicitConvertTo_1[TryExplicitConvertTo_1_T1]: ...

        TryExplicitConvertTo_1_T1 = typing.TypeVar('TryExplicitConvertTo_1_T1')
        class TryExplicitConvertTo_1(typing.Generic[TryExplicitConvertTo_1_T1]):
            TryExplicitConvertTo_1_T = DynamicOperations.TryExplicitConvertTo_MethodGroup.TryExplicitConvertTo_1_T1
            def __call__(self, obj: typing.Any, result: clr.Reference[TryExplicitConvertTo_1_T]) -> bool:...

        def __call__(self, obj: typing.Any, type: typing.Type[typing.Any], result: clr.Reference[typing.Any]) -> bool:...

    # Skipped TryGetMember due to it being static, abstract and generic.

    TryGetMember : TryGetMember_MethodGroup
    class TryGetMember_MethodGroup:
        @typing.overload
        def __call__(self, obj: typing.Any, name: str, value: clr.Reference[typing.Any]) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any, name: str, ignoreCase: bool, value: clr.Reference[typing.Any]) -> bool:...

    # Skipped TryImplicitConvertTo due to it being static, abstract and generic.

    TryImplicitConvertTo : TryImplicitConvertTo_MethodGroup
    class TryImplicitConvertTo_MethodGroup:
        def __getitem__(self, t:typing.Type[TryImplicitConvertTo_1_T1]) -> TryImplicitConvertTo_1[TryImplicitConvertTo_1_T1]: ...

        TryImplicitConvertTo_1_T1 = typing.TypeVar('TryImplicitConvertTo_1_T1')
        class TryImplicitConvertTo_1(typing.Generic[TryImplicitConvertTo_1_T1]):
            TryImplicitConvertTo_1_T = DynamicOperations.TryImplicitConvertTo_MethodGroup.TryImplicitConvertTo_1_T1
            def __call__(self, obj: typing.Any, result: clr.Reference[TryImplicitConvertTo_1_T]) -> bool:...

        def __call__(self, obj: typing.Any, type: typing.Type[typing.Any], result: clr.Reference[typing.Any]) -> bool:...



class DynamicRuntimeHostingProvider(abc.ABC):
    @property
    def PlatformAdaptationLayer(self) -> PlatformAdaptationLayer: ...


class DynamicStackFrame:
    def __init__(self, method: MethodBase, funcName: str, filename: str, line: int) -> None: ...
    def GetFileLineNumber(self) -> int: ...
    def GetFileName(self) -> str: ...
    def GetMethod(self) -> MethodBase: ...
    def GetMethodName(self) -> str: ...
    def ToString(self) -> str: ...


class IExpressionSerializable(typing.Protocol):
    @abc.abstractmethod
    def CreateExpression(self) -> Expression: ...


class IMembersList(typing.Protocol):
    @abc.abstractmethod
    def GetMemberNames(self) -> IList_1[str]: ...


class ISlice(typing.Protocol):
    @property
    def Start(self) -> typing.Any: ...
    @property
    def Step(self) -> typing.Any: ...
    @property
    def Stop(self) -> typing.Any: ...


class LanguageContext(abc.ABC):
    @property
    def CanCreateSourceCode(self) -> bool: ...
    @property
    def ContextId(self) -> ContextId: ...
    @property
    def DefaultEncoding(self) -> Encoding: ...
    @property
    def DomainManager(self) -> ScriptDomainManager: ...
    @property
    def LanguageGuid(self) -> Guid: ...
    @property
    def LanguageVersion(self) -> Version: ...
    @property
    def Operations(self) -> DynamicOperations: ...
    @property
    def Options(self) -> LanguageOptions: ...
    @property
    def VendorGuid(self) -> Guid: ...
    @abc.abstractmethod
    def CompileSourceCode(self, sourceUnit: SourceUnit, options: CompilerOptions, errorSink: ErrorSink) -> ScriptCode: ...
    def CreateBinaryOperationBinder(self, operation: ExpressionType) -> BinaryOperationBinder: ...
    def CreateCallBinder(self, name: str, ignoreCase: bool, callInfo: CallInfo) -> InvokeMemberBinder: ...
    def CreateConvertBinder(self, toType: typing.Type[typing.Any], explicitCast: typing.Optional[bool]) -> ConvertBinder: ...
    def CreateCreateBinder(self, callInfo: CallInfo) -> CreateInstanceBinder: ...
    def CreateDeleteMemberBinder(self, name: str, ignoreCase: bool) -> DeleteMemberBinder: ...
    def CreateGetMemberBinder(self, name: str, ignoreCase: bool) -> GetMemberBinder: ...
    def CreateInvokeBinder(self, callInfo: CallInfo) -> InvokeBinder: ...
    def CreateScopeExtension(self, scope: Scope) -> ScopeExtension: ...
    def CreateSetMemberBinder(self, name: str, ignoreCase: bool) -> SetMemberBinder: ...
    def CreateUnaryOperationBinder(self, operation: ExpressionType) -> UnaryOperationBinder: ...
    def EnsureScopeExtension(self, scope: Scope) -> ScopeExtension: ...
    def ExecuteProgram(self, program: SourceUnit) -> int: ...
    def FormatException(self, exception: Exception) -> str: ...
    def FormatObject(self, operations: DynamicOperations, obj: typing.Any) -> str: ...
    def GenerateSourceCode(self, codeDom: CodeObject, path: str, kind: SourceCodeKind) -> SourceUnit: ...
    def GetCallSignatures(self, obj: typing.Any) -> IList_1[str]: ...
    def GetCompilerErrorSink(self) -> ErrorSink: ...
    def GetDocumentation(self, obj: typing.Any) -> str: ...
    def GetExceptionMessage(self, exception: Exception, message: clr.Reference[str], errorTypeName: clr.Reference[str]) -> None: ...
    def GetMemberNames(self, obj: typing.Any) -> IList_1[str]: ...
    def GetScope(self, path: str) -> Scope: ...
    def GetSearchPaths(self) -> ICollection_1[str]: ...
    def GetSourceReader(self, stream: Stream, defaultEncoding: Encoding, path: str) -> SourceCodeReader: ...
    def GetStackFrames(self, exception: Exception) -> IList_1[DynamicStackFrame]: ...
    def IsCallable(self, obj: typing.Any) -> bool: ...
    def LoadCompiledCode(self, method: Delegate, path: str, customData: str) -> ScriptCode: ...
    def ScopeSetVariable(self, scope: Scope, name: str, value: typing.Any) -> None: ...
    def ScopeTryGetVariable(self, scope: Scope, name: str, value: clr.Reference[typing.Any]) -> bool: ...
    def SetSearchPaths(self, paths: ICollection_1[str]) -> None: ...
    def Shutdown(self) -> None: ...
    # Skipped CreateFileUnit due to it being static, abstract and generic.

    CreateFileUnit : CreateFileUnit_MethodGroup
    class CreateFileUnit_MethodGroup:
        @typing.overload
        def __call__(self, path: str) -> SourceUnit:...
        @typing.overload
        def __call__(self, path: str, content: str) -> SourceUnit:...
        @typing.overload
        def __call__(self, path: str, encoding: Encoding) -> SourceUnit:...
        @typing.overload
        def __call__(self, path: str, encoding: Encoding, kind: SourceCodeKind) -> SourceUnit:...

    # Skipped CreateScope due to it being static, abstract and generic.

    CreateScope : CreateScope_MethodGroup
    class CreateScope_MethodGroup:
        @typing.overload
        def __call__(self) -> Scope:...
        @typing.overload
        def __call__(self, dictionary: IDictionary_2[str, typing.Any]) -> Scope:...
        @typing.overload
        def __call__(self, storage: IDynamicMetaObjectProvider) -> Scope:...

    # Skipped CreateSnippet due to it being static, abstract and generic.

    CreateSnippet : CreateSnippet_MethodGroup
    class CreateSnippet_MethodGroup:
        @typing.overload
        def __call__(self, code: str, kind: SourceCodeKind) -> SourceUnit:...
        @typing.overload
        def __call__(self, code: str, id: str, kind: SourceCodeKind) -> SourceUnit:...

    # Skipped CreateSourceUnit due to it being static, abstract and generic.

    CreateSourceUnit : CreateSourceUnit_MethodGroup
    class CreateSourceUnit_MethodGroup:
        @typing.overload
        def __call__(self, contentProvider: TextContentProvider, path: str, kind: SourceCodeKind) -> SourceUnit:...
        @typing.overload
        def __call__(self, contentProvider: StreamContentProvider, path: str, encoding: Encoding, kind: SourceCodeKind) -> SourceUnit:...

    # Skipped GetCompilerOptions due to it being static, abstract and generic.

    GetCompilerOptions : GetCompilerOptions_MethodGroup
    class GetCompilerOptions_MethodGroup:
        @typing.overload
        def __call__(self) -> CompilerOptions:...
        @typing.overload
        def __call__(self, scope: Scope) -> CompilerOptions:...

    # Skipped GetService due to it being static, abstract and generic.

    GetService : GetService_MethodGroup
    class GetService_MethodGroup:
        def __getitem__(self, t:typing.Type[GetService_1_T1]) -> GetService_1[GetService_1_T1]: ...

        GetService_1_T1 = typing.TypeVar('GetService_1_T1')
        class GetService_1(typing.Generic[GetService_1_T1]):
            GetService_1_TService = LanguageContext.GetService_MethodGroup.GetService_1_T1
            def __call__(self, args: Array_1[typing.Any]) -> GetService_1_TService:...


    # Skipped ScopeGetVariable due to it being static, abstract and generic.

    ScopeGetVariable : ScopeGetVariable_MethodGroup
    class ScopeGetVariable_MethodGroup:
        def __getitem__(self, t:typing.Type[ScopeGetVariable_1_T1]) -> ScopeGetVariable_1[ScopeGetVariable_1_T1]: ...

        ScopeGetVariable_1_T1 = typing.TypeVar('ScopeGetVariable_1_T1')
        class ScopeGetVariable_1(typing.Generic[ScopeGetVariable_1_T1]):
            ScopeGetVariable_1_T = LanguageContext.ScopeGetVariable_MethodGroup.ScopeGetVariable_1_T1
            def __call__(self, scope: Scope, name: str) -> ScopeGetVariable_1_T:...

        def __call__(self, scope: Scope, name: str) -> typing.Any:...



class Scope(IDynamicMetaObjectProvider):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, dictionary: IDictionary_2[str, typing.Any]) -> None: ...
    @typing.overload
    def __init__(self, storage: IDynamicMetaObjectProvider) -> None: ...
    @property
    def Storage(self) -> typing.Any: ...
    def GetExtension(self, languageContextId: ContextId) -> ScopeExtension: ...
    def SetExtension(self, languageContextId: ContextId, extension: ScopeExtension) -> ScopeExtension: ...


class ScopeExtension:
    def __init__(self, scope: Scope) -> None: ...
    EmptyArray : Array_1[ScopeExtension]
    @property
    def Scope(self) -> Scope: ...


class ScriptDomainManager:
    def __init__(self, hostingProvider: DynamicRuntimeHostingProvider, configuration: DlrConfiguration) -> None: ...
    @property
    def Configuration(self) -> DlrConfiguration: ...
    @property
    def Globals(self) -> Scope: ...
    @Globals.setter
    def Globals(self, value: Scope) -> Scope: ...
    @property
    def Host(self) -> DynamicRuntimeHostingProvider: ...
    @property
    def Platform(self) -> PlatformAdaptationLayer: ...
    @property
    def SharedIO(self) -> SharedIO: ...
    def GetLanguage(self, providerType: typing.Type[typing.Any]) -> LanguageContext: ...
    def GetLanguageByExtension(self, fileExtension: str) -> LanguageContext: ...
    def GetLanguageByName(self, languageName: str) -> LanguageContext: ...
    def GetLanguageByTypeName(self, providerAssemblyQualifiedTypeName: str) -> LanguageContext: ...
    def GetLoadedAssemblyList(self) -> IList_1[Assembly]: ...
    def LoadAssembly(self, assembly: Assembly) -> bool: ...
    def TryGetLanguage(self, languageName: str, language: clr.Reference[LanguageContext]) -> bool: ...
    def TryGetLanguageByFileExtension(self, fileExtension: str, language: clr.Reference[LanguageContext]) -> bool: ...


class SharedIO:
    @property
    def ErrorEncoding(self) -> Encoding: ...
    @property
    def ErrorStream(self) -> Stream: ...
    @property
    def ErrorWriter(self) -> TextWriter: ...
    @property
    def InputEncoding(self) -> Encoding: ...
    @property
    def InputReader(self) -> TextReader: ...
    @property
    def InputStream(self) -> Stream: ...
    @property
    def OutputEncoding(self) -> Encoding: ...
    @property
    def OutputStream(self) -> Stream: ...
    @property
    def OutputWriter(self) -> TextWriter: ...
    def GetEncoding(self, type: ConsoleStreamType) -> Encoding: ...
    def GetReader(self, encoding: clr.Reference[Encoding]) -> TextReader: ...
    def GetStream(self, type: ConsoleStreamType) -> Stream: ...
    def GetStreamProxy(self, type: ConsoleStreamType) -> Stream: ...
    def GetWriter(self, type: ConsoleStreamType) -> TextWriter: ...
    def RedirectToConsole(self) -> None: ...
    def SetErrorOutput(self, stream: Stream, writer: TextWriter) -> None: ...
    def SetInput(self, stream: Stream, reader: TextReader, encoding: Encoding) -> None: ...
    def SetOutput(self, stream: Stream, writer: TextWriter) -> None: ...

