import typing, clr
from System.Dynamic import DynamicObject, GetMemberBinder, InvokeBinder, SetMemberBinder
from System import Delegate, Array_1

class DynamicHookGen(DynamicObject):
    @typing.overload
    def __init__(self, type: typing.Type[typing.Any]) -> None: ...
    @typing.overload
    def __init__(self, type: typing.Type[typing.Any], hookType: DynamicHookGen.HookType) -> None: ...
    IL : typing.Any
    On : typing.Any
    OnOrIL : typing.Any
    def __add__(self, ctx: DynamicHookGen, target: Delegate) -> DynamicHookGen: ...
    def __sub__(self, ctx: DynamicHookGen, target: Delegate) -> DynamicHookGen: ...
    def TryGetMember(self, binder: GetMemberBinder, result: clr.Reference[typing.Any]) -> bool: ...
    def TryInvoke(self, binder: InvokeBinder, args: Array_1[typing.Any], result: clr.Reference[typing.Any]) -> bool: ...
    def TrySetMember(self, binder: SetMemberBinder, value: typing.Any) -> bool: ...

    class HookType(typing.SupportsInt):
        @typing.overload
        def __init__(self, value : int) -> None: ...
        @typing.overload
        def __init__(self, value : int, force_if_true: bool) -> None: ...
        def __int__(self) -> int: ...
        
        # Values:
        OnOrIL : DynamicHookGen.HookType # 0
        On : DynamicHookGen.HookType # 1
        IL : DynamicHookGen.HookType # 2


