import typing, clr, abc
from Microsoft.Xna.Framework import Color, Rectangle, Matrix, Quaternion, Vector2, Vector3, Vector4, DisplayOrientation
from System.Collections.Generic import IEnumerable_1, IEnumerator_1, List_1, Dictionary_2
from System import Array_1, IDisposable, Action_1, IEquatable_1
from System.Collections.ObjectModel import ReadOnlyCollection_1
from System.Text import StringBuilder
from System.IO import Stream

class Blend(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    One : Blend # 0
    Zero : Blend # 1
    SourceColor : Blend # 2
    InverseSourceColor : Blend # 3
    SourceAlpha : Blend # 4
    InverseSourceAlpha : Blend # 5
    DestinationColor : Blend # 6
    InverseDestinationColor : Blend # 7
    DestinationAlpha : Blend # 8
    InverseDestinationAlpha : Blend # 9
    BlendFactor : Blend # 10
    InverseBlendFactor : Blend # 11
    SourceAlphaSaturation : Blend # 12


class BlendFunction(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Add : BlendFunction # 0
    Subtract : BlendFunction # 1
    ReverseSubtract : BlendFunction # 2
    Min : BlendFunction # 3
    Max : BlendFunction # 4


class BlendState(GraphicsResource):
    def __init__(self) -> None: ...
    Additive : BlendState
    AlphaBlend : BlendState
    NonPremultiplied : BlendState
    Opaque : BlendState
    @property
    def AlphaBlendFunction(self) -> BlendFunction: ...
    @AlphaBlendFunction.setter
    def AlphaBlendFunction(self, value: BlendFunction) -> BlendFunction: ...
    @property
    def AlphaDestinationBlend(self) -> Blend: ...
    @AlphaDestinationBlend.setter
    def AlphaDestinationBlend(self, value: Blend) -> Blend: ...
    @property
    def AlphaSourceBlend(self) -> Blend: ...
    @AlphaSourceBlend.setter
    def AlphaSourceBlend(self, value: Blend) -> Blend: ...
    @property
    def BlendFactor(self) -> Color: ...
    @BlendFactor.setter
    def BlendFactor(self, value: Color) -> Color: ...
    @property
    def ColorBlendFunction(self) -> BlendFunction: ...
    @ColorBlendFunction.setter
    def ColorBlendFunction(self, value: BlendFunction) -> BlendFunction: ...
    @property
    def ColorDestinationBlend(self) -> Blend: ...
    @ColorDestinationBlend.setter
    def ColorDestinationBlend(self, value: Blend) -> Blend: ...
    @property
    def ColorSourceBlend(self) -> Blend: ...
    @ColorSourceBlend.setter
    def ColorSourceBlend(self, value: Blend) -> Blend: ...
    @property
    def ColorWriteChannels(self) -> ColorWriteChannels: ...
    @ColorWriteChannels.setter
    def ColorWriteChannels(self, value: ColorWriteChannels) -> ColorWriteChannels: ...
    @property
    def ColorWriteChannels1(self) -> ColorWriteChannels: ...
    @ColorWriteChannels1.setter
    def ColorWriteChannels1(self, value: ColorWriteChannels) -> ColorWriteChannels: ...
    @property
    def ColorWriteChannels2(self) -> ColorWriteChannels: ...
    @ColorWriteChannels2.setter
    def ColorWriteChannels2(self, value: ColorWriteChannels) -> ColorWriteChannels: ...
    @property
    def ColorWriteChannels3(self) -> ColorWriteChannels: ...
    @ColorWriteChannels3.setter
    def ColorWriteChannels3(self, value: ColorWriteChannels) -> ColorWriteChannels: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IndependentBlendEnable(self) -> bool: ...
    @IndependentBlendEnable.setter
    def IndependentBlendEnable(self, value: bool) -> bool: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Item(self) -> TargetBlendState: ...
    @property
    def MultiSampleMask(self) -> int: ...
    @MultiSampleMask.setter
    def MultiSampleMask(self, value: int) -> int: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...


class BufferUsage(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : BufferUsage # 0
    WriteOnly : BufferUsage # 1


class ClearOptions(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Target : ClearOptions # 1
    DepthBuffer : ClearOptions # 2
    Stencil : ClearOptions # 4


class ColorWriteChannels(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : ColorWriteChannels # 0
    Red : ColorWriteChannels # 1
    Green : ColorWriteChannels # 2
    Blue : ColorWriteChannels # 4
    Alpha : ColorWriteChannels # 8
    All : ColorWriteChannels # 15


class CompareFunction(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Always : CompareFunction # 0
    Never : CompareFunction # 1
    Less : CompareFunction # 2
    LessEqual : CompareFunction # 3
    Equal : CompareFunction # 4
    GreaterEqual : CompareFunction # 5
    Greater : CompareFunction # 6
    NotEqual : CompareFunction # 7


class CubeMapFace(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    PositiveX : CubeMapFace # 0
    NegativeX : CubeMapFace # 1
    PositiveY : CubeMapFace # 2
    NegativeY : CubeMapFace # 3
    PositiveZ : CubeMapFace # 4
    NegativeZ : CubeMapFace # 5


class CullMode(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : CullMode # 0
    CullClockwiseFace : CullMode # 1
    CullCounterClockwiseFace : CullMode # 2


class DepthFormat(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : DepthFormat # 0
    Depth16 : DepthFormat # 1
    Depth24 : DepthFormat # 2
    Depth24Stencil8 : DepthFormat # 3


class DepthStencilState(GraphicsResource):
    def __init__(self) -> None: ...
    Default : DepthStencilState
    DepthRead : DepthStencilState
    None_ : DepthStencilState
    @property
    def CounterClockwiseStencilDepthBufferFail(self) -> StencilOperation: ...
    @CounterClockwiseStencilDepthBufferFail.setter
    def CounterClockwiseStencilDepthBufferFail(self, value: StencilOperation) -> StencilOperation: ...
    @property
    def CounterClockwiseStencilFail(self) -> StencilOperation: ...
    @CounterClockwiseStencilFail.setter
    def CounterClockwiseStencilFail(self, value: StencilOperation) -> StencilOperation: ...
    @property
    def CounterClockwiseStencilFunction(self) -> CompareFunction: ...
    @CounterClockwiseStencilFunction.setter
    def CounterClockwiseStencilFunction(self, value: CompareFunction) -> CompareFunction: ...
    @property
    def CounterClockwiseStencilPass(self) -> StencilOperation: ...
    @CounterClockwiseStencilPass.setter
    def CounterClockwiseStencilPass(self, value: StencilOperation) -> StencilOperation: ...
    @property
    def DepthBufferEnable(self) -> bool: ...
    @DepthBufferEnable.setter
    def DepthBufferEnable(self, value: bool) -> bool: ...
    @property
    def DepthBufferFunction(self) -> CompareFunction: ...
    @DepthBufferFunction.setter
    def DepthBufferFunction(self, value: CompareFunction) -> CompareFunction: ...
    @property
    def DepthBufferWriteEnable(self) -> bool: ...
    @DepthBufferWriteEnable.setter
    def DepthBufferWriteEnable(self, value: bool) -> bool: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def ReferenceStencil(self) -> int: ...
    @ReferenceStencil.setter
    def ReferenceStencil(self, value: int) -> int: ...
    @property
    def StencilDepthBufferFail(self) -> StencilOperation: ...
    @StencilDepthBufferFail.setter
    def StencilDepthBufferFail(self, value: StencilOperation) -> StencilOperation: ...
    @property
    def StencilEnable(self) -> bool: ...
    @StencilEnable.setter
    def StencilEnable(self, value: bool) -> bool: ...
    @property
    def StencilFail(self) -> StencilOperation: ...
    @StencilFail.setter
    def StencilFail(self, value: StencilOperation) -> StencilOperation: ...
    @property
    def StencilFunction(self) -> CompareFunction: ...
    @StencilFunction.setter
    def StencilFunction(self, value: CompareFunction) -> CompareFunction: ...
    @property
    def StencilMask(self) -> int: ...
    @StencilMask.setter
    def StencilMask(self, value: int) -> int: ...
    @property
    def StencilPass(self) -> StencilOperation: ...
    @StencilPass.setter
    def StencilPass(self, value: StencilOperation) -> StencilOperation: ...
    @property
    def StencilWriteMask(self) -> int: ...
    @StencilWriteMask.setter
    def StencilWriteMask(self, value: int) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def TwoSidedStencilMode(self) -> bool: ...
    @TwoSidedStencilMode.setter
    def TwoSidedStencilMode(self, value: bool) -> bool: ...


class DisplayMode:
    @property
    def AspectRatio(self) -> float: ...
    @property
    def Format(self) -> SurfaceFormat: ...
    @property
    def Height(self) -> int: ...
    @property
    def TitleSafeArea(self) -> Rectangle: ...
    @property
    def Width(self) -> int: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: DisplayMode, right: DisplayMode) -> bool: ...
    def __ne__(self, left: DisplayMode, right: DisplayMode) -> bool: ...
    def ToString(self) -> str: ...


class DisplayModeCollection(IEnumerable_1[DisplayMode]):
    @property
    def Item(self) -> IEnumerable_1[DisplayMode]: ...
    def GetEnumerator(self) -> IEnumerator_1[DisplayMode]: ...


class Effect(GraphicsResource):
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, effectCode: Array_1[int]) -> None: ...
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, effectCode: Array_1[int], index: int, count: int) -> None: ...
    @property
    def CurrentTechnique(self) -> EffectTechnique: ...
    @CurrentTechnique.setter
    def CurrentTechnique(self, value: EffectTechnique) -> EffectTechnique: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Parameters(self) -> EffectParameterCollection: ...
    @Parameters.setter
    def Parameters(self, value: EffectParameterCollection) -> EffectParameterCollection: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def Techniques(self) -> EffectTechniqueCollection: ...
    @Techniques.setter
    def Techniques(self, value: EffectTechniqueCollection) -> EffectTechniqueCollection: ...
    def Clone(self) -> Effect: ...


class EffectAnnotation:
    @property
    def ColumnCount(self) -> int: ...
    @ColumnCount.setter
    def ColumnCount(self, value: int) -> int: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def ParameterClass(self) -> EffectParameterClass: ...
    @ParameterClass.setter
    def ParameterClass(self, value: EffectParameterClass) -> EffectParameterClass: ...
    @property
    def ParameterType(self) -> EffectParameterType: ...
    @ParameterType.setter
    def ParameterType(self, value: EffectParameterType) -> EffectParameterType: ...
    @property
    def RowCount(self) -> int: ...
    @RowCount.setter
    def RowCount(self, value: int) -> int: ...
    @property
    def Semantic(self) -> str: ...
    @Semantic.setter
    def Semantic(self, value: str) -> str: ...


class EffectAnnotationCollection(IEnumerable_1[EffectAnnotation]):
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> EffectAnnotation: ...
    @property
    def Item(self) -> EffectAnnotation: ...
    def GetEnumerator(self) -> IEnumerator_1[EffectAnnotation]: ...


class EffectParameter:
    @property
    def Annotations(self) -> EffectAnnotationCollection: ...
    @Annotations.setter
    def Annotations(self, value: EffectAnnotationCollection) -> EffectAnnotationCollection: ...
    @property
    def ColumnCount(self) -> int: ...
    @ColumnCount.setter
    def ColumnCount(self, value: int) -> int: ...
    @property
    def Elements(self) -> EffectParameterCollection: ...
    @Elements.setter
    def Elements(self, value: EffectParameterCollection) -> EffectParameterCollection: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def ParameterClass(self) -> EffectParameterClass: ...
    @ParameterClass.setter
    def ParameterClass(self, value: EffectParameterClass) -> EffectParameterClass: ...
    @property
    def ParameterType(self) -> EffectParameterType: ...
    @ParameterType.setter
    def ParameterType(self, value: EffectParameterType) -> EffectParameterType: ...
    @property
    def RowCount(self) -> int: ...
    @RowCount.setter
    def RowCount(self, value: int) -> int: ...
    @property
    def Semantic(self) -> str: ...
    @Semantic.setter
    def Semantic(self, value: str) -> str: ...
    @property
    def StructureMembers(self) -> EffectParameterCollection: ...
    @StructureMembers.setter
    def StructureMembers(self, value: EffectParameterCollection) -> EffectParameterCollection: ...
    def GetValueBoolean(self) -> bool: ...
    def GetValueInt32(self) -> int: ...
    def GetValueInt32Array(self) -> Array_1[int]: ...
    def GetValueMatrix(self) -> Matrix: ...
    def GetValueMatrixArray(self, count: int) -> Array_1[Matrix]: ...
    def GetValueQuaternion(self) -> Quaternion: ...
    def GetValueSingle(self) -> float: ...
    def GetValueSingleArray(self) -> Array_1[float]: ...
    def GetValueString(self) -> str: ...
    def GetValueTexture2D(self) -> Texture2D: ...
    def GetValueTexture3D(self) -> Texture3D: ...
    def GetValueTextureCube(self) -> TextureCube: ...
    def GetValueVector2(self) -> Vector2: ...
    def GetValueVector2Array(self) -> Array_1[Vector2]: ...
    def GetValueVector3(self) -> Vector3: ...
    def GetValueVector3Array(self) -> Array_1[Vector3]: ...
    def GetValueVector4(self) -> Vector4: ...
    def GetValueVector4Array(self) -> Array_1[Vector4]: ...
    def SetValueTranspose(self, value: Matrix) -> None: ...
    # Skipped SetValue due to it being static, abstract and generic.

    SetValue : SetValue_MethodGroup
    class SetValue_MethodGroup:
        @typing.overload
        def __call__(self, value: float) -> None:...
        # Method SetValue(value : Int32) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: Array_1[float]) -> None:...
        # Method SetValue(value : Int32[]) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: Array_1[Matrix]) -> None:...
        @typing.overload
        def __call__(self, value: Array_1[Vector2]) -> None:...
        @typing.overload
        def __call__(self, value: Array_1[Vector3]) -> None:...
        @typing.overload
        def __call__(self, value: Array_1[Vector4]) -> None:...
        # Method SetValue(value : Boolean) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: Matrix) -> None:...
        @typing.overload
        def __call__(self, value: Quaternion) -> None:...
        @typing.overload
        def __call__(self, value: Texture) -> None:...
        @typing.overload
        def __call__(self, value: Vector2) -> None:...
        @typing.overload
        def __call__(self, value: Vector3) -> None:...
        @typing.overload
        def __call__(self, value: Vector4) -> None:...



class EffectParameterClass(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Scalar : EffectParameterClass # 0
    Vector : EffectParameterClass # 1
    Matrix : EffectParameterClass # 2
    Object : EffectParameterClass # 3
    Struct : EffectParameterClass # 4


class EffectParameterCollection(IEnumerable_1[EffectParameter]):
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> EffectParameter: ...
    @property
    def Item(self) -> EffectParameter: ...
    def GetEnumerator(self) -> IEnumerator_1[EffectParameter]: ...


class EffectParameterType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Void : EffectParameterType # 0
    Bool : EffectParameterType # 1
    Int32 : EffectParameterType # 2
    Single : EffectParameterType # 3
    String : EffectParameterType # 4
    Texture : EffectParameterType # 5
    Texture1D : EffectParameterType # 6
    Texture2D : EffectParameterType # 7
    Texture3D : EffectParameterType # 8
    TextureCube : EffectParameterType # 9


class EffectPass:
    @property
    def Annotations(self) -> EffectAnnotationCollection: ...
    @Annotations.setter
    def Annotations(self, value: EffectAnnotationCollection) -> EffectAnnotationCollection: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    def Apply(self) -> None: ...


class EffectPassCollection(IEnumerable_1[EffectPass]):
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> EffectPass: ...
    @property
    def Item(self) -> EffectPass: ...
    def GetEnumerator(self) -> EffectPassCollection.Enumerator: ...

    class Enumerator(IEnumerator_1[EffectPass]):
        @property
        def Current(self) -> EffectPass: ...
        def Dispose(self) -> None: ...
        def MoveNext(self) -> bool: ...



class EffectTechnique:
    @property
    def Annotations(self) -> EffectAnnotationCollection: ...
    @Annotations.setter
    def Annotations(self, value: EffectAnnotationCollection) -> EffectAnnotationCollection: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Passes(self) -> EffectPassCollection: ...
    @Passes.setter
    def Passes(self, value: EffectPassCollection) -> EffectPassCollection: ...


class EffectTechniqueCollection(IEnumerable_1[EffectTechnique]):
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> EffectTechnique: ...
    @property
    def Item(self) -> EffectTechnique: ...
    def GetEnumerator(self) -> IEnumerator_1[EffectTechnique]: ...


class FillMode(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Solid : FillMode # 0
    WireFrame : FillMode # 1


class GraphicsAdapter(IDisposable):
    def __init__(self) -> None: ...
    @classmethod
    @property
    def Adapters(cls) -> ReadOnlyCollection_1[GraphicsAdapter]: ...
    @property
    def CurrentDisplayMode(self) -> DisplayMode: ...
    @classmethod
    @property
    def DefaultAdapter(cls) -> GraphicsAdapter: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> str: ...
    @property
    def IsWideScreen(self) -> bool: ...
    @property
    def SupportedDisplayModes(self) -> DisplayModeCollection: ...
    @classmethod
    @property
    def UseDriverType(cls) -> GraphicsAdapter.DriverType: ...
    @classmethod
    @UseDriverType.setter
    def UseDriverType(cls, value: GraphicsAdapter.DriverType) -> GraphicsAdapter.DriverType: ...
    @classmethod
    @property
    def UseReferenceDevice(cls) -> bool: ...
    @classmethod
    @UseReferenceDevice.setter
    def UseReferenceDevice(cls, value: bool) -> bool: ...
    def Dispose(self) -> None: ...
    def IsProfileSupported(self, graphicsProfile: GraphicsProfile) -> bool: ...
    def QueryRenderTargetFormat(self, graphicsProfile: GraphicsProfile, format: SurfaceFormat, depthFormat: DepthFormat, multiSampleCount: int, selectedFormat: clr.Reference[SurfaceFormat], selectedDepthFormat: clr.Reference[DepthFormat], selectedMultiSampleCount: clr.Reference[int]) -> bool: ...

    class DriverType(typing.SupportsInt):
        @typing.overload
        def __init__(self, value : int) -> None: ...
        @typing.overload
        def __init__(self, value : int, force_if_true: bool) -> None: ...
        def __int__(self) -> int: ...
        
        # Values:
        Hardware : GraphicsAdapter.DriverType # 0
        Reference : GraphicsAdapter.DriverType # 1
        FastSoftware : GraphicsAdapter.DriverType # 2



class GraphicsDebug:
    def __init__(self) -> None: ...
    def TryDequeueMessage(self, message: clr.Reference[GraphicsDebugMessage]) -> bool: ...


class GraphicsDebugMessage:
    def __init__(self) -> None: ...
    @property
    def Category(self) -> str: ...
    @Category.setter
    def Category(self, value: str) -> str: ...
    @property
    def Id(self) -> int: ...
    @Id.setter
    def Id(self, value: int) -> int: ...
    @property
    def IdName(self) -> str: ...
    @IdName.setter
    def IdName(self, value: str) -> str: ...
    @property
    def Message(self) -> str: ...
    @Message.setter
    def Message(self, value: str) -> str: ...
    @property
    def Severity(self) -> str: ...
    @Severity.setter
    def Severity(self, value: str) -> str: ...


class GraphicsDevice(IDisposable):
    @typing.overload
    def __init__(self, adapter: GraphicsAdapter, graphicsProfile: GraphicsProfile, preferHalfPixelOffset: bool, presentationParameters: PresentationParameters) -> None: ...
    @typing.overload
    def __init__(self, adapter: GraphicsAdapter, graphicsProfile: GraphicsProfile, presentationParameters: PresentationParameters) -> None: ...
    @property
    def Adapter(self) -> GraphicsAdapter: ...
    @Adapter.setter
    def Adapter(self, value: GraphicsAdapter) -> GraphicsAdapter: ...
    @property
    def BlendFactor(self) -> Color: ...
    @BlendFactor.setter
    def BlendFactor(self, value: Color) -> Color: ...
    @property
    def BlendState(self) -> BlendState: ...
    @BlendState.setter
    def BlendState(self, value: BlendState) -> BlendState: ...
    @property
    def DepthStencilState(self) -> DepthStencilState: ...
    @DepthStencilState.setter
    def DepthStencilState(self, value: DepthStencilState) -> DepthStencilState: ...
    @classmethod
    @property
    def DiscardColor(cls) -> Color: ...
    @classmethod
    @DiscardColor.setter
    def DiscardColor(cls, value: Color) -> Color: ...
    @property
    def DisplayMode(self) -> DisplayMode: ...
    @property
    def GraphicsDebug(self) -> GraphicsDebug: ...
    @GraphicsDebug.setter
    def GraphicsDebug(self, value: GraphicsDebug) -> GraphicsDebug: ...
    @property
    def GraphicsDeviceStatus(self) -> GraphicsDeviceStatus: ...
    @property
    def GraphicsProfile(self) -> GraphicsProfile: ...
    @property
    def Indices(self) -> IndexBuffer: ...
    @Indices.setter
    def Indices(self, value: IndexBuffer) -> IndexBuffer: ...
    @property
    def IsContentLost(self) -> bool: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Metrics(self) -> GraphicsMetrics: ...
    @Metrics.setter
    def Metrics(self, value: GraphicsMetrics) -> GraphicsMetrics: ...
    @property
    def PresentationParameters(self) -> PresentationParameters: ...
    @PresentationParameters.setter
    def PresentationParameters(self, value: PresentationParameters) -> PresentationParameters: ...
    @property
    def RasterizerState(self) -> RasterizerState: ...
    @RasterizerState.setter
    def RasterizerState(self, value: RasterizerState) -> RasterizerState: ...
    @property
    def RenderTargetCount(self) -> int: ...
    @property
    def ResourcesLost(self) -> bool: ...
    @ResourcesLost.setter
    def ResourcesLost(self, value: bool) -> bool: ...
    @property
    def SamplerStates(self) -> SamplerStateCollection: ...
    @SamplerStates.setter
    def SamplerStates(self, value: SamplerStateCollection) -> SamplerStateCollection: ...
    @property
    def ScissorRectangle(self) -> Rectangle: ...
    @ScissorRectangle.setter
    def ScissorRectangle(self, value: Rectangle) -> Rectangle: ...
    @property
    def Textures(self) -> TextureCollection: ...
    @Textures.setter
    def Textures(self, value: TextureCollection) -> TextureCollection: ...
    @property
    def UseHalfPixelOffset(self) -> bool: ...
    @UseHalfPixelOffset.setter
    def UseHalfPixelOffset(self, value: bool) -> bool: ...
    @property
    def VertexSamplerStates(self) -> SamplerStateCollection: ...
    @VertexSamplerStates.setter
    def VertexSamplerStates(self, value: SamplerStateCollection) -> SamplerStateCollection: ...
    @property
    def VertexTextures(self) -> TextureCollection: ...
    @VertexTextures.setter
    def VertexTextures(self, value: TextureCollection) -> TextureCollection: ...
    @property
    def Viewport(self) -> Viewport: ...
    @Viewport.setter
    def Viewport(self, value: Viewport) -> Viewport: ...
    def Dispose(self) -> None: ...
    def DrawPrimitives(self, primitiveType: PrimitiveType, vertexStart: int, primitiveCount: int) -> None: ...
    def Present(self) -> None: ...
    def SetRenderTargets(self, renderTargets: Array_1[RenderTargetBinding]) -> None: ...
    def SetVertexBuffers(self, vertexBuffers: Array_1[VertexBufferBinding]) -> None: ...
    # Skipped Clear due to it being static, abstract and generic.

    Clear : Clear_MethodGroup
    class Clear_MethodGroup:
        @typing.overload
        def __call__(self, color: Color) -> None:...
        @typing.overload
        def __call__(self, options: ClearOptions, color: Color, depth: float, stencil: int) -> None:...
        @typing.overload
        def __call__(self, options: ClearOptions, color: Vector4, depth: float, stencil: int) -> None:...

    # Skipped DrawIndexedPrimitives due to it being static, abstract and generic.

    DrawIndexedPrimitives : DrawIndexedPrimitives_MethodGroup
    class DrawIndexedPrimitives_MethodGroup:
        @typing.overload
        def __call__(self, primitiveType: PrimitiveType, baseVertex: int, startIndex: int, primitiveCount: int) -> None:...
        @typing.overload
        def __call__(self, primitiveType: PrimitiveType, baseVertex: int, minVertexIndex: int, numVertices: int, startIndex: int, primitiveCount: int) -> None:...

    # Skipped DrawInstancedPrimitives due to it being static, abstract and generic.

    DrawInstancedPrimitives : DrawInstancedPrimitives_MethodGroup
    class DrawInstancedPrimitives_MethodGroup:
        @typing.overload
        def __call__(self, primitiveType: PrimitiveType, baseVertex: int, startIndex: int, primitiveCount: int, instanceCount: int) -> None:...
        @typing.overload
        def __call__(self, primitiveType: PrimitiveType, baseVertex: int, startIndex: int, primitiveCount: int, baseInstance: int, instanceCount: int) -> None:...
        @typing.overload
        def __call__(self, primitiveType: PrimitiveType, baseVertex: int, minVertexIndex: int, numVertices: int, startIndex: int, primitiveCount: int, instanceCount: int) -> None:...

    # Skipped DrawUserIndexedPrimitives due to it being static, abstract and generic.

    DrawUserIndexedPrimitives : DrawUserIndexedPrimitives_MethodGroup
    class DrawUserIndexedPrimitives_MethodGroup:
        def __getitem__(self, t:typing.Type[DrawUserIndexedPrimitives_1_T1]) -> DrawUserIndexedPrimitives_1[DrawUserIndexedPrimitives_1_T1]: ...

        DrawUserIndexedPrimitives_1_T1 = typing.TypeVar('DrawUserIndexedPrimitives_1_T1')
        class DrawUserIndexedPrimitives_1(typing.Generic[DrawUserIndexedPrimitives_1_T1]):
            DrawUserIndexedPrimitives_1_T = GraphicsDevice.DrawUserIndexedPrimitives_MethodGroup.DrawUserIndexedPrimitives_1_T1
            @typing.overload
            def __call__(self, primitiveType: PrimitiveType, vertexData: Array_1[DrawUserIndexedPrimitives_1_T], vertexOffset: int, numVertices: int, indexData: Array_1[int], indexOffset: int, primitiveCount: int) -> None:...
            # Method DrawUserIndexedPrimitives(primitiveType : PrimitiveType, vertexData : T[], vertexOffset : Int32, numVertices : Int32, indexData : Int32[], indexOffset : Int32, primitiveCount : Int32) was skipped since it collides with above method
            @typing.overload
            def __call__(self, primitiveType: PrimitiveType, vertexData: Array_1[DrawUserIndexedPrimitives_1_T], vertexOffset: int, numVertices: int, indexData: Array_1[int], indexOffset: int, primitiveCount: int, vertexDeclaration: VertexDeclaration) -> None:...
            # Method DrawUserIndexedPrimitives(primitiveType : PrimitiveType, vertexData : T[], vertexOffset : Int32, numVertices : Int32, indexData : Int32[], indexOffset : Int32, primitiveCount : Int32, vertexDeclaration : VertexDeclaration) was skipped since it collides with above method


    # Skipped DrawUserPrimitives due to it being static, abstract and generic.

    DrawUserPrimitives : DrawUserPrimitives_MethodGroup
    class DrawUserPrimitives_MethodGroup:
        def __getitem__(self, t:typing.Type[DrawUserPrimitives_1_T1]) -> DrawUserPrimitives_1[DrawUserPrimitives_1_T1]: ...

        DrawUserPrimitives_1_T1 = typing.TypeVar('DrawUserPrimitives_1_T1')
        class DrawUserPrimitives_1(typing.Generic[DrawUserPrimitives_1_T1]):
            DrawUserPrimitives_1_T = GraphicsDevice.DrawUserPrimitives_MethodGroup.DrawUserPrimitives_1_T1
            @typing.overload
            def __call__(self, primitiveType: PrimitiveType, vertexData: Array_1[DrawUserPrimitives_1_T], vertexOffset: int, primitiveCount: int) -> None:...
            @typing.overload
            def __call__(self, primitiveType: PrimitiveType, vertexData: Array_1[DrawUserPrimitives_1_T], vertexOffset: int, primitiveCount: int, vertexDeclaration: VertexDeclaration) -> None:...


    # Skipped GetBackBufferData due to it being static, abstract and generic.

    GetBackBufferData : GetBackBufferData_MethodGroup
    class GetBackBufferData_MethodGroup:
        def __getitem__(self, t:typing.Type[GetBackBufferData_1_T1]) -> GetBackBufferData_1[GetBackBufferData_1_T1]: ...

        GetBackBufferData_1_T1 = typing.TypeVar('GetBackBufferData_1_T1')
        class GetBackBufferData_1(typing.Generic[GetBackBufferData_1_T1]):
            GetBackBufferData_1_T = GraphicsDevice.GetBackBufferData_MethodGroup.GetBackBufferData_1_T1
            @typing.overload
            def __call__(self, data: Array_1[GetBackBufferData_1_T]) -> None:...
            @typing.overload
            def __call__(self, data: Array_1[GetBackBufferData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, rect: typing.Optional[Rectangle], data: Array_1[GetBackBufferData_1_T], startIndex: int, elementCount: int) -> None:...


    # Skipped GetRenderTargets due to it being static, abstract and generic.

    GetRenderTargets : GetRenderTargets_MethodGroup
    class GetRenderTargets_MethodGroup:
        @typing.overload
        def __call__(self) -> Array_1[RenderTargetBinding]:...
        @typing.overload
        def __call__(self, outTargets: Array_1[RenderTargetBinding]) -> None:...

    # Skipped Reset due to it being static, abstract and generic.

    Reset : Reset_MethodGroup
    class Reset_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, presentationParameters: PresentationParameters) -> None:...

    # Skipped SetRenderTarget due to it being static, abstract and generic.

    SetRenderTarget : SetRenderTarget_MethodGroup
    class SetRenderTarget_MethodGroup:
        @typing.overload
        def __call__(self, renderTarget: RenderTarget2D) -> None:...
        @typing.overload
        def __call__(self, renderTarget: RenderTargetCube, cubeMapFace: CubeMapFace) -> None:...

    # Skipped SetVertexBuffer due to it being static, abstract and generic.

    SetVertexBuffer : SetVertexBuffer_MethodGroup
    class SetVertexBuffer_MethodGroup:
        @typing.overload
        def __call__(self, vertexBuffer: VertexBuffer) -> None:...
        @typing.overload
        def __call__(self, vertexBuffer: VertexBuffer, vertexOffset: int) -> None:...



class GraphicsDeviceStatus(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Normal : GraphicsDeviceStatus # 0
    Lost : GraphicsDeviceStatus # 1
    NotReset : GraphicsDeviceStatus # 2


class GraphicsMetrics:
    @property
    def ClearCount(self) -> int: ...
    @property
    def DrawCount(self) -> int: ...
    @property
    def PixelShaderCount(self) -> int: ...
    @property
    def PrimitiveCount(self) -> int: ...
    @property
    def SpriteCount(self) -> int: ...
    @property
    def TargetCount(self) -> int: ...
    @property
    def TextureCount(self) -> int: ...
    @property
    def VertexShaderCount(self) -> int: ...
    def __add__(self, value1: GraphicsMetrics, value2: GraphicsMetrics) -> GraphicsMetrics: ...
    def __sub__(self, value1: GraphicsMetrics, value2: GraphicsMetrics) -> GraphicsMetrics: ...


class GraphicsProfile(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Reach : GraphicsProfile # 0
    HiDef : GraphicsProfile # 1


class GraphicsResource(IDisposable, abc.ABC):
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    def Dispose(self) -> None: ...
    def ToString(self) -> str: ...


class IGraphicsDeviceService(typing.Protocol):
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...


class IndexBuffer(GraphicsResource):
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, indexElementSize: IndexElementSize, indexCount: int, bufferUsage: BufferUsage) -> None: ...
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, indexType: typing.Type[typing.Any], indexCount: int, usage: BufferUsage) -> None: ...
    @property
    def BufferUsage(self) -> BufferUsage: ...
    @BufferUsage.setter
    def BufferUsage(self, value: BufferUsage) -> BufferUsage: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IndexCount(self) -> int: ...
    @IndexCount.setter
    def IndexCount(self, value: int) -> int: ...
    @property
    def IndexElementSize(self) -> IndexElementSize: ...
    @IndexElementSize.setter
    def IndexElementSize(self, value: IndexElementSize) -> IndexElementSize: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    # Skipped GetData due to it being static, abstract and generic.

    GetData : GetData_MethodGroup
    class GetData_MethodGroup:
        def __getitem__(self, t:typing.Type[GetData_1_T1]) -> GetData_1[GetData_1_T1]: ...

        GetData_1_T1 = typing.TypeVar('GetData_1_T1')
        class GetData_1(typing.Generic[GetData_1_T1]):
            GetData_1_T = IndexBuffer.GetData_MethodGroup.GetData_1_T1
            @typing.overload
            def __call__(self, data: Array_1[GetData_1_T]) -> None:...
            @typing.overload
            def __call__(self, data: Array_1[GetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, offsetInBytes: int, data: Array_1[GetData_1_T], startIndex: int, elementCount: int) -> None:...


    # Skipped SetData due to it being static, abstract and generic.

    SetData : SetData_MethodGroup
    class SetData_MethodGroup:
        def __getitem__(self, t:typing.Type[SetData_1_T1]) -> SetData_1[SetData_1_T1]: ...

        SetData_1_T1 = typing.TypeVar('SetData_1_T1')
        class SetData_1(typing.Generic[SetData_1_T1]):
            SetData_1_T = IndexBuffer.SetData_MethodGroup.SetData_1_T1
            @typing.overload
            def __call__(self, data: Array_1[SetData_1_T]) -> None:...
            @typing.overload
            def __call__(self, data: Array_1[SetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, offsetInBytes: int, data: Array_1[SetData_1_T], startIndex: int, elementCount: int) -> None:...




class IndexElementSize(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    SixteenBits : IndexElementSize # 0
    ThirtyTwoBits : IndexElementSize # 1


class IVertexType(typing.Protocol):
    @property
    def VertexDeclaration(self) -> VertexDeclaration: ...


class PresentationParameters:
    def __init__(self) -> None: ...
    DefaultPresentRate : int
    @property
    def BackBufferFormat(self) -> SurfaceFormat: ...
    @BackBufferFormat.setter
    def BackBufferFormat(self, value: SurfaceFormat) -> SurfaceFormat: ...
    @property
    def BackBufferHeight(self) -> int: ...
    @BackBufferHeight.setter
    def BackBufferHeight(self, value: int) -> int: ...
    @property
    def BackBufferWidth(self) -> int: ...
    @BackBufferWidth.setter
    def BackBufferWidth(self, value: int) -> int: ...
    @property
    def Bounds(self) -> Rectangle: ...
    @property
    def DepthStencilFormat(self) -> DepthFormat: ...
    @DepthStencilFormat.setter
    def DepthStencilFormat(self, value: DepthFormat) -> DepthFormat: ...
    @property
    def DeviceWindowHandle(self) -> int: ...
    @DeviceWindowHandle.setter
    def DeviceWindowHandle(self, value: int) -> int: ...
    @property
    def DisplayOrientation(self) -> DisplayOrientation: ...
    @DisplayOrientation.setter
    def DisplayOrientation(self, value: DisplayOrientation) -> DisplayOrientation: ...
    @property
    def HardwareModeSwitch(self) -> bool: ...
    @HardwareModeSwitch.setter
    def HardwareModeSwitch(self, value: bool) -> bool: ...
    @property
    def IsFullScreen(self) -> bool: ...
    @IsFullScreen.setter
    def IsFullScreen(self, value: bool) -> bool: ...
    @property
    def MultiSampleCount(self) -> int: ...
    @MultiSampleCount.setter
    def MultiSampleCount(self, value: int) -> int: ...
    @property
    def PresentationInterval(self) -> PresentInterval: ...
    @PresentationInterval.setter
    def PresentationInterval(self, value: PresentInterval) -> PresentInterval: ...
    @property
    def RenderTargetUsage(self) -> RenderTargetUsage: ...
    @RenderTargetUsage.setter
    def RenderTargetUsage(self, value: RenderTargetUsage) -> RenderTargetUsage: ...
    def Clear(self) -> None: ...
    def Clone(self) -> PresentationParameters: ...


class PresentInterval(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Default : PresentInterval # 0
    One : PresentInterval # 1
    Two : PresentInterval # 2
    Immediate : PresentInterval # 3


class PrimitiveType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    TriangleList : PrimitiveType # 0
    TriangleStrip : PrimitiveType # 1
    LineList : PrimitiveType # 2
    LineStrip : PrimitiveType # 3
    PointList : PrimitiveType # 4


class RasterizerState(GraphicsResource):
    def __init__(self) -> None: ...
    CullClockwise : RasterizerState
    CullCounterClockwise : RasterizerState
    CullNone : RasterizerState
    @property
    def CullMode(self) -> CullMode: ...
    @CullMode.setter
    def CullMode(self, value: CullMode) -> CullMode: ...
    @property
    def DepthBias(self) -> float: ...
    @DepthBias.setter
    def DepthBias(self, value: float) -> float: ...
    @property
    def DepthClipEnable(self) -> bool: ...
    @DepthClipEnable.setter
    def DepthClipEnable(self, value: bool) -> bool: ...
    @property
    def FillMode(self) -> FillMode: ...
    @FillMode.setter
    def FillMode(self, value: FillMode) -> FillMode: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def MultiSampleAntiAlias(self) -> bool: ...
    @MultiSampleAntiAlias.setter
    def MultiSampleAntiAlias(self, value: bool) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def ScissorTestEnable(self) -> bool: ...
    @ScissorTestEnable.setter
    def ScissorTestEnable(self, value: bool) -> bool: ...
    @property
    def SlopeScaleDepthBias(self) -> float: ...
    @SlopeScaleDepthBias.setter
    def SlopeScaleDepthBias(self, value: float) -> float: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...


class RenderTarget2D(Texture2D):
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int) -> None: ...
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, mipMap: bool, preferredFormat: SurfaceFormat, preferredDepthFormat: DepthFormat) -> None: ...
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, mipMap: bool, preferredFormat: SurfaceFormat, preferredDepthFormat: DepthFormat, preferredMultiSampleCount: int, usage: RenderTargetUsage) -> None: ...
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, mipMap: bool, preferredFormat: SurfaceFormat, preferredDepthFormat: DepthFormat, preferredMultiSampleCount: int, usage: RenderTargetUsage, shared: bool) -> None: ...
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, mipMap: bool, preferredFormat: SurfaceFormat, preferredDepthFormat: DepthFormat, preferredMultiSampleCount: int, usage: RenderTargetUsage, shared: bool, arraySize: int) -> None: ...
    @property
    def Bounds(self) -> Rectangle: ...
    @property
    def DepthStencilFormat(self) -> DepthFormat: ...
    @DepthStencilFormat.setter
    def DepthStencilFormat(self, value: DepthFormat) -> DepthFormat: ...
    @property
    def Format(self) -> SurfaceFormat: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def Height(self) -> int: ...
    @property
    def IsContentLost(self) -> bool: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def LevelCount(self) -> int: ...
    @property
    def MultiSampleCount(self) -> int: ...
    @MultiSampleCount.setter
    def MultiSampleCount(self, value: int) -> int: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def RenderTargetUsage(self) -> RenderTargetUsage: ...
    @RenderTargetUsage.setter
    def RenderTargetUsage(self, value: RenderTargetUsage) -> RenderTargetUsage: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def Width(self) -> int: ...


class RenderTargetBinding:
    @typing.overload
    def __init__(self, renderTarget: RenderTarget2D) -> None: ...
    @typing.overload
    def __init__(self, renderTarget: RenderTargetCube, cubeMapFace: CubeMapFace) -> None: ...
    @property
    def ArraySlice(self) -> int: ...
    @property
    def RenderTarget(self) -> Texture: ...
    # Operator not supported op_Implicit(renderTarget: RenderTarget2D)


class RenderTargetCube(TextureCube):
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, size: int, mipMap: bool, preferredFormat: SurfaceFormat, preferredDepthFormat: DepthFormat) -> None: ...
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, size: int, mipMap: bool, preferredFormat: SurfaceFormat, preferredDepthFormat: DepthFormat, preferredMultiSampleCount: int, usage: RenderTargetUsage) -> None: ...
    @property
    def DepthStencilFormat(self) -> DepthFormat: ...
    @DepthStencilFormat.setter
    def DepthStencilFormat(self, value: DepthFormat) -> DepthFormat: ...
    @property
    def Format(self) -> SurfaceFormat: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IsContentLost(self) -> bool: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def LevelCount(self) -> int: ...
    @property
    def MultiSampleCount(self) -> int: ...
    @MultiSampleCount.setter
    def MultiSampleCount(self, value: int) -> int: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def RenderTargetUsage(self) -> RenderTargetUsage: ...
    @RenderTargetUsage.setter
    def RenderTargetUsage(self, value: RenderTargetUsage) -> RenderTargetUsage: ...
    @property
    def Size(self) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...


class RenderTargetUsage(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    DiscardContents : RenderTargetUsage # 0
    PreserveContents : RenderTargetUsage # 1
    PlatformContents : RenderTargetUsage # 2


class SamplerState(GraphicsResource):
    def __init__(self) -> None: ...
    AnisotropicClamp : SamplerState
    AnisotropicWrap : SamplerState
    LinearClamp : SamplerState
    LinearWrap : SamplerState
    PointClamp : SamplerState
    PointWrap : SamplerState
    @property
    def AddressU(self) -> TextureAddressMode: ...
    @AddressU.setter
    def AddressU(self, value: TextureAddressMode) -> TextureAddressMode: ...
    @property
    def AddressV(self) -> TextureAddressMode: ...
    @AddressV.setter
    def AddressV(self, value: TextureAddressMode) -> TextureAddressMode: ...
    @property
    def AddressW(self) -> TextureAddressMode: ...
    @AddressW.setter
    def AddressW(self, value: TextureAddressMode) -> TextureAddressMode: ...
    @property
    def BorderColor(self) -> Color: ...
    @BorderColor.setter
    def BorderColor(self, value: Color) -> Color: ...
    @property
    def ComparisonFunction(self) -> CompareFunction: ...
    @ComparisonFunction.setter
    def ComparisonFunction(self, value: CompareFunction) -> CompareFunction: ...
    @property
    def Filter(self) -> TextureFilter: ...
    @Filter.setter
    def Filter(self, value: TextureFilter) -> TextureFilter: ...
    @property
    def FilterMode(self) -> TextureFilterMode: ...
    @FilterMode.setter
    def FilterMode(self, value: TextureFilterMode) -> TextureFilterMode: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def MaxAnisotropy(self) -> int: ...
    @MaxAnisotropy.setter
    def MaxAnisotropy(self, value: int) -> int: ...
    @property
    def MaxMipLevel(self) -> int: ...
    @MaxMipLevel.setter
    def MaxMipLevel(self, value: int) -> int: ...
    @property
    def MipMapLevelOfDetailBias(self) -> float: ...
    @MipMapLevelOfDetailBias.setter
    def MipMapLevelOfDetailBias(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...


class SamplerStateCollection:
    @property
    def Item(self) -> SamplerState: ...
    @Item.setter
    def Item(self, value: SamplerState) -> SamplerState: ...


class SpriteBatch(GraphicsResource):
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice) -> None: ...
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, capacity: int) -> None: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    def Begin(self, sortMode: SpriteSortMode = ..., blendState: BlendState = ..., samplerState: SamplerState = ..., depthStencilState: DepthStencilState = ..., rasterizerState: RasterizerState = ..., effect: Effect = ..., transformMatrix: typing.Optional[Matrix] = ...) -> None: ...
    def End(self) -> None: ...
    # Skipped Draw due to it being static, abstract and generic.

    Draw : Draw_MethodGroup
    class Draw_MethodGroup:
        @typing.overload
        def __call__(self, texture: Texture2D, destinationRectangle: Rectangle, color: Color) -> None:...
        @typing.overload
        def __call__(self, texture: Texture2D, position: Vector2, color: Color) -> None:...
        @typing.overload
        def __call__(self, texture: Texture2D, destinationRectangle: Rectangle, sourceRectangle: typing.Optional[Rectangle], color: Color) -> None:...
        @typing.overload
        def __call__(self, texture: Texture2D, position: Vector2, sourceRectangle: typing.Optional[Rectangle], color: Color) -> None:...
        @typing.overload
        def __call__(self, texture: Texture2D, destinationRectangle: Rectangle, sourceRectangle: typing.Optional[Rectangle], color: Color, rotation: float, origin: Vector2, effects: SpriteEffects, layerDepth: float) -> None:...
        @typing.overload
        def __call__(self, texture: Texture2D, position: Vector2, sourceRectangle: typing.Optional[Rectangle], color: Color, rotation: float, origin: Vector2, scale: float, effects: SpriteEffects, layerDepth: float) -> None:...
        @typing.overload
        def __call__(self, texture: Texture2D, position: Vector2, sourceRectangle: typing.Optional[Rectangle], color: Color, rotation: float, origin: Vector2, scale: Vector2, effects: SpriteEffects, layerDepth: float) -> None:...

    # Skipped DrawString due to it being static, abstract and generic.

    DrawString : DrawString_MethodGroup
    class DrawString_MethodGroup:
        @typing.overload
        def __call__(self, spriteFont: SpriteFont, text: str, position: Vector2, color: Color) -> None:...
        @typing.overload
        def __call__(self, spriteFont: SpriteFont, text: StringBuilder, position: Vector2, color: Color) -> None:...
        @typing.overload
        def __call__(self, spriteFont: SpriteFont, text: str, position: Vector2, color: Color, rotation: float, origin: Vector2, scale: float, effects: SpriteEffects, layerDepth: float) -> None:...
        @typing.overload
        def __call__(self, spriteFont: SpriteFont, text: str, position: Vector2, color: Color, rotation: float, origin: Vector2, scale: Vector2, effects: SpriteEffects, layerDepth: float) -> None:...
        @typing.overload
        def __call__(self, spriteFont: SpriteFont, text: StringBuilder, position: Vector2, color: Color, rotation: float, origin: Vector2, scale: float, effects: SpriteEffects, layerDepth: float) -> None:...
        @typing.overload
        def __call__(self, spriteFont: SpriteFont, text: StringBuilder, position: Vector2, color: Color, rotation: float, origin: Vector2, scale: Vector2, effects: SpriteEffects, layerDepth: float) -> None:...
        @typing.overload
        def __call__(self, spriteFont: SpriteFont, text: str, position: Vector2, color: Color, rotation: float, origin: Vector2, scale: Vector2, effects: SpriteEffects, layerDepth: float, rtl: bool) -> None:...
        @typing.overload
        def __call__(self, spriteFont: SpriteFont, text: StringBuilder, position: Vector2, color: Color, rotation: float, origin: Vector2, scale: Vector2, effects: SpriteEffects, layerDepth: float, rtl: bool) -> None:...



class SpriteEffects(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : SpriteEffects # 0
    FlipHorizontally : SpriteEffects # 1
    FlipVertically : SpriteEffects # 2


class SpriteFont:
    def __init__(self, texture: Texture2D, glyphBounds: List_1[Rectangle], cropping: List_1[Rectangle], characters: List_1[str], lineSpacing: int, spacing: float, kerning: List_1[Vector3], defaultCharacter: typing.Optional[str]) -> None: ...
    @property
    def Characters(self) -> ReadOnlyCollection_1[str]: ...
    @Characters.setter
    def Characters(self, value: ReadOnlyCollection_1[str]) -> ReadOnlyCollection_1[str]: ...
    @property
    def DefaultCharacter(self) -> typing.Optional[str]: ...
    @DefaultCharacter.setter
    def DefaultCharacter(self, value: typing.Optional[str]) -> typing.Optional[str]: ...
    @property
    def Glyphs(self) -> Array_1[SpriteFont.Glyph]: ...
    @property
    def LineSpacing(self) -> int: ...
    @LineSpacing.setter
    def LineSpacing(self, value: int) -> int: ...
    @property
    def Spacing(self) -> float: ...
    @Spacing.setter
    def Spacing(self, value: float) -> float: ...
    @property
    def Texture(self) -> Texture2D: ...
    def GetGlyphs(self) -> Dictionary_2[str, SpriteFont.Glyph]: ...
    # Skipped MeasureString due to it being static, abstract and generic.

    MeasureString : MeasureString_MethodGroup
    class MeasureString_MethodGroup:
        @typing.overload
        def __call__(self, text: str) -> Vector2:...
        @typing.overload
        def __call__(self, text: StringBuilder) -> Vector2:...


    class Glyph:
        BoundsInTexture : Rectangle
        Character : str
        Cropping : Rectangle
        Empty : SpriteFont.Glyph
        LeftSideBearing : float
        RightSideBearing : float
        Width : float
        WidthIncludingBearings : float
        def ToString(self) -> str: ...



class SpriteSortMode(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Deferred : SpriteSortMode # 0
    Immediate : SpriteSortMode # 1
    Texture : SpriteSortMode # 2
    BackToFront : SpriteSortMode # 3
    FrontToBack : SpriteSortMode # 4


class StencilOperation(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Keep : StencilOperation # 0
    Zero : StencilOperation # 1
    Replace : StencilOperation # 2
    Increment : StencilOperation # 3
    Decrement : StencilOperation # 4
    IncrementSaturation : StencilOperation # 5
    DecrementSaturation : StencilOperation # 6
    Invert : StencilOperation # 7


class SurfaceFormat(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Color : SurfaceFormat # 0
    Bgr565 : SurfaceFormat # 1
    Bgra5551 : SurfaceFormat # 2
    Bgra4444 : SurfaceFormat # 3
    Dxt1 : SurfaceFormat # 4
    Dxt3 : SurfaceFormat # 5
    Dxt5 : SurfaceFormat # 6
    NormalizedByte2 : SurfaceFormat # 7
    NormalizedByte4 : SurfaceFormat # 8
    Rgba1010102 : SurfaceFormat # 9
    Rg32 : SurfaceFormat # 10
    Rgba64 : SurfaceFormat # 11
    Alpha8 : SurfaceFormat # 12
    Single : SurfaceFormat # 13
    Vector2 : SurfaceFormat # 14
    Vector4 : SurfaceFormat # 15
    HalfSingle : SurfaceFormat # 16
    HalfVector2 : SurfaceFormat # 17
    HalfVector4 : SurfaceFormat # 18
    HdrBlendable : SurfaceFormat # 19
    Bgr32 : SurfaceFormat # 20
    Bgra32 : SurfaceFormat # 21
    ColorSRgb : SurfaceFormat # 30
    Bgr32SRgb : SurfaceFormat # 31
    Bgra32SRgb : SurfaceFormat # 32
    Dxt1SRgb : SurfaceFormat # 33
    Dxt3SRgb : SurfaceFormat # 34
    Dxt5SRgb : SurfaceFormat # 35
    RgbPvrtc2Bpp : SurfaceFormat # 50
    RgbPvrtc4Bpp : SurfaceFormat # 51
    RgbaPvrtc2Bpp : SurfaceFormat # 52
    RgbaPvrtc4Bpp : SurfaceFormat # 53
    RgbEtc1 : SurfaceFormat # 60
    Dxt1a : SurfaceFormat # 70
    RgbaAtcExplicitAlpha : SurfaceFormat # 80
    RgbaAtcInterpolatedAlpha : SurfaceFormat # 81
    Rgb8Etc2 : SurfaceFormat # 90
    Srgb8Etc2 : SurfaceFormat # 91
    Rgb8A1Etc2 : SurfaceFormat # 92
    Srgb8A1Etc2 : SurfaceFormat # 93
    Rgba8Etc2 : SurfaceFormat # 94
    SRgb8A8Etc2 : SurfaceFormat # 95


class TargetBlendState:
    @property
    def AlphaBlendFunction(self) -> BlendFunction: ...
    @AlphaBlendFunction.setter
    def AlphaBlendFunction(self, value: BlendFunction) -> BlendFunction: ...
    @property
    def AlphaDestinationBlend(self) -> Blend: ...
    @AlphaDestinationBlend.setter
    def AlphaDestinationBlend(self, value: Blend) -> Blend: ...
    @property
    def AlphaSourceBlend(self) -> Blend: ...
    @AlphaSourceBlend.setter
    def AlphaSourceBlend(self, value: Blend) -> Blend: ...
    @property
    def ColorBlendFunction(self) -> BlendFunction: ...
    @ColorBlendFunction.setter
    def ColorBlendFunction(self, value: BlendFunction) -> BlendFunction: ...
    @property
    def ColorDestinationBlend(self) -> Blend: ...
    @ColorDestinationBlend.setter
    def ColorDestinationBlend(self, value: Blend) -> Blend: ...
    @property
    def ColorSourceBlend(self) -> Blend: ...
    @ColorSourceBlend.setter
    def ColorSourceBlend(self, value: Blend) -> Blend: ...
    @property
    def ColorWriteChannels(self) -> ColorWriteChannels: ...
    @ColorWriteChannels.setter
    def ColorWriteChannels(self, value: ColorWriteChannels) -> ColorWriteChannels: ...


class Texture(GraphicsResource):
    @property
    def Format(self) -> SurfaceFormat: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def LevelCount(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...


class Texture2D(Texture):
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int) -> None: ...
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, mipmap: bool, format: SurfaceFormat) -> None: ...
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, mipmap: bool, format: SurfaceFormat, arraySize: int) -> None: ...
    @property
    def Bounds(self) -> Rectangle: ...
    @property
    def Format(self) -> SurfaceFormat: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def Height(self) -> int: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def LevelCount(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def Width(self) -> int: ...
    def Reload(self, textureStream: Stream) -> None: ...
    def SaveAsJpeg(self, stream: Stream, width: int, height: int) -> None: ...
    def SaveAsPng(self, stream: Stream, width: int, height: int) -> None: ...
    # Skipped FromFile due to it being static, abstract and generic.

    FromFile : FromFile_MethodGroup
    class FromFile_MethodGroup:
        @typing.overload
        def __call__(self, graphicsDevice: GraphicsDevice, path: str) -> Texture2D:...
        @typing.overload
        def __call__(self, graphicsDevice: GraphicsDevice, path: str, colorProcessor: Action_1[Array_1[int]]) -> Texture2D:...

    # Skipped FromStream due to it being static, abstract and generic.

    FromStream : FromStream_MethodGroup
    class FromStream_MethodGroup:
        @typing.overload
        def __call__(self, graphicsDevice: GraphicsDevice, stream: Stream) -> Texture2D:...
        @typing.overload
        def __call__(self, graphicsDevice: GraphicsDevice, stream: Stream, colorProcessor: Action_1[Array_1[int]]) -> Texture2D:...

    # Skipped GetData due to it being static, abstract and generic.

    GetData : GetData_MethodGroup
    class GetData_MethodGroup:
        def __getitem__(self, t:typing.Type[GetData_1_T1]) -> GetData_1[GetData_1_T1]: ...

        GetData_1_T1 = typing.TypeVar('GetData_1_T1')
        class GetData_1(typing.Generic[GetData_1_T1]):
            GetData_1_T = Texture2D.GetData_MethodGroup.GetData_1_T1
            @typing.overload
            def __call__(self, data: Array_1[GetData_1_T]) -> None:...
            @typing.overload
            def __call__(self, data: Array_1[GetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, level: int, rect: typing.Optional[Rectangle], data: Array_1[GetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, level: int, arraySlice: int, rect: typing.Optional[Rectangle], data: Array_1[GetData_1_T], startIndex: int, elementCount: int) -> None:...


    # Skipped SetData due to it being static, abstract and generic.

    SetData : SetData_MethodGroup
    class SetData_MethodGroup:
        def __getitem__(self, t:typing.Type[SetData_1_T1]) -> SetData_1[SetData_1_T1]: ...

        SetData_1_T1 = typing.TypeVar('SetData_1_T1')
        class SetData_1(typing.Generic[SetData_1_T1]):
            SetData_1_T = Texture2D.SetData_MethodGroup.SetData_1_T1
            @typing.overload
            def __call__(self, data: Array_1[SetData_1_T]) -> None:...
            @typing.overload
            def __call__(self, data: Array_1[SetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, level: int, rect: typing.Optional[Rectangle], data: Array_1[SetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, level: int, arraySlice: int, rect: typing.Optional[Rectangle], data: Array_1[SetData_1_T], startIndex: int, elementCount: int) -> None:...




class Texture3D(Texture):
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, depth: int, mipMap: bool, format: SurfaceFormat) -> None: ...
    @property
    def Depth(self) -> int: ...
    @property
    def Format(self) -> SurfaceFormat: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def Height(self) -> int: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def LevelCount(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def Width(self) -> int: ...
    # Skipped GetData due to it being static, abstract and generic.

    GetData : GetData_MethodGroup
    class GetData_MethodGroup:
        def __getitem__(self, t:typing.Type[GetData_1_T1]) -> GetData_1[GetData_1_T1]: ...

        GetData_1_T1 = typing.TypeVar('GetData_1_T1')
        class GetData_1(typing.Generic[GetData_1_T1]):
            GetData_1_T = Texture3D.GetData_MethodGroup.GetData_1_T1
            @typing.overload
            def __call__(self, data: Array_1[GetData_1_T]) -> None:...
            @typing.overload
            def __call__(self, data: Array_1[GetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, level: int, left: int, top: int, right: int, bottom: int, front: int, back: int, data: Array_1[GetData_1_T], startIndex: int, elementCount: int) -> None:...


    # Skipped SetData due to it being static, abstract and generic.

    SetData : SetData_MethodGroup
    class SetData_MethodGroup:
        def __getitem__(self, t:typing.Type[SetData_1_T1]) -> SetData_1[SetData_1_T1]: ...

        SetData_1_T1 = typing.TypeVar('SetData_1_T1')
        class SetData_1(typing.Generic[SetData_1_T1]):
            SetData_1_T = Texture3D.SetData_MethodGroup.SetData_1_T1
            @typing.overload
            def __call__(self, data: Array_1[SetData_1_T]) -> None:...
            @typing.overload
            def __call__(self, data: Array_1[SetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, level: int, left: int, top: int, right: int, bottom: int, front: int, back: int, data: Array_1[SetData_1_T], startIndex: int, elementCount: int) -> None:...




class TextureAddressMode(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Wrap : TextureAddressMode # 0
    Clamp : TextureAddressMode # 1
    Mirror : TextureAddressMode # 2
    Border : TextureAddressMode # 3


class TextureCollection:
    @property
    def Item(self) -> Texture: ...
    @Item.setter
    def Item(self, value: Texture) -> Texture: ...


class TextureCube(Texture):
    def __init__(self, graphicsDevice: GraphicsDevice, size: int, mipMap: bool, format: SurfaceFormat) -> None: ...
    @property
    def Format(self) -> SurfaceFormat: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def LevelCount(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Size(self) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    # Skipped GetData due to it being static, abstract and generic.

    GetData : GetData_MethodGroup
    class GetData_MethodGroup:
        def __getitem__(self, t:typing.Type[GetData_1_T1]) -> GetData_1[GetData_1_T1]: ...

        GetData_1_T1 = typing.TypeVar('GetData_1_T1')
        class GetData_1(typing.Generic[GetData_1_T1]):
            GetData_1_T = TextureCube.GetData_MethodGroup.GetData_1_T1
            @typing.overload
            def __call__(self, cubeMapFace: CubeMapFace, data: Array_1[GetData_1_T]) -> None:...
            @typing.overload
            def __call__(self, cubeMapFace: CubeMapFace, data: Array_1[GetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, cubeMapFace: CubeMapFace, level: int, rect: typing.Optional[Rectangle], data: Array_1[GetData_1_T], startIndex: int, elementCount: int) -> None:...


    # Skipped SetData due to it being static, abstract and generic.

    SetData : SetData_MethodGroup
    class SetData_MethodGroup:
        def __getitem__(self, t:typing.Type[SetData_1_T1]) -> SetData_1[SetData_1_T1]: ...

        SetData_1_T1 = typing.TypeVar('SetData_1_T1')
        class SetData_1(typing.Generic[SetData_1_T1]):
            SetData_1_T = TextureCube.SetData_MethodGroup.SetData_1_T1
            @typing.overload
            def __call__(self, face: CubeMapFace, data: Array_1[SetData_1_T]) -> None:...
            @typing.overload
            def __call__(self, face: CubeMapFace, data: Array_1[SetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, face: CubeMapFace, level: int, rect: typing.Optional[Rectangle], data: Array_1[SetData_1_T], startIndex: int, elementCount: int) -> None:...




class TextureFilter(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Linear : TextureFilter # 0
    Point : TextureFilter # 1
    Anisotropic : TextureFilter # 2
    LinearMipPoint : TextureFilter # 3
    PointMipLinear : TextureFilter # 4
    MinLinearMagPointMipLinear : TextureFilter # 5
    MinLinearMagPointMipPoint : TextureFilter # 6
    MinPointMagLinearMipLinear : TextureFilter # 7
    MinPointMagLinearMipPoint : TextureFilter # 8


class TextureFilterMode(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Default : TextureFilterMode # 0
    Comparison : TextureFilterMode # 1


class VertexBuffer(GraphicsResource):
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, type: typing.Type[typing.Any], vertexCount: int, bufferUsage: BufferUsage) -> None: ...
    @typing.overload
    def __init__(self, graphicsDevice: GraphicsDevice, vertexDeclaration: VertexDeclaration, vertexCount: int, bufferUsage: BufferUsage) -> None: ...
    @property
    def BufferUsage(self) -> BufferUsage: ...
    @BufferUsage.setter
    def BufferUsage(self, value: BufferUsage) -> BufferUsage: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def VertexCount(self) -> int: ...
    @VertexCount.setter
    def VertexCount(self, value: int) -> int: ...
    @property
    def VertexDeclaration(self) -> VertexDeclaration: ...
    @VertexDeclaration.setter
    def VertexDeclaration(self, value: VertexDeclaration) -> VertexDeclaration: ...
    # Skipped GetData due to it being static, abstract and generic.

    GetData : GetData_MethodGroup
    class GetData_MethodGroup:
        def __getitem__(self, t:typing.Type[GetData_1_T1]) -> GetData_1[GetData_1_T1]: ...

        GetData_1_T1 = typing.TypeVar('GetData_1_T1')
        class GetData_1(typing.Generic[GetData_1_T1]):
            GetData_1_T = VertexBuffer.GetData_MethodGroup.GetData_1_T1
            @typing.overload
            def __call__(self, data: Array_1[GetData_1_T]) -> None:...
            @typing.overload
            def __call__(self, data: Array_1[GetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, offsetInBytes: int, data: Array_1[GetData_1_T], startIndex: int, elementCount: int, vertexStride: int = ...) -> None:...


    # Skipped SetData due to it being static, abstract and generic.

    SetData : SetData_MethodGroup
    class SetData_MethodGroup:
        def __getitem__(self, t:typing.Type[SetData_1_T1]) -> SetData_1[SetData_1_T1]: ...

        SetData_1_T1 = typing.TypeVar('SetData_1_T1')
        class SetData_1(typing.Generic[SetData_1_T1]):
            SetData_1_T = VertexBuffer.SetData_MethodGroup.SetData_1_T1
            @typing.overload
            def __call__(self, data: Array_1[SetData_1_T]) -> None:...
            @typing.overload
            def __call__(self, data: Array_1[SetData_1_T], startIndex: int, elementCount: int) -> None:...
            @typing.overload
            def __call__(self, offsetInBytes: int, data: Array_1[SetData_1_T], startIndex: int, elementCount: int, vertexStride: int) -> None:...




class VertexBufferBinding:
    @typing.overload
    def __init__(self, vertexBuffer: VertexBuffer) -> None: ...
    @typing.overload
    def __init__(self, vertexBuffer: VertexBuffer, vertexOffset: int) -> None: ...
    @typing.overload
    def __init__(self, vertexBuffer: VertexBuffer, vertexOffset: int, instanceFrequency: int) -> None: ...
    @property
    def InstanceFrequency(self) -> int: ...
    @property
    def VertexBuffer(self) -> VertexBuffer: ...
    @property
    def VertexOffset(self) -> int: ...


class VertexDeclaration(GraphicsResource, IEquatable_1[VertexDeclaration]):
    @typing.overload
    def __init__(self, elements: Array_1[VertexElement]) -> None: ...
    @typing.overload
    def __init__(self, vertexStride: int, elements: Array_1[VertexElement]) -> None: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @GraphicsDevice.setter
    def GraphicsDevice(self, value: GraphicsDevice) -> GraphicsDevice: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def VertexStride(self) -> int: ...
    def GetHashCode(self) -> int: ...
    def GetVertexElements(self) -> Array_1[VertexElement]: ...
    def __eq__(self, left: VertexDeclaration, right: VertexDeclaration) -> bool: ...
    def __ne__(self, left: VertexDeclaration, right: VertexDeclaration) -> bool: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: VertexDeclaration) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class VertexElement(IEquatable_1[VertexElement]):
    def __init__(self, offset: int, elementFormat: VertexElementFormat, elementUsage: VertexElementUsage, usageIndex: int) -> None: ...
    @property
    def Offset(self) -> int: ...
    @Offset.setter
    def Offset(self, value: int) -> int: ...
    @property
    def UsageIndex(self) -> int: ...
    @UsageIndex.setter
    def UsageIndex(self, value: int) -> int: ...
    @property
    def VertexElementFormat(self) -> VertexElementFormat: ...
    @VertexElementFormat.setter
    def VertexElementFormat(self, value: VertexElementFormat) -> VertexElementFormat: ...
    @property
    def VertexElementUsage(self) -> VertexElementUsage: ...
    @VertexElementUsage.setter
    def VertexElementUsage(self, value: VertexElementUsage) -> VertexElementUsage: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: VertexElement, right: VertexElement) -> bool: ...
    def __ne__(self, left: VertexElement, right: VertexElement) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: VertexElement) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class VertexElementFormat(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Single : VertexElementFormat # 0
    Vector2 : VertexElementFormat # 1
    Vector3 : VertexElementFormat # 2
    Vector4 : VertexElementFormat # 3
    Color : VertexElementFormat # 4
    Byte4 : VertexElementFormat # 5
    Short2 : VertexElementFormat # 6
    Short4 : VertexElementFormat # 7
    NormalizedShort2 : VertexElementFormat # 8
    NormalizedShort4 : VertexElementFormat # 9
    HalfVector2 : VertexElementFormat # 10
    HalfVector4 : VertexElementFormat # 11


class VertexElementUsage(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Position : VertexElementUsage # 0
    Color : VertexElementUsage # 1
    TextureCoordinate : VertexElementUsage # 2
    Normal : VertexElementUsage # 3
    Binormal : VertexElementUsage # 4
    Tangent : VertexElementUsage # 5
    BlendIndices : VertexElementUsage # 6
    BlendWeight : VertexElementUsage # 7
    Depth : VertexElementUsage # 8
    Fog : VertexElementUsage # 9
    PointSize : VertexElementUsage # 10
    Sample : VertexElementUsage # 11
    TessellateFactor : VertexElementUsage # 12


class VertexPositionColorTexture(IVertexType):
    def __init__(self, position: Vector3, color: Color, textureCoordinate: Vector2) -> None: ...
    Color : Color
    Position : Vector3
    TextureCoordinate : Vector2
    VertexDeclaration : VertexDeclaration
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: VertexPositionColorTexture, right: VertexPositionColorTexture) -> bool: ...
    def __ne__(self, left: VertexPositionColorTexture, right: VertexPositionColorTexture) -> bool: ...
    def ToString(self) -> str: ...


class VertexPositionTexture(IVertexType):
    def __init__(self, position: Vector3, textureCoordinate: Vector2) -> None: ...
    Position : Vector3
    TextureCoordinate : Vector2
    VertexDeclaration : VertexDeclaration
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: VertexPositionTexture, right: VertexPositionTexture) -> bool: ...
    def __ne__(self, left: VertexPositionTexture, right: VertexPositionTexture) -> bool: ...
    def ToString(self) -> str: ...


class Viewport:
    @typing.overload
    def __init__(self, bounds: Rectangle) -> None: ...
    @typing.overload
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    @typing.overload
    def __init__(self, x: int, y: int, width: int, height: int, minDepth: float, maxDepth: float) -> None: ...
    @property
    def AspectRatio(self) -> float: ...
    @property
    def Bounds(self) -> Rectangle: ...
    @Bounds.setter
    def Bounds(self, value: Rectangle) -> Rectangle: ...
    @property
    def Height(self) -> int: ...
    @Height.setter
    def Height(self, value: int) -> int: ...
    @property
    def MaxDepth(self) -> float: ...
    @MaxDepth.setter
    def MaxDepth(self, value: float) -> float: ...
    @property
    def MinDepth(self) -> float: ...
    @MinDepth.setter
    def MinDepth(self, value: float) -> float: ...
    @property
    def TitleSafeArea(self) -> Rectangle: ...
    @property
    def Width(self) -> int: ...
    @Width.setter
    def Width(self, value: int) -> int: ...
    @property
    def X(self) -> int: ...
    @X.setter
    def X(self, value: int) -> int: ...
    @property
    def Y(self) -> int: ...
    @Y.setter
    def Y(self, value: int) -> int: ...
    def Project(self, source: Vector3, projection: Matrix, view: Matrix, world: Matrix) -> Vector3: ...
    def ToString(self) -> str: ...
    def Unproject(self, source: Vector3, projection: Matrix, view: Matrix, world: Matrix) -> Vector3: ...

