import typing, clr, abc
from System import Array_1, ReadOnlySpan_1, Span_1
from System.Net.Sockets import AddressFamily
from System.IO import TextWriter

class IPAddress:
    @typing.overload
    def __init__(self, address: Array_1[int]) -> None: ...
    @typing.overload
    def __init__(self, address: ReadOnlySpan_1[int]) -> None: ...
    @typing.overload
    def __init__(self, address: Array_1[int], scopeid: int) -> None: ...
    @typing.overload
    def __init__(self, address: ReadOnlySpan_1[int], scopeid: int) -> None: ...
    @typing.overload
    def __init__(self, newAddress: int) -> None: ...
    Any : IPAddress
    Broadcast : IPAddress
    IPv6Any : IPAddress
    IPv6Loopback : IPAddress
    IPv6None : IPAddress
    Loopback : IPAddress
    None_ : IPAddress
    @property
    def Address(self) -> int: ...
    @Address.setter
    def Address(self, value: int) -> int: ...
    @property
    def AddressFamily(self) -> AddressFamily: ...
    @property
    def IsIPv4MappedToIPv6(self) -> bool: ...
    @property
    def IsIPv6LinkLocal(self) -> bool: ...
    @property
    def IsIPv6Multicast(self) -> bool: ...
    @property
    def IsIPv6SiteLocal(self) -> bool: ...
    @property
    def IsIPv6Teredo(self) -> bool: ...
    @property
    def IsIPv6UniqueLocal(self) -> bool: ...
    @property
    def ScopeId(self) -> int: ...
    @ScopeId.setter
    def ScopeId(self, value: int) -> int: ...
    def Equals(self, comparand: typing.Any) -> bool: ...
    def GetAddressBytes(self) -> Array_1[int]: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def IsLoopback(address: IPAddress) -> bool: ...
    def MapToIPv4(self) -> IPAddress: ...
    def MapToIPv6(self) -> IPAddress: ...
    def ToString(self) -> str: ...
    def TryFormat(self, destination: Span_1[str], charsWritten: clr.Reference[int]) -> bool: ...
    def TryWriteBytes(self, destination: Span_1[int], bytesWritten: clr.Reference[int]) -> bool: ...
    # Skipped HostToNetworkOrder due to it being static, abstract and generic.

    HostToNetworkOrder : HostToNetworkOrder_MethodGroup
    class HostToNetworkOrder_MethodGroup:
        def __call__(self, host: int) -> int:...
        # Method HostToNetworkOrder(host : Int32) was skipped since it collides with above method
        # Method HostToNetworkOrder(host : Int16) was skipped since it collides with above method

    # Skipped NetworkToHostOrder due to it being static, abstract and generic.

    NetworkToHostOrder : NetworkToHostOrder_MethodGroup
    class NetworkToHostOrder_MethodGroup:
        def __call__(self, network: int) -> int:...
        # Method NetworkToHostOrder(network : Int32) was skipped since it collides with above method
        # Method NetworkToHostOrder(network : Int16) was skipped since it collides with above method

    # Skipped Parse due to it being static, abstract and generic.

    Parse : Parse_MethodGroup
    class Parse_MethodGroup:
        @typing.overload
        def __call__(self, ipSpan: ReadOnlySpan_1[str]) -> IPAddress:...
        @typing.overload
        def __call__(self, ipString: str) -> IPAddress:...

    # Skipped TryParse due to it being static, abstract and generic.

    TryParse : TryParse_MethodGroup
    class TryParse_MethodGroup:
        @typing.overload
        def __call__(self, ipSpan: ReadOnlySpan_1[str], address: clr.Reference[IPAddress]) -> bool:...
        @typing.overload
        def __call__(self, ipString: str, address: clr.Reference[IPAddress]) -> bool:...



class WebUtility(abc.ABC):
    @staticmethod
    def UrlDecode(encodedValue: str) -> str: ...
    @staticmethod
    def UrlDecodeToBytes(encodedValue: Array_1[int], offset: int, count: int) -> Array_1[int]: ...
    @staticmethod
    def UrlEncode(value: str) -> str: ...
    @staticmethod
    def UrlEncodeToBytes(value: Array_1[int], offset: int, count: int) -> Array_1[int]: ...
    # Skipped HtmlDecode due to it being static, abstract and generic.

    HtmlDecode : HtmlDecode_MethodGroup
    class HtmlDecode_MethodGroup:
        @typing.overload
        def __call__(self, value: str) -> str:...
        @typing.overload
        def __call__(self, value: str, output: TextWriter) -> None:...

    # Skipped HtmlEncode due to it being static, abstract and generic.

    HtmlEncode : HtmlEncode_MethodGroup
    class HtmlEncode_MethodGroup:
        @typing.overload
        def __call__(self, value: str) -> str:...
        @typing.overload
        def __call__(self, value: str, output: TextWriter) -> None:...


