import typing, clr, abc
from Microsoft.Xna.Framework import Vector2, Point, Rectangle, Color
from Microsoft.Xna.Framework.Graphics import Texture2D, GraphicsDevice, SpriteBatch
from FontStashSharp.Interfaces import IFontSource, IFontLoader, IFontStashRenderer, IFontStashRenderer2
from System import IDisposable, Array_1, MulticastDelegate, IAsyncResult, AsyncCallback
from System.Collections.Generic import List_1
from System.IO import Stream
from System.Reflection import MethodInfo
from System.Text import StringBuilder

class Bounds:
    def __init__(self, x: float, y: float, x2: float, y2: float) -> None: ...
    Empty : Bounds
    X : float
    X2 : float
    Y : float
    Y2 : float
    def ApplyScale(self, scale: Vector2) -> None: ...


class DynamicFontGlyph(FontGlyph):
    def __init__(self) -> None: ...
    Codepoint : int
    Effect : FontSystemEffect
    EffectAmount : int
    FontSize : float
    FontSourceIndex : int
    Id : int
    RenderOffset : Point
    Size : Point
    Texture : Texture2D
    TextureOffset : Point
    XAdvance : int
    @property
    def IsEmpty(self) -> bool: ...
    @property
    def RenderRectangle(self) -> Rectangle: ...
    @property
    def TextureRectangle(self) -> Rectangle: ...


class DynamicSpriteFont(SpriteFontBase):
    @property
    def FontSize(self) -> float: ...
    @property
    def FontSystem(self) -> FontSystem: ...
    @FontSystem.setter
    def FontSystem(self, value: FontSystem) -> FontSystem: ...
    @property
    def LineHeight(self) -> int: ...


class FontAtlas:
    def __init__(self, w: int, h: int, count: int, texture: Texture2D) -> None: ...
    @property
    def Height(self) -> int: ...
    @Height.setter
    def Height(self, value: int) -> int: ...
    @property
    def NodesNumber(self) -> int: ...
    @NodesNumber.setter
    def NodesNumber(self, value: int) -> int: ...
    @property
    def Texture(self) -> Texture2D: ...
    @Texture.setter
    def Texture(self, value: Texture2D) -> Texture2D: ...
    @property
    def Width(self) -> int: ...
    @Width.setter
    def Width(self, value: int) -> int: ...
    def AddRect(self, rw: int, rh: int, rx: clr.Reference[int], ry: clr.Reference[int]) -> bool: ...
    def AddSkylineLevel(self, idx: int, x: int, y: int, w: int, h: int) -> bool: ...
    def InsertNode(self, idx: int, x: int, y: int, w: int) -> None: ...
    def RectFits(self, i: int, w: int, h: int) -> int: ...
    def RemoveNode(self, idx: int) -> None: ...
    def RenderGlyph(self, graphicsDevice: GraphicsDevice, glyph: DynamicFontGlyph, fontSource: IFontSource, glyphRenderer: GlyphRenderer, premultiplyAlpha: bool, kernelWidth: int, kernelHeight: int) -> None: ...
    def Reset(self, w: int, h: int) -> None: ...


class FontGlyph:
    def __init__(self) -> None: ...
    Codepoint : int
    Id : int
    RenderOffset : Point
    Size : Point
    Texture : Texture2D
    TextureOffset : Point
    XAdvance : int
    @property
    def IsEmpty(self) -> bool: ...
    @property
    def RenderRectangle(self) -> Rectangle: ...
    @property
    def TextureRectangle(self) -> Rectangle: ...


class FontSystem(IDisposable):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, settings: FontSystemSettings) -> None: ...
    GlyphPad : int
    @property
    def Atlases(self) -> List_1[FontAtlas]: ...
    @property
    def CurrentAtlas(self) -> FontAtlas: ...
    @property
    def DefaultCharacter(self) -> typing.Optional[int]: ...
    @DefaultCharacter.setter
    def DefaultCharacter(self, value: typing.Optional[int]) -> typing.Optional[int]: ...
    @property
    def ExistingTexture(self) -> Texture2D: ...
    @property
    def ExistingTextureUsedSpace(self) -> Rectangle: ...
    @property
    def FontResolutionFactor(self) -> float: ...
    @property
    def GlyphRenderer(self) -> GlyphRenderer: ...
    @property
    def KernelHeight(self) -> int: ...
    @property
    def KernelWidth(self) -> int: ...
    @property
    def PremultiplyAlpha(self) -> bool: ...
    @property
    def TextureHeight(self) -> int: ...
    @property
    def TextureWidth(self) -> int: ...
    @property
    def UseKernings(self) -> bool: ...
    @UseKernings.setter
    def UseKernings(self, value: bool) -> bool: ...
    def Dispose(self) -> None: ...
    def GetFont(self, fontSize: float) -> DynamicSpriteFont: ...
    def Reset(self) -> None: ...
    def SetFontAtlas(self, fontAtlas: FontAtlas) -> None: ...
    # Skipped AddFont due to it being static, abstract and generic.

    AddFont : AddFont_MethodGroup
    class AddFont_MethodGroup:
        @typing.overload
        def __call__(self, data: Array_1[int]) -> None:...
        @typing.overload
        def __call__(self, stream: Stream) -> None:...



class FontSystemEffect(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : FontSystemEffect # 0
    Blurry : FontSystemEffect # 1
    Stroked : FontSystemEffect # 2


class FontSystemSettings:
    def __init__(self) -> None: ...
    @property
    def ExistingTexture(self) -> Texture2D: ...
    @ExistingTexture.setter
    def ExistingTexture(self, value: Texture2D) -> Texture2D: ...
    @property
    def ExistingTextureUsedSpace(self) -> Rectangle: ...
    @ExistingTextureUsedSpace.setter
    def ExistingTextureUsedSpace(self, value: Rectangle) -> Rectangle: ...
    @property
    def FontLoader(self) -> IFontLoader: ...
    @FontLoader.setter
    def FontLoader(self, value: IFontLoader) -> IFontLoader: ...
    @property
    def FontResolutionFactor(self) -> float: ...
    @FontResolutionFactor.setter
    def FontResolutionFactor(self, value: float) -> float: ...
    @property
    def GlyphRenderer(self) -> GlyphRenderer: ...
    @GlyphRenderer.setter
    def GlyphRenderer(self, value: GlyphRenderer) -> GlyphRenderer: ...
    @property
    def KernelHeight(self) -> int: ...
    @KernelHeight.setter
    def KernelHeight(self, value: int) -> int: ...
    @property
    def KernelWidth(self) -> int: ...
    @KernelWidth.setter
    def KernelWidth(self, value: int) -> int: ...
    @property
    def PremultiplyAlpha(self) -> bool: ...
    @PremultiplyAlpha.setter
    def PremultiplyAlpha(self, value: bool) -> bool: ...
    @property
    def StbTrueTypeUseOldRasterizer(self) -> bool: ...
    @StbTrueTypeUseOldRasterizer.setter
    def StbTrueTypeUseOldRasterizer(self, value: bool) -> bool: ...
    @property
    def TextureHeight(self) -> int: ...
    @TextureHeight.setter
    def TextureHeight(self, value: int) -> int: ...
    @property
    def TextureWidth(self) -> int: ...
    @TextureWidth.setter
    def TextureWidth(self, value: int) -> int: ...
    def Clone(self) -> FontSystemSettings: ...


class Glyph:
    Bounds : Rectangle
    Codepoint : int
    Index : int
    XAdvance : int


class GlyphRenderer(MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, input: Array_1[int], output: Array_1[int], options: GlyphRenderOptions, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, input: Array_1[int], output: Array_1[int], options: GlyphRenderOptions) -> None: ...


class GlyphRenderOptions:
    Effect : FontSystemEffect
    EffectAmount : int
    PremultiplyAlpha : bool
    Size : Point


class SpriteFontBase(abc.ABC):
    @property
    def FontSize(self) -> float: ...
    @FontSize.setter
    def FontSize(self, value: float) -> float: ...
    @property
    def LineHeight(self) -> int: ...
    @LineHeight.setter
    def LineHeight(self, value: int) -> int: ...
    @staticmethod
    def GetWhite(graphicsDevice: GraphicsDevice) -> Texture2D: ...
    # Skipped DrawText due to it being static, abstract and generic.

    DrawText : DrawText_MethodGroup
    class DrawText_MethodGroup:
        @typing.overload
        def __call__(self, batch: SpriteBatch, text: StringSegment, position: Vector2, colors: Array_1[Color], rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, batch: SpriteBatch, text: str, position: Vector2, colors: Array_1[Color], rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, batch: SpriteBatch, text: StringSegment, position: Vector2, color: Color, rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, batch: SpriteBatch, text: str, position: Vector2, color: Color, rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, batch: SpriteBatch, text: StringBuilder, position: Vector2, colors: Array_1[Color], rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, batch: SpriteBatch, text: StringBuilder, position: Vector2, color: Color, rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer, text: str, position: Vector2, colors: Array_1[Color], rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer, text: StringSegment, position: Vector2, colors: Array_1[Color], rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer2, text: str, position: Vector2, colors: Array_1[Color], rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer2, text: StringSegment, position: Vector2, colors: Array_1[Color], rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer, text: str, position: Vector2, color: Color, rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer, text: StringSegment, position: Vector2, color: Color, rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer2, text: str, position: Vector2, color: Color, rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer2, text: StringSegment, position: Vector2, color: Color, rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer, text: StringBuilder, position: Vector2, colors: Array_1[Color], rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer2, text: StringBuilder, position: Vector2, colors: Array_1[Color], rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer, text: StringBuilder, position: Vector2, color: Color, rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...
        @typing.overload
        def __call__(self, renderer: IFontStashRenderer2, text: StringBuilder, position: Vector2, color: Color, rotation: float = ..., origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., layerDepth: float = ..., characterSpacing: float = ..., lineSpacing: float = ..., textStyle: TextStyle = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> float:...

    # Skipped GetGlyphRects due to it being static, abstract and generic.

    GetGlyphRects : GetGlyphRects_MethodGroup
    class GetGlyphRects_MethodGroup:
        @typing.overload
        def __call__(self, text: str, position: Vector2, origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., characterSpacing: float = ..., lineSpacing: float = ...) -> List_1[Rectangle]:...
        @typing.overload
        def __call__(self, text: StringBuilder, position: Vector2, origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., characterSpacing: float = ..., lineSpacing: float = ...) -> List_1[Rectangle]:...

    # Skipped GetGlyphs due to it being static, abstract and generic.

    GetGlyphs : GetGlyphs_MethodGroup
    class GetGlyphs_MethodGroup:
        @typing.overload
        def __call__(self, text: str, position: Vector2, origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., characterSpacing: float = ..., lineSpacing: float = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> List_1[Glyph]:...
        @typing.overload
        def __call__(self, text: StringBuilder, position: Vector2, origin: Vector2 = ..., scale: typing.Optional[Vector2] = ..., characterSpacing: float = ..., lineSpacing: float = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> List_1[Glyph]:...

    # Skipped MeasureString due to it being static, abstract and generic.

    MeasureString : MeasureString_MethodGroup
    class MeasureString_MethodGroup:
        @typing.overload
        def __call__(self, text: str, scale: typing.Optional[Vector2] = ..., characterSpacing: float = ..., lineSpacing: float = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> Vector2:...
        @typing.overload
        def __call__(self, text: StringBuilder, scale: typing.Optional[Vector2] = ..., characterSpacing: float = ..., lineSpacing: float = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> Vector2:...

    # Skipped TextBounds due to it being static, abstract and generic.

    TextBounds : TextBounds_MethodGroup
    class TextBounds_MethodGroup:
        @typing.overload
        def __call__(self, text: str, position: Vector2, scale: typing.Optional[Vector2] = ..., characterSpacing: float = ..., lineSpacing: float = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> Bounds:...
        @typing.overload
        def __call__(self, text: StringBuilder, position: Vector2, scale: typing.Optional[Vector2] = ..., characterSpacing: float = ..., lineSpacing: float = ..., effect: FontSystemEffect = ..., effectAmount: int = ...) -> Bounds:...



class StringSegment:
    @typing.overload
    def __init__(self, value: str) -> None: ...
    @typing.overload
    def __init__(self, value: str, offset: int) -> None: ...
    @typing.overload
    def __init__(self, value: str, offset: int, length: int) -> None: ...
    Length : int
    Offset : int
    String : str
    @property
    def IsNullOrEmpty(self) -> bool: ...
    @property
    def Item(self) -> str: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, a: StringSegment, b: StringSegment) -> bool: ...
    def __ne__(self, a: StringSegment, b: StringSegment) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, b: StringSegment) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class TextStyle(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : TextStyle # 0
    Underline : TextStyle # 1
    Strikethrough : TextStyle # 2

