import typing, clr, abc
from System import Array_1, EventArgs
from Microsoft.Xna.Framework import Game, Rectangle, GameTime
from Microsoft.Xna.Framework.Input import Keys

class CandidateList:
    Candidates : Array_1[str]
    CandidatesPageSize : int
    CandidatesPageStart : int
    CandidatesSelection : int


class CompositionAttributes(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Input : CompositionAttributes # 0
    TargetConverted : CompositionAttributes # 1
    Converted : CompositionAttributes # 2
    TargetNotConverted : CompositionAttributes # 3
    InputError : CompositionAttributes # 4
    FixedConverted : CompositionAttributes # 5


class IMEHandler(abc.ABC):
    @property
    def Candidates(self) -> Array_1[str]: ...
    @property
    def CandidatesPageSize(self) -> int: ...
    @property
    def CandidatesPageStart(self) -> int: ...
    @property
    def CandidatesSelection(self) -> int: ...
    @property
    def Composition(self) -> str: ...
    @property
    def CompositionClause(self) -> str: ...
    @property
    def CompositionCursorPos(self) -> int: ...
    @property
    def CompositionRead(self) -> str: ...
    @property
    def CompositionReadClause(self) -> str: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> bool: ...
    @property
    def GameInstance(self) -> Game: ...
    @GameInstance.setter
    def GameInstance(self, value: Game) -> Game: ...
    @classmethod
    @property
    def ImplInstance(cls) -> IMEHandler: ...
    @classmethod
    @ImplInstance.setter
    def ImplInstance(cls, value: IMEHandler) -> IMEHandler: ...
    @property
    def Result(self) -> str: ...
    @property
    def ResultClause(self) -> str: ...
    @property
    def ResultRead(self) -> str: ...
    @property
    def ResultReadClause(self) -> str: ...
    @property
    def ShowDefaultIMEWindow(self) -> bool: ...
    @ShowDefaultIMEWindow.setter
    def ShowDefaultIMEWindow(self, value: bool) -> bool: ...
    @property
    def VirtualKeyboardHeight(self) -> int: ...
    def GetCompositionAttr(self, charIndex: int) -> CompositionAttributes: ...
    def GetCompositionReadAttr(self, charIndex: int) -> CompositionAttributes: ...
    def OnTextComposition(self, compString: str, cursorPosition: int, candidateList: typing.Optional[CandidateList] = ...) -> None: ...
    @abc.abstractmethod
    def PlatformInitialize(self) -> None: ...
    def SetTextInputRect(self, rect: clr.Reference[Rectangle]) -> None: ...
    @abc.abstractmethod
    def StartTextComposition(self) -> None: ...
    @abc.abstractmethod
    def StopTextComposition(self) -> None: ...
    def Update(self, gameTime: GameTime) -> None: ...
    # Skipped OnTextInput due to it being static, abstract and generic.

    OnTextInput : OnTextInput_MethodGroup
    class OnTextInput_MethodGroup:
        @typing.overload
        def __call__(self, args: TextInputEventArgs) -> None:...
        @typing.overload
        def __call__(self, character: str, key: Keys = ...) -> None:...



class TextInputEventArgs(EventArgs):
    def __init__(self, character: str, key: Keys = ...) -> None: ...
    Character : str
    Key : Keys

