import typing, abc
from System import IDisposable, ReadOnlyMemory_1, ValueTuple_2, ValueTuple_3, ValueTuple_5, Array_1, ReadOnlySpan_1
from System.Text.Json import JsonElement
from Lawn import GameMode, CardPair, SeedType, ZombieType, BackgroundType, MusicTune, ProjectileType
from System.Collections.Generic import List_1, Dictionary_2, HashSet_1
from Sexy import Image

class CreativeLevel(IDisposable):
    def __init__(self) -> None: ...
    mCrc : int
    mLevelId : str
    mVersion : int
    def Dispose(self) -> None: ...
    def Init(self, root: JsonElement) -> None: ...
    def IsValidVersion(self) -> bool: ...
    # Skipped GetComponent due to it being static, abstract and generic.

    GetComponent : GetComponent_MethodGroup
    class GetComponent_MethodGroup:
        def __getitem__(self, t:typing.Type[GetComponent_1_T1]) -> GetComponent_1[GetComponent_1_T1]: ...

        GetComponent_1_T1 = typing.TypeVar('GetComponent_1_T1')
        class GetComponent_1(typing.Generic[GetComponent_1_T1]):
            GetComponent_1_T = CreativeLevel.GetComponent_MethodGroup.GetComponent_1_T1
            def __call__(self) -> GetComponent_1_T:...




class CreativeLevelManager(abc.ABC):
    mError : str
    readStateLock : typing.Any
    @staticmethod
    def GetLevelDefine(gameMode: GameMode) -> CreativeLevel: ...
    @staticmethod
    def GetLevelName(gameMode: GameMode) -> str: ...
    @staticmethod
    def Init() -> None: ...
    @staticmethod
    def IsCreativeMode(gameMode: GameMode) -> bool: ...
    @staticmethod
    def LoadLevel(json: ReadOnlyMemory_1[int], gameMode: GameMode, file: str, levelId: str = ...) -> None: ...
    @staticmethod
    def ReloadDIYLevel() -> str: ...


class CSAutoZombiePoint(IComponent):
    def __init__(self) -> None: ...
    mFlagPointMultiplier : float
    mPointIncrementPerWave : float
    mPointMultiplier : float
    mStartingPoints : int
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSBungeeBlitz(IComponent):
    def __init__(self) -> None: ...
    mShowHugeFlagAdvice : bool
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSColumnPlanting(IComponent):
    def __init__(self) -> None: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSConveyorBelt(IComponent):
    def __init__(self) -> None: ...
    mAllowedPlants : List_1[ValueTuple_2[CardPair, int]]
    mInitCards : List_1[CardPair]
    mPrepareTimeMultiplier : float
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSDefaultPlantOnLawn(IComponent):
    def __init__(self) -> None: ...
    mPlants : List_1[ValueTuple_3[CardPair, int, int]]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSExtendedPoolZombies(IComponent):
    def __init__(self) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> bool: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSFusion(IComponent):
    def __init__(self) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> bool: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSGlove(IComponent):
    def __init__(self) -> None: ...
    @property
    def Cooldown(self) -> typing.Optional[int]: ...
    @Cooldown.setter
    def Cooldown(self, value: typing.Optional[int]) -> typing.Optional[int]: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> bool: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSInvisibleZombie(IComponent):
    def __init__(self) -> None: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSIZombieLevel(IComponent):
    def __init__(self) -> None: ...
    mLimit : int
    mPlantInRow : List_1[ValueTuple_3[SeedType, int, int]]
    mPlantInSquare : List_1[ValueTuple_3[SeedType, int, int]]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSLevelProperty(IDisposable, IComponent):
    def __init__(self) -> None: ...
    mAllowedZombies : List_1[ZombieType]
    mBackground : BackgroundType
    mChineseName : str
    mEasyUpgrade : bool
    mEnglishName : str
    mIcon : int
    mIconImage : Image
    mInitPlantColumn : int
    mMaxPlainZombiesPerFlag : int
    mMusicType : typing.Optional[MusicTune]
    mName : str
    mNumWaves : int
    mSpawnFlagZombie : bool
    mStartingSun : int
    mStartingTime : int
    mStartingWave : int
    mWavesPerFlag : int
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Dispose(self) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSManualZombieCountDown(IComponent):
    def __init__(self) -> None: ...
    mInfo : Dictionary_2[int, ValueTuple_2[int, int]]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSManualZombiePoint(IComponent):
    def __init__(self) -> None: ...
    mDensity : List_1[int]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSMustHaveZombie(IComponent):
    def __init__(self) -> None: ...
    mZombies : Dictionary_2[int, List_1[ZombieType]]
    mZombiesInRow : Dictionary_2[int, List_1[ValueTuple_2[ZombieType, int]]]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSOverridePlantProperty(IComponent):
    def __init__(self) -> None: ...
    mProperties : Dictionary_2[SeedType, CSOverridePlantProperty.Info]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...

    class Info:
        def __init__(self) -> None: ...
        mLaunchRate : typing.Optional[int]
        mPlantHealth : typing.Optional[int]
        mRefreshTime : typing.Optional[int]
        mSeedCost : typing.Optional[int]
        def Init(self, item: JsonElement) -> None: ...



class CSOverrideProjectileProperty(IComponent):
    def __init__(self) -> None: ...
    mAllowZombiePeaAttackFlowerPot : typing.Optional[bool]
    mProperties : Dictionary_2[ProjectileType, CSOverrideProjectileProperty.Info]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...

    class Info:
        def __init__(self) -> None: ...
        mDamage : typing.Optional[int]
        def Init(self, item: JsonElement) -> None: ...



class CSOverrideZombieProperty(IComponent):
    def __init__(self) -> None: ...
    mProperties : Dictionary_2[ZombieType, CSOverrideZombieProperty.Info]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...

    class Info:
        def __init__(self) -> None: ...
        mBodyHealth : typing.Optional[int]
        mCanGoInPool : typing.Optional[bool]
        mCanGoOnHighGround : typing.Optional[bool]
        mFirstAllowedWave : typing.Optional[int]
        mFlyingHealth : typing.Optional[int]
        mHelmHealth : typing.Optional[int]
        mPickWeight : typing.Optional[int]
        mScaleHealth : typing.Optional[float]
        mScaleZombie : typing.Optional[float]
        mShieldHealth : typing.Optional[int]
        mZombieValue : typing.Optional[int]
        def Init(self, item: JsonElement) -> None: ...



class CSPause(IComponent):
    def __init__(self) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> bool: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSPlantSkill(IComponent):
    def __init__(self) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> bool: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSRainingSeeds(IComponent):
    def __init__(self) -> None: ...
    mAllowedPlants : List_1[ValueTuple_2[SeedType, int]]
    mMaxPrepareTime : int
    mMinPrepareTime : int
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSSeedBank(IComponent):
    def __init__(self) -> None: ...
    mBannedCards : HashSet_1[SeedType]
    mLockedCards : List_1[CardPair]
    mNumPackets : int
    mReverseBanning : bool
    mUserChoose : bool
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSShovel(IComponent):
    def __init__(self) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> bool: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSSlotMachineLevel(IComponent):
    def __init__(self) -> None: ...
    mAllowedPlants : List_1[ValueTuple_5[SeedType, int, int, int, int]]
    mTargetSunCount : int
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSSpawnFog(IComponent):
    def __init__(self) -> None: ...
    mColumn : int
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSSpawnGraveStone(IComponent):
    def __init__(self) -> None: ...
    mAllowGraveStoneOnDirt : bool
    mCountPerColumn : Array_1[int]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSSpawnLadder(IComponent):
    def __init__(self) -> None: ...
    mLadders : List_1[ValueTuple_3[int, int, int]]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSSpawnPortal(IComponent):
    def __init__(self) -> None: ...
    mFixPlantAttackView : bool
    mFixSpawnZombieView : bool
    mPortals : List_1[ValueTuple_3[int, int, int]]
    mRandomPortalTime : int
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSSpawnSkySun(IComponent):
    def __init__(self) -> None: ...
    mIncrementPerSun : int
    mMaxTime : int
    mMinTime : int
    mRandomRangeTime : int
    mSpawnFromSky : bool
    mSunType : int
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSSpeed(IComponent):
    def __init__(self) -> None: ...
    mExtraUpdateTimes : int
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSSurvivalLevel(IComponent):
    def __init__(self) -> None: ...
    mAcceleratedPricing : bool
    mEndless : bool
    mMaxRandomZombieTypeCount : int
    mMustHaveZombieGroup : List_1[List_1[ValueTuple_2[ZombieType, int]]]
    mStages : int
    mZombies : Dictionary_2[ZombieType, CSSurvivalLevel.Info]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...

    class Info:
        def __init__(self) -> None: ...
        mStartingWave : typing.Optional[int]
        mStartWeightModifyingWave : int
        mUseDefault : bool
        mValue : typing.Optional[int]
        mWeight : typing.Optional[int]
        mWeightCap : typing.Optional[int]
        mWeightModifierPerWave : typing.Optional[float]
        def Init(self, item: JsonElement) -> None: ...



class CSTrashcan(IComponent):
    def __init__(self) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> bool: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSVaseLevel(IComponent):
    def __init__(self) -> None: ...
    mMaxColumn : int
    mMinColumn : int
    mNumPlantVases : int
    mNumZombieVases : int
    mPlantVases : List_1[ValueTuple_2[SeedType, int]]
    mZombieVases : List_1[ValueTuple_2[ZombieType, int]]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSWallnutBowlingLevel(IComponent):
    def __init__(self) -> None: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSWeather(IComponent):
    def __init__(self) -> None: ...
    mHasRain : bool
    mHasStorm : bool
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...


class CSWhackAZombieLevel(IComponent):
    def __init__(self) -> None: ...
    mDoubleChance : Array_1[int]
    mInitGraveStoneCount : int
    mMinGraveStoneCount : int
    mSpawnInterval : int
    mTripleChance : Array_1[int]
    mZombies : Dictionary_2[ZombieType, CSWhackAZombieLevel.Info]
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    def Check(self, level: CreativeLevel) -> None: ...
    def Init(self, root: JsonElement) -> None: ...

    class Info:
        def __init__(self) -> None: ...
        mSpawnAtTriple : bool
        mSpawnOnLastWave : bool
        mWeights : Array_1[int]
        def Init(self, item: JsonElement) -> None: ...



class IComponent(typing.Protocol):
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    @abc.abstractmethod
    def Check(self, level: CreativeLevel) -> None: ...
    @abc.abstractmethod
    def Init(self, root: JsonElement) -> None: ...


class SecretCrc:
    @property
    def Value(self) -> int: ...
    @Value.setter
    def Value(self, value: int) -> int: ...
    def Init(self) -> None: ...
    def Update(self, data: ReadOnlySpan_1[int]) -> None: ...

