import typing, clr, abc
from Microsoft.Scripting.Runtime import Scope, IMembersList, LanguageContext, ScriptDomainManager, ContextId, DynamicDelegateCreator, DynamicOperations, ScopeExtension, DynamicStackFrame, IExpressionSerializable, ISlice
from System.Collections.Generic import ICollection_1, IEnumerator_1, IEnumerable_1, IList_1, IDictionary_2, IEqualityComparer_1, KeyValuePair_2, IReadOnlyList_1
from System.Collections import IEnumerable, ICollection, IStructuralEquatable, IEnumerator, IEqualityComparer, IDictionary, IList
from System import Array, Array_1, Guid, Version, Action, Exception, Action_1, Delegate, Func_3, Func_1
from IronPython.Runtime.Types import PythonType, NotImplementedType
from System.Text import Encoding
from System.Threading import Thread
from Microsoft.Scripting import LanguageOptions, ScriptCode, SourceUnit, CompilerOptions, ErrorSink, SourceCodeKind, SourceCodeReader
from System.Dynamic import BinaryOperationBinder, ConvertBinder, CreateInstanceBinder, CallInfo, DeleteMemberBinder, GetMemberBinder, InvokeBinder, SetMemberBinder, UnaryOperationBinder, DynamicMetaObjectBinder, DynamicMetaObject, IDynamicMetaObjectProvider
from System.Linq.Expressions import ExpressionType, Expression
from System.CodeDom import CodeObject
from System.IO import Stream
from System.Numerics import BigInteger

class CodeContext:
    def __init__(self, dict: PythonDictionary, moduleContext: ModuleContext) -> None: ...
    @property
    def GlobalScope(self) -> Scope: ...
    @property
    def LanguageContext(self) -> PythonContext: ...
    @property
    def ModuleContext(self) -> ModuleContext: ...


class DictionaryItemView(ICollection_1[typing.Any], ICodeFormattable):
    def __reduce__(self, context: CodeContext) -> typing.Any: ...
    def __repr__(self, context: CodeContext) -> str: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetEnumerator(self) -> IEnumerator_1[typing.Any]: ...
    def GetHashCode(self) -> int: ...
    def isdisjoint(self, other: IEnumerable) -> bool: ...
    @typing.overload
    def __and__(self, x: DictionaryItemView, y: IEnumerable) -> SetCollection: ...
    @typing.overload
    def __and__(self, y: IEnumerable, x: DictionaryItemView) -> SetCollection: ...
    @typing.overload
    def __or__(self, x: DictionaryItemView, y: IEnumerable) -> SetCollection: ...
    @typing.overload
    def __or__(self, y: IEnumerable, x: DictionaryItemView) -> SetCollection: ...
    @typing.overload
    def __eq__(self, x: DictionaryItemView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __eq__(self, x: DictionaryItemView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __eq__(self, x: DictionaryItemView, y: SetCollection) -> bool: ...
    @typing.overload
    def __eq__(self, x: DictionaryItemView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __xor__(self, x: DictionaryItemView, y: IEnumerable) -> SetCollection: ...
    @typing.overload
    def __xor__(self, y: IEnumerable, x: DictionaryItemView) -> SetCollection: ...
    @typing.overload
    def __gt__(self, x: DictionaryItemView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __gt__(self, x: DictionaryItemView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __gt__(self, x: DictionaryItemView, y: SetCollection) -> bool: ...
    @typing.overload
    def __gt__(self, x: DictionaryItemView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __ge__(self, x: DictionaryItemView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __ge__(self, x: DictionaryItemView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __ge__(self, x: DictionaryItemView, y: SetCollection) -> bool: ...
    @typing.overload
    def __ge__(self, x: DictionaryItemView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __ne__(self, x: DictionaryItemView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __ne__(self, x: DictionaryItemView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __ne__(self, x: DictionaryItemView, y: SetCollection) -> bool: ...
    @typing.overload
    def __ne__(self, x: DictionaryItemView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __lt__(self, x: DictionaryItemView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __lt__(self, x: DictionaryItemView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __lt__(self, x: DictionaryItemView, y: SetCollection) -> bool: ...
    @typing.overload
    def __lt__(self, x: DictionaryItemView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __le__(self, x: DictionaryItemView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __le__(self, x: DictionaryItemView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __le__(self, x: DictionaryItemView, y: SetCollection) -> bool: ...
    @typing.overload
    def __le__(self, x: DictionaryItemView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __sub__(self, x: DictionaryItemView, y: IEnumerable) -> SetCollection: ...
    @typing.overload
    def __sub__(self, y: IEnumerable, x: DictionaryItemView) -> SetCollection: ...


class DictionaryKeyView(ICollection_1[typing.Any], ICollection, ICodeFormattable):
    def __reduce__(self, context: CodeContext) -> typing.Any: ...
    def __repr__(self, context: CodeContext) -> str: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetEnumerator(self) -> IEnumerator_1[typing.Any]: ...
    def GetHashCode(self) -> int: ...
    def isdisjoint(self, other: IEnumerable) -> bool: ...
    @typing.overload
    def __and__(self, x: DictionaryKeyView, y: IEnumerable) -> SetCollection: ...
    @typing.overload
    def __and__(self, y: IEnumerable, x: DictionaryKeyView) -> SetCollection: ...
    @typing.overload
    def __or__(self, x: DictionaryKeyView, y: IEnumerable) -> SetCollection: ...
    @typing.overload
    def __or__(self, y: IEnumerable, x: DictionaryKeyView) -> SetCollection: ...
    @typing.overload
    def __eq__(self, x: DictionaryKeyView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __eq__(self, x: DictionaryKeyView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __eq__(self, x: DictionaryKeyView, y: SetCollection) -> bool: ...
    @typing.overload
    def __eq__(self, x: DictionaryKeyView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __xor__(self, x: DictionaryKeyView, y: IEnumerable) -> SetCollection: ...
    @typing.overload
    def __xor__(self, y: IEnumerable, x: DictionaryKeyView) -> SetCollection: ...
    @typing.overload
    def __gt__(self, x: DictionaryKeyView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __gt__(self, x: DictionaryKeyView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __gt__(self, x: DictionaryKeyView, y: SetCollection) -> bool: ...
    @typing.overload
    def __gt__(self, x: DictionaryKeyView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __ge__(self, x: DictionaryKeyView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __ge__(self, x: DictionaryKeyView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __ge__(self, x: DictionaryKeyView, y: SetCollection) -> bool: ...
    @typing.overload
    def __ge__(self, x: DictionaryKeyView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __ne__(self, x: DictionaryKeyView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __ne__(self, x: DictionaryKeyView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __ne__(self, x: DictionaryKeyView, y: SetCollection) -> bool: ...
    @typing.overload
    def __ne__(self, x: DictionaryKeyView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __lt__(self, x: DictionaryKeyView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __lt__(self, x: DictionaryKeyView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __lt__(self, x: DictionaryKeyView, y: SetCollection) -> bool: ...
    @typing.overload
    def __lt__(self, x: DictionaryKeyView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __le__(self, x: DictionaryKeyView, y: DictionaryKeyView) -> bool: ...
    @typing.overload
    def __le__(self, x: DictionaryKeyView, y: DictionaryItemView) -> bool: ...
    @typing.overload
    def __le__(self, x: DictionaryKeyView, y: SetCollection) -> bool: ...
    @typing.overload
    def __le__(self, x: DictionaryKeyView, y: FrozenSetCollection) -> bool: ...
    @typing.overload
    def __sub__(self, x: DictionaryKeyView, y: IEnumerable) -> SetCollection: ...
    @typing.overload
    def __sub__(self, y: IEnumerable, x: DictionaryKeyView) -> SetCollection: ...


class DictionaryValueView(ICollection_1[typing.Any], ICollection, ICodeFormattable):
    def __reduce__(self, context: CodeContext) -> typing.Any: ...
    def __repr__(self, context: CodeContext) -> str: ...


class FrozenSetCollection(ICollection, IEnumerable_1[typing.Any], IWeakReferenceable, ICodeFormattable, IStructuralEquatable):
    @property
    def Count(self) -> int: ...
    def __contains__(self, item: typing.Any) -> bool: ...
    def __eq__(self, other: typing.Any) -> typing.Any: ...
    def __init__(self, o: Array_1[typing.Any]) -> None: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> typing.Any: ...
    def __reduce__(self, context: CodeContext) -> PythonTuple: ...
    def __repr__(self, context: CodeContext) -> str: ...
    def copy(self) -> FrozenSetCollection: ...
    @typing.overload
    def __and__(self, x: FrozenSetCollection, y: FrozenSetCollection) -> FrozenSetCollection: ...
    @typing.overload
    def __and__(self, x: FrozenSetCollection, y: SetCollection) -> FrozenSetCollection: ...
    @typing.overload
    def __or__(self, x: FrozenSetCollection, y: FrozenSetCollection) -> FrozenSetCollection: ...
    @typing.overload
    def __or__(self, x: FrozenSetCollection, y: SetCollection) -> FrozenSetCollection: ...
    @typing.overload
    def __xor__(self, x: FrozenSetCollection, y: FrozenSetCollection) -> FrozenSetCollection: ...
    @typing.overload
    def __xor__(self, x: FrozenSetCollection, y: SetCollection) -> FrozenSetCollection: ...
    def __gt__(self, self: FrozenSetCollection, other: typing.Any) -> typing.Any: ...
    def __ge__(self, self: FrozenSetCollection, other: typing.Any) -> typing.Any: ...
    def __lt__(self, self: FrozenSetCollection, other: typing.Any) -> typing.Any: ...
    def __le__(self, self: FrozenSetCollection, other: typing.Any) -> typing.Any: ...
    @typing.overload
    def __sub__(self, x: FrozenSetCollection, y: FrozenSetCollection) -> FrozenSetCollection: ...
    @typing.overload
    def __sub__(self, x: FrozenSetCollection, y: SetCollection) -> FrozenSetCollection: ...
    # Skipped __new__ due to it being static, abstract and generic.

    __new__ : __new___MethodGroup
    class __new___MethodGroup:
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, set: typing.Any) -> FrozenSetCollection:...

    # Skipped difference due to it being static, abstract and generic.

    difference : difference_MethodGroup
    class difference_MethodGroup:
        @typing.overload
        def __call__(self) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, sets: Array_1[typing.Any]) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, set: SetCollection) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> FrozenSetCollection:...

    # Skipped intersection due to it being static, abstract and generic.

    intersection : intersection_MethodGroup
    class intersection_MethodGroup:
        @typing.overload
        def __call__(self) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, sets: Array_1[typing.Any]) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, set: SetCollection) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> FrozenSetCollection:...

    # Skipped isdisjoint due to it being static, abstract and generic.

    isdisjoint : isdisjoint_MethodGroup
    class isdisjoint_MethodGroup:
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: SetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: typing.Any) -> bool:...

    # Skipped issubset due to it being static, abstract and generic.

    issubset : issubset_MethodGroup
    class issubset_MethodGroup:
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: SetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: typing.Any) -> bool:...

    # Skipped issuperset due to it being static, abstract and generic.

    issuperset : issuperset_MethodGroup
    class issuperset_MethodGroup:
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: SetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: typing.Any) -> bool:...

    # Skipped symmetric_difference due to it being static, abstract and generic.

    symmetric_difference : symmetric_difference_MethodGroup
    class symmetric_difference_MethodGroup:
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, set: SetCollection) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> FrozenSetCollection:...

    # Skipped union due to it being static, abstract and generic.

    union : union_MethodGroup
    class union_MethodGroup:
        @typing.overload
        def __call__(self) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, sets: Array_1[typing.Any]) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, set: SetCollection) -> FrozenSetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> FrozenSetCollection:...



class ICodeFormattable(typing.Protocol):
    @abc.abstractmethod
    def __repr__(self, context: CodeContext) -> str: ...


class Index:
    def __init__(self, value: typing.Any) -> None: ...


class IPythonMembersList(IMembersList, typing.Protocol):
    @abc.abstractmethod
    def GetMemberNames(self, context: CodeContext) -> IList_1[typing.Any]: ...


class IReversible(typing.Protocol):
    @abc.abstractmethod
    def __reversed__(self) -> IEnumerator: ...


class IWeakReferenceable(typing.Protocol):
    @abc.abstractmethod
    def GetWeakRef(self) -> WeakRefTracker: ...
    @abc.abstractmethod
    def SetFinalizer(self, value: WeakRefTracker) -> None: ...
    @abc.abstractmethod
    def SetWeakRef(self, value: WeakRefTracker) -> bool: ...


class IWeakReferenceableByProxy(typing.Protocol):
    @abc.abstractmethod
    def GetWeakRefProxy(self, context: PythonContext) -> IWeakReferenceable: ...


class ModuleContext:
    @typing.overload
    def __init__(self, globals: PythonDictionary, creatingContext: PythonContext) -> None: ...
    @typing.overload
    def __init__(self, module: PythonModule, creatingContext: PythonContext) -> None: ...
    @property
    def Context(self) -> PythonContext: ...
    @property
    def Features(self) -> ModuleOptions: ...
    @Features.setter
    def Features(self, value: ModuleOptions) -> ModuleOptions: ...
    @property
    def GlobalContext(self) -> CodeContext: ...
    @property
    def Globals(self) -> PythonDictionary: ...
    @property
    def GlobalScope(self) -> Scope: ...
    @property
    def Module(self) -> PythonModule: ...
    @property
    def ShowCls(self) -> bool: ...
    @ShowCls.setter
    def ShowCls(self, value: bool) -> bool: ...


class ModuleOptions(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : ModuleOptions # 0
    ShowClsMethods : ModuleOptions # 2
    Optimized : ModuleOptions # 4
    Initialize : ModuleOptions # 8
    NoBuiltins : ModuleOptions # 64
    ModuleBuiltins : ModuleOptions # 128
    ExecOrEvalCode : ModuleOptions # 256
    SkipFirstLine : ModuleOptions # 512
    Interpret : ModuleOptions # 4096
    Verbatim : ModuleOptions # 16384
    LightThrow : ModuleOptions # 32768
    GeneratorStop : ModuleOptions # 65536


class PythonContext(LanguageContext):
    def __init__(self, manager: ScriptDomainManager, options: IDictionary_2[str, typing.Any]) -> None: ...
    @property
    def BuiltinModuleDict(self) -> PythonDictionary: ...
    @BuiltinModuleDict.setter
    def BuiltinModuleDict(self, value: PythonDictionary) -> PythonDictionary: ...
    @property
    def BuiltinModuleInstance(self) -> PythonModule: ...
    @BuiltinModuleInstance.setter
    def BuiltinModuleInstance(self, value: PythonModule) -> PythonModule: ...
    @property
    def CanCreateSourceCode(self) -> bool: ...
    @property
    def ClrModule(self) -> PythonModule: ...
    @property
    def ContextId(self) -> ContextId: ...
    @property
    def DefaultEncoding(self) -> Encoding: ...
    @property
    def DelegateCreator(self) -> DynamicDelegateCreator: ...
    @property
    def DomainManager(self) -> ScriptDomainManager: ...
    @property
    def EqualityComparer(self) -> IEqualityComparer_1[typing.Any]: ...
    @property
    def EqualityComparerNonGeneric(self) -> IEqualityComparer: ...
    @property
    def LanguageGuid(self) -> Guid: ...
    @property
    def LanguageVersion(self) -> Version: ...
    @property
    def MainThread(self) -> Thread: ...
    @MainThread.setter
    def MainThread(self, value: Thread) -> Thread: ...
    @property
    def Operations(self) -> DynamicOperations: ...
    @property
    def Options(self) -> LanguageOptions: ...
    @property
    def RecursionLimit(self) -> int: ...
    @RecursionLimit.setter
    def RecursionLimit(self, value: int) -> int: ...
    @property
    def SystemState(self) -> PythonModule: ...
    @property
    def VendorGuid(self) -> Guid: ...
    def CompileSourceCode(self, sourceUnit: SourceUnit, options: CompilerOptions, errorSink: ErrorSink) -> ScriptCode: ...
    def CreateBinaryOperationBinder(self, operation: ExpressionType) -> BinaryOperationBinder: ...
    def CreateConvertBinder(self, toType: typing.Type[typing.Any], explicitCast: typing.Optional[bool]) -> ConvertBinder: ...
    def CreateCreateBinder(self, callInfo: CallInfo) -> CreateInstanceBinder: ...
    def CreateDeleteMemberBinder(self, name: str, ignoreCase: bool) -> DeleteMemberBinder: ...
    def CreateGetMemberBinder(self, name: str, ignoreCase: bool) -> GetMemberBinder: ...
    def CreateInvokeBinder(self, callInfo: CallInfo) -> InvokeBinder: ...
    def CreateScopeExtension(self, scope: Scope) -> ScopeExtension: ...
    def CreateSetMemberBinder(self, name: str, ignoreCase: bool) -> SetMemberBinder: ...
    def CreateUnaryOperationBinder(self, operation: ExpressionType) -> UnaryOperationBinder: ...
    def DispatchCommand(self, command: Action) -> None: ...
    def EnsureEncodings(self) -> None: ...
    def ExecuteProgram(self, program: SourceUnit) -> int: ...
    def FormatException(self, exception: Exception) -> str: ...
    def FormatObject(self, operations: DynamicOperations, obj: typing.Any) -> str: ...
    def GenerateSourceCode(self, codeDom: CodeObject, path: str, kind: SourceCodeKind) -> SourceUnit: ...
    def GetCallSignatures(self, obj: typing.Any) -> IList_1[str]: ...
    @staticmethod
    def GetCodeContext(action: DynamicMetaObjectBinder) -> Expression: ...
    @staticmethod
    def GetCodeContextMO(action: DynamicMetaObjectBinder) -> DynamicMetaObject: ...
    @staticmethod
    def GetCodeContextMOCls(action: DynamicMetaObjectBinder) -> DynamicMetaObject: ...
    def GetCommandDispatcher(self) -> Action_1[Action]: ...
    def GetDefaultEncodingName(self) -> str: ...
    def GetDocumentation(self, obj: typing.Any) -> str: ...
    def GetExceptionMessage(self, exception: Exception, message: clr.Reference[str], typeName: clr.Reference[str]) -> None: ...
    @staticmethod
    def GetIronPythonAssembly(baseName: str) -> str: ...
    def GetMemberNames(self, obj: typing.Any) -> IList_1[str]: ...
    def GetModuleState(self, key: typing.Any) -> typing.Any: ...
    @staticmethod
    def GetPythonContext(action: DynamicMetaObjectBinder) -> PythonContext: ...
    def GetScope(self, path: str) -> Scope: ...
    def GetSearchPaths(self) -> ICollection_1[str]: ...
    def GetSetCommandDispatcher(self, newDispatcher: Action_1[Action]) -> Action_1[Action]: ...
    def GetSetModuleState(self, key: typing.Any, value: typing.Any) -> typing.Any: ...
    def GetSourceReader(self, stream: Stream, defaultEncoding: Encoding, path: str) -> SourceCodeReader: ...
    def GetStackFrames(self, exception: Exception) -> IList_1[DynamicStackFrame]: ...
    def GetWarningsModule(self) -> typing.Any: ...
    def HasModuleState(self, key: typing.Any) -> bool: ...
    def InitializeModule(self, fileName: str, moduleContext: ModuleContext, scriptCode: ScriptCode, options: ModuleOptions) -> PythonModule: ...
    def IsCallable(self, obj: typing.Any) -> bool: ...
    def LoadCompiledCode(self, method: Delegate, path: str, customData: str) -> ScriptCode: ...
    def PublishModule(self, name: str, module: PythonModule) -> None: ...
    def ScopeSetVariable(self, scope: Scope, name: str, value: typing.Any) -> None: ...
    def ScopeTryGetVariable(self, scope: Scope, name: str, value: clr.Reference[typing.Any]) -> bool: ...
    def SetModuleState(self, key: typing.Any, value: typing.Any) -> None: ...
    def SetSearchPaths(self, paths: ICollection_1[str]) -> None: ...
    def Shutdown(self) -> None: ...
    # Skipped CompileModule due to it being static, abstract and generic.

    CompileModule : CompileModule_MethodGroup
    class CompileModule_MethodGroup:
        @typing.overload
        def __call__(self, fileName: str, moduleName: str, sourceCode: SourceUnit, options: ModuleOptions) -> PythonModule:...
        @typing.overload
        def __call__(self, fileName: str, moduleName: str, sourceCode: SourceUnit, options: ModuleOptions, scriptCode: clr.Reference[ScriptCode]) -> PythonModule:...

    # Skipped EnsureModuleException due to it being static, abstract and generic.

    EnsureModuleException : EnsureModuleException_MethodGroup
    class EnsureModuleException_MethodGroup:
        @typing.overload
        def __call__(self, key: typing.Any, dict: PythonDictionary, name: str, module: str) -> PythonType:...
        @typing.overload
        def __call__(self, key: typing.Any, baseType: PythonType, dict: PythonDictionary, name: str, module: str) -> PythonType:...
        @typing.overload
        def __call__(self, key: typing.Any, baseTypes: Array_1[PythonType], underlyingType: typing.Type[typing.Any], dict: PythonDictionary, name: str, module: str) -> PythonType:...
        @typing.overload
        def __call__(self, key: typing.Any, baseType: PythonType, underlyingType: typing.Type[typing.Any], dict: PythonDictionary, name: str, module: str, exceptionMaker: Func_3[str, Exception, Exception]) -> PythonType:...
        @typing.overload
        def __call__(self, key: typing.Any, baseType: PythonType, underlyingType: typing.Type[typing.Any], dict: PythonDictionary, name: str, module: str, documentation: str, exceptionMaker: Func_3[str, Exception, Exception]) -> PythonType:...

    # Skipped GetCompilerOptions due to it being static, abstract and generic.

    GetCompilerOptions : GetCompilerOptions_MethodGroup
    class GetCompilerOptions_MethodGroup:
        @typing.overload
        def __call__(self) -> CompilerOptions:...
        @typing.overload
        def __call__(self, scope: Scope) -> CompilerOptions:...

    # Skipped GetOrCreateModuleState due to it being static, abstract and generic.

    GetOrCreateModuleState : GetOrCreateModuleState_MethodGroup
    class GetOrCreateModuleState_MethodGroup:
        def __getitem__(self, t:typing.Type[GetOrCreateModuleState_1_T1]) -> GetOrCreateModuleState_1[GetOrCreateModuleState_1_T1]: ...

        GetOrCreateModuleState_1_T1 = typing.TypeVar('GetOrCreateModuleState_1_T1')
        class GetOrCreateModuleState_1(typing.Generic[GetOrCreateModuleState_1_T1]):
            GetOrCreateModuleState_1_T = PythonContext.GetOrCreateModuleState_MethodGroup.GetOrCreateModuleState_1_T1
            def __call__(self, key: typing.Any, value: Func_1[GetOrCreateModuleState_1_T]) -> GetOrCreateModuleState_1_T:...


    # Skipped GetService due to it being static, abstract and generic.

    GetService : GetService_MethodGroup
    class GetService_MethodGroup:
        def __getitem__(self, t:typing.Type[GetService_1_T1]) -> GetService_1[GetService_1_T1]: ...

        GetService_1_T1 = typing.TypeVar('GetService_1_T1')
        class GetService_1(typing.Generic[GetService_1_T1]):
            GetService_1_TService = PythonContext.GetService_MethodGroup.GetService_1_T1
            def __call__(self, args: Array_1[typing.Any]) -> GetService_1_TService:...


    # Skipped ScopeGetVariable due to it being static, abstract and generic.

    ScopeGetVariable : ScopeGetVariable_MethodGroup
    class ScopeGetVariable_MethodGroup:
        def __getitem__(self, t:typing.Type[ScopeGetVariable_1_T1]) -> ScopeGetVariable_1[ScopeGetVariable_1_T1]: ...

        ScopeGetVariable_1_T1 = typing.TypeVar('ScopeGetVariable_1_T1')
        class ScopeGetVariable_1(typing.Generic[ScopeGetVariable_1_T1]):
            ScopeGetVariable_1_T = PythonContext.ScopeGetVariable_MethodGroup.ScopeGetVariable_1_T1
            def __call__(self, scope: Scope, name: str) -> ScopeGetVariable_1_T:...

        def __call__(self, scope: Scope, name: str) -> typing.Any:...



class PythonDictionary(IDictionary_2[typing.Any, typing.Any], IDictionary, IStructuralEquatable, ICodeFormattable):
    def __init__(self) -> None: ...
    __hash__ : typing.Any
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> typing.Any: ...
    @Item.setter
    def Item(self, value: typing.Any) -> typing.Any: ...
    @property
    def Item(self) -> typing.Any: ...
    @Item.setter
    def Item(self, value: typing.Any) -> typing.Any: ...
    @property
    def Keys(self) -> ICollection_1[typing.Any]: ...
    @property
    def Values(self) -> ICollection_1[typing.Any]: ...
    def __contains__(self, key: typing.Any) -> bool: ...
    def __eq__(self, context: CodeContext, other: typing.Any) -> typing.Any: ...
    def __ge__(self, context: CodeContext, other: typing.Any) -> NotImplementedType: ...
    def __gt__(self, context: CodeContext, other: typing.Any) -> NotImplementedType: ...
    def __iter__(self) -> typing.Any: ...
    def __le__(self, context: CodeContext, other: typing.Any) -> NotImplementedType: ...
    def __len__(self) -> int: ...
    def __lt__(self, context: CodeContext, other: typing.Any) -> NotImplementedType: ...
    def __ne__(self, context: CodeContext, other: typing.Any) -> typing.Any: ...
    def __repr__(self, context: CodeContext) -> str: ...
    def clear(self) -> None: ...
    def Clear(self) -> None: ...
    def ContainsKey(self, key: typing.Any) -> bool: ...
    def copy(self, context: CodeContext) -> PythonDictionary: ...
    def CopyTo(self, array: Array_1[KeyValuePair_2[typing.Any, typing.Any]], arrayIndex: int) -> None: ...
    def GetEnumerator(self) -> IEnumerator_1[KeyValuePair_2[typing.Any, typing.Any]]: ...
    def items(self) -> DictionaryItemView: ...
    def keys(self) -> DictionaryKeyView: ...
    def popitem(self) -> PythonTuple: ...
    def RemoveDirect(self, key: typing.Any) -> bool: ...
    def TryGetValue(self, key: typing.Any, value: clr.Reference[typing.Any]) -> bool: ...
    def values(self) -> DictionaryValueView: ...
    # Skipped __delitem__ due to it being static, abstract and generic.

    __delitem__ : __delitem___MethodGroup
    class __delitem___MethodGroup:
        @typing.overload
        def __call__(self, key: Array_1[typing.Any]) -> None:...
        @typing.overload
        def __call__(self, key: typing.Any) -> None:...

    # Skipped __init__ due to it being static, abstract and generic.

    __init__ : __init___MethodGroup
    class __init___MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, context: CodeContext, kwArgs: IDictionary_2[typing.Any, typing.Any]) -> None:...
        @typing.overload
        def __call__(self, context: CodeContext, oø: typing.Any) -> None:...
        @typing.overload
        def __call__(self, context: CodeContext, oø: typing.Any, kwArgs: IDictionary_2[typing.Any, typing.Any]) -> None:...

    # Skipped Add due to it being static, abstract and generic.

    Add : Add_MethodGroup
    class Add_MethodGroup:
        @typing.overload
        def __call__(self, item: KeyValuePair_2[typing.Any, typing.Any]) -> None:...
        @typing.overload
        def __call__(self, key: typing.Any, value: typing.Any) -> None:...

    # Skipped Contains due to it being static, abstract and generic.

    Contains : Contains_MethodGroup
    class Contains_MethodGroup:
        @typing.overload
        def __call__(self, item: KeyValuePair_2[typing.Any, typing.Any]) -> bool:...
        @typing.overload
        def __call__(self, key: typing.Any) -> bool:...

    # Skipped fromkeys due to it being static, abstract and generic.

    fromkeys : fromkeys_MethodGroup
    class fromkeys_MethodGroup:
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, seq: typing.Any) -> typing.Any:...
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, seq: typing.Any, value: typing.Any) -> typing.Any:...

    # Skipped get due to it being static, abstract and generic.

    get : get_MethodGroup
    class get_MethodGroup:
        @typing.overload
        def __call__(self, key: typing.Any) -> typing.Any:...
        @typing.overload
        def __call__(self, key: typing.Any, defaultValue: typing.Any) -> typing.Any:...

    # Skipped pop due to it being static, abstract and generic.

    pop : pop_MethodGroup
    class pop_MethodGroup:
        @typing.overload
        def __call__(self, key: typing.Any) -> typing.Any:...
        @typing.overload
        def __call__(self, key: typing.Any, defaultValue: typing.Any) -> typing.Any:...

    # Skipped Remove due to it being static, abstract and generic.

    Remove : Remove_MethodGroup
    class Remove_MethodGroup:
        @typing.overload
        def __call__(self, item: KeyValuePair_2[typing.Any, typing.Any]) -> bool:...
        @typing.overload
        def __call__(self, key: typing.Any) -> bool:...

    # Skipped setdefault due to it being static, abstract and generic.

    setdefault : setdefault_MethodGroup
    class setdefault_MethodGroup:
        @typing.overload
        def __call__(self, key: typing.Any) -> typing.Any:...
        @typing.overload
        def __call__(self, key: typing.Any, defaultValue: typing.Any) -> typing.Any:...

    # Skipped update due to it being static, abstract and generic.

    update : update_MethodGroup
    class update_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, context: CodeContext, otherø: IDictionary_2[typing.Any, typing.Any]) -> None:...
        @typing.overload
        def __call__(self, context: CodeContext, otherø: typing.Any) -> None:...
        @typing.overload
        def __call__(self, context: CodeContext, otherø: typing.Any, otherArgsø: IDictionary_2[typing.Any, typing.Any]) -> None:...



class PythonList(IReadOnlyList_1[typing.Any], IList_1[typing.Any], IList, IStructuralEquatable, IReversible, ICodeFormattable):
    def __init__(self) -> None: ...
    __hash__ : typing.Any
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> typing.Any: ...
    @Item.setter
    def Item(self, value: typing.Any) -> typing.Any: ...
    @property
    def Item(self) -> typing.Any: ...
    @Item.setter
    def Item(self, value: typing.Any) -> typing.Any: ...
    @property
    def Item(self) -> typing.Any: ...
    @Item.setter
    def Item(self, value: typing.Any) -> typing.Any: ...
    @property
    def Item(self) -> typing.Any: ...
    @Item.setter
    def Item(self, value: typing.Any) -> typing.Any: ...
    def __contains__(self, value: typing.Any) -> bool: ...
    def __iter__(self) -> IEnumerator: ...
    def __len__(self) -> int: ...
    def __repr__(self, context: CodeContext) -> str: ...
    def __reversed__(self) -> IEnumerator: ...
    def Add(self, value: typing.Any) -> int: ...
    def append(self, item: typing.Any) -> None: ...
    def clear(self) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, value: typing.Any) -> bool: ...
    def copy(self) -> PythonList: ...
    def count(self, item: typing.Any) -> int: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def IndexOf(self, value: typing.Any) -> int: ...
    def InPlaceAdd(self, other: typing.Any) -> typing.Any: ...
    def insert(self, index: int, value: typing.Any) -> None: ...
    def Insert(self, index: int, value: typing.Any) -> None: ...
    @typing.overload
    def __add__(self, l1: PythonList, l2: PythonList) -> PythonList: ...
    @typing.overload
    def __add__(self, self: PythonList, other: typing.Any) -> PythonList: ...
    def __gt__(self, self: PythonList, other: PythonList) -> typing.Any: ...
    def __ge__(self, self: PythonList, other: PythonList) -> typing.Any: ...
    def __lt__(self, self: PythonList, other: PythonList) -> typing.Any: ...
    def __le__(self, self: PythonList, other: PythonList) -> typing.Any: ...
    @typing.overload
    def __mul__(self, count: int, self: PythonList) -> PythonList: ...
    @typing.overload
    def __mul__(self, self: PythonList, count: int) -> PythonList: ...
    @typing.overload
    def __mul__(self, self: PythonList, count: Index) -> typing.Any: ...
    @typing.overload
    def __mul__(self, self: PythonList, count: typing.Any) -> typing.Any: ...
    @typing.overload
    def __mul__(self, count: Index, self: PythonList) -> typing.Any: ...
    @typing.overload
    def __mul__(self, count: typing.Any, self: PythonList) -> typing.Any: ...
    def remove(self, value: typing.Any) -> None: ...
    def Remove(self, item: typing.Any) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...
    def reverse(self) -> None: ...
    def sort(self, context: CodeContext, kwArgs: IDictionary_2[str, typing.Any]) -> None: ...
    def Sort(self, context: CodeContext, key: typing.Any = ..., reverse: bool = ...) -> None: ...
    # Skipped __delitem__ due to it being static, abstract and generic.

    __delitem__ : __delitem___MethodGroup
    class __delitem___MethodGroup:
        @typing.overload
        def __call__(self, index: int) -> None:...
        @typing.overload
        def __call__(self, slice: Slice) -> None:...
        @typing.overload
        def __call__(self, index: typing.Any) -> None:...

    # Skipped __init__ due to it being static, abstract and generic.

    __init__ : __init___MethodGroup
    class __init___MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, sequence: PythonList) -> None:...
        @typing.overload
        def __call__(self, sequence: SetCollection) -> None:...
        @typing.overload
        def __call__(self, sequence: FrozenSetCollection) -> None:...
        @typing.overload
        def __call__(self, sequence: str) -> None:...
        @typing.overload
        def __call__(self, sequence: ICollection) -> None:...
        @typing.overload
        def __call__(self, enumerable: IEnumerable) -> None:...
        @typing.overload
        def __call__(self, context: CodeContext, sequence: typing.Any) -> None:...

    # Skipped __new__ due to it being static, abstract and generic.

    __new__ : __new___MethodGroup
    class __new___MethodGroup:
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType) -> typing.Any:...
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, argsø: Array_1[typing.Any]) -> typing.Any:...
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, arg: typing.Any) -> typing.Any:...
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, kwArgsø: IDictionary_2[typing.Any, typing.Any], argsø: Array_1[typing.Any]) -> typing.Any:...

    # Skipped CopyTo due to it being static, abstract and generic.

    CopyTo : CopyTo_MethodGroup
    class CopyTo_MethodGroup:
        @typing.overload
        def __call__(self, array: Array_1[typing.Any], arrayIndex: int) -> None:...
        @typing.overload
        def __call__(self, array: Array, index: int) -> None:...

    # Skipped extend due to it being static, abstract and generic.

    extend : extend_MethodGroup
    class extend_MethodGroup:
        @typing.overload
        def __call__(self, seq: PythonList) -> None:...
        @typing.overload
        def __call__(self, seq: PythonTuple) -> None:...
        @typing.overload
        def __call__(self, seq: typing.Any) -> None:...

    # Skipped index due to it being static, abstract and generic.

    index : index_MethodGroup
    class index_MethodGroup:
        @typing.overload
        def __call__(self, item: typing.Any) -> int:...
        @typing.overload
        def __call__(self, item: typing.Any, start: int) -> int:...
        @typing.overload
        def __call__(self, item: typing.Any, start: typing.Any) -> int:...
        @typing.overload
        def __call__(self, item: typing.Any, start: int, stop: int) -> int:...
        @typing.overload
        def __call__(self, item: typing.Any, start: typing.Any, stop: typing.Any) -> int:...

    # Skipped InPlaceMultiply due to it being static, abstract and generic.

    InPlaceMultiply : InPlaceMultiply_MethodGroup
    class InPlaceMultiply_MethodGroup:
        @typing.overload
        def __call__(self, count: int) -> PythonList:...
        @typing.overload
        def __call__(self, count: Index) -> typing.Any:...
        @typing.overload
        def __call__(self, count: typing.Any) -> typing.Any:...

    # Skipped pop due to it being static, abstract and generic.

    pop : pop_MethodGroup
    class pop_MethodGroup:
        @typing.overload
        def __call__(self) -> typing.Any:...
        @typing.overload
        def __call__(self, index: int) -> typing.Any:...



class PythonModule(IPythonMembersList, IDynamicMetaObjectProvider):
    def __init__(self) -> None: ...
    @property
    def Scope(self) -> Scope: ...
    def __delattr__(self, context: CodeContext, name: str) -> None: ...
    def __getattribute__(self, context: CodeContext, name: str) -> typing.Any: ...
    def __repr__(self) -> str: ...
    def __setattr__(self, context: CodeContext, name: str, value: typing.Any) -> None: ...
    def __str__(self) -> str: ...
    def Delete__dict__(self) -> None: ...
    def Get__dict__(self) -> PythonDictionary: ...
    def GetMetaObject(self, parameter: Expression) -> DynamicMetaObject: ...
    def Set__dict__(self, value: typing.Any) -> None: ...
    # Skipped __init__ due to it being static, abstract and generic.

    __init__ : __init___MethodGroup
    class __init___MethodGroup:
        @typing.overload
        def __call__(self, name: str) -> None:...
        @typing.overload
        def __call__(self, name: str, doc: str) -> None:...

    # Skipped __new__ due to it being static, abstract and generic.

    __new__ : __new___MethodGroup
    class __new___MethodGroup:
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, argsø: Array_1[typing.Any]) -> PythonModule:...
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, kwDict0: IDictionary_2[typing.Any, typing.Any], argsø: Array_1[typing.Any]) -> PythonModule:...



class PythonTuple(IReadOnlyList_1[typing.Any], IList_1[typing.Any], IList, IStructuralEquatable, IExpressionSerializable, ICodeFormattable):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, o: typing.Any) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> typing.Any: ...
    @property
    def Item(self) -> typing.Any: ...
    @property
    def Item(self) -> typing.Any: ...
    @property
    def Item(self) -> typing.Any: ...
    def __getnewargs__(self) -> typing.Any: ...
    def __iter__(self) -> IEnumerator: ...
    def __len__(self) -> int: ...
    def __repr__(self, context: CodeContext) -> str: ...
    def Contains(self, item: typing.Any) -> bool: ...
    def count(self, obj: typing.Any) -> int: ...
    def CreateExpression(self) -> Expression: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def GetHashCode(self) -> int: ...
    def IndexOf(self, item: typing.Any) -> int: ...
    @typing.overload
    def __add__(self, x: PythonTuple, y: PythonTuple) -> PythonTuple: ...
    @typing.overload
    def __add__(self, x: PythonTuple, y: typing.Any) -> PythonTuple: ...
    def __gt__(self, self: PythonTuple, other: PythonTuple) -> typing.Any: ...
    def __ge__(self, self: PythonTuple, other: PythonTuple) -> typing.Any: ...
    def __lt__(self, self: PythonTuple, other: PythonTuple) -> typing.Any: ...
    def __le__(self, self: PythonTuple, other: PythonTuple) -> typing.Any: ...
    @typing.overload
    def __mul__(self, n: int, x: PythonTuple) -> PythonTuple: ...
    @typing.overload
    def __mul__(self, x: PythonTuple, n: int) -> PythonTuple: ...
    @typing.overload
    def __mul__(self, self: PythonTuple, count: Index) -> typing.Any: ...
    @typing.overload
    def __mul__(self, self: PythonTuple, count: typing.Any) -> typing.Any: ...
    @typing.overload
    def __mul__(self, count: Index, self: PythonTuple) -> typing.Any: ...
    @typing.overload
    def __mul__(self, count: typing.Any, self: PythonTuple) -> typing.Any: ...
    def ToString(self) -> str: ...
    # Skipped __new__ due to it being static, abstract and generic.

    __new__ : __new___MethodGroup
    class __new___MethodGroup:
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType) -> PythonTuple:...
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, sequence: typing.Any) -> PythonTuple:...

    # Skipped CopyTo due to it being static, abstract and generic.

    CopyTo : CopyTo_MethodGroup
    class CopyTo_MethodGroup:
        @typing.overload
        def __call__(self, array: Array_1[typing.Any], arrayIndex: int) -> None:...
        @typing.overload
        def __call__(self, array: Array, index: int) -> None:...

    # Skipped index due to it being static, abstract and generic.

    index : index_MethodGroup
    class index_MethodGroup:
        @typing.overload
        def __call__(self, obj: typing.Any, start: int = ...) -> int:...
        @typing.overload
        def __call__(self, obj: typing.Any, start: typing.Any) -> int:...
        @typing.overload
        def __call__(self, obj: typing.Any, start: int, end: int) -> int:...
        @typing.overload
        def __call__(self, obj: typing.Any, start: typing.Any, end: typing.Any) -> int:...



class SetCollection(ICollection, IEnumerable_1[typing.Any], IWeakReferenceable, ICodeFormattable, IStructuralEquatable):
    def __init__(self) -> None: ...
    __hash__ : typing.Any
    @property
    def Count(self) -> int: ...
    def __contains__(self, item: typing.Any) -> bool: ...
    def __eq__(self, other: typing.Any) -> typing.Any: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> typing.Any: ...
    def __reduce__(self, context: CodeContext) -> PythonTuple: ...
    def __repr__(self, context: CodeContext) -> str: ...
    def add(self, item: typing.Any) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> SetCollection: ...
    def discard(self, item: typing.Any) -> None: ...
    @typing.overload
    def __and__(self, x: SetCollection, y: FrozenSetCollection) -> SetCollection: ...
    @typing.overload
    def __and__(self, x: SetCollection, y: SetCollection) -> SetCollection: ...
    @typing.overload
    def __or__(self, x: SetCollection, y: FrozenSetCollection) -> SetCollection: ...
    @typing.overload
    def __or__(self, x: SetCollection, y: SetCollection) -> SetCollection: ...
    @typing.overload
    def __xor__(self, x: SetCollection, y: FrozenSetCollection) -> SetCollection: ...
    @typing.overload
    def __xor__(self, x: SetCollection, y: SetCollection) -> SetCollection: ...
    def __gt__(self, self: SetCollection, other: typing.Any) -> typing.Any: ...
    def __ge__(self, self: SetCollection, other: typing.Any) -> typing.Any: ...
    def __lt__(self, self: SetCollection, other: typing.Any) -> typing.Any: ...
    def __le__(self, self: SetCollection, other: typing.Any) -> typing.Any: ...
    @typing.overload
    def __sub__(self, x: SetCollection, y: FrozenSetCollection) -> SetCollection: ...
    @typing.overload
    def __sub__(self, x: SetCollection, y: SetCollection) -> SetCollection: ...
    def pop(self) -> typing.Any: ...
    def remove(self, item: typing.Any) -> None: ...
    # Skipped __init__ due to it being static, abstract and generic.

    __init__ : __init___MethodGroup
    class __init___MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, set: SetCollection) -> None:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> None:...
        @typing.overload
        def __call__(self, set: typing.Any) -> None:...

    # Skipped __new__ due to it being static, abstract and generic.

    __new__ : __new___MethodGroup
    class __new___MethodGroup:
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType) -> typing.Any:...
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, argsø: Array_1[typing.Any]) -> typing.Any:...
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, arg: typing.Any) -> typing.Any:...
        @typing.overload
        def __call__(self, context: CodeContext, cls: PythonType, kwArgs: IDictionary_2[typing.Any, typing.Any], argsø: Array_1[typing.Any]) -> typing.Any:...

    # Skipped difference due to it being static, abstract and generic.

    difference : difference_MethodGroup
    class difference_MethodGroup:
        @typing.overload
        def __call__(self) -> SetCollection:...
        @typing.overload
        def __call__(self, sets: Array_1[typing.Any]) -> SetCollection:...
        @typing.overload
        def __call__(self, set: SetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> SetCollection:...

    # Skipped difference_update due to it being static, abstract and generic.

    difference_update : difference_update_MethodGroup
    class difference_update_MethodGroup:
        @typing.overload
        def __call__(self, sets: Array_1[typing.Any]) -> None:...
        @typing.overload
        def __call__(self, set: SetCollection) -> None:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> None:...
        @typing.overload
        def __call__(self, set: typing.Any) -> None:...

    # Skipped InPlaceBitwiseAnd due to it being static, abstract and generic.

    InPlaceBitwiseAnd : InPlaceBitwiseAnd_MethodGroup
    class InPlaceBitwiseAnd_MethodGroup:
        @typing.overload
        def __call__(self, set: SetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> SetCollection:...

    # Skipped InPlaceBitwiseOr due to it being static, abstract and generic.

    InPlaceBitwiseOr : InPlaceBitwiseOr_MethodGroup
    class InPlaceBitwiseOr_MethodGroup:
        @typing.overload
        def __call__(self, set: SetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> SetCollection:...

    # Skipped InPlaceExclusiveOr due to it being static, abstract and generic.

    InPlaceExclusiveOr : InPlaceExclusiveOr_MethodGroup
    class InPlaceExclusiveOr_MethodGroup:
        @typing.overload
        def __call__(self, set: SetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> SetCollection:...

    # Skipped InPlaceSubtract due to it being static, abstract and generic.

    InPlaceSubtract : InPlaceSubtract_MethodGroup
    class InPlaceSubtract_MethodGroup:
        @typing.overload
        def __call__(self, set: SetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> SetCollection:...

    # Skipped intersection due to it being static, abstract and generic.

    intersection : intersection_MethodGroup
    class intersection_MethodGroup:
        @typing.overload
        def __call__(self) -> SetCollection:...
        @typing.overload
        def __call__(self, sets: Array_1[typing.Any]) -> SetCollection:...
        @typing.overload
        def __call__(self, set: SetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> SetCollection:...

    # Skipped intersection_update due to it being static, abstract and generic.

    intersection_update : intersection_update_MethodGroup
    class intersection_update_MethodGroup:
        @typing.overload
        def __call__(self, sets: Array_1[typing.Any]) -> None:...
        @typing.overload
        def __call__(self, set: SetCollection) -> None:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> None:...
        @typing.overload
        def __call__(self, set: typing.Any) -> None:...

    # Skipped isdisjoint due to it being static, abstract and generic.

    isdisjoint : isdisjoint_MethodGroup
    class isdisjoint_MethodGroup:
        @typing.overload
        def __call__(self, set: SetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: typing.Any) -> bool:...

    # Skipped issubset due to it being static, abstract and generic.

    issubset : issubset_MethodGroup
    class issubset_MethodGroup:
        @typing.overload
        def __call__(self, set: SetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: typing.Any) -> bool:...

    # Skipped issuperset due to it being static, abstract and generic.

    issuperset : issuperset_MethodGroup
    class issuperset_MethodGroup:
        @typing.overload
        def __call__(self, set: SetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> bool:...
        @typing.overload
        def __call__(self, set: typing.Any) -> bool:...

    # Skipped symmetric_difference due to it being static, abstract and generic.

    symmetric_difference : symmetric_difference_MethodGroup
    class symmetric_difference_MethodGroup:
        @typing.overload
        def __call__(self, set: SetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> SetCollection:...

    # Skipped symmetric_difference_update due to it being static, abstract and generic.

    symmetric_difference_update : symmetric_difference_update_MethodGroup
    class symmetric_difference_update_MethodGroup:
        @typing.overload
        def __call__(self, set: SetCollection) -> None:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> None:...
        @typing.overload
        def __call__(self, set: typing.Any) -> None:...

    # Skipped union due to it being static, abstract and generic.

    union : union_MethodGroup
    class union_MethodGroup:
        @typing.overload
        def __call__(self) -> SetCollection:...
        @typing.overload
        def __call__(self, sets: Array_1[typing.Any]) -> SetCollection:...
        @typing.overload
        def __call__(self, set: SetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> SetCollection:...
        @typing.overload
        def __call__(self, set: typing.Any) -> SetCollection:...

    # Skipped update due to it being static, abstract and generic.

    update : update_MethodGroup
    class update_MethodGroup:
        @typing.overload
        def __call__(self, sets: Array_1[typing.Any]) -> None:...
        @typing.overload
        def __call__(self, set: SetCollection) -> None:...
        @typing.overload
        def __call__(self, set: FrozenSetCollection) -> None:...
        @typing.overload
        def __call__(self, set: typing.Any) -> None:...



class SiteLocalStorage_GenericClasses(abc.ABCMeta):
    Generic_SiteLocalStorage_GenericClasses_SiteLocalStorage_1_T = typing.TypeVar('Generic_SiteLocalStorage_GenericClasses_SiteLocalStorage_1_T')
    def __getitem__(self, types : typing.Type[Generic_SiteLocalStorage_GenericClasses_SiteLocalStorage_1_T]) -> typing.Type[SiteLocalStorage_1[Generic_SiteLocalStorage_GenericClasses_SiteLocalStorage_1_T]]: ...

class SiteLocalStorage(SiteLocalStorage_0, metaclass =SiteLocalStorage_GenericClasses): ...

class SiteLocalStorage_0(abc.ABC):
    pass


SiteLocalStorage_1_T = typing.TypeVar('SiteLocalStorage_1_T')
class SiteLocalStorage_1(typing.Generic[SiteLocalStorage_1_T], SiteLocalStorage_0):
    def __init__(self) -> None: ...
    Data : SiteLocalStorage_1_T


class Slice(ISlice, ICodeFormattable):
    @typing.overload
    def __init__(self, start: typing.Any, stop: typing.Any) -> None: ...
    @typing.overload
    def __init__(self, start: typing.Any, stop: typing.Any, step: typing.Any) -> None: ...
    @typing.overload
    def __init__(self, stop: typing.Any) -> None: ...
    @property
    def start(self) -> typing.Any: ...
    @property
    def step(self) -> typing.Any: ...
    @property
    def stop(self) -> typing.Any: ...
    def __eq__(self, other: Slice) -> bool: ...
    def __hash__(self) -> int: ...
    def __ne__(self, other: Slice) -> bool: ...
    def __reduce__(self) -> PythonTuple: ...
    def __repr__(self, context: CodeContext) -> str: ...
    def __gt__(self, self: Slice, other: Slice) -> typing.Any: ...
    def __ge__(self, self: Slice, other: Slice) -> typing.Any: ...
    def __lt__(self, self: Slice, other: Slice) -> typing.Any: ...
    def __le__(self, self: Slice, other: Slice) -> typing.Any: ...
    # Skipped indices due to it being static, abstract and generic.

    indices : indices_MethodGroup
    class indices_MethodGroup:
        @typing.overload
        def __call__(self, length: int, ostart: clr.Reference[BigInteger], ostop: clr.Reference[BigInteger], ostep: clr.Reference[BigInteger]) -> None:...
        @typing.overload
        def __call__(self, length: typing.Any, ostart: clr.Reference[BigInteger], ostop: clr.Reference[BigInteger], ostep: clr.Reference[BigInteger]) -> None:...



class WeakRefTracker:
    @typing.overload
    def __init__(self, target: IWeakReferenceable) -> None: ...
    @typing.overload
    def __init__(self, target: IWeakReferenceable, callback: typing.Any, weakRef: typing.Any) -> None: ...
    @property
    def HandlerCount(self) -> int: ...
    def ChainCallback(self, callback: typing.Any, weakRef: typing.Any) -> None: ...
    def GetHandlerCallback(self, index: int) -> typing.Any: ...
    def GetWeakRef(self, index: int) -> typing.Any: ...
    def RemoveHandler(self, o: typing.Any) -> None: ...
    def RemoveHandlerAt(self, index: int) -> None: ...

