import typing, abc
from System import DateTime, IDisposable, Array_1, IAsyncResult, AsyncCallback, Exception, EventArgs
from System.IO import Stream
from System.Collections.Generic import IList_1, IEnumerator_1, IEnumerable_1, List_1
from System.Collections.ObjectModel import ReadOnlyCollection_1
from System.Collections import IDictionary
from System.Reflection import MethodBase
from Microsoft.Xna.Framework.Graphics import Texture2D
from Microsoft.Xna.Framework import GameComponent, Game, GameTime, GameWindow, PlayerIndex

class Achievement:
    def __init__(self) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> str: ...
    @property
    def DisplayBeforeEarned(self) -> bool: ...
    @DisplayBeforeEarned.setter
    def DisplayBeforeEarned(self, value: bool) -> bool: ...
    @property
    def EarnedDateTime(self) -> DateTime: ...
    @EarnedDateTime.setter
    def EarnedDateTime(self, value: DateTime) -> DateTime: ...
    @property
    def EarnedOnline(self) -> bool: ...
    @EarnedOnline.setter
    def EarnedOnline(self, value: bool) -> bool: ...
    @property
    def GamerScore(self) -> int: ...
    @GamerScore.setter
    def GamerScore(self, value: int) -> int: ...
    @property
    def HowToEarn(self) -> str: ...
    @HowToEarn.setter
    def HowToEarn(self, value: str) -> str: ...
    @property
    def IsEarned(self) -> bool: ...
    @IsEarned.setter
    def IsEarned(self, value: bool) -> bool: ...
    @property
    def Key(self) -> str: ...
    @Key.setter
    def Key(self, value: str) -> str: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    def GetPicture(self) -> Stream: ...


class AchievementCollection(IList_1[Achievement], IDisposable):
    def __init__(self) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def IsReadOnly(self) -> bool: ...
    @property
    def Item(self) -> Achievement: ...
    @Item.setter
    def Item(self, value: Achievement) -> Achievement: ...
    def Add(self, item: Achievement) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, item: Achievement) -> bool: ...
    def CopyTo(self, array: Array_1[Achievement], arrayIndex: int) -> None: ...
    def Dispose(self) -> None: ...
    def GetEnumerator(self) -> IEnumerator_1[Achievement]: ...
    def IndexOf(self, item: Achievement) -> int: ...
    def Insert(self, index: int, item: Achievement) -> None: ...
    def Remove(self, item: Achievement) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...


class FriendCollection(IList_1[FriendGamer], IDisposable):
    def __init__(self) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def IsReadOnly(self) -> bool: ...
    @IsReadOnly.setter
    def IsReadOnly(self, value: bool) -> bool: ...
    @property
    def Item(self) -> FriendGamer: ...
    @Item.setter
    def Item(self, value: FriendGamer) -> FriendGamer: ...
    def Add(self, item: FriendGamer) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, item: FriendGamer) -> bool: ...
    def CopyTo(self, array: Array_1[FriendGamer], arrayIndex: int) -> None: ...
    def Dispose(self) -> None: ...
    def GetEnumerator(self) -> IEnumerator_1[FriendGamer]: ...
    def IndexOf(self, item: FriendGamer) -> int: ...
    def Insert(self, index: int, item: FriendGamer) -> None: ...
    def Remove(self, item: FriendGamer) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...


class FriendGamer(Gamer):
    def __init__(self) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> str: ...
    @property
    def Gamertag(self) -> str: ...
    @Gamertag.setter
    def Gamertag(self, value: str) -> str: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def LeaderboardWriter(self) -> LeaderboardWriter: ...
    @LeaderboardWriter.setter
    def LeaderboardWriter(self, value: LeaderboardWriter) -> LeaderboardWriter: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...


class GameDefaults:
    def __init__(self) -> None: ...
    @property
    def AccelerateWithButtons(self) -> bool: ...


class Gamer(abc.ABC):
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> str: ...
    @property
    def Gamertag(self) -> str: ...
    @Gamertag.setter
    def Gamertag(self, value: str) -> str: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def LeaderboardWriter(self) -> LeaderboardWriter: ...
    @LeaderboardWriter.setter
    def LeaderboardWriter(self, value: LeaderboardWriter) -> LeaderboardWriter: ...
    @classmethod
    @property
    def SignedInGamers(cls) -> SignedInGamerCollection: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    def BeginGetProfile(self, callback: AsyncCallback, asyncState: typing.Any) -> IAsyncResult: ...
    def EndGetProfile(self, result: IAsyncResult) -> GamerProfile: ...
    def GetProfile(self) -> GamerProfile: ...
    def ToString(self) -> str: ...


class GamerCollection_GenericClasses(abc.ABCMeta):
    Generic_GamerCollection_GenericClasses_GamerCollection_1_T = typing.TypeVar('Generic_GamerCollection_GenericClasses_GamerCollection_1_T')
    def __getitem__(self, types : typing.Type[Generic_GamerCollection_GenericClasses_GamerCollection_1_T]) -> typing.Type[GamerCollection_1[Generic_GamerCollection_GenericClasses_GamerCollection_1_T]]: ...

GamerCollection : GamerCollection_GenericClasses

GamerCollection_1_T = typing.TypeVar('GamerCollection_1_T')
class GamerCollection_1(typing.Generic[GamerCollection_1_T], ReadOnlyCollection_1[GamerCollection_1_T]):
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> GamerCollection_1_T: ...


class GamerPresence:
    def __init__(self) -> None: ...
    @property
    def PresenceMode(self) -> GamerPresenceMode: ...
    @PresenceMode.setter
    def PresenceMode(self, value: GamerPresenceMode) -> GamerPresenceMode: ...
    @property
    def PresenceValue(self) -> int: ...
    @PresenceValue.setter
    def PresenceValue(self, value: int) -> int: ...


class GamerPresenceMode(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    ArcadeMode : GamerPresenceMode # 0
    AtMenu : GamerPresenceMode # 1
    BattlingBoss : GamerPresenceMode # 2
    CampaignMode : GamerPresenceMode # 3
    ChallengeMode : GamerPresenceMode # 4
    ConfiguringSettings : GamerPresenceMode # 5
    CoOpLevel : GamerPresenceMode # 6
    CoOpStage : GamerPresenceMode # 7
    CornflowerBlue : GamerPresenceMode # 8
    CustomizingPlayer : GamerPresenceMode # 9
    DifficultyEasy : GamerPresenceMode # 10
    DifficultyExtreme : GamerPresenceMode # 11
    DifficultyHard : GamerPresenceMode # 12
    DifficultyMedium : GamerPresenceMode # 13
    EditingLevel : GamerPresenceMode # 14
    ExplorationMode : GamerPresenceMode # 15
    FoundSecret : GamerPresenceMode # 16
    FreePlay : GamerPresenceMode # 17
    GameOver : GamerPresenceMode # 18
    InCombat : GamerPresenceMode # 19
    InGameStore : GamerPresenceMode # 20
    Level : GamerPresenceMode # 21
    LocalCoOp : GamerPresenceMode # 22
    LocalVersus : GamerPresenceMode # 23
    LookingForGames : GamerPresenceMode # 24
    Losing : GamerPresenceMode # 25
    Multiplayer : GamerPresenceMode # 26
    NearlyFinished : GamerPresenceMode # 27
    None_ : GamerPresenceMode # 28
    OnARoll : GamerPresenceMode # 29
    OnlineCoOp : GamerPresenceMode # 30
    OnlineVersus : GamerPresenceMode # 31
    Outnumbered : GamerPresenceMode # 32
    Paused : GamerPresenceMode # 33
    PlayingMinigame : GamerPresenceMode # 34
    PlayingWithFriends : GamerPresenceMode # 35
    PracticeMode : GamerPresenceMode # 36
    PuzzleMode : GamerPresenceMode # 37
    ScenarioMode : GamerPresenceMode # 38
    Score : GamerPresenceMode # 39
    ScoreIsTied : GamerPresenceMode # 40
    SettingUpMatch : GamerPresenceMode # 41
    SinglePlayer : GamerPresenceMode # 42
    Stage : GamerPresenceMode # 43
    StartingGame : GamerPresenceMode # 44
    StoryMode : GamerPresenceMode # 45
    StuckOnAHardBit : GamerPresenceMode # 46
    SurvivalMode : GamerPresenceMode # 47
    TimeAttack : GamerPresenceMode # 48
    TryingForRecord : GamerPresenceMode # 49
    TutorialMode : GamerPresenceMode # 50
    VersusComputer : GamerPresenceMode # 51
    VersusScore : GamerPresenceMode # 52
    WaitingForPlayers : GamerPresenceMode # 53
    WaitingInLobby : GamerPresenceMode # 54
    WastingTime : GamerPresenceMode # 55
    WatchingCredits : GamerPresenceMode # 56
    WatchingCutscene : GamerPresenceMode # 57
    Winning : GamerPresenceMode # 58
    WonTheGame : GamerPresenceMode # 59


class GamerPrivilegeException(Exception):
    def __init__(self) -> None: ...
    @property
    def Data(self) -> IDictionary: ...
    @property
    def HelpLink(self) -> str: ...
    @HelpLink.setter
    def HelpLink(self, value: str) -> str: ...
    @property
    def HResult(self) -> int: ...
    @HResult.setter
    def HResult(self, value: int) -> int: ...
    @property
    def InnerException(self) -> Exception: ...
    @property
    def Message(self) -> str: ...
    @property
    def Source(self) -> str: ...
    @Source.setter
    def Source(self, value: str) -> str: ...
    @property
    def StackTrace(self) -> str: ...
    @property
    def TargetSite(self) -> MethodBase: ...


class GamerPrivileges:
    def __init__(self) -> None: ...
    @property
    def AllowCommunication(self) -> GamerPrivilegeSetting: ...
    @property
    def AllowOnlineSessions(self) -> bool: ...
    @property
    def AllowProfileViewing(self) -> GamerPrivilegeSetting: ...
    @property
    def AllowPurchaseContent(self) -> bool: ...
    @property
    def AllowTradeContent(self) -> bool: ...
    @property
    def AllowUserCreatedContent(self) -> GamerPrivilegeSetting: ...


class GamerPrivilegeSetting(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Blocked : GamerPrivilegeSetting # 0
    Everyone : GamerPrivilegeSetting # 1
    FriendsOnly : GamerPrivilegeSetting # 2


class GamerProfile(IDisposable):
    def __init__(self) -> None: ...
    def Dispose(self) -> None: ...
    def GetGamerPicture(self) -> Texture2D: ...


class GamerServicesComponent(GameComponent):
    def __init__(self, game: Game) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> bool: ...
    @property
    def Game(self) -> Game: ...
    @property
    def UpdateOrder(self) -> int: ...
    @UpdateOrder.setter
    def UpdateOrder(self, value: int) -> int: ...
    def Update(self, gameTime: GameTime) -> None: ...


class GamerServicesDispatcher(abc.ABC):
    @classmethod
    @property
    def IsInitialized(cls) -> bool: ...
    @classmethod
    @property
    def WindowHandle(cls) -> int: ...
    @classmethod
    @WindowHandle.setter
    def WindowHandle(cls, value: int) -> int: ...
    @staticmethod
    def Update() -> None: ...


class GamerZone(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Family : GamerZone # 0
    Pro : GamerZone # 1
    Recreation : GamerZone # 2
    Underground : GamerZone # 3
    Unknown : GamerZone # 4


class GameUpdateRequiredException(Exception):
    def __init__(self) -> None: ...
    @property
    def Data(self) -> IDictionary: ...
    @property
    def HelpLink(self) -> str: ...
    @HelpLink.setter
    def HelpLink(self, value: str) -> str: ...
    @property
    def HResult(self) -> int: ...
    @HResult.setter
    def HResult(self, value: int) -> int: ...
    @property
    def InnerException(self) -> Exception: ...
    @property
    def Message(self) -> str: ...
    @property
    def Source(self) -> str: ...
    @Source.setter
    def Source(self, value: str) -> str: ...
    @property
    def StackTrace(self) -> str: ...
    @property
    def TargetSite(self) -> MethodBase: ...


class Guide(abc.ABC):
    @classmethod
    @property
    def IsScreenSaverEnabled(cls) -> bool: ...
    @classmethod
    @IsScreenSaverEnabled.setter
    def IsScreenSaverEnabled(cls, value: bool) -> bool: ...
    @classmethod
    @property
    def IsTrialMode(cls) -> bool: ...
    @classmethod
    @property
    def IsVisible(cls) -> bool: ...
    @classmethod
    @IsVisible.setter
    def IsVisible(cls, value: bool) -> bool: ...
    @classmethod
    @property
    def SimulateTrialMode(cls) -> bool: ...
    @classmethod
    @SimulateTrialMode.setter
    def SimulateTrialMode(cls, value: bool) -> bool: ...
    @classmethod
    @property
    def Window(cls) -> GameWindow: ...
    @classmethod
    @Window.setter
    def Window(cls, value: GameWindow) -> GameWindow: ...
    @staticmethod
    def EndShowKeyboardInput(result: IAsyncResult) -> str: ...
    @staticmethod
    def EndShowMessageBox(result: IAsyncResult) -> typing.Optional[int]: ...
    @staticmethod
    def Show() -> None: ...
    @staticmethod
    def ShowAchievements() -> None: ...
    @staticmethod
    def ShowLeaderboard() -> None: ...
    @staticmethod
    def ShowMarketplace(player: PlayerIndex) -> None: ...
    @staticmethod
    def ShowSignIn(paneCount: int, onlineOnly: bool) -> None: ...
    # Skipped BeginShowKeyboardInput due to it being static, abstract and generic.

    BeginShowKeyboardInput : BeginShowKeyboardInput_MethodGroup
    class BeginShowKeyboardInput_MethodGroup:
        @typing.overload
        def __call__(self, player: PlayerIndex, title: str, description: str, defaultText: str, callback: AsyncCallback, state: typing.Any) -> IAsyncResult:...
        @typing.overload
        def __call__(self, player: PlayerIndex, title: str, description: str, defaultText: str, callback: AsyncCallback, state: typing.Any, usePasswordMode: bool) -> IAsyncResult:...

    # Skipped BeginShowMessageBox due to it being static, abstract and generic.

    BeginShowMessageBox : BeginShowMessageBox_MethodGroup
    class BeginShowMessageBox_MethodGroup:
        @typing.overload
        def __call__(self, title: str, text: str, buttons: IEnumerable_1[str], focusButton: int, icon: MessageBoxIcon, callback: AsyncCallback, state: typing.Any) -> IAsyncResult:...
        @typing.overload
        def __call__(self, player: PlayerIndex, title: str, text: str, buttons: IEnumerable_1[str], focusButton: int, icon: MessageBoxIcon, callback: AsyncCallback, state: typing.Any) -> IAsyncResult:...



class GuideAlreadyVisibleException(Exception):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str) -> None: ...
    @typing.overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @property
    def Data(self) -> IDictionary: ...
    @property
    def HelpLink(self) -> str: ...
    @HelpLink.setter
    def HelpLink(self, value: str) -> str: ...
    @property
    def HResult(self) -> int: ...
    @HResult.setter
    def HResult(self, value: int) -> int: ...
    @property
    def InnerException(self) -> Exception: ...
    @property
    def Message(self) -> str: ...
    @property
    def Source(self) -> str: ...
    @Source.setter
    def Source(self, value: str) -> str: ...
    @property
    def StackTrace(self) -> str: ...
    @property
    def TargetSite(self) -> MethodBase: ...


class LeaderboardEntry:
    def __init__(self) -> None: ...
    @property
    def Columns(self) -> PropertyDictionary: ...
    @Columns.setter
    def Columns(self, value: PropertyDictionary) -> PropertyDictionary: ...
    @property
    def Gamer(self) -> Gamer: ...
    @Gamer.setter
    def Gamer(self, value: Gamer) -> Gamer: ...
    @property
    def Rating(self) -> int: ...
    @Rating.setter
    def Rating(self, value: int) -> int: ...


class LeaderboardIdentity:
    @property
    def GameMode(self) -> int: ...
    @GameMode.setter
    def GameMode(self, value: int) -> int: ...
    @property
    def Key(self) -> LeaderboardKey: ...
    @Key.setter
    def Key(self, value: LeaderboardKey) -> LeaderboardKey: ...
    # Skipped Create due to it being static, abstract and generic.

    Create : Create_MethodGroup
    class Create_MethodGroup:
        @typing.overload
        def __call__(self, aKey: LeaderboardKey) -> LeaderboardIdentity:...
        @typing.overload
        def __call__(self, aKey: LeaderboardKey, aGameMode: int) -> LeaderboardIdentity:...



class LeaderboardKey(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    BestScoreLifeTime : LeaderboardKey # 0
    BestScoreRecent : LeaderboardKey # 1
    BestTimeLifeTime : LeaderboardKey # 2
    BestTimeRecent : LeaderboardKey # 3


class LeaderboardReader(IDisposable):
    def __init__(self) -> None: ...
    PageStart : int
    TotalLeaderboardSize : int
    @property
    def CanPageDown(self) -> bool: ...
    @CanPageDown.setter
    def CanPageDown(self, value: bool) -> bool: ...
    @property
    def CanPageUp(self) -> bool: ...
    @CanPageUp.setter
    def CanPageUp(self, value: bool) -> bool: ...
    @property
    def Entries(self) -> List_1[LeaderboardEntry]: ...
    @Entries.setter
    def Entries(self, value: List_1[LeaderboardEntry]) -> List_1[LeaderboardEntry]: ...
    def BeginPageDown(self, aAsyncCallback: AsyncCallback, aAsyncState: typing.Any) -> IAsyncResult: ...
    def BeginPageUp(self, aAsyncCallback: AsyncCallback, aAsyncState: typing.Any) -> IAsyncResult: ...
    @staticmethod
    def BeginRead(id: LeaderboardIdentity, gamer: SignedInGamer, leaderboardPageSize: int, leaderboardReadCallback: AsyncCallback, gamer2: SignedInGamer) -> None: ...
    def Dispose(self) -> None: ...
    def EndPageDown(self, result: IAsyncResult) -> LeaderboardReader: ...
    def EndPageUp(self, result: IAsyncResult) -> LeaderboardReader: ...
    @staticmethod
    def EndRead(result: IAsyncResult) -> LeaderboardReader: ...
    def PageDown(self) -> None: ...
    def PageUp(self) -> None: ...


class LeaderboardWriter(IDisposable):
    def __init__(self) -> None: ...
    def GetLeaderboard(self, aLeaderboardIdentity: LeaderboardIdentity) -> LeaderboardEntry: ...


class MessageBoxIcon(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Alert : MessageBoxIcon # 0
    Error : MessageBoxIcon # 1
    None_ : MessageBoxIcon # 2
    Warning : MessageBoxIcon # 3


class MonoGameGamerServicesComponent(GamerServicesComponent):
    def __init__(self, game: Game) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> bool: ...
    @property
    def Game(self) -> Game: ...
    @property
    def UpdateOrder(self) -> int: ...
    @UpdateOrder.setter
    def UpdateOrder(self, value: int) -> int: ...


class PropertyDictionary:
    def __init__(self) -> None: ...
    def GetValueDateTime(self, aKey: str) -> DateTime: ...
    def GetValueInt32(self, aKey: str) -> int: ...
    def SetValue(self, aKey: str, aValue: DateTime) -> None: ...


class SignedInEventArgs(EventArgs):
    def __init__(self, gamer: SignedInGamer) -> None: ...
    Gamer : SignedInGamer


class SignedInGamer(Gamer):
    def __init__(self) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> str: ...
    @property
    def GameDefaults(self) -> GameDefaults: ...
    @property
    def Gamertag(self) -> str: ...
    @Gamertag.setter
    def Gamertag(self, value: str) -> str: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IsGuest(self) -> bool: ...
    @property
    def IsSignedInToLive(self) -> bool: ...
    @property
    def LeaderboardWriter(self) -> LeaderboardWriter: ...
    @LeaderboardWriter.setter
    def LeaderboardWriter(self, value: LeaderboardWriter) -> LeaderboardWriter: ...
    @property
    def PartySize(self) -> int: ...
    @PartySize.setter
    def PartySize(self, value: int) -> int: ...
    @property
    def PlayerIndex(self) -> PlayerIndex: ...
    @property
    def Presence(self) -> GamerPresence: ...
    @property
    def Privileges(self) -> GamerPrivileges: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    def BeginAuthentication(self, callback: AsyncCallback, asyncState: typing.Any) -> IAsyncResult: ...
    def BeginGetAchievements(self, callback: AsyncCallback, asyncState: typing.Any) -> IAsyncResult: ...
    def DoAwardAchievement(self, achievementId: str, percentageComplete: float) -> None: ...
    def EndAuthentication(self, result: IAsyncResult) -> None: ...
    def EndAwardAchievement(self, result: IAsyncResult) -> None: ...
    def EndGetAchievements(self, result: IAsyncResult) -> AchievementCollection: ...
    def GetAchievements(self) -> AchievementCollection: ...
    def GetFriends(self) -> FriendCollection: ...
    def IsFriend(self, gamer: Gamer) -> bool: ...
    def ResetAchievements(self) -> None: ...
    def UpdateScore(self, aCategory: str, aScore: int) -> None: ...
    # Skipped AwardAchievement due to it being static, abstract and generic.

    AwardAchievement : AwardAchievement_MethodGroup
    class AwardAchievement_MethodGroup:
        @typing.overload
        def __call__(self, achievementId: str) -> None:...
        @typing.overload
        def __call__(self, achievementId: str, percentageComplete: float) -> None:...

    # Skipped BeginAwardAchievement due to it being static, abstract and generic.

    BeginAwardAchievement : BeginAwardAchievement_MethodGroup
    class BeginAwardAchievement_MethodGroup:
        @typing.overload
        def __call__(self, achievementId: str, callback: AsyncCallback, state: typing.Any) -> IAsyncResult:...
        @typing.overload
        def __call__(self, achievementId: str, percentageComplete: float, callback: AsyncCallback, state: typing.Any) -> IAsyncResult:...



class SignedInGamerCollection(List_1[SignedInGamer]):
    def __init__(self) -> None: ...
    @property
    def Capacity(self) -> int: ...
    @Capacity.setter
    def Capacity(self, value: int) -> int: ...
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> SignedInGamer: ...
    @property
    def Item(self) -> SignedInGamer: ...
    @Item.setter
    def Item(self, value: SignedInGamer) -> SignedInGamer: ...


class SignedOutEventArgs(EventArgs):
    def __init__(self, gamer: SignedInGamer) -> None: ...

